Repository plotly/plotly.js, pull requests merged in 2018-05, with the labels that each got.

#2583 SVG trace on selection perf
  src/components/drawing/index.js
  src/components/legend/style.js
  src/plots/cartesian/select.js
  src/plots/plots.js
  src/traces/bar/index.js
  src/traces/bar/style.js
  src/traces/box/index.js
  src/traces/box/style.js
  src/traces/candlestick/index.js
  src/traces/choropleth/index.js
  src/traces/choropleth/plot.js
  src/traces/choropleth/style.js
  src/traces/histogram/index.js
  src/traces/scatter/index.js
  src/traces/scatter/plot.js
  src/traces/scatter/style.js
  src/traces/scattercarpet/index.js
  src/traces/scattergeo/index.js
  src/traces/scattermapbox/convert.js
  src/traces/scatterternary/index.js
  src/traces/violin/index.js
  test/jasmine/tests/scatter_test.js
  test/jasmine/tests/select_test.js
Labels: status: reviewable, type: performance

#2593 Scattergl selection / clustering fix
  package-lock.json
  package.json
  src/traces/scattergl/index.js
  test/image/baselines/gl2d_scatter-color-clustering.png
  test/image/baselines/gl2d_scatter-continuous-clustering.png
  test/image/mocks/gl2d_scatter-continuous-clustering.json
  test/jasmine/tests/splom_test.js
Labels: status: reviewable, type: bug

#2603 Fix Plotly.react add/remove traces bug
  src/plot_api/plot_api.js
  test/jasmine/tests/plot_api_test.js
Labels: status: reviewable, type: bug

#2607 Override toImage modebar button opts via config
  src/components/modebar/buttons.js
  src/plot_api/plot_config.js
  test/jasmine/tests/modebar_test.js
Labels: status: reviewable, type: feature

#2617 Link to https://get.webgl.org instead of the unsafe http version
  src/lib/show_no_webgl_msg.js
Labels: status: reviewable, type: bug

#2622 Brazilian portuguese translation
  lib/locales/pt-br.js
Labels: type: translation

#2623 Faster svg pan
  src/components/drawing/index.js
  src/plots/cartesian/dragbox.js
  src/plots/cartesian/index.js
  src/plots/cartesian/transition_axes.js
  src/traces/bar/index.js
  src/traces/box/index.js
  src/traces/scatter/index.js
  src/traces/scattercarpet/index.js
  src/traces/violin/index.js
Labels: status: reviewable, type: performance

#2629 More robust Sankey
  src/lib/index.js
  src/plot_api/plot_schema.js
  src/traces/sankey/calc.js
  src/traces/sankey/defaults.js
  src/traces/sankey/render.js
  test/image/baselines/sankey_messy.png
  test/image/mocks/sankey_messy.json
  test/jasmine/tests/sankey_test.js
Labels: status: reviewable, type: bug

#2628 Fix relayout constrained axes + various multi-subplot perf improvements
  src/components/colorbar/draw.js
  src/components/grid/index.js
  src/plot_api/plot_api.js
  src/plot_api/subroutines.js
  src/plots/cartesian/axes.js
  src/plots/cartesian/dragbox.js
  src/plots/cartesian/transition_axes.js
  src/plots/plots.js
  src/plots/polar/polar.js
  src/plots/ternary/ternary.js
  src/traces/splom/defaults.js
  test/image/baselines/splom_0.png
  test/image/baselines/splom_array-styles.png
  test/image/baselines/splom_dates.png
  test/image/baselines/splom_iris.png
  test/image/baselines/splom_large.png
  test/image/baselines/splom_log.png
  test/image/baselines/splom_lower-nodiag.png
  test/image/baselines/splom_lower.png
  test/image/baselines/splom_ragged-via-axes.png
  test/image/baselines/splom_ragged-via-visible-false.png
  test/image/baselines/splom_with-cartesian.png
  test/jasmine/tests/cartesian_interact_test.js
  test/jasmine/tests/plot_api_test.js
  test/jasmine/tests/splom_test.js
Labels: status: reviewable, type: bug, type: performance

#2634 Add MIT License button from shields.io
  README.md
Labels: type: documentation

#2635 Add dy to list of creators
  README.md
Labels: type: documentation

#2632 Italian translation
  lib/locales/it.js
Labels: status: reviewable, type: translation

#2638 fix #2633 - make sure we have a grid before attaching it to layoutOut
  src/components/grid/index.js
  test/jasmine/tests/plots_test.js
Labels: status: reviewable, type: bug

#2647 Fix single cone
  package-lock.json
  package.json
  src/traces/cone/attributes.js
  src/traces/cone/calc.js
  test/image/baselines/gl3d_cone-single.png
  test/image/mocks/gl3d_cone-single.json
  test/jasmine/tests/cone_test.js
Labels: status: reviewable, type: bug

#2650 Violin span fix
  src/traces/violin/calc.js
  test/image/baselines/violin_bandwidth-edge-cases.png
  test/image/mocks/violin_bandwidth-edge-cases.json
Labels: status: reviewable, type: bug

#2552 use supplied bandwidth if provided
  src/traces/violin/calc.js
Labels: status: in progress, type: bug, type: feature

#2612 Add null-data buffer fix for parcoords
  src/traces/parcoords/lines.js
Labels: status: reviewable, type: bug

#2654 Add Building.md
  BUILDING.md
  README.md
  tasks/test_syntax.js
Labels: type: documentation

#2657 remove cached `trace._interpz` from heatmaps/contour maps with gaps
  src/traces/contourcarpet/calc.js
  src/traces/heatmap/calc.js
  src/traces/heatmap/interp2d.js
  test/jasmine/tests/contour_test.js
  test/jasmine/tests/heatmap_test.js
Labels: status: reviewable, type: bug

#2656 Fixup noci_test.sh
  package-lock.json
  package.json
  tasks/noci_test.sh
  test/jasmine/karma.conf.js
  test/jasmine/tests/plot_api_test.js
Labels: status: reviewable, type: maintenance

#2662 Create two (not three) WebGL contexts for scattergl/splom graphs
  src/lib/prepare_regl.js
  test/jasmine/tests/gl2d_plot_interact_test.js
  test/jasmine/tests/parcoords_test.js
Labels: status: reviewable, type: bug

#2668 Fix select <-> pan double-click behavior
  src/plots/cartesian/dragbox.js
  test/jasmine/tests/select_test.js
Labels: status: reviewable, type: bug

#2677 Scattergl transform fixes
  src/lib/index.js
  src/plots/plots.js
  src/traces/scattergl/convert.js
  src/traces/scattergl/index.js
  test/image/baselines/gl2d_point-selection.png
  test/image/baselines/gl2d_transforms.png
  test/image/mocks/gl2d_point-selection.json
  test/image/mocks/gl2d_transforms.json
  test/jasmine/tests/gl2d_click_test.js
  test/jasmine/tests/gl2d_plot_interact_test.js
Labels: status: reviewable, type: bug

#2676 Fix shift selection after pan
  src/plots/cartesian/dragbox.js
  test/jasmine/assets/custom_matchers.js
  test/jasmine/tests/select_test.js
Labels: status: reviewable, type: bug
