Repository plotly/plotly.js, pull requests merged in 2018-09, with the labels that each got.

#2932 improve pseudo-html entity conversion
  src/constants/string_mappings.js
  src/lib/html2unicode.js
  src/lib/svg_text_utils.js
  test/jasmine/tests/svg_text_utils_test.js
Labels: status: reviewable, type: bug, type: feature

#2945 Welsh translation
  lib/locales/cy.js
Labels: status: reviewable, type: translation

#2973 ensure makesData transforms work with Plotly.react
  src/plot_api/plot_api.js
  src/plots/plots.js
  test/jasmine/tests/transform_multi_test.js
Labels: type: bug

#2954 Add barpolar traces
  lib/barpolar.js
  lib/index.js
  src/lib/angles.js
  src/lib/coerce.js
  src/lib/dates.js
  src/lib/geometry2d.js
  src/lib/index.js
  src/lib/mod.js
  src/lib/search.js
  src/plots/plots.js
  src/plots/polar/helpers.js
  src/plots/polar/polar.js
  src/plots/polar/set_convert.js
  src/traces/bar/cross_trace_calc.js
  src/traces/bar/hover.js
  src/traces/bar/index.js
  src/traces/bar/plot.js
  src/traces/barpolar/attributes.js
  src/traces/barpolar/calc.js
  src/traces/barpolar/defaults.js
  src/traces/barpolar/hover.js
  src/traces/barpolar/index.js
  src/traces/barpolar/layout_attributes.js
  src/traces/barpolar/layout_defaults.js
  src/traces/barpolar/plot.js
  src/traces/histogram/calc.js
  src/traces/histogram/hover.js
  src/traces/histogram/index.js
  src/traces/scattermapbox/hover.js
  src/traces/scattermapbox/select.js
  src/traces/scatterpolar/hover.js
  src/traces/scatterpolargl/index.js
  test/image/baselines/polar_bar-overlay.png
  test/image/baselines/polar_bar-stacked.png
  test/image/baselines/polar_bar-width-base-offset.png
  test/image/baselines/polar_dates.png
  test/image/baselines/polar_funky-bars.png
  test/image/baselines/polar_polygon-bars.png
  test/image/baselines/polar_r0dr-theta0dtheta.png
  test/image/baselines/polar_radial-range.png
  test/image/baselines/polar_transforms.png
  test/image/baselines/polar_wind-rose.png
  test/image/mocks/polar_bar-overlay.json
  test/image/mocks/polar_bar-stacked.json
  test/image/mocks/polar_bar-width-base-offset.json
  test/image/mocks/polar_dates.json
  test/image/mocks/polar_funky-bars.json
  test/image/mocks/polar_polygon-bars.json
  test/image/mocks/polar_wind-rose.json
  test/jasmine/assets/mock_lists.js
  test/jasmine/tests/barpolar_test.js
  test/jasmine/tests/histogram_test.js
  test/jasmine/tests/select_test.js
Labels: status: reviewable, type: bug, type: feature

#2960 Stacked Area Charts
  src/components/errorbars/calc.js
  src/components/fx/hover.js
  src/constants/numerical.js
  src/lib/index.js
  src/lib/search.js
  src/plots/cartesian/autorange.js
  src/plots/cartesian/axes.js
  src/plots/cartesian/axis_defaults.js
  src/plots/cartesian/layout_attributes.js
  src/plots/cartesian/set_convert.js
  src/plots/plots.js
  src/plots/polar/layout_defaults.js
  src/traces/bar/layout_attributes.js
  src/traces/scatter/attributes.js
  src/traces/scatter/calc.js
  src/traces/scatter/cross_trace_calc.js
  src/traces/scatter/defaults.js
  src/traces/scatter/hover.js
  src/traces/scatter/index.js
  src/traces/scatter/line_points.js
  src/traces/scatter/plot.js
  src/traces/scatter/select.js
  src/traces/scatter/stack_defaults.js
  src/traces/scattercarpet/attributes.js
  src/traces/scattergl/attributes.js
  src/traces/scattergl/index.js
  src/traces/scatterpolar/attributes.js
  src/traces/scatterternary/attributes.js
  test/image/baselines/autorange-tozero-rangemode.png
  test/image/baselines/axes_range_type.png
  test/image/baselines/contour_log.png
  test/image/baselines/log_lines_fills.png
  test/image/baselines/stacked_area.png
  test/image/baselines/stacked_area_duplicates.png
  test/image/baselines/stacked_area_horz.png
  test/image/baselines/stacked_area_log.png
  test/image/mocks/log_lines_fills.json
  test/image/mocks/scatter_fill_corner_cases.json
  test/image/mocks/stacked_area.json
  test/image/mocks/stacked_area_duplicates.json
  test/image/mocks/stacked_area_horz.json
  test/image/mocks/stacked_area_log.json
  test/jasmine/assets/custom_assertions.js
  test/jasmine/tests/axes_test.js
  test/jasmine/tests/hover_label_test.js
  test/jasmine/tests/lib_test.js
  test/jasmine/tests/scatter_test.js
Labels: status: reviewable, type: bug, type: feature

#2983 fix legend when figures has large margins
  src/components/legend/draw.js
  test/image/baselines/legend_large_margin.png
  test/image/mocks/legend_large_margin.json
Labels: status: reviewable, type: bug

#2984 make sankey honor positioning specified by domain.x
  src/traces/sankey/render.js
  test/image/baselines/sankey_subplots.png
  test/image/mocks/sankey_subplots.json
Labels: status: reviewable, type: bug

#2956 Bump regl trace deps
  package-lock.json
  package.json
  src/traces/scattergl/index.js
Labels: status: reviewable, type: bug

#2944 1852 persistent click via select points
  src/components/fx/layout_attributes.js
  src/components/fx/layout_defaults.js
  src/lib/polygon.js
  src/plots/cartesian/dragbox.js
  src/plots/cartesian/select.js
  src/plots/geo/geo.js
  src/plots/mapbox/mapbox.js
  src/plots/polar/polar.js
  src/plots/ternary/ternary.js
  src/traces/bar/select.js
  src/traces/box/event_data.js
  src/traces/box/hover.js
  src/traces/box/index.js
  src/traces/box/select.js
  src/traces/choropleth/select.js
  src/traces/ohlc/select.js
  src/traces/scatter/select.js
  src/traces/scattergeo/select.js
  src/traces/scattergl/index.js
  src/traces/scattermapbox/select.js
  src/traces/splom/index.js
  test/jasmine/assets/double_click.js
  test/jasmine/tests/hover_label_test.js
  test/jasmine/tests/select_test.js
Labels: status: reviewable, type: bug, type: feature

#1584 Enable compress attributes browserify transform by default
  BUILDING.md
  package.json
  tasks/bundle.js
  tasks/cibundle.js
  tasks/compress_attributes.js
  tasks/util/browserify_wrapper.js
  tasks/util/watchified_bundle.js
  test/jasmine/bundle_tests/plotschema_test.js
  test/jasmine/karma.conf.js
Labels: status: reviewable, type: maintenance, type: performance

#2977 Add `polar.hole`
  src/plots/polar/constants.js
  src/plots/polar/layout_attributes.js
  src/plots/polar/layout_defaults.js
  src/plots/polar/polar.js
  src/plots/polar/set_convert.js
  test/image/baselines/glpolar_scatter.png
  test/image/baselines/glpolar_style.png
  test/image/baselines/glpolar_subplots.png
  test/image/baselines/polar_bar-overlay.png
  test/image/baselines/polar_bar-stacked.png
  test/image/baselines/polar_bar-width-base-offset.png
  test/image/baselines/polar_blank.png
  test/image/baselines/polar_categories.png
  test/image/baselines/polar_dates.png
  test/image/baselines/polar_direction.png
  test/image/baselines/polar_fills.png
  test/image/baselines/polar_funky-bars.png
  test/image/baselines/polar_hole.png
  test/image/baselines/polar_line.png
  test/image/baselines/polar_polygon-bars.png
  test/image/baselines/polar_polygon-grids.png
  test/image/baselines/polar_r0dr-theta0dtheta.png
  test/image/baselines/polar_radial-range.png
  test/image/baselines/polar_scatter.png
  test/image/baselines/polar_sector.png
  test/image/baselines/polar_subplots.png
  test/image/baselines/polar_ticks.png
  test/image/baselines/polar_transforms.png
  test/image/baselines/polar_wind-rose.png
  test/image/mocks/polar_hole.json
  test/jasmine/tests/barpolar_test.js
  test/jasmine/tests/polar_test.js
  test/jasmine/tests/scatterpolar_test.js
Labels: status: reviewable, type: bug, type: feature

#2978 fix layer ordering of scatter subtypes
  src/components/legend/style.js
  src/traces/scatter/plot.js
  src/traces/scatter/style.js
  src/traces/scattergeo/style.js
  test/jasmine/assets/custom_assertions.js
  test/jasmine/assets/transitions.js
  test/jasmine/tests/cartesian_test.js
  test/jasmine/tests/scatter_test.js
  test/jasmine/tests/select_test.js
Labels: status: reviewable, type: bug

#2993 Ternary w/o ticks fixes
  src/plots/ternary/index.js
  src/plots/ternary/layout/attributes.js
  src/plots/ternary/layout/axis_defaults.js
  src/plots/ternary/layout/defaults.js
  src/plots/ternary/layout/layout_attributes.js
  src/plots/ternary/layout_attributes.js
  src/plots/ternary/layout_defaults.js
  src/plots/ternary/ternary.js
  test/image/baselines/ternary_noticks.png
  test/image/mocks/ternary_noticks.json
  test/jasmine/tests/polar_test.js
  test/jasmine/tests/ternary_test.js
Labels: status: reviewable, type: bug

#2986 Emit 'plotly_webglcontextlost' event on WebGL context lost
  src/lib/prepare_regl.js
  src/plots/gl3d/scene.js
  test/jasmine/tests/gl2d_plot_interact_test.js
  test/jasmine/tests/gl3d_plot_interact_test.js
  test/jasmine/tests/parcoords_test.js
Labels: status: reviewable, type: feature

#2995 Convert typed array to 'regular' arrays before sendToCloud
  src/plots/plots.js
  test/jasmine/tests/plots_test.js
Labels: status: reviewable, type: bug

#2990 Fix scattergl missing lines after non-line trace
  package-lock.json
  package.json
  src/traces/scattergl/index.js
  test/image/baselines/gl2d_fill-ordering.png
  test/image/baselines/gl2d_text_chart_basic.png
  test/image/baselines/gl2d_text_chart_single-string.png
  test/image/mocks/gl2d_fill-ordering.json
Labels: status: reviewable, type: bug

#2996 There are now 4 `<g.drag>` nodes in polar subplots
  test/jasmine/tests/plot_api_test.js
Labels: status: reviewable, type: maintenance

#3005 Fix stacked area layering and deletion bugs
  src/traces/scatter/attributes.js
  src/traces/scatter/calc.js
  src/traces/scatter/link_traces.js
  src/traces/scatter/plot.js
  test/image/baselines/stacked_area_groups.png
  test/image/mocks/stacked_area_groups.json
  test/jasmine/tests/scatter_test.js
Labels: status: reviewable, type: bug

#3015 Update splom zero line logic
  src/plots/cartesian/axes.js
  src/traces/splom/base_plot.js
  test/image/baselines/splom_large.png
  test/image/mocks/splom_large.json
  test/jasmine/tests/splom_test.js
Labels: status: reviewable, type: bug

#3017 Fix #3013 - broken stacked area gap insertion case
  src/traces/scatter/cross_trace_calc.js
  test/image/baselines/stacked_area.png
  test/image/mocks/stacked_area.json
  test/jasmine/tests/scatter_test.js
Labels: status: reviewable, type: bug

#3011 scatter3d display errorbars when error_z is not specified
  src/traces/scatter3d/convert.js
  test/image/baselines/gl3d_errorbars_xy.png
  test/image/mocks/gl3d_errorbars_xy.json
  test/image/mocks/gl3d_errorbars_zx.json
Labels: status: reviewable, type: bug

#2992 scatter3d now performs axis transformation on error bars
  src/plots/gl3d/scene.js
  src/traces/scatter3d/calc_errors.js
  src/traces/scatter3d/convert.js
  test/image/baselines/gl3d_error_bars_log.png
  test/image/baselines/gl3d_error_bars_log_2.png
  test/image/mocks/gl3d_error_bars_log.json
  test/image/mocks/gl3d_error_bars_log_2.json
Labels: status: reviewable, type: bug

#3016 Don't skip over dtick and tick0 in geo subplot in diffLayout
  src/plot_api/plot_api.js
  test/jasmine/tests/plot_api_test.js
Labels: status: reviewable, type: bug

#3021 Make polar be more graceful on non sense inputs
  src/lib/angles.js
  src/plots/polar/polar.js
  src/plots/polar/set_convert.js
  src/traces/splom/defaults.js
  test/image/baselines/polar_blank.png
  test/image/mocks/polar_blank.json
  test/image/mocks/polar_sector.json
  test/jasmine/tests/gl2d_plot_interact_test.js
  test/jasmine/tests/polar_test.js
  test/jasmine/tests/select_test.js
Labels: status: reviewable, type: bug, type: maintenance

#2997 DragElement: initialize clientX and clientY for touch events
  src/components/dragelement/index.js
  test/jasmine/tests/hover_label_test.js
Labels: status: reviewable, type: bug

#3018 Fix support for Latex in legends
  src/components/legend/constants.js
  src/components/legend/draw.js
  test/image/baselines/mathjax.png
  test/image/mocks/mathjax.json
Labels: status: reviewable, type: bug

#3028 Reset updates object on every zoomDone
  src/plots/cartesian/dragbox.js
  test/jasmine/tests/cartesian_interact_test.js
Labels: status: reviewable, type: bug

#3023 Fix #3022 - validate + polar.bargap
  src/plot_api/validate.js
  src/plots/polar/legacy/area_attributes.js
  src/plots/polar/legacy/axis_attributes.js
  src/traces/barpolar/layout_defaults.js
  src/traces/scatter/attributes.js
  test/jasmine/tests/barpolar_test.js
  test/jasmine/tests/validate_test.js
Labels: status: reviewable, type: bug

#3040 Polar 'text' in hover labels fixes
  src/traces/barpolar/hover.js
  src/traces/scatterpolar/hover.js
  src/traces/scatterpolargl/index.js
  test/jasmine/tests/barpolar_test.js
  test/jasmine/tests/scatterpolar_test.js
  test/jasmine/tests/scatterpolargl_test.js
Labels: status: reviewable, type: bug

#3030 Fix pie's support for individual stroke width values [2989]
  src/components/legend/get_legend_data.js
  test/jasmine/tests/pie_test.js
Labels: status: reviewable, type: bug

#3033 fallback to max-width and max-height if necessary
  src/plots/plots.js
  test/jasmine/tests/config_test.js
Labels: status: reviewable, type: bug

#3048 Fix hover label coloring on white bgcolor
  src/components/fx/hover.js
  test/jasmine/tests/hover_label_test.js
Labels: status: reviewable, type: bug

#3043 Rotate hover labels in a few more scenarios
  src/components/fx/hover.js
  test/jasmine/assets/custom_assertions.js
  test/jasmine/tests/hover_label_test.js
  test/jasmine/tests/violin_test.js
Labels: status: reviewable, type: bug

#3053 Do not to look for 'add' or 'remove' when replacing array containers
  src/plot_api/plot_api.js
  test/jasmine/tests/shapes_test.js
Labels: status: reviewable, type: bug

#2987 Pie title
  src/traces/pie/attributes.js
  src/traces/pie/defaults.js
  src/traces/pie/plot.js
  test/image/baselines/pie_title_groupscale.png
  test/image/baselines/pie_title_middle_center.png
  test/image/baselines/pie_title_middle_center_multiline.png
  test/image/baselines/pie_title_multiple.png
  test/image/baselines/pie_title_pull.png
  test/image/baselines/pie_title_subscript.png
  test/image/baselines/pie_title_variations.png
  test/image/mocks/pie_title_groupscale.json
  test/image/mocks/pie_title_middle_center.json
  test/image/mocks/pie_title_middle_center_multiline.json
  test/image/mocks/pie_title_multiple.json
  test/image/mocks/pie_title_pull.json
  test/image/mocks/pie_title_subscript.json
  test/image/mocks/pie_title_variations.json
  test/jasmine/tests/pie_test.js
Labels: status: reviewable, type: feature
