Repository plotly/plotly.js, pull requests merged in 2018-02, with the labels that each got.

#2339 Negate axis offset and then turn it into a string
  src/components/fx/hover.js
  src/components/modebar/buttons.js
  src/components/modebar/manage.js
  src/plots/ternary/ternary.js
  test/image/strict-d3.js
  test/jasmine/tests/gl3d_plot_interact_test.js
  test/jasmine/tests/hover_label_test.js
  test/jasmine/tests/modebar_test.js
  test/jasmine/tests/ternary_test.js
Labels: status: reviewable, type: bug

#2360 fix errorbars for Plotly.react and for uneven data arrays
  src/components/errorbars/compute_error.js
  src/components/errorbars/defaults.js
  src/components/errorbars/plot.js
  test/image/mocks/basic_error_bar.json
  test/jasmine/tests/errorbars_test.js
  test/jasmine/tests/plot_api_test.js
Labels: status: reviewable, type: bug

#2361 Bump mapbox gl to 0.44.0
  package-lock.json
  package.json
  src/components/drawing/index.js
  src/plots/cartesian/dragbox.js
  src/plots/mapbox/constants.js
  src/plots/mapbox/index.js
  src/plots/mapbox/layers.js
  src/plots/mapbox/mapbox.js
  src/snapshot/helpers.js
  src/traces/scattermapbox/attributes.js
  src/traces/scattermapbox/convert.js
  src/traces/scattermapbox/defaults.js
  src/traces/scattermapbox/hover.js
  src/traces/scattermapbox/plot.js
  src/traces/scattermapbox/select.js
  tasks/noci_test.sh
  test/image/baselines/mapbox_0.png
  test/image/baselines/mapbox_angles.png
  test/image/baselines/mapbox_bubbles-text.png
  test/image/baselines/mapbox_bubbles.png
  test/image/baselines/mapbox_connectgaps.png
  test/image/baselines/mapbox_custom-style.png
  test/image/baselines/mapbox_fill.png
  test/image/baselines/mapbox_layers.png
  test/image/baselines/mapbox_symbol-text.png
  test/image/mocks/mapbox_bubbles.json
  test/jasmine/tests/mapbox_test.js
  test/jasmine/tests/scattermapbox_test.js
  test/jasmine/tests/select_test.js
Labels: status: reviewable, type: bug, type: feature, type: maintenance, type: performance

#2368 Fix edits for date-string referenced annotations
  src/components/annotations/draw.js
  test/jasmine/tests/annotations_test.js
Labels: status: reviewable, type: bug

#2375 Relink less stuff
  src/lib/relink_private.js
  src/plots/attributes.js
  tasks/util/make_schema.js
  test/jasmine/tests/lib_test.js
Labels: status: reviewable, type: performance

#2373 Auto-retry jasmine test on CI
  .circleci/test.sh
  test/jasmine/tests/animate_test.js
  test/jasmine/tests/gl2d_plot_interact_test.js
  test/jasmine/tests/parcoords_test.js
  test/jasmine/tests/select_test.js
Labels: status: reviewable, type: maintenance

#2378 Implement `cliponaxis: false` for bar text
  src/components/drawing/index.js
  src/plot_api/subroutines.js
  src/plots/cartesian/dragbox.js
  src/traces/bar/attributes.js
  src/traces/bar/defaults.js
  src/traces/bar/plot.js
  test/image/baselines/bar_cliponaxis-false.png
  test/image/mocks/bar_cliponaxis-false.json
  test/jasmine/tests/bar_test.js
  test/jasmine/tests/cartesian_interact_test.js
  test/jasmine/tests/scatter_test.js
  test/jasmine/tests/select_test.js
  test/jasmine/tests/shapes_test.js
Labels: status: reviewable, type: feature

#2377 Fix color clustering
  package-lock.json
  package.json
  src/lib/index.js
  src/traces/box/plot.js
  src/traces/scattergl/index.js
  test/image/baselines/gl2d_line_select.png
  test/image/baselines/gl2d_scatter-color-clustering.png
  test/image/mocks/gl2d_line_select.json
  test/image/mocks/gl2d_scatter-color-clustering.json
  test/jasmine/tests/gl2d_plot_interact_test.js
Labels: status: reviewable, type: bug

#2399 Layout grids
  src/lib/coerce.js
  src/lib/regex.js
  src/lib/stats.js
  src/plot_api/plot_schema.js
  src/plot_api/validate.js
  src/plots/cartesian/constants.js
  src/plots/cartesian/layout_attributes.js
  src/plots/cartesian/layout_defaults.js
  src/plots/cartesian/position_defaults.js
  src/plots/domain.js
  src/plots/geo/layout/layout_attributes.js
  src/plots/gl3d/layout/layout_attributes.js
  src/plots/grid.js
  src/plots/layout_attributes.js
  src/plots/mapbox/layout_attributes.js
  src/plots/plots.js
  src/plots/polar/layout_attributes.js
  src/plots/subplot_defaults.js
  src/plots/ternary/layout/layout_attributes.js
  src/traces/parcoords/attributes.js
  src/traces/parcoords/calc.js
  src/traces/parcoords/defaults.js
  src/traces/parcoords/parcoords.js
  src/traces/pie/attributes.js
  src/traces/pie/defaults.js
  src/traces/sankey/attributes.js
  src/traces/sankey/defaults.js
  src/traces/table/attributes.js
  src/traces/table/defaults.js
  test/image/baselines/grid_subplot_types.png
  test/image/mocks/grid_subplot_types.json
  test/image/mocks/grouped_bar.json
  test/jasmine/tests/annotations_test.js
  test/jasmine/tests/gl3d_plot_interact_test.js
  test/jasmine/tests/lib_test.js
  test/jasmine/tests/parcoords_test.js
  test/jasmine/tests/plots_test.js
  test/jasmine/tests/validate_test.js
Labels: status: reviewable, type: feature

#2406 Plotly.purge in parcoords_test
  test/jasmine/tests/parcoords_test.js
Labels: status: reviewable, type: maintenance

#2413 Fix yet another histogram edge case
  src/plots/cartesian/axes.js
  src/traces/histogram/calc.js
  test/jasmine/tests/axes_test.js
  test/jasmine/tests/histogram2d_test.js
  test/jasmine/tests/histogram_test.js
Labels: type: bug

#2411 fall back for contour labels when there's only one contour
  src/plots/cartesian/axes.js
  src/traces/carpet/calc_gridlines.js
  src/traces/contour/plot.js
  test/jasmine/tests/contour_test.js
Labels: type: bug

#2414 push hover labels in to the bar group extent in compare mode
  src/traces/bar/hover.js
  src/traces/bar/set_positions.js
  test/jasmine/tests/bar_test.js
Labels: status: reviewable, type: bug

#2416 Clean up removed axes and axis lines
  src/plot_api/subroutines.js
  src/plots/cartesian/index.js
  test/jasmine/tests/cartesian_test.js
Labels: status: reviewable, type: bug

#2422 Z exponent fix
  src/plots/cartesian/axes.js
  test/jasmine/tests/hover_label_test.js
Labels: type: bug

#2404 On-par autorange for scattergl
  src/plot_api/plot_api.js
  src/plots/cartesian/axes.js
  src/traces/scatter/calc.js
  src/traces/scattergl/index.js
  test/image/baselines/gl2d_10.png
  test/image/baselines/gl2d_12.png
  test/image/baselines/gl2d_14.png
  test/image/baselines/gl2d_17.png
  test/image/baselines/gl2d_axes_booleans.png
  test/image/baselines/gl2d_axes_labels.png
  test/image/baselines/gl2d_axes_labels2.png
  test/image/baselines/gl2d_axes_lines.png
  test/image/baselines/gl2d_axes_range_mode.png
  test/image/baselines/gl2d_axes_range_type.png
  test/image/baselines/gl2d_clean-number.png
  test/image/baselines/gl2d_connect_gaps.png
  test/image/baselines/gl2d_date_axes.png
  test/image/baselines/gl2d_error_bars.png
  test/image/baselines/gl2d_error_bars_log.png
  test/image/baselines/gl2d_fonts.png
  test/image/baselines/gl2d_layout_image.png
  test/image/baselines/gl2d_line_aligned.png
  test/image/baselines/gl2d_line_dash.png
  test/image/baselines/gl2d_line_select.png
  test/image/baselines/gl2d_marker_size.png
  test/image/baselines/gl2d_marker_symbols.png
  test/image/baselines/gl2d_multiple-traces-axes-labels.png
  test/image/baselines/gl2d_multiple-traces-axes.png
  test/image/baselines/gl2d_multiple_subplots.png
  test/image/baselines/gl2d_open_marker_line_width.png
  test/image/baselines/gl2d_scatter-color-clustering.png
  test/image/baselines/gl2d_scatter-colorscale-colorbar.png
  test/image/baselines/gl2d_scatter-colorscale-points.png
  test/image/baselines/gl2d_scatter-marker-line-colorscales.png
  test/image/baselines/gl2d_scatter_fill_self_next.png
  test/image/baselines/gl2d_shapes_below_traces.png
  test/image/baselines/gl2d_simple_inset.png
  test/image/baselines/gl2d_size_margins.png
  test/image/baselines/gl2d_stacked_coupled_subplots.png
  test/image/baselines/gl2d_stacked_subplots.png
  test/image/baselines/gl2d_subplots_anchor.png
  test/image/baselines/gl2d_tick-labels.png
  test/image/mocks/gl2d_clean-number.json
  test/jasmine/tests/gl2d_click_test.js
  test/jasmine/tests/gl2d_plot_interact_test.js
  test/jasmine/tests/plot_api_test.js
Labels: status: reviewable, type: bug, type: feature
