Repository plotly/plotly.js, pull requests merged in 2018-03, with the labels that each got.

#2426 Legend scroll fix
  src/components/dragelement/index.js
  src/components/legend/constants.js
  src/components/legend/draw.js
  test/jasmine/tests/legend_scroll_test.js
Labels: status: reviewable, type: bug

#2243 automatic margins for long labels
  src/plot_api/edit_types.js
  src/plot_api/helpers.js
  src/plot_api/plot_api.js
  src/plots/cartesian/axes.js
  src/plots/cartesian/axis_defaults.js
  src/plots/cartesian/layout_attributes.js
  src/plots/cartesian/layout_defaults.js
  src/plots/polar/polar.js
  src/plots/ternary/ternary.js
  test/image/baselines/long_axis_labels.png
  test/image/mocks/long_axis_labels.json
  test/jasmine/tests/axes_test.js
Labels: status: reviewable, type: feature

#2424 [WIP] Vertically center multi-line labels on Y axis
  src/plots/cartesian/axes.js
  test/image/baselines/bar_multiline_labels.png
  test/image/baselines/benchmarks.png
  test/image/baselines/cliponaxis_false-dates-log.png
  test/image/baselines/gl2d_date_axes.png
  test/image/baselines/world-cals.png
  test/image/mocks/bar_multiline_labels.json
Labels: type: bug

#2445 Fix stacking of centered hover info elements #865
  src/components/fx/hover.js
  test/jasmine/tests/hover_label_test.js
Labels: type: bug

#2442 scattergl visible restyle fix
  src/traces/scattergl/attributes.js
  src/traces/scattergl/index.js
  test/jasmine/tests/gl2d_plot_interact_test.js
Labels: status: reviewable, type: bug

#2449 Fix category angular axis mocked range logic
  src/plots/polar/polar.js
  src/traces/scatterpolar/calc.js
  test/jasmine/tests/polar_test.js
Labels: status: reviewable, type: bug

#2447 Bundle with browser-pack-flat plugin
  package-lock.json
  package.json
  tasks/bundle.js
  tasks/util/browserify_wrapper.js
Labels: status: reviewable, type: maintenance

#2451 Fix rangeslider titles with stacked y axes
  src/components/rangeslider/draw.js
  src/components/titles/index.js
  src/plots/cartesian/axes.js
  src/plots/cartesian/index.js
  src/plots/plots.js
  test/image/baselines/candlestick_rangeslider_thai.png
  test/image/baselines/range_slider.png
  test/image/baselines/range_slider_axes_double.png
  test/image/baselines/range_slider_axes_stacked.png
  test/image/baselines/range_slider_box.png
  test/image/baselines/range_slider_initial_expanded.png
  test/image/baselines/range_slider_initial_valid.png
  test/image/baselines/range_slider_multiple.png
  test/image/mocks/range_slider_axes_stacked.json
  test/image/mocks/range_slider_multiple.json
Labels: type: bug, type: regression

#2364 Rangeslider allow zoom on oppaxis
  src/components/rangeslider/attributes.js
  src/components/rangeslider/constants.js
  src/components/rangeslider/defaults.js
  src/components/rangeslider/draw.js
  src/components/rangeslider/index.js
  src/components/rangeslider/oppaxis_attributes.js
  src/plots/cartesian/autorange.js
  src/plots/cartesian/axis_defaults.js
  test/image/baselines/range_slider_rangemode.png
  test/image/mocks/range_slider_rangemode.json
  test/jasmine/tests/axes_test.js
  test/jasmine/tests/plotschema_test.js
  test/jasmine/tests/range_slider_test.js
  test/jasmine/tests/validate_test.js
Labels: status: reviewable, type: feature

#2454 fix #1645 - ensure we don't draw ticks if there are none to draw
  src/plots/cartesian/axes.js
  test/jasmine/tests/axes_test.js
Labels: type: bug

#2455 fix #2452 - removing and adding scatter(gl) as not the first module
  src/plots/cartesian/index.js
  src/traces/scattergl/index.js
  test/jasmine/tests/cartesian_test.js
  test/jasmine/tests/gl2d_plot_interact_test.js
Labels: status: reviewable, type: bug

#2458 Polar + flat-pack
  src/plots/cartesian/axes.js
Labels: type: bug, type: regression

#2461 throw an error if the test window is hidden
  test/jasmine/assets/mouse_event.js
Labels: status: reviewable, type: maintenance

#2464 Bundle with pack-flat on ci
  tasks/cibundle.js
Labels: status: reviewable, type: maintenance

#2467 Bump and ping mapbox-gl to 0.44.1
  package-lock.json
  package.json
  src/plots/mapbox/constants.js
Labels: status: reviewable, type: bug

#2479 fixed typo
  src/plots/cartesian/attributes.js
Labels: type: documentation

#2492 Fix scattergl selectedpoints clearance under select/lasso drag modes
  src/constants/gl2d_dashes.js
  src/traces/scattergl/attributes.js
  src/traces/scattergl/constants.js
  src/traces/scattergl/convert.js
  src/traces/scattergl/index.js
  test/jasmine/tests/gl2d_plot_interact_test.js
Labels: status: reviewable, type: bug

#2487 More optimization for cartesian subplots
  src/plot_api/plot_api.js
  src/plot_api/subroutines.js
  src/plots/cartesian/axes.js
Labels: status: reviewable, type: performance

#2474 Perf drawFramwork
  src/components/colorbar/draw.js
  src/components/drawing/index.js
  src/components/fx/hover.js
  src/components/legend/draw.js
  src/components/legend/style.js
  src/components/rangeselector/draw.js
  src/components/rangeslider/draw.js
  src/components/sliders/draw.js
  src/components/titles/index.js
  src/components/updatemenus/draw.js
  src/lib/index.js
  src/plot_api/plot_api.js
  src/plot_api/subroutines.js
  src/plots/cartesian/axes.js
  src/plots/cartesian/dragbox.js
  src/plots/cartesian/index.js
  src/plots/plots.js
  src/plots/ternary/ternary.js
  src/traces/carpet/plot.js
  src/traces/contour/plot.js
  src/traces/contourcarpet/plot.js
  src/traces/pie/plot.js
  test/jasmine/assets/custom_matchers.js
  test/jasmine/tests/cartesian_test.js
  test/jasmine/tests/click_test.js
  test/jasmine/tests/drawing_test.js
  test/jasmine/tests/plot_api_test.js
  test/jasmine/tests/plot_interact_test.js
Labels: status: reviewable, type: performance

#2483 Czech localization
  lib/locales/cs.js
Labels: type: translation

#2503 Fix scattergl unselected marker opacity for array marker opacity traces
  src/traces/scattergl/convert.js
  test/image/baselines/gl2d_selectedpoints.png
  test/image/mocks/gl2d_selectedpoints.json
Labels: status: reviewable, type: bug

#2499 Point cluster dev
  package-lock.json
  package.json
  src/traces/scattergl/convert.js
  src/traces/scattergl/index.js
  src/traces/scatterpolargl/index.js
  tasks/test_syntax.js
  test/image/baselines/gl2d_14.png
  test/image/baselines/gl2d_17.png
  test/image/baselines/gl2d_annotations.png
  test/image/baselines/gl2d_axes_booleans.png
  test/image/baselines/gl2d_axes_labels.png
  test/image/baselines/gl2d_axes_labels2.png
  test/image/baselines/gl2d_axes_lines.png
  test/image/baselines/gl2d_axes_range_manual.png
  test/image/baselines/gl2d_axes_range_mode.png
  test/image/baselines/gl2d_axes_range_type.png
  test/image/baselines/gl2d_clean-number.png
  test/image/baselines/gl2d_date_axes.png
  test/image/baselines/gl2d_error_bars.png
  test/image/baselines/gl2d_fonts.png
  test/image/baselines/gl2d_layout_image.png
  test/image/baselines/gl2d_line_aligned.png
  test/image/baselines/gl2d_line_dash.png
  test/image/baselines/gl2d_multiple-traces-axes-labels.png
  test/image/baselines/gl2d_multiple-traces-axes.png
  test/image/baselines/gl2d_multiple_subplots.png
  test/image/baselines/gl2d_scatter-color-clustering.png
  test/image/baselines/gl2d_scatter-colorscale-colorbar.png
  test/image/baselines/gl2d_scatter-colorscale-points.png
  test/image/baselines/gl2d_scatter-subplot-panel.png
  test/image/baselines/gl2d_scatter_fill_self_next.png
  test/image/baselines/gl2d_selectedpoints.png
  test/image/baselines/gl2d_shapes_below_traces.png
  test/image/baselines/gl2d_simple_inset.png
  test/image/baselines/gl2d_size_margins.png
  test/image/baselines/gl2d_stacked_coupled_subplots.png
  test/image/baselines/gl2d_stacked_subplots.png
  test/image/baselines/gl2d_tick-labels.png
  test/image/baselines/glpolar_scatter.png
  test/image/baselines/glpolar_style.png
  test/image/mocks/gl2d_selectedpoints.json
  test/jasmine/tests/gl2d_click_test.js
  test/jasmine/tests/gl2d_plot_interact_test.js
Labels: status: reviewable, type: performance

#2511 Support ragged tables and show full table borders
  src/traces/table/data_preparation_helper.js
  src/traces/table/plot.js
  test/image/baselines/grid_subplot_types.png
  test/image/baselines/table_latex_multitrace.png
  test/image/baselines/table_latex_multitrace_scatter.png
  test/image/baselines/table_plain_birds.png
  test/image/baselines/table_ragged.png
  test/image/baselines/table_wrapped_birds.png
  test/image/mocks/table_latex_multitrace.json
  test/image/mocks/table_latex_multitrace_scatter.json
  test/image/mocks/table_plain_birds.json
  test/image/mocks/table_ragged.json
  test/image/mocks/table_wrapped_birds.json
  test/jasmine/tests/table_test.js
Labels: status: reviewable, type: bug, type: feature

#2489 Make ordered category algo skip over visible false traces
  src/plots/cartesian/axis_defaults.js
  src/plots/cartesian/category_order_defaults.js
  src/plots/cartesian/ordered_categories.js
  src/plots/polar/layout_defaults.js
  src/traces/carpet/axis_defaults.js
  test/jasmine/tests/calcdata_test.js
Labels: status: reviewable, type: bug

#2513 fixes #2512 - skip over BADNUM lonlat in scattermapbox select
  src/traces/scattermapbox/select.js
  test/jasmine/tests/select_test.js
Labels: status: reviewable, type: bug
