Repository plotly/plotly.js, pull requests merged in 2018-07, with the labels that each got.

#2766 Fix mapbox interaction inconsistencies
  src/components/drawing/index.js
  src/plots/mapbox/mapbox.js
  src/traces/scattermapbox/defaults.js
  test/jasmine/tests/mapbox_test.js
  test/jasmine/tests/scattermapbox_test.js
Labels: status: reviewable, type: bug

#2776 Fix x-only zoom moves when `xaxis.fixedrange: true`
  src/plots/cartesian/dragbox.js
  test/jasmine/tests/cartesian_interact_test.js
Labels: status: reviewable, type: bug

#2773 Emit 'plotly_afterplot' on all edits
  src/plot_api/plot_api.js
  src/plot_api/subroutines.js
  src/plots/plots.js
  test/jasmine/tests/plot_api_test.js
Labels: status: reviewable, type: bug

#2775 Fix bandwidth for single-value violins
  src/traces/violin/calc.js
  test/jasmine/tests/violin_test.js
Labels: status: reviewable, type: bug

#2762 Revamp of mode bar's createIcon
  build/ploticon.js
  src/components/modebar/modebar.js
  tasks/util/pull_font_svg.js
  test/jasmine/tests/modebar_test.js
Labels: status: reviewable, type: feature

#2737 Enable text for scattergl trace
  package-lock.json
  package.json
  src/components/drawing/index.js
  src/traces/scattergl/attributes.js
  src/traces/scattergl/convert.js
  src/traces/scattergl/defaults.js
  src/traces/scattergl/index.js
  src/traces/scatterpolargl/index.js
  src/traces/splom/index.js
  tasks/header.js
  test/image/baselines/gl2d_point-selection.png
  test/image/baselines/gl2d_text_chart_arrays.png
  test/image/baselines/gl2d_text_chart_basic.png
  test/image/baselines/gl2d_text_chart_invalid-arrays.png
  test/image/baselines/gl2d_text_chart_single-string.png
  test/image/baselines/gl2d_text_chart_styling.png
  test/image/mocks/gl2d_point-selection.json
  test/image/mocks/gl2d_text_chart_arrays.json
  test/image/mocks/gl2d_text_chart_basic.json
  test/image/mocks/gl2d_text_chart_invalid-arrays.json
  test/image/mocks/gl2d_text_chart_single-string.json
  test/image/mocks/gl2d_text_chart_styling.json
  test/jasmine/tests/gl2d_click_test.js
  test/jasmine/tests/gl2d_plot_interact_test.js
Labels: status: reviewable, type: feature

#2658 3D streamtube traces
  lib/index-gl3d.js
  lib/index.js
  lib/streamtube.js
  package-lock.json
  package.json
  src/components/colorscale/attributes.js
  src/components/colorscale/color_attributes.js
  src/plots/gl3d/scene.js
  src/plots/gl3d/zip3.js
  src/traces/bar/attributes.js
  src/traces/choropleth/attributes.js
  src/traces/cone/attributes.js
  src/traces/cone/calc.js
  src/traces/cone/convert.js
  src/traces/contour/attributes.js
  src/traces/contourcarpet/attributes.js
  src/traces/heatmap/attributes.js
  src/traces/heatmapgl/attributes.js
  src/traces/histogram2d/attributes.js
  src/traces/histogram2dcontour/attributes.js
  src/traces/mesh3d/attributes.js
  src/traces/mesh3d/convert.js
  src/traces/parcoords/attributes.js
  src/traces/scatter/attributes.js
  src/traces/scatter3d/attributes.js
  src/traces/scattercarpet/attributes.js
  src/traces/scattergeo/attributes.js
  src/traces/scattergl/attributes.js
  src/traces/scatterternary/attributes.js
  src/traces/streamtube/attributes.js
  src/traces/streamtube/calc.js
  src/traces/streamtube/convert.js
  src/traces/streamtube/defaults.js
  src/traces/streamtube/index.js
  src/traces/surface/attributes.js
  test/image/baselines/gl3d_cone-with-streamtube.png
  test/image/baselines/gl3d_streamtube-first.png
  test/image/baselines/gl3d_streamtube-simple.png
  test/image/baselines/gl3d_streamtube-thin.png
  test/image/baselines/gl3d_streamtube-wind.png
  test/image/mocks/gl3d_cone-with-streamtube.json
  test/image/mocks/gl3d_streamtube-first.json
  test/image/mocks/gl3d_streamtube-simple.json
  test/image/mocks/gl3d_streamtube-thin.json
  test/image/mocks/gl3d_streamtube-wind.json
  test/jasmine/tests/cone_test.js
  test/jasmine/tests/plot_api_test.js
  test/jasmine/tests/streamtube_test.js
Labels: status: reviewable, type: feature

#2670 NPM pkg for dist bundles
  BUILDING.md
  CONTRIBUTING.md
  README.md
  package.json
  tasks/stats.js
  tasks/sync_packages.js
  tasks/util/common.js
Labels: status: reviewable, type: feature

#2783 Use @etpinard/gl-text
  package-lock.json
  package.json
  src/traces/scattergl/index.js
Labels: status: reviewable, type: bug

#2784 Fix typo in postpublish script
  package.json
Labels: status: reviewable, type: maintenance

#2785 Fix box & violin inner parts removal
  src/traces/box/plot.js
  src/traces/violin/plot.js
  src/traces/violin/style.js
  test/jasmine/tests/box_test.js
  test/jasmine/tests/violin_test.js
Labels: status: reviewable, type: bug

#2789 Set minify option 'compress' to false to fix mapbox-gl minification
  tasks/bundle.js
  tasks/cibundle.js
  tasks/util/constants.js
Labels: type: bug, type: maintenance

#2801 Use updated fullLayout._size in scene.clear
  src/traces/scattergl/index.js
  test/jasmine/tests/gl2d_click_test.js
Labels: status: reviewable, type: bug

#2805 Transform removal from react fix
  src/plots/plots.js
  test/jasmine/tests/transform_filter_test.js
  test/jasmine/tests/transform_multi_test.js
Labels: status: reviewable, type: bug

#2806 Fix contour labels that required "thousands" suffixes
  src/traces/contour/plot.js
  test/image/baselines/contour_label-thousands-suffix.png
  test/image/mocks/contour_label-thousands-suffix.json
Labels: status: reviewable, type: bug

#2793 Do not clear _glcanvas ref during layout replot edits
  src/plot_api/plot_api.js
  test/jasmine/tests/gl2d_plot_interact_test.js
Labels: status: reviewable, type: bug

#2790 fix: tooltip misplaced in RTL documents
  src/css/_base.scss
Labels: status: reviewable, type: bug

#2811 Guard against undefined projection.invert results
  src/plots/geo/zoom.js
  test/jasmine/tests/geo_test.js
Labels: status: reviewable, type: bug

#2816 Fix legend item for 'legendonly' traces with array 'marker.symbol'
  src/components/legend/style.js
  test/image/baselines/legend_visibility.png
  test/image/mocks/legend_visibility.json
Labels: status: reviewable, type: bug

#2814 Do not collapse duplicate end points when `line.simplify: false`
  src/traces/scatter/line_points.js
  test/jasmine/tests/scatter_test.js
Labels: status: reviewable, type: bug

#2821 Mention documentation repo in issue template
  .github/ISSUE_TEMPLATE.md
Labels: type: documentation

#2831 Fix overlaying subplot configuration relayouts
  src/plot_api/subroutines.js
  src/plots/cartesian/axes.js
  src/plots/cartesian/graph_interact.js
  src/plots/cartesian/index.js
  src/plots/plots.js
  test/jasmine/tests/cartesian_test.js
  test/jasmine/tests/splom_test.js
Labels: status: reviewable, type: bug

#2829 Position-editable horizontal legend toggle fixups
  src/components/legend/draw.js
  test/jasmine/tests/legend_test.js
Labels: status: reviewable, type: bug

#2847 fix #1363 - honor tenths of milliseconds in old numeric date data
  src/plots/cartesian/set_convert.js
  test/jasmine/tests/axes_test.js
Labels: status: reviewable, type: bug

#2857 Fix 'yaxis-over-yaxis2' behavior
  src/plots/cartesian/index.js
  test/image/baselines/yaxis-over-yaxis2.png
  test/image/mocks/yaxis-over-yaxis2.json
Labels: status: reviewable, type: bug
