Repository plotly/plotly.js, pull requests merged in 2018-08, with the labels that each got.

#2823 Faster axis autorange + remove calcIfAutorange edit type
  src/components/annotations/attributes.js
  src/components/annotations/calc_autorange.js
  src/components/annotations/draw.js
  src/components/rangeslider/defaults.js
  src/components/shapes/attributes.js
  src/plot_api/edit_types.js
  src/plot_api/plot_api.js
  src/plots/cartesian/autorange.js
  src/plots/cartesian/axis_defaults.js
  src/plots/cartesian/layout_attributes.js
  src/traces/box/attributes.js
  src/traces/ohlc/attributes.js
  src/traces/scatter/attributes.js
  src/traces/scatter/calc.js
  test/jasmine/tests/annotations_test.js
  test/jasmine/tests/axes_test.js
  test/jasmine/tests/box_test.js
  test/jasmine/tests/finance_test.js
  test/jasmine/tests/gl2d_click_test.js
  test/jasmine/tests/gl2d_pointcloud_test.js
  test/jasmine/tests/plot_api_test.js
  test/jasmine/tests/scatter_test.js
  test/jasmine/tests/shapes_test.js
Labels: status: reviewable, type: performance

#2860 Recycled commits from abandoned fast trace toggle PRs
  src/components/annotations/calc_autorange.js
  src/components/annotations/defaults.js
  src/components/errorbars/calc.js
  src/components/rangeslider/calc_autorange.js
  src/components/shapes/calc_autorange.js
  src/components/shapes/defaults.js
  src/lib/index.js
  src/plot_api/subroutines.js
  src/plots/cartesian/autorange.js
  src/plots/cartesian/axes.js
  src/plots/cartesian/constraints.js
  src/plots/cartesian/index.js
  src/plots/cartesian/layout_defaults.js
  src/plots/cartesian/set_convert.js
  src/plots/cartesian/type_defaults.js
  src/plots/get_data.js
  src/plots/gl2d/scene2d.js
  src/plots/plots.js
  src/plots/polar/layout_defaults.js
  src/plots/polar/polar.js
  src/traces/bar/calc.js
  src/traces/bar/set_positions.js
  src/traces/box/calc.js
  src/traces/box/set_positions.js
  src/traces/carpet/calc.js
  src/traces/contourgl/convert.js
  src/traces/heatmap/calc.js
  src/traces/heatmapgl/convert.js
  src/traces/ohlc/calc.js
  src/traces/pointcloud/convert.js
  src/traces/scatter/calc.js
  src/traces/scattergl/convert.js
  src/traces/scattergl/index.js
  src/traces/scatterpolar/calc.js
  src/traces/scatterpolargl/index.js
  src/traces/splom/index.js
  src/traces/violin/calc.js
  test/image/baselines/polar_transforms.png
  test/image/mocks/polar_transforms.json
  test/jasmine/tests/annotations_test.js
  test/jasmine/tests/axes_test.js
  test/jasmine/tests/bar_test.js
  test/jasmine/tests/cartesian_test.js
  test/jasmine/tests/contour_test.js
  test/jasmine/tests/gl2d_plot_interact_test.js
  test/jasmine/tests/gl2d_pointcloud_test.js
  test/jasmine/tests/gl2d_scatterplot_contour_test.js
  test/jasmine/tests/heatmap_test.js
  test/jasmine/tests/scatter_test.js
  test/jasmine/tests/shapes_test.js
  test/jasmine/tests/splom_test.js
  test/jasmine/tests/transform_groupby_test.js
  test/jasmine/tests/transform_multi_test.js
Labels: status: reviewable, type: bug, type: maintenance, type: performance

#2840 Bound scalar marker size in legend item
  src/components/legend/style.js
  test/image/baselines/cliponaxis_false-dates-log.png
  test/image/baselines/error_bar_layers.png
  test/image/baselines/geo_bg-color.png
  test/image/baselines/gl2d_transforms.png
  test/image/baselines/gl3d_projection-traces.png
  test/image/baselines/line_scatter.png
  test/image/baselines/transforms.png
Labels: status: reviewable, type: bug

#2868 setPositions -> crossTraceCalc
  src/plot_api/plot_api.js
  src/plots/plots.js
  src/traces/bar/cross_trace_calc.js
  src/traces/bar/index.js
  src/traces/box/cross_trace_calc.js
  src/traces/box/index.js
  src/traces/candlestick/index.js
  src/traces/histogram/index.js
  src/traces/violin/cross_trace_calc.js
  src/traces/violin/index.js
  test/jasmine/tests/bar_test.js
  test/jasmine/tests/finance_test.js
  test/jasmine/tests/histogram_test.js
Labels: status: reviewable, type: maintenance

#2870 Pie colors fix & enhancements
  src/plot_api/plot_api.js
  src/plots/plots.js
  src/traces/pie/calc.js
  src/traces/pie/index.js
  src/traces/pie/layout_attributes.js
  src/traces/pie/layout_defaults.js
  test/jasmine/tests/annotations_test.js
  test/jasmine/tests/bar_test.js
  test/jasmine/tests/pie_test.js
Labels: status: reviewable, type: bug, type: feature, type: maintenance

#2879 Scatter3d attributes fixups
  src/components/colorscale/defaults.js
  src/traces/scatter/line_defaults.js
  src/traces/scatter3d/attributes.js
Labels: status: reviewable, type: documentation

#2815 Fix scattergl select -> dblclick -> pan bug
  src/traces/scattergl/index.js
  test/jasmine/tests/gl2d_click_test.js
Labels: status: reviewable, type: bug

#2895 Better polar setConvert + a few misc polar touch ups
  src/lib/angles.js
  src/lib/index.js
  src/plots/cartesian/axes.js
  src/plots/polar/helpers.js
  src/plots/polar/layout_defaults.js
  src/plots/polar/polar.js
  src/plots/polar/set_convert.js
  src/traces/bar/calc.js
  src/traces/scatter/line_points.js
  src/traces/scattergl/attributes.js
  src/traces/scattergl/defaults.js
  src/traces/scattergl/index.js
  src/traces/scatterpolar/attributes.js
  src/traces/scatterpolar/calc.js
  src/traces/scatterpolar/defaults.js
  src/traces/scatterpolar/hover.js
  src/traces/scatterpolar/index.js
  src/traces/scatterpolar/plot.js
  src/traces/scatterpolargl/attributes.js
  src/traces/scatterpolargl/defaults.js
  src/traces/scatterpolargl/index.js
  test/image/baselines/glpolar_subplots.png
  test/image/baselines/polar_r0dr-theta0dtheta.png
  test/image/mocks/glpolar_subplots.json
  test/image/mocks/polar_r0dr-theta0dtheta.json
  test/jasmine/tests/polar_test.js
  test/jasmine/tests/scatterpolar_test.js
Labels: status: reviewable, type: bug, type: feature

#2905 Apply derequire to generated bundles
  package-lock.json
  package.json
  tasks/util/browserify_wrapper.js
Labels: status: reviewable, type: bug

#2906 Bump dev deps that require sshpk
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#2891 Contour legend
  src/components/drawing/index.js
  src/components/legend/defaults.js
  src/components/legend/get_legend_data.js
  src/components/legend/helpers.js
  src/components/legend/style.js
  src/plots/layout_attributes.js
  src/plots/plots.js
  src/traces/contour/defaults.js
  src/traces/contour/plot.js
  src/traces/contour/style_defaults.js
  src/traces/contourcarpet/defaults.js
  src/traces/contourcarpet/plot.js
  src/traces/histogram2dcontour/index.js
  test/image/baselines/15.png
  test/image/baselines/5.png
  test/image/baselines/airfoil.png
  test/image/baselines/cheater.png
  test/image/baselines/cheater_constraints.png
  test/image/baselines/cheater_fully_filled.png
  test/image/baselines/cheater_smooth.png
  test/image/baselines/connectgaps_2d.png
  test/image/baselines/contour_constraints.png
  test/image/baselines/contour_heatmap_coloring.png
  test/image/baselines/contour_legend.png
  test/image/baselines/error_bar_layers.png
  test/image/baselines/range_slider.png
  test/image/baselines/range_slider_initial_expanded.png
  test/image/baselines/range_slider_initial_valid.png
  test/image/baselines/yaxis-over-yaxis2.png
  test/image/mocks/airfoil.json
  test/image/mocks/contour_legend.json
  test/jasmine/assets/custom_assertions.js
  test/jasmine/tests/carpet_test.js
  test/jasmine/tests/contour_test.js
  test/jasmine/tests/legend_test.js
Labels: status: reviewable, type: bug, type: feature

#2899 Multi-axis-type sploms
  src/plot_api/subroutines.js
  src/plots/cartesian/axis_defaults.js
  src/plots/cartesian/graph_interact.js
  src/plots/cartesian/layout_defaults.js
  src/plots/cartesian/type_defaults.js
  src/plots/geo/index.js
  src/plots/gl2d/index.js
  src/plots/gl3d/index.js
  src/plots/gl3d/layout/axis_defaults.js
  src/plots/mapbox/index.js
  src/traces/splom/attributes.js
  src/traces/splom/base_plot.js
  src/traces/splom/defaults.js
  src/traces/splom/index.js
  test/image/baselines/splom_mismatched-axis-types.png
  test/image/baselines/splom_multi-axis-type.png
  test/image/mocks/splom_mismatched-axis-types.json
  test/image/mocks/splom_multi-axis-type.json
  test/jasmine/tests/splom_test.js
Labels: status: reviewable, type: bug, type: feature

#2910 Use new multistop gradients for continuous colorbars
  src/components/colorbar/connect.js
  src/components/colorbar/draw.js
  src/traces/contour/colorbar.js
  test/image/baselines/16.png
  test/image/baselines/colorbar_enumerated_ticks.png
  test/image/baselines/colorscale_constraint.png
  test/image/baselines/geo_multiple-usa-choropleths.png
  test/image/baselines/gl2d_parcoords_1.png
  test/image/baselines/gl2d_parcoords_2.png
  test/image/baselines/hist2d_summed.png
  test/image/baselines/zsmooth_methods.png
  test/jasmine/tests/colorbar_test.js
Labels: status: reviewable, type: bug

#2912 fix #2892 - don't allow auto date ticks < our 100 microseconds limit
  src/plots/cartesian/axes.js
  test/jasmine/tests/axes_test.js
Labels: status: reviewable, type: bug

#2914 Fix `toSVG` for graphs that call `Drawing.gradient`
  src/snapshot/tosvg.js
  tasks/noci_test.sh
  test/jasmine/tests/snapshot_test.js
Labels: status: reviewable, type: bug

#2917 Heatmap ordering bug
  src/lib/index.js
  src/lib/make_trace_groups.js
  src/plots/get_data.js
  src/traces/bar/plot.js
  src/traces/box/plot.js
  src/traces/carpet/plot.js
  src/traces/choropleth/plot.js
  src/traces/contour/plot.js
  src/traces/contour/style.js
  src/traces/contourcarpet/plot.js
  src/traces/heatmap/plot.js
  src/traces/ohlc/plot.js
  src/traces/pie/plot.js
  src/traces/scattergeo/plot.js
  src/traces/violin/plot.js
  test/image/baselines/connectgaps_2d.png
  test/image/baselines/contour_heatmap_coloring.png
  test/jasmine/tests/carpet_test.js
  test/jasmine/tests/choropleth_test.js
  test/jasmine/tests/contour_test.js
  test/jasmine/tests/heatmap_test.js
  test/jasmine/tests/scattergeo_test.js
Labels: status: reviewable, type: bug

#2918 no more fail for async tests, only failTest
  test/jasmine/tests/command_test.js
  test/jasmine/tests/download_test.js
  test/jasmine/tests/drawing_test.js
  test/jasmine/tests/errorbars_test.js
  test/jasmine/tests/frame_api_test.js
  test/jasmine/tests/gl3d_plot_interact_test.js
  test/jasmine/tests/gl3dlayout_test.js
  test/jasmine/tests/histogram2d_test.js
  test/jasmine/tests/hover_spikeline_test.js
  test/jasmine/tests/mesh3d_test.js
  test/jasmine/tests/page_test.js
  test/jasmine/tests/plots_test.js
  test/jasmine/tests/sankey_test.js
  test/jasmine/tests/scattermapbox_test.js
  test/jasmine/tests/scatterpolar_test.js
  test/jasmine/tests/scatterpolargl_test.js
  test/jasmine/tests/scatterternary_test.js
  test/jasmine/tests/ternary_test.js
  test/jasmine/tests/toimage_test.js
  test/jasmine/tests/transform_sort_test.js
Labels: status: reviewable, type: maintenance

#2923 Drop node4 for devs + a few more dep updates
  CONTRIBUTING.md
  package-lock.json
  package.json
  test/jasmine/assets/custom_matchers.js
Labels: status: reviewable, type: maintenance

#2921 support 'e' and 'E' exponentformat on log axes
  src/plots/cartesian/axes.js
  test/image/mocks/12.json
  test/image/mocks/14.json
  test/image/mocks/gl2d_12.json
  test/image/mocks/gl2d_14.json
  test/jasmine/tests/axes_test.js
  test/jasmine/tests/hover_label_test.js
Labels: status: reviewable, type: bug

#2933 Shard gl jasmine tests
  .circleci/test.sh
  package-lock.json
  package.json
  tasks/shard_jasmine_tests.js
  tasks/test_syntax.js
  tasks/util/common.js
  test/jasmine/karma.conf.js
  test/jasmine/tests/cone_test.js
  test/jasmine/tests/gl2d_click_test.js
  test/jasmine/tests/gl2d_date_axis_render_test.js
  test/jasmine/tests/gl2d_plot_interact_test.js
  test/jasmine/tests/gl2d_pointcloud_test.js
  test/jasmine/tests/gl2d_scatterplot_contour_test.js
  test/jasmine/tests/gl3d_plot_interact_test.js
  test/jasmine/tests/gl_plot_interact_basic_test.js
  test/jasmine/tests/parcoords_test.js
  test/jasmine/tests/polar_test.js
  test/jasmine/tests/select_test.js
  test/jasmine/tests/shapes_test.js
  test/jasmine/tests/splom_test.js
  test/jasmine/tests/streamtube_test.js
Labels: status: reviewable, type: maintenance

#2931 Fix Plotly.download using graph id as 1st argument
  src/snapshot/download.js
  test/jasmine/tests/download_test.js
Labels: status: reviewable, type: bug

#2939 Replot when webgl buffer dims don't match canvas dims
  src/plot_api/plot_api.js
  test/jasmine/tests/splom_test.js
Labels: status: reviewable, type: bug

#2934 Use Node 10 and npm 6 for development
  .circleci/config.yml
  .circleci/test.sh
  CONTRIBUTING.md
  package-lock.json
  package.json
  test/jasmine/tests/splom_test.js
Labels: status: reviewable, type: maintenance

#2949 disable hover for sankey traces when hovermode is false
  src/traces/sankey/plot.js
  test/jasmine/tests/sankey_test.js
Labels: status: reviewable, type: bug
