Repository plotly/plotly.js, pull requests merged in 2018-04, with the labels that each got.

#2516 fix plotinfo when mainplot is no longer linked
  src/plots/cartesian/index.js
  test/jasmine/tests/cartesian_test.js
Labels: type: bug

#2530 fix #2529 - box plot with one jittered outlier
  src/traces/box/plot.js
  test/jasmine/tests/box_test.js
Labels: type: bug

#2533 Fix containment check for reversed ranges
  src/plots/cartesian/set_convert.js
  test/image/baselines/bar_cliponaxis-false.png
  test/image/mocks/bar_cliponaxis-false.json
Labels: status: reviewable, type: bug

#2532 Fixed size shapes
  src/components/shapes/attributes.js
  src/components/shapes/calc_autorange.js
  src/components/shapes/draw.js
  src/components/shapes/shape_defaults.js
  src/plots/cartesian/autorange.js
  test/image/baselines/fixed_size_shapes.png
  test/image/mocks/fixed_size_shapes.json
  test/jasmine/assets/custom_assertions.js
  test/jasmine/tests/hover_label_test.js
  test/jasmine/tests/shapes_test.js
Labels: status: reviewable, type: feature

#2527 Splom zoom perf
  src/components/shapes/draw.js
  src/plot_api/edit_types.js
  src/plot_api/plot_api.js
  src/plot_api/subroutines.js
  src/plots/cartesian/axes.js
  src/plots/cartesian/dragbox.js
  src/plots/cartesian/graph_interact.js
  src/plots/cartesian/index.js
  src/plots/cartesian/layout_attributes.js
  src/plots/cartesian/transition_axes.js
  src/plots/plots.js
  src/traces/bar/index.js
  src/traces/box/index.js
  src/traces/candlestick/index.js
  src/traces/carpet/index.js
  src/traces/contour/index.js
  src/traces/contourcarpet/index.js
  src/traces/heatmap/index.js
  src/traces/histogram/index.js
  src/traces/histogram2d/index.js
  src/traces/histogram2dcontour/index.js
  src/traces/ohlc/index.js
  src/traces/scatter/index.js
  src/traces/scattercarpet/index.js
  src/traces/violin/index.js
  test/jasmine/tests/cartesian_interact_test.js
  test/jasmine/tests/fx_test.js
  test/jasmine/tests/plot_api_test.js
Labels: status: reviewable, type: performance

#2556 Bump line2d
  package-lock.json
  package.json
  src/traces/scattergl/convert.js
  src/traces/scattergl/index.js
  src/traces/scatterpolargl/index.js
  test/image/baselines/gl2d_line_dash.png
Labels: status: reviewable, type: performance

#2558 Update ja.js
  lib/locales/ja.js
Labels: status: reviewable, type: translation

#2564 Fix missing gl2d lines
  .circleci/test.sh
  package-lock.json
  package.json
  test/image/baselines/gl2d_horiz-lines.png
  test/image/baselines/gl2d_simple_inset.png
  test/image/baselines/gl2d_stacked_subplots.png
  test/image/mocks/gl2d_horiz-lines.json
Labels: status: reviewable, type: bug

#2506 Configurable select direction
  src/components/fx/layout_attributes.js
  src/components/fx/layout_defaults.js
  src/plots/cartesian/select.js
  test/jasmine/tests/select_test.js
  test/jasmine/tests/shapes_test.js
Labels: status: reviewable, type: feature

#2567 Add tips for writing selection tests
  CONTRIBUTING.md
Labels: type: documentation

#2568 Bump lines
  package-lock.json
  package.json
  test/image/baselines/gl2d_line_limit.png
  test/image/mocks/gl2d_line_limit.json
Labels: status: reviewable, type: bug

#2587 Blank editable legend item fixes
  src/components/legend/draw.js
  src/lib/svg_text_utils.js
  src/transforms/groupby.js
  test/jasmine/tests/legend_test.js
Labels: status: reviewable, type: bug

#2590 fix spikesnap: cursor in FF
  src/components/fx/hover.js
  tasks/test_syntax.js
Labels: status: reviewable, type: bug

#2592 Update modebar buttons when locale changes
  src/components/modebar/modebar.js
  test/jasmine/tests/localize_test.js
Labels: status: reviewable, type: bug

#2579 Even better cartesian trace updates and removal
  src/components/rangeslider/draw.js
  src/plot_api/subroutines.js
  src/plots/cartesian/constants.js
  src/plots/cartesian/index.js
  src/plots/get_data.js
  src/plots/plots.js
  src/traces/bar/plot.js
  src/traces/box/plot.js
  src/traces/candlestick/index.js
  src/traces/carpet/plot.js
  src/traces/contour/plot.js
  src/traces/contourcarpet/plot.js
  src/traces/heatmap/plot.js
  src/traces/histogram/index.js
  src/traces/histogram2d/index.js
  src/traces/histogram2dcontour/index.js
  src/traces/ohlc/plot.js
  src/traces/scatter/plot.js
  src/traces/scattercarpet/plot.js
  src/traces/scatterpolar/plot.js
  src/traces/scatterternary/plot.js
  src/traces/violin/plot.js
  tasks/baseline.js
  tasks/test_export.js
  tasks/test_image.js
  tasks/util/container_commands.js
  test/jasmine/tests/bar_test.js
  test/jasmine/tests/carpet_test.js
  test/jasmine/tests/contour_test.js
  test/jasmine/tests/range_slider_test.js
  test/jasmine/tests/scatter_test.js
Labels: status: reviewable, type: maintenance, type: performance

#2574 Better cartesian trace updates and removal
  src/components/rangeslider/draw.js
  src/plot_api/subroutines.js
  src/plots/cartesian/constants.js
  src/plots/cartesian/index.js
  src/plots/get_data.js
  src/plots/plots.js
  src/traces/bar/plot.js
  src/traces/box/plot.js
  src/traces/candlestick/index.js
  src/traces/carpet/plot.js
  src/traces/contour/plot.js
  src/traces/contourcarpet/plot.js
  src/traces/heatmap/plot.js
  src/traces/histogram/index.js
  src/traces/histogram2d/index.js
  src/traces/histogram2dcontour/index.js
  src/traces/ohlc/plot.js
  src/traces/scatter/plot.js
  src/traces/scattercarpet/plot.js
  src/traces/scatterpolar/plot.js
  src/traces/scatterternary/plot.js
  src/traces/violin/plot.js
  tasks/baseline.js
  tasks/test_export.js
  tasks/test_image.js
  tasks/util/container_commands.js
  test/jasmine/tests/bar_test.js
  test/jasmine/tests/carpet_test.js
  test/jasmine/tests/contour_test.js
  test/jasmine/tests/range_slider_test.js
  test/jasmine/tests/scatter_test.js
Labels: status: reviewable, type: maintenance, type: performance
