Repository plotly/plotly.js, pull requests merged in 2018-06, with the labels that each got.

#2689 Fixup bartext removal in update selections
  src/traces/bar/plot.js
  test/jasmine/tests/bar_test.js
Labels: status: reviewable, type: bug

#2698 Fix scatter3d scalar hovertext handling
  src/traces/scatter3d/convert.js
  test/jasmine/tests/gl3d_plot_interact_test.js
Labels: status: reviewable, type: bug

#2697 Make all gl traces show "no webgl message" and fail gracefully
  src/lib/prepare_regl.js
  src/lib/show_no_webgl_msg.js
  src/plots/gl2d/scene2d.js
  src/plots/gl3d/scene.js
  src/plots/plots.js
  src/traces/parcoords/plot.js
  src/traces/scattergl/index.js
  src/traces/splom/base_plot.js
  test/jasmine/bundle_tests/no_webgl_test.js
  test/jasmine/karma.conf.js
Labels: status: reviewable, type: bug

#2705 fix line decimation for segments crossing the viewport
  src/traces/scatter/line_points.js
  test/jasmine/tests/scatter_test.js
Labels: status: reviewable, type: bug

#2709 plotly_relayout on mapbox scroll
  package-lock.json
  package.json
  src/plots/mapbox/constants.js
  src/plots/mapbox/mapbox.js
  test/image/baselines/mapbox_0.png
  test/image/baselines/mapbox_angles.png
  test/image/baselines/mapbox_bubbles-text.png
  test/image/baselines/mapbox_bubbles.png
  test/image/baselines/mapbox_connectgaps.png
  test/image/baselines/mapbox_custom-style.png
  test/image/baselines/mapbox_fill.png
  test/image/baselines/mapbox_layers.png
  test/image/baselines/mapbox_symbol-text.png
  test/jasmine/tests/mapbox_test.js
Labels: status: reviewable, type: bug

#2694 Bump regl to 1.3.6
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#2712 A few surface contours fixes
  package-lock.json
  package.json
  src/traces/surface/convert.js
  test/image/baselines/gl3d_contour-lines2.png
  test/image/mocks/gl3d_contour-lines2.json
Labels: status: reviewable, type: bug

#2715 Cone sizeref fixes
  package-lock.json
  package.json
  src/traces/cone/attributes.js
  src/traces/cone/convert.js
  test/image/baselines/gl3d_cone-absolute.png
  test/image/baselines/gl3d_cone-autorange.png
  test/image/baselines/gl3d_cone-lighting.png
  test/image/baselines/gl3d_cone-rossler.png
  test/image/baselines/gl3d_cone-simple.png
  test/image/baselines/gl3d_cone-single.png
  test/image/baselines/gl3d_cone-wind.png
  test/image/mocks/gl3d_cone-absolute.json
  test/image/mocks/gl3d_cone-rossler.json
  test/image/mocks/gl3d_cone-wind.json
  test/jasmine/tests/cone_test.js
Labels: status: reviewable, type: bug

#2724 fix #2722 - get the right traces in hist calc for cross-trace coupling
  src/traces/histogram/calc.js
  test/jasmine/tests/histogram_test.js
Labels: status: reviewable, type: bug

#2728 over 30 chart types
  README.md
Labels: type: documentation

#2734 Fix mapbox layout layer updates
  src/plots/mapbox/layers.js
  test/jasmine/tests/mapbox_test.js
Labels: status: reviewable, type: bug

#2710 Plots.resize - additional check for gd.layout
  src/plots/plots.js
  test/jasmine/tests/plot_promise_test.js
Labels: type: bug

#2747 Fix #2743 - old date timezone precision in Chrome 67+
  src/lib/dates.js
  test/jasmine/tests/lib_date_test.js
Labels: status: reviewable, type: bug

#2739 Polar polygon grids
  src/plots/polar/layout_attributes.js
  src/plots/polar/layout_defaults.js
  src/plots/polar/polar.js
  src/traces/scatterpolar/plot.js
  test/image/baselines/polar_polygon-grids.png
  test/image/mocks/polar_polygon-grids.json
  test/jasmine/assets/drag.js
  test/jasmine/tests/polar_test.js
Labels: status: reviewable, type: feature

#2758 Sanitize margin after 'autosize' relayouts
  src/plots/plots.js
  test/jasmine/tests/plots_test.js
Labels: status: reviewable, type: bug

#2760 Add `plotlyServerUrl` to `baseUrl`
  src/plot_api/plot_config.js
  src/plots/plots.js
  test/jasmine/tests/config_test.js
Labels: status: reviewable, type: feature

#2764 Aggregate functions
  src/transforms/aggregate.js
  test/jasmine/tests/transform_aggregate_test.js
Labels: status: reviewable, type: feature
