Repository plotly/plotly.js, pull requests merged in 2019-06, with the labels that each got.

#3934 Fix contour label rendering for non-monotonically increasing x/y
  src/traces/carpet/plot.js
  src/traces/contour/plot.js
  test/image/baselines/contour_label-reversed-xy.png
  test/image/mocks/contour_label-reversed-xy.json
Labels: status: reviewable, type: bug

#3935 More single-value overlaid histogram fixes
  src/traces/histogram/calc.js
  test/jasmine/tests/histogram_test.js
Labels: status: reviewable, type: bug

#3945 Bump fast-isnumeric gl-contour2d and mouse-wheel
  package-lock.json
  package.json
Labels: type: maintenance

#3948 Bump tinycolor2 to 1.4.1 - as well as few dev-dependencies
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#3950 1d -> 2d -> 1d zoombox regression fix + drag test maintenance
  src/plots/cartesian/dragbox.js
  test/jasmine/assets/drag.js
  test/jasmine/tests/annotations_test.js
  test/jasmine/tests/cartesian_interact_test.js
  test/jasmine/tests/click_test.js
  test/jasmine/tests/colorbar_test.js
  test/jasmine/tests/drawing_test.js
  test/jasmine/tests/geo_test.js
  test/jasmine/tests/gl2d_plot_interact_test.js
  test/jasmine/tests/gl3d_plot_interact_test.js
  test/jasmine/tests/legend_test.js
  test/jasmine/tests/plot_api_react_test.js
  test/jasmine/tests/polar_test.js
  test/jasmine/tests/sankey_test.js
  test/jasmine/tests/shapes_test.js
  test/jasmine/tests/splom_test.js
  test/jasmine/tests/template_test.js
  test/jasmine/tests/ternary_test.js
Labels: status: reviewable, type: bug, type: maintenance

#3951 Bump dev deps 11-06-2019 edition
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#3958 Implement percentage flags to control funnel hoverinfo and hovertemplete
  src/traces/funnel/attributes.js
  src/traces/funnel/constants.js
  src/traces/funnel/event_data.js
  src/traces/funnel/hover.js
  src/traces/funnel/index.js
  test/jasmine/tests/funnel_test.js
Labels: status: reviewable, type: bug

#3952 Bump more dependencies - edition 2019 June 11
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#3963 fixup hoverinfo & hovertemplate initial, delta and final flags for waterfalls
  src/traces/waterfall/attributes.js
  src/traces/waterfall/constants.js
  src/traces/waterfall/event_data.js
  src/traces/waterfall/hover.js
  src/traces/waterfall/index.js
  test/jasmine/tests/waterfall_test.js
Labels: status: reviewable, type: bug

#3967 Split and reuse functions reside inside index files of scattergl scatterpolargl and splom traces
  src/traces/scattergl/calc.js
  src/traces/scattergl/edit_style.js
  src/traces/scattergl/hover.js
  src/traces/scattergl/index.js
  src/traces/scattergl/plot.js
  src/traces/scattergl/scene_update.js
  src/traces/scattergl/select.js
  src/traces/scatterpolargl/calc.js
  src/traces/scatterpolargl/hover.js
  src/traces/scatterpolargl/index.js
  src/traces/scatterpolargl/plot.js
  src/traces/splom/calc.js
  src/traces/splom/edit_style.js
  src/traces/splom/helpers.js
  src/traces/splom/hover.js
  src/traces/splom/index.js
  src/traces/splom/plot.js
  src/traces/splom/scene_update.js
  src/traces/splom/select.js
Labels: status: reviewable, type: maintenance

#3968 Ensure hoverinfo <--> hovertemplate number formatting equivalence
  src/components/fx/hover.js
  src/traces/choropleth/hover.js
  src/traces/scattergeo/hover.js
  src/traces/scatterpolar/hover.js
  src/traces/scatterternary/hover.js
  test/jasmine/tests/barpolar_test.js
  test/jasmine/tests/choropleth_test.js
  test/jasmine/tests/scattergeo_test.js
  test/jasmine/tests/scatterpolar_test.js
  test/jasmine/tests/scatterpolargl_test.js
  test/jasmine/tests/scatterternary_test.js
Labels: status: reviewable, type: bug

#3969 Use jasmine-core 3.4.0
  package-lock.json
  package.json
  test/jasmine/assets/custom_assertions.js
  test/jasmine/assets/custom_matchers.js
  test/jasmine/assets/negate_if.js
  test/jasmine/karma.conf.js
  test/jasmine/tests/bar_test.js
  test/jasmine/tests/colorbar_test.js
  test/jasmine/tests/geo_test.js
  test/jasmine/tests/plot_api_test.js
  test/jasmine/tests/polar_test.js
  test/jasmine/tests/scatter_test.js
Labels: status: reviewable, type: maintenance

#3979 Trigger `plotly_clickannotation` when `editable:true`
  src/components/annotations/draw.js
  test/jasmine/tests/annotations_test.js
Labels: status: reviewable, type: bug

#3965 More zoomed-in box/violin hover labels fixes
  src/components/fx/hover.js
  src/traces/box/hover.js
  test/jasmine/tests/box_test.js
  test/jasmine/tests/violin_test.js
Labels: status: reviewable, type: bug

#3983 Fix boxplot with categoryorder
  src/plots/plots.js
  test/image/baselines/box_grouped_mean_descending.png
  test/image/mocks/box_grouped_mean_descending.json
Labels: status: reviewable, type: bug

#3972 responsive handler: do not resize if gd is hidden
  src/lib/index.js
  src/plot_api/plot_api.js
  src/plots/plots.js
  test/jasmine/tests/config_test.js
Labels: status: reviewable, type: bug

#3932 improve robustness of circular Sankey
  package-lock.json
  package.json
  src/traces/sankey/render.js
  test/image/baselines/sankey_circular_process.png
  test/image/baselines/sankey_circular_simple2.png
  test/image/mocks/sankey_circular_simple2.json
  test/jasmine/tests/sankey_test.js
Labels: status: reviewable, type: bug

#3966 Refactor parcoords - bug fixes - reuse axes ticktext - support pseudo html labels - features for label angle & position
  src/traces/parcoords/attributes.js
  src/traces/parcoords/axisbrush.js
  src/traces/parcoords/base_plot.js
  src/traces/parcoords/calc.js
  src/traces/parcoords/constants.js
  src/traces/parcoords/defaults.js
  src/traces/parcoords/helpers.js
  src/traces/parcoords/lines.js
  src/traces/parcoords/parcoords.js
  src/traces/parcoords/plot.js
  src/traces/parcoords/shaders/context_vertex.glsl
  src/traces/parcoords/shaders/fragment.glsl
  src/traces/parcoords/shaders/pick_vertex.glsl
  src/traces/parcoords/shaders/position.glsl
  src/traces/parcoords/shaders/unfiltered_position.glsl
  src/traces/parcoords/shaders/vertex.glsl
  src/traces/parcoords/shaders/y.glsl
  test/image/baselines/gl2d_parcoords.png
  test/image/baselines/gl2d_parcoords_2.png
  test/image/baselines/gl2d_parcoords_256_colors.png
  test/image/baselines/gl2d_parcoords_60_dims.png
  test/image/baselines/gl2d_parcoords_coloraxis.png
  test/image/baselines/gl2d_parcoords_constraints.png
  test/image/baselines/gl2d_parcoords_large.png
  test/image/baselines/gl2d_parcoords_out-of-range_selected-all.png
  test/image/baselines/gl2d_parcoords_out-of-range_selected-none.png
  test/image/baselines/gl2d_parcoords_rgba_colorscale.png
  test/image/baselines/gl2d_parcoords_style_labels.png
  test/image/baselines/gl2d_parcoords_tick_format.png
  test/image/mocks/gl2d_parcoords_256_colors.json
  test/image/mocks/gl2d_parcoords_60_dims.json
  test/image/mocks/gl2d_parcoords_out-of-range_selected-all.json
  test/image/mocks/gl2d_parcoords_out-of-range_selected-none.json
  test/image/mocks/gl2d_parcoords_style_labels.json
  test/image/mocks/gl2d_parcoords_tick_format.json
  test/jasmine/tests/parcoords_test.js
  test/jasmine/tests/plot_api_react_test.js
Labels: status: reviewable, type: bug, type: feature, type: performance

#3994 Fetch topojson when 1+ trace(s) has `locationmode`
  src/plots/geo/geo.js
  test/jasmine/tests/geo_test.js
Labels: status: reviewable, type: bug

#3978 trace type `indicator`
  lib/index-finance.js
  lib/index.js
  lib/indicator.js
  src/components/modebar/manage.js
  src/constants/delta.js
  src/plot_api/plot_api.js
  src/snapshot/tosvg.js
  src/traces/indicator/attributes.js
  src/traces/indicator/base_plot.js
  src/traces/indicator/calc.js
  src/traces/indicator/constants.js
  src/traces/indicator/defaults.js
  src/traces/indicator/index.js
  src/traces/indicator/plot.js
  src/traces/ohlc/attributes.js
  src/traces/ohlc/hover.js
  src/traces/waterfall/defaults.js
  src/traces/waterfall/hover.js
  test/image/baselines/gl3d_indicator_scatter3d.png
  test/image/baselines/indicator_bignumber.png
  test/image/baselines/indicator_bullet.png
  test/image/baselines/indicator_datacard.png
  test/image/baselines/indicator_datacard2.png
  test/image/baselines/indicator_gauge.png
  test/image/baselines/indicator_grid_template.png
  test/image/baselines/indicator_scatter.png
  test/image/mocks/gl3d_indicator_scatter3d.json
  test/image/mocks/indicator_bignumber.json
  test/image/mocks/indicator_bullet.json
  test/image/mocks/indicator_datacard.json
  test/image/mocks/indicator_datacard2.json
  test/image/mocks/indicator_gauge.json
  test/image/mocks/indicator_grid_template.json
  test/image/mocks/indicator_scatter.json
  test/jasmine/tests/indicator_test.js
  test/jasmine/tests/modebar_test.js
  test/jasmine/tests/snapshot_test.js
Labels: status: reviewable, type: new trace type
