Repository plotly/plotly.js, pull requests merged in 2019-01, with the labels that each got.

#3382 Compact http to https with zero dependency
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#3394 React + uirevision fixes
  src/plots/geo/zoom.js
  src/plots/gl3d/scene.js
  src/plots/mapbox/mapbox.js
  test/jasmine/tests/plot_api_react_test.js
Labels: status: reviewable, type: bug

#3366 Finance trace hover fixups
  src/components/fx/hover.js
  src/traces/box/plot.js
  src/traces/box/style.js
  src/traces/ohlc/calc.js
  src/traces/ohlc/hover.js
  src/traces/ohlc/plot.js
  src/traces/ohlc/style.js
  test/jasmine/tests/finance_test.js
Labels: status: reviewable, type: bug

#3401 Fix horizontal box/violin hover label misalignment under hovermode:'closest'
  src/components/fx/hover.js
  test/jasmine/tests/box_test.js
  test/jasmine/tests/violin_test.js
Labels: status: reviewable, type: bug

#3369 Mesh3d cell data checks
  src/traces/mesh3d/convert.js
  src/traces/mesh3d/defaults.js
  test/jasmine/tests/mesh3d_test.js
Labels: status: reviewable, type: bug, type: maintenance

#3397 Add :hover styleRule for modebar.bgcolor
  build/plotcss.js
  src/components/modebar/modebar.js
  src/css/_modebar.scss
  test/jasmine/tests/modebar_test.js
Labels: status: reviewable, type: bug

#3418 gl3d reversescale fixup
  src/lib/gl_format_color.js
  src/traces/cone/convert.js
  src/traces/mesh3d/convert.js
  src/traces/streamtube/convert.js
  src/traces/surface/convert.js
  src/traces/surface/defaults.js
  test/image/baselines/gl3d_reversescale.png
  test/image/mocks/gl3d_reversescale.json
Labels: status: reviewable, type: bug

#3423 Renaming old attributes should not replace existing current attributes if both provided
  src/plot_api/helpers.js
  test/jasmine/tests/plot_api_test.js
Labels: status: reviewable, type: bug

#3404 Cartesian small domain
  src/plots/cartesian/position_defaults.js
  test/image/baselines/heatmap_small_aspect-ratio.png
  test/image/mocks/heatmap_small_aspect-ratio.json
Labels: status: reviewable, type: bug

#3375 Add support for div id as 1st arg to Plotly.makeTemplate
  src/plot_api/template_api.js
  test/jasmine/tests/template_test.js
Labels: status: reviewable, type: feature

#3398 adding hovertemplates to polar bar and scatter and ternary scatter
  src/traces/barpolar/attributes.js
  src/traces/barpolar/defaults.js
  src/traces/barpolar/hover.js
  src/traces/scatterpolar/attributes.js
  src/traces/scatterpolar/defaults.js
  src/traces/scatterpolar/hover.js
  src/traces/scatterpolargl/attributes.js
  src/traces/scatterpolargl/defaults.js
  src/traces/scatterternary/attributes.js
  src/traces/scatterternary/defaults.js
  src/traces/scatterternary/hover.js
  test/jasmine/tests/barpolar_test.js
  test/jasmine/tests/scatterpolar_test.js
  test/jasmine/tests/scatterpolargl_test.js
  test/jasmine/tests/scatterternary_test.js
Labels: status: reviewable, type: feature

#3384 Display a colorscale when scatter3d.line.showscale is set
  src/components/colorbar/connect.js
  src/traces/scatter/line_defaults.js
  src/traces/scatter3d/attributes.js
  src/traces/scatter3d/index.js
  test/image/baselines/gl3d_scatter3d-colorscale-with-line.png
  test/image/mocks/gl3d_scatter3d-colorscale-with-line.json
Labels: status: reviewable, type: feature

#3408 finalist: Errorbars inherit color from line or marker color
  src/traces/bar/defaults.js
  src/traces/histogram/defaults.js
  src/traces/scatter/defaults.js
  src/traces/scatter3d/defaults.js
  src/traces/scattergl/defaults.js
  test/image/baselines/bar_errorbars_inherit_color.png
  test/image/baselines/benchmarks.png
  test/image/baselines/error_bar_bar_ids.png
  test/image/baselines/gl2d_scattergl_errorbars_inherit_color.png
  test/image/baselines/gl3d_scatter3d_errorbars_inherit_color.png
  test/image/baselines/histogram_errorbars_inherit_color.png
  test/image/baselines/scatter_errorbars_inherit_color.png
  test/image/mocks/bar_errorbars_inherit_color.json
  test/image/mocks/gl2d_scattergl_errorbars_inherit_color.json
  test/image/mocks/gl3d_scatter3d_errorbars_inherit_color.json
  test/image/mocks/histogram_errorbars_inherit_color.json
  test/image/mocks/scatter_errorbars_inherit_color.json
Labels: status: reviewable, type: bug

#3435 legend valign fix for pie traces
  src/components/legend/draw.js
  src/components/legend/style.js
  test/image/baselines/legend_valign_top.png
  test/image/mocks/legend_valign_top.json
Labels: status: reviewable, type: bug

#3436 add hovertemplate to choropleth, scattergeo and scattermapbox
  src/traces/choropleth/attributes.js
  src/traces/choropleth/defaults.js
  src/traces/choropleth/hover.js
  src/traces/scattergeo/attributes.js
  src/traces/scattergeo/defaults.js
  src/traces/scattergeo/hover.js
  src/traces/scattermapbox/attributes.js
  src/traces/scattermapbox/defaults.js
  src/traces/scattermapbox/hover.js
  test/jasmine/tests/choropleth_test.js
  test/jasmine/tests/scattergeo_test.js
  test/jasmine/tests/scattermapbox_test.js
Labels: status: reviewable, type: feature

#3422 Make scrollZoom config option a flaglist
  src/plot_api/plot_api.js
  src/plot_api/plot_config.js
  src/plots/cartesian/dragbox.js
  src/plots/geo/geo.js
  src/plots/gl2d/scene2d.js
  src/plots/gl3d/camera.js
  src/plots/gl3d/scene.js
  src/plots/mapbox/mapbox.js
  test/jasmine/tests/config_test.js
  test/jasmine/tests/geo_test.js
  test/jasmine/tests/gl3d_plot_interact_test.js
  test/jasmine/tests/mapbox_test.js
Labels: status: reviewable, type: feature

#3439 Metatext
  src/components/annotations/draw.js
  src/components/titles/index.js
  src/plots/gl3d/layout/convert.js
  src/plots/gl3d/scene.js
  src/plots/layout_attributes.js
  src/plots/plots.js
  src/traces/pie/plot.js
  test/image/baselines/layout_metatext.png
  test/image/mocks/layout_metatext.json
Labels: status: reviewable, type: feature

#3421 Updating dependencies of gl-vis modules
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#3376 Add config options in plot schema
  src/lib/loggers.js
  src/lib/queue.js
  src/plot_api/plot_api.js
  src/plot_api/plot_config.js
  src/plot_api/plot_schema.js
  src/plot_api/template_api.js
  src/plot_api/validate.js
  src/plots/cartesian/dragbox.js
  src/plots/geo/geo.js
  src/plots/gl2d/scene2d.js
  src/plots/gl3d/camera.js
  src/plots/gl3d/scene.js
  src/plots/mapbox/mapbox.js
  test/jasmine/bundle_tests/plotschema_test.js
  test/jasmine/tests/config_test.js
  test/jasmine/tests/geo_test.js
  test/jasmine/tests/gl3d_plot_interact_test.js
  test/jasmine/tests/lib_test.js
  test/jasmine/tests/mapbox_test.js
Labels: status: reviewable, type: documentation, type: feature

#3415 Mesh3d lighting fix
  package-lock.json
  package.json
  test/image/baselines/gl3d_mesh3d_surface3d_scatter3d_line3d_error3d_log_reversed_ranges.png
  test/image/baselines/gl3d_mesh3d_surface_lighting.png
  test/image/baselines/gl3d_reversescale.png
  test/image/baselines/gl3d_snowden.png
  test/image/baselines/gl3d_snowden_altered.png
  test/image/baselines/gl3d_tetrahedra.png
  test/image/baselines/gl3d_world-cals.png
  test/image/mocks/gl3d_mesh3d_surface_lighting.json
Labels: status: reviewable, type: bug

#3445 Remove box ungrouping magic
  src/traces/box/cross_trace_calc.js
  test/image/baselines/box_single-group.png
  test/image/mocks/box_single-group.json
Labels: status: reviewable, type: bug

#3234 Joyplots2
  src/traces/box/attributes.js
  src/traces/box/calc.js
  src/traces/box/cross_trace_calc.js
  src/traces/box/defaults.js
  src/traces/box/layout_attributes.js
  src/traces/box/plot.js
  src/traces/violin/attributes.js
  src/traces/violin/calc.js
  src/traces/violin/cross_trace_calc.js
  src/traces/violin/defaults.js
  src/traces/violin/layout_attributes.js
  src/traces/violin/plot.js
  test/image/baselines/10.png
  test/image/baselines/31.png
  test/image/baselines/box_grouped.png
  test/image/baselines/box_grouped_horz.png
  test/image/baselines/box_plot_jitter_edge_cases.png
  test/image/baselines/box_single-group.png
  test/image/baselines/box_with-empty-1st-trace.png
  test/image/baselines/hist_cum_stacked.png
  test/image/baselines/point-selection2.png
  test/image/baselines/violin_box_multiple_widths.png
  test/image/baselines/violin_box_overlay.png
  test/image/baselines/violin_grouped.png
  test/image/baselines/violin_negative_sides_w_points.png
  test/image/baselines/violin_old-faithful.png
  test/image/baselines/violin_positive_and_negative.png
  test/image/baselines/violin_positive_sides_w_points.png
  test/image/baselines/violin_side-by-side.png
  test/image/mocks/box_single-group.json
  test/image/mocks/violin_box_multiple_widths.json
  test/image/mocks/violin_negative_sides_w_points.json
  test/image/mocks/violin_positive_and_negative.json
  test/image/mocks/violin_positive_sides_w_points.json
  test/jasmine/tests/box_test.js
  test/jasmine/tests/cartesian_interact_test.js
  test/jasmine/tests/select_test.js
  test/jasmine/tests/violin_test.js
Labels: status: reviewable, type: bug, type: feature

#3443 Add support for <sub> and <sup> in "extra" hover label
  src/components/fx/hover.js
  src/lib/svg_text_utils.js
  test/jasmine/tests/hover_label_test.js
  test/jasmine/tests/svg_text_utils_test.js
Labels: status: reviewable, type: feature

#3441 Show box/violin position when hovering over pts
  src/traces/box/hover.js
  test/jasmine/tests/box_test.js
  test/jasmine/tests/violin_test.js
Labels: status: reviewable, type: bug

#3438 iso-surface finalist with caps, slices & spaceframe display on uniform or non-uniform coordinates
  lib/index.js
  lib/isosurface.js
  src/plots/gl3d/scene.js
  src/traces/isosurface/attributes.js
  src/traces/isosurface/calc.js
  src/traces/isosurface/convert.js
  src/traces/isosurface/defaults.js
  src/traces/isosurface/index.js
  test/image/baselines/gl3d_isosurface_1single-surface_middle-range.png
  test/image/baselines/gl3d_isosurface_2surfaces-checker_spaceframe.png
  test/image/baselines/gl3d_isosurface_5more-surfaces_between-ranges.png
  test/image/baselines/gl3d_isosurface_log-axis_slices_surface-fill.png
  test/image/baselines/gl3d_isosurface_math.png
  test/image/baselines/gl3d_isosurface_multiple-traces.png
  test/image/baselines/gl3d_isosurface_out_of_iso_range_case.png
  test/image/baselines/gl3d_isosurface_thin_caps_different_dims.png
  test/image/baselines/gl3d_isosurface_uneven-scales_ranges_iso-null.png
  test/image/baselines/gl3d_isosurface_with_surface-pattern.png
  test/image/baselines/gl3d_isosurface_xycaps_volume_slices.png
  test/image/mocks/gl3d_isosurface_1single-surface_middle-range.json
  test/image/mocks/gl3d_isosurface_2surfaces-checker_spaceframe.json
  test/image/mocks/gl3d_isosurface_5more-surfaces_between-ranges.json
  test/image/mocks/gl3d_isosurface_log-axis_slices_surface-fill.json
  test/image/mocks/gl3d_isosurface_math.json
  test/image/mocks/gl3d_isosurface_multiple-traces.json
  test/image/mocks/gl3d_isosurface_out_of_iso_range_case.json
  test/image/mocks/gl3d_isosurface_thin_caps_different_dims.json
  test/image/mocks/gl3d_isosurface_uneven-scales_ranges_iso-null.json
  test/image/mocks/gl3d_isosurface_with_surface-pattern.json
  test/image/mocks/gl3d_isosurface_xycaps_volume_slices.json
  test/jasmine/assets/mock_lists.js
  test/jasmine/tests/isosurface_test.js
Labels: status: reviewable, type: feature, type: new trace type

#3448 Clear subplotType cache on Plotly.register()
  src/plots/plots.js
  src/registry.js
  test/jasmine/bundle_tests/dynamic_import_test.js
Labels: status: reviewable, type: bug

#3452 Bar & ErrorBar autorange fixes
  src/components/errorbars/calc.js
  src/plots/cartesian/autorange.js
  src/traces/bar/cross_trace_calc.js
  test/image/baselines/bar_autorange-above-zero-normalized.png
  test/image/baselines/bar_autorange-above-zero.png
  test/image/baselines/bar_errorbars_inherit_color.png
  test/image/baselines/histogram_errorbars_inherit_color.png
  test/image/mocks/bar_autorange-above-zero-normalized.json
  test/image/mocks/bar_autorange-above-zero.json
Labels: status: reviewable, type: bug

#3217 Transitions with Plotly.react
  src/components/colorscale/attributes.js
  src/components/images/defaults.js
  src/plot_api/plot_api.js
  src/plots/animation_attributes.js
  src/plots/attributes.js
  src/plots/cartesian/axes.js
  src/plots/cartesian/dragbox.js
  src/plots/cartesian/layout_attributes.js
  src/plots/cartesian/layout_defaults.js
  src/plots/cartesian/transition_axes.js
  src/plots/gl3d/layout/axis_attributes.js
  src/plots/layout_attributes.js
  src/plots/plots.js
  src/traces/scatter/attributes.js
  test/jasmine/bundle_tests/plotschema_test.js
  test/jasmine/tests/annotations_test.js
  test/jasmine/tests/plots_test.js
  test/jasmine/tests/transition_test.js
Labels: status: reviewable, type: feature

#3453 Description of borderwidth
  src/components/rangeslider/attributes.js
Labels: type: documentation

#3458 Adapt box test
  test/jasmine/tests/box_test.js
Labels: status: reviewable, type: maintenance

#3461 Clear _inputDomain on cartesian axes with altered domains
  src/plot_api/plot_api.js
  test/jasmine/tests/axes_test.js
Labels: status: reviewable, type: bug

#3464 Add missing polish character
  lib/locales/pl.js
Labels: type: translation

#3463 Disable dark highlights from Mesh3d
  package-lock.json
  package.json
Labels: status: reviewable, type: bug, type: regression

#3465 Do not set camera mode to turntable when up.z is zero
  src/plots/gl3d/layout/defaults.js
  test/image/baselines/gl3d_snowden_altered.png
  test/jasmine/tests/gl3d_plot_interact_test.js
Labels: status: reviewable, type: bug, type: regression

#3474 bump vectorize-text 3.2.1
  package-lock.json
  package.json
Labels: status: reviewable, type: bug, type: regression

#3475 change camera up vector in plot api react test
  test/jasmine/tests/plot_api_react_test.js
Labels: status: reviewable, type: maintenance

#3481 Add info about 2D array `fill.color` input in table attributes
  src/traces/table/attributes.js
Labels: type: documentation

#3484 responsive tests: check size of DOM elements with getBoundingClientRect()
  test/jasmine/tests/config_test.js
Labels: status: reviewable, type: maintenance

#3480 do not delete hoverlabel when hovertemplate is defined
  src/components/fx/hover.js
  test/jasmine/tests/pie_test.js
  test/jasmine/tests/scattergeo_test.js
  test/jasmine/tests/scattermapbox_test.js
  test/jasmine/tests/scatterpolar_test.js
  test/jasmine/tests/scatterternary_test.js
Labels: status: in progress, type: bug

#3491 replace prepend() calls since they aren't supported in IE11
  src/components/modebar/modebar.js
  test/jasmine/assets/unpolyfill.js
Labels: status: reviewable, type: bug

#3494 Bug fix 3D grid lines and tick labels colored by rgba color with full transparency
  package-lock.json
  package.json
  test/image/baselines/gl3d_scatter3d_line3d_error3d_transparent-with-zero-alpha.png
  test/image/mocks/gl3d_scatter3d_line3d_error3d_transparent-with-zero-alpha.json
Labels: type: bug
