Repository plotly/plotly.js, pull requests merged in 2019-10, with the labels that each got.

#4241 Modebar toggle spikes fixup
  src/components/modebar/buttons.js
  test/jasmine/tests/modebar_test.js
Labels: status: reviewable, type: bug

#4245 Update attributes.js
  src/traces/sunburst/attributes.js
Labels: status: reviewable, type: documentation

#4246 Update indicator description
  src/traces/indicator/index.js
Labels: status: reviewable, type: documentation

#4253 Fix `branchvalues:total` for generated sunburst/treemap sectors
  src/traces/sunburst/calc.js
  test/jasmine/tests/sunburst_test.js
  test/jasmine/tests/treemap_test.js
Labels: status: reviewable, type: bug

#4254 README: fix typesetting of "GitHub"
  README.md
Labels: type: documentation

#4249 Correctly handle non-linear axis types during transitions
  src/plots/cartesian/transition_axes.js
  src/plots/plots.js
  test/jasmine/tests/animate_test.js
  test/jasmine/tests/transition_test.js
Labels: status: reviewable, type: bug

#4256 Enable second try to create gl3d scenes for Chrome 77 webgl bug
  src/plots/gl3d/scene.js
Labels: status: reviewable, type: bug

#4265 streamtube handle case of having starts but missing a dimension
  src/traces/streamtube/convert.js
  test/jasmine/tests/streamtube_test.js
Labels: status: reviewable, type: bug

#4268 Check for typed array in minExtend
  src/lib/index.js
  test/jasmine/tests/scatter_test.js
Labels: status: reviewable, type: bug, type: performance

#4269 Do not attempt to re-hover on exiting subplots
  src/components/fx/hover.js
  src/plots/cartesian/graph_interact.js
  src/plots/mapbox/mapbox.js
  test/jasmine/tests/hover_label_test.js
  test/jasmine/tests/mapbox_test.js
Labels: status: reviewable, type: bug

#4273 Guard against mirrored+autorange anchor:'free' axes
  src/plots/cartesian/axes.js
  src/plots/plots.js
  test/jasmine/tests/axes_test.js
  test/jasmine/tests/transition_test.js
Labels: status: reviewable, type: regression

#4277 Remove obsolete comment about noCI test for cone traces
  tasks/noci_test.sh
Labels: status: reviewable, type: maintenance

#4284 Update connectgaps description in respect to heatmap and contour default logics
  src/traces/contour/attributes.js
  src/traces/heatmap/attributes.js
  test/jasmine/tests/contour_test.js
  test/jasmine/tests/heatmap_test.js
Labels: status: reviewable, type: documentation

#4295 Fix trace-type update calls on mapbox subplots
  src/plots/mapbox/mapbox.js
  src/traces/choroplethmapbox/plot.js
  src/traces/densitymapbox/plot.js
  src/traces/scattermapbox/plot.js
  test/jasmine/tests/densitymapbox_test.js
Labels: status: reviewable, type: bug

#4278 Add `automargin` to pie traces with outside text labels
  src/plot_api/plot_api.js
  src/traces/pie/attributes.js
  src/traces/pie/defaults.js
  src/traces/pie/plot.js
  test/image/baselines/pie_automargin-margin0.png
  test/image/baselines/pie_automargin.png
  test/image/mocks/pie_automargin-margin0.json
  test/image/mocks/pie_automargin.json
  test/jasmine/tests/pie_test.js
Labels: status: reviewable, type: feature

#4271 Correct streamtube positions and colouring
  package-lock.json
  package.json
  src/traces/streamtube/calc.js
  src/traces/streamtube/convert.js
  test/image/baselines/gl3d_coloraxes.png
  test/image/baselines/gl3d_cone-with-streamtube.png
  test/image/baselines/gl3d_directions-streamtube1.png
  test/image/baselines/gl3d_directions-streamtube2.png
  test/image/baselines/gl3d_reversescale.png
  test/image/baselines/gl3d_streamtube-first.png
  test/image/baselines/gl3d_streamtube-simple.png
  test/image/baselines/gl3d_streamtube-thin.png
  test/image/baselines/gl3d_streamtube-wind.png
  test/image/baselines/gl3d_streamtube_reversed_ranges.png
  test/image/mocks/gl3d_directions-streamtube1.json
  test/image/mocks/gl3d_directions-streamtube2.json
  test/jasmine/tests/streamtube_test.js
Labels: status: reviewable, type: bug

#4291 Add hoverongaps to heatmap and contour for suppressing hovers on missing data
  src/traces/contour/attributes.js
  src/traces/contour/defaults.js
  src/traces/heatmap/attributes.js
  src/traces/heatmap/defaults.js
  src/traces/heatmap/hover.js
  test/jasmine/tests/contour_test.js
  test/jasmine/tests/heatmap_test.js
Labels: status: reviewable, type: feature

#4279 Add axis title standoff
  src/components/titles/index.js
  src/plots/cartesian/axes.js
  src/plots/cartesian/layout_attributes.js
  src/plots/cartesian/layout_defaults.js
  src/plots/gl3d/layout/axis_attributes.js
  src/plots/polar/layout_attributes.js
  src/plots/ternary/layout_attributes.js
  src/traces/carpet/axis_attributes.js
  test/image/baselines/automargin-title-standoff.png
  test/image/baselines/axis-title-standoff.png
  test/image/mocks/automargin-title-standoff.json
  test/image/mocks/axis-title-standoff.json
Labels: status: reviewable, type: feature

#4289 image trace type
  lib/image.js
  lib/index-cartesian.js
  lib/index.js
  src/plots/cartesian/constants.js
  src/plots/cartesian/layout_defaults.js
  src/traces/carpet/index.js
  src/traces/contourcarpet/index.js
  src/traces/image/attributes.js
  src/traces/image/calc.js
  src/traces/image/constants.js
  src/traces/image/defaults.js
  src/traces/image/event_data.js
  src/traces/image/hover.js
  src/traces/image/index.js
  src/traces/image/plot.js
  src/traces/image/style.js
  test/image/baselines/image_adventurer.png
  test/image/baselines/image_axis_reverse.png
  test/image/baselines/image_axis_type.png
  test/image/baselines/image_cat.png
  test/image/baselines/image_colormodel.png
  test/image/baselines/image_opacity.png
  test/image/baselines/image_with_gaps.png
  test/image/baselines/image_with_heatmap.png
  test/image/baselines/image_zmin_zmax.png
  test/image/mocks/image_adventurer.json
  test/image/mocks/image_axis_reverse.json
  test/image/mocks/image_axis_type.json
  test/image/mocks/image_cat.json
  test/image/mocks/image_colormodel.json
  test/image/mocks/image_opacity.json
  test/image/mocks/image_with_gaps.json
  test/image/mocks/image_with_heatmap.json
  test/image/mocks/image_zmin_zmax.json
  test/jasmine/tests/calcdata_test.js
  test/jasmine/tests/image_test.js
Labels: status: reviewable, type: new trace type

#4292 Keep orthographic zoom scales in fullLayout
  package-lock.json
  package.json
  src/components/modebar/buttons.js
  src/plot_api/subroutines.js
  src/plots/gl3d/scene.js
  test/jasmine/tests/gl3d_plot_interact_test.js
  test/jasmine/tests/plot_api_react_test.js
Labels: status: reviewable, type: bug

#4298 Workarounds for "common" (aka axis) hover label clipping
  src/components/fx/hover.js
  test/jasmine/tests/hover_label_test.js
Labels: status: reviewable, type: bug

#4306 Handle data with identical positions in cone plots
  package-lock.json
  package.json
  test/jasmine/tests/cone_test.js
Labels: status: reviewable, type: bug

#4304 do not accept domain ranges where end is not greater than start
  src/plots/domain.js
  test/jasmine/tests/plots_test.js
Labels: status: reviewable, type: bug

#4305 Updatemenus toggle buttons via args2
  src/components/updatemenus/attributes.js
  src/components/updatemenus/defaults.js
  src/components/updatemenus/draw.js
  test/image/baselines/updatemenus_toggle.png
  test/image/mocks/updatemenus_toggle.json
  test/jasmine/tests/updatemenus_test.js
Labels: status: reviewable, type: feature

#4276 Add initial zh-CN translation based on ja.js dictionary strings
  lib/locales/zh-cn.js
Labels: type: translation

#4310 zh-CN translation - fix trailing spaces
  lib/locales/zh-cn.js
Labels: status: reviewable, type: translation

#4312 Handle invalid entry during treemap plot
  src/traces/treemap/plot.js
  test/jasmine/tests/treemap_test.js
Labels: status: reviewable, type: bug

#4283 Fix width of box plots with log-scale axis
  src/plots/cartesian/autorange.js
  src/traces/box/cross_trace_calc.js
  src/traces/box/hover.js
  src/traces/box/plot.js
  src/traces/scatter/line_points.js
  src/traces/violin/plot.js
  test/image/baselines/box_log_scale.png
  test/image/baselines/violin_log_scale.png
  test/image/mocks/box_log_scale.json
  test/image/mocks/violin_log_scale.json
Labels: status: reviewable, type: bug

#4314 Fix box/meanline offset for one-sided vertical violins
  src/traces/violin/plot.js
  test/image/baselines/violin_log_scale.png
  test/image/baselines/violin_one-sided.png
  test/image/mocks/violin_one-sided.json
Labels: status: reviewable, type: bug

#4316 Preserve line gaps in scattergl plot
  package-lock.json
  package.json
  test/image/baselines/gl2d_scattergl_gaps.png
  test/image/mocks/gl2d_scattergl_gaps.json
Labels: status: reviewable, type: bug

#4313 image: constrain axes to domain, apply defaults whenever an image is present
  src/plots/cartesian/constraints.js
  src/plots/cartesian/layout_defaults.js
  src/traces/image/index.js
  test/image/baselines/image_axis_reverse.png
  test/image/baselines/image_axis_type.png
  test/image/baselines/image_cat.png
  test/image/baselines/image_colormodel.png
  test/image/baselines/image_opacity.png
  test/image/baselines/image_with_gaps.png
  test/image/baselines/image_with_heatmap.png
  test/image/baselines/image_zmin_zmax.png
  test/image/mocks/image_adventurer.json
  test/jasmine/tests/image_test.js
Labels: status: reviewable

#4307 image: improve layout defaults
  src/plots/cartesian/constraints.js
  src/plots/cartesian/layout_defaults.js
  src/traces/image/index.js
  test/image/baselines/image_axis_reverse.png
  test/image/baselines/image_axis_type.png
  test/image/baselines/image_cat.png
  test/image/baselines/image_colormodel.png
  test/image/baselines/image_opacity.png
  test/image/baselines/image_with_gaps.png
  test/image/baselines/image_with_heatmap.png
  test/image/baselines/image_zmin_zmax.png
  test/image/mocks/image_adventurer.json
  test/image/mocks/image_cat.json
  test/image/mocks/image_colormodel.json
  test/jasmine/assets/mock_lists.js
  test/jasmine/tests/image_test.js
Labels: status: reviewable, type: feature

#4319 Disable transforms for `image` traces
  src/traces/image/attributes.js
  src/traces/image/defaults.js
Labels: status: reviewable, type: bug

#4321 Flaky image tests
  .circleci/test.sh
  test/image/compare_pixels_test.js
  test/jasmine/tests/titles_test.js
Labels: status: reviewable, type: maintenance
