Repository plotly/plotly.js, pull requests merged in 2019-05, with the labels that each got.

#3821 Swedish translation
  lib/locales/sv.js
Labels: type: translation

#3827 cartesian 2dMap: implement sorting of categorical axes
  src/plots/cartesian/set_convert.js
  src/traces/heatmap/calc.js
  src/traces/heatmap/clean_2d_array.js
  src/traces/heatmap/convert_column_xyz.js
  src/traces/heatmap/hover.js
  test/image/baselines/heatmap_categoryorder.png
  test/image/baselines/heatmap_columnar.png
  test/image/baselines/heatmap_shared_categories.png
  test/image/mocks/heatmap_categoryorder.json
  test/image/mocks/heatmap_columnar.json
  test/image/mocks/heatmap_shared_categories.json
  test/jasmine/tests/axes_test.js
  test/jasmine/tests/calcdata_test.js
  test/jasmine/tests/contour_test.js
  test/jasmine/tests/heatmap_test.js
  test/jasmine/tests/histogram2d_test.js
Labels: status: reviewable, type: bug

#3819 reduce plot api imports
  src/plot_api/plot_schema.js
Labels: type: maintenance

#3825 Plotly.update replot fixes
  src/plot_api/plot_api.js
  test/jasmine/tests/plot_api_test.js
Labels: status: reviewable, type: bug

#3766 Set enabled:false when filter target array is empty
  src/components/fx/hover.js
  src/lib/filter_visible.js
  src/plot_api/subroutines.js
  src/plots/cartesian/set_convert.js
  src/plots/get_data.js
  src/plots/gl3d/scene.js
  src/plots/plots.js
  src/plots/polar/set_convert.js
  src/traces/scattermapbox/convert.js
  src/transforms/filter.js
  test/jasmine/tests/funnel_test.js
  test/jasmine/tests/transform_filter_test.js
  test/jasmine/tests/waterfall_test.js
Labels: status: reviewable, type: bug

#3847 Display zero number in pie and sunburst text and hover
  src/lib/index.js
  src/plots/gl3d/camera.js
  src/traces/bar/hover.js
  src/traces/barpolar/hover.js
  src/traces/box/hover.js
  src/traces/choropleth/hover.js
  src/traces/ohlc/hover.js
  src/traces/pie/calc.js
  src/traces/pie/plot.js
  src/traces/scatter/fill_hover_text.js
  src/traces/scatter/hover.js
  src/traces/scattercarpet/hover.js
  src/traces/scattergeo/hover.js
  src/traces/scattergl/index.js
  src/traces/scattermapbox/hover.js
  src/traces/sunburst/plot.js
  test/image/baselines/display-text_zero-number.png
  test/image/mocks/display-text_zero-number.json
  test/jasmine/tests/pie_test.js
  test/jasmine/tests/sunburst_test.js
Labels: type: bug

#3859 Reorganise gl tests for less flakiness
  .circleci/config.yml
  test/jasmine/tests/contourgl_test.js
  test/jasmine/tests/gl2d_date_axis_render_test.js
  test/jasmine/tests/gl2d_plot_interact_test.js
  test/jasmine/tests/gl3d_hover_click_test.js
  test/jasmine/tests/gl3d_plot_interact_test.js
  test/jasmine/tests/gl3daxes_test.js
  test/jasmine/tests/gl3dlayout_test.js
  test/jasmine/tests/gl_plot_interact_basic_test.js
  test/jasmine/tests/mesh3d_test.js
  test/jasmine/tests/pointcloud_test.js
  test/jasmine/tests/scatter3d_test.js
  test/jasmine/tests/scattergl_select_test.js
  test/jasmine/tests/scattergl_test.js
  test/jasmine/tests/scatterpolargl_test.js
  test/jasmine/tests/volume_test.js
Labels: status: reviewable, type: maintenance

#3860 Fix Plotly.animate on graphs with multiple basePlotModules
  src/plots/cartesian/index.js
  src/plots/plots.js
  src/traces/sunburst/attributes.js
  test/jasmine/tests/sunburst_test.js
Labels: status: reviewable, type: bug

#3867 Bump dev deps 2019-05-15
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#3869 Fix selection range event data on category axes
  src/plots/cartesian/select.js
  test/jasmine/tests/select_test.js
Labels: status: reviewable, type: bug

#3874 Use sane-topojson v3
  dist/topojson/africa_110m.json
  dist/topojson/africa_50m.json
  dist/topojson/asia_110m.json
  dist/topojson/asia_50m.json
  dist/topojson/europe_110m.json
  dist/topojson/europe_50m.json
  dist/topojson/north-america_110m.json
  dist/topojson/north-america_50m.json
  dist/topojson/south-america_110m.json
  dist/topojson/south-america_50m.json
  dist/topojson/usa_110m.json
  dist/topojson/usa_50m.json
  dist/topojson/world_110m.json
  dist/topojson/world_50m.json
  package-lock.json
  package.json
  src/lib/geo_location_utils.js
  tasks/util/constants.js
  test/image/baselines/geo_canadian-cites.png
  test/image/baselines/geo_canadian-cities.png
  test/image/baselines/geo_choropleth-text.png
  test/image/baselines/geo_country-names.png
  test/image/baselines/geo_custom-colorscale.png
  test/image/baselines/geo_europe-bubbles.png
  test/image/baselines/geo_first.png
  test/image/baselines/geo_orthographic.png
  test/image/baselines/geo_point-selection.png
  test/image/baselines/geo_scattergeo-out-of-usa.png
  test/image/baselines/geo_second.png
  test/image/baselines/geo_stereographic.png
  test/image/mocks/geo_canadian-cities.json
Labels: status: discussion needed, type: feature

#3851 Display true boolean text on bars
  src/traces/bar/helpers.js
  test/jasmine/tests/bar_test.js
Labels: status: reviewable, type: bug

#3846 Draw box/violin pts as legend item when other parts have opacity 0
  src/components/legend/style.js
  test/image/baselines/box_violin_just_pts.png
  test/image/mocks/box_violin_just_pts.json
Labels: status: reviewable, type: bug

#3864 sort categorical Cartesian axes by value
  src/lib/index.js
  src/lib/stats.js
  src/plot_api/plot_schema.js
  src/plots/cartesian/layout_attributes.js
  src/plots/cartesian/set_convert.js
  src/plots/cartesian/type_defaults.js
  src/plots/plots.js
  src/traces/box/calc.js
  src/traces/ohlc/calc.js
  src/traces/splom/defaults.js
  test/image/baselines/hist_category_total_ascending.png
  test/image/baselines/scatter_category_total_descending.png
  test/image/baselines/sort_by_total_matching_axes.png
  test/image/mocks/hist_category_total_ascending.json
  test/image/mocks/scatter_category_total_descending.json
  test/image/mocks/sort_by_total_matching_axes.json
  test/jasmine/tests/calcdata_test.js
  test/jasmine/tests/lib_test.js
Labels: status: discussion needed, status: reviewable, type: feature

#3880 Bump down karma-jasmine-spec-tags to 1.0.1
  package-lock.json
  package.json
  test/jasmine/tests/select_test.js
Labels: type: maintenance

#3845 Introducing histogram* bingroup attributes
  src/plots/cartesian/axes.js
  src/plots/cartesian/clean_ticks.js
  src/traces/bar/defaults.js
  src/traces/heatmap/calc.js
  src/traces/histogram/attributes.js
  src/traces/histogram/calc.js
  src/traces/histogram/cross_trace_defaults.js
  src/traces/histogram/index.js
  src/traces/histogram2d/attributes.js
  src/traces/histogram2d/calc.js
  src/traces/histogram2d/cross_trace_defaults.js
  src/traces/histogram2d/defaults.js
  src/traces/histogram2d/index.js
  src/traces/histogram2dcontour/attributes.js
  src/traces/histogram2dcontour/index.js
  test/image/baselines/2dhistogram_contour_subplots_bingroup.png
  test/image/baselines/histogram2d_bingroup.png
  test/image/baselines/histogram_overlay-bingroup.png
  test/image/mocks/2dhistogram_contour_subplots_bingroup.json
  test/image/mocks/histogram2d_bingroup.json
  test/image/mocks/histogram_overlay-bingroup.json
  test/jasmine/tests/bar_test.js
  test/jasmine/tests/histogram_test.js
  test/jasmine/tests/plot_api_test.js
Labels: status: reviewable, type: feature

#3862 Add legend click interaction attrs
  src/components/legend/attributes.js
  src/components/legend/defaults.js
  src/components/legend/handle_click.js
  test/jasmine/tests/legend_test.js
Labels: status: reviewable, type: feature

#3865 Trace meta text
  src/components/annotations/draw.js
  src/components/colorbar/draw.js
  src/components/fx/hover.js
  src/components/legend/draw.js
  src/components/rangeselector/draw.js
  src/components/sliders/draw.js
  src/components/titles/index.js
  src/components/updatemenus/draw.js
  src/plots/attributes.js
  src/plots/gl3d/layout/convert.js
  src/plots/layout_attributes.js
  src/plots/plots.js
  src/traces/pie/plot.js
  test/image/baselines/trace_metatext.png
  test/image/mocks/trace_metatext.json
  test/jasmine/tests/hover_label_test.js
Labels: status: reviewable, type: feature

#3848 Display bar outlines with height zero
  src/traces/bar/plot.js
  test/image/baselines/bar-marker-line-colorscales.png
  test/image/baselines/bar_display_height_zero.png
  test/image/baselines/error_bar_bar_ids.png
  test/image/baselines/funnel_horizontal_group_basic.png
  test/image/baselines/funnel_vertical_overlay_custom_arrays.png
  test/image/mocks/bar_display_height_zero.json
  test/jasmine/tests/bar_test.js
Labels: status: reviewable, type: bug

#3856 Miscellaneous geo fixes
  dist/topojson/africa_110m.json
  dist/topojson/africa_50m.json
  dist/topojson/asia_110m.json
  dist/topojson/asia_50m.json
  dist/topojson/europe_110m.json
  dist/topojson/europe_50m.json
  dist/topojson/north-america_110m.json
  dist/topojson/north-america_50m.json
  dist/topojson/south-america_110m.json
  dist/topojson/south-america_50m.json
  dist/topojson/usa_110m.json
  dist/topojson/usa_50m.json
  dist/topojson/world_110m.json
  dist/topojson/world_50m.json
  package-lock.json
  package.json
  src/lib/geo_location_utils.js
  src/plots/geo/geo.js
  tasks/util/constants.js
  test/image/baselines/geo_canadian-cites.png
  test/image/baselines/geo_canadian-cities.png
  test/image/baselines/geo_choropleth-text.png
  test/image/baselines/geo_country-names.png
  test/image/baselines/geo_custom-colorscale.png
  test/image/baselines/geo_europe-bubbles.png
  test/image/baselines/geo_first.png
  test/image/baselines/geo_orthographic.png
  test/image/baselines/geo_point-selection.png
  test/image/baselines/geo_scattergeo-out-of-usa.png
  test/image/baselines/geo_second.png
  test/image/baselines/geo_skymap.png
  test/image/baselines/geo_stereographic.png
  test/image/baselines/geo_usa-states-on-world-scope.png
  test/image/mocks/geo_canadian-cities.json
  test/image/mocks/geo_skymap.json
  test/image/mocks/geo_usa-states-on-world-scope.json
  test/jasmine/karma.conf.js
  test/jasmine/tests/geo_test.js
Labels: status: reviewable, type: bug, type: feature

#3890 Use correct index to lookup unique histogram2d y vals
  src/traces/histogram2d/calc.js
  test/jasmine/tests/hover_label_test.js
Labels: status: reviewable, type: bug

#3889 Fix hoverAvoidOverlaps for zoomed-in violin traces
  src/components/fx/hover.js
  src/traces/violin/hover.js
  test/image/baselines/violin_zoomed-in.png
  test/image/mocks/violin_zoomed-in.json
  test/jasmine/tests/violin_test.js
Labels: status: reviewable, type: bug

#3891 fix pie-like legend when line color array has length greater than 3
  src/components/legend/style.js
  test/image/baselines/funnelarea_line_width.png
  test/image/baselines/pie_legend_line_color_array.png
  test/image/mocks/pie_legend_line_color_array.json
Labels: status: reviewable, type: bug

#3888 `plotly_relayouting` event: live updates during panning/zooming
  src/plots/cartesian/dragbox.js
  src/plots/geo/zoom.js
  src/plots/gl3d/scene.js
  src/plots/mapbox/mapbox.js
  src/plots/polar/polar.js
  src/plots/ternary/ternary.js
  test/jasmine/tests/cartesian_interact_test.js
  test/jasmine/tests/geo_test.js
  test/jasmine/tests/gl3d_plot_interact_test.js
  test/jasmine/tests/mapbox_test.js
  test/jasmine/tests/polar_test.js
  test/jasmine/tests/ternary_test.js
Labels: status: reviewable, type: feature

#3644 Bug fix errorbars on bar trace may disappear after switch modebar to select and double click
  src/traces/bar/style.js
  test/jasmine/tests/select_test.js
Labels: status: reviewable, type: bug, type: regression

#3688 Update vertextcolor description to note the range of the values
  src/traces/mesh3d/attributes.js
Labels: type: documentation

#3901 Parcoords coloraxis
  src/traces/parcoords/attributes.js
  src/traces/parcoords/calc.js
  src/traces/parcoords/parcoords.js
  test/image/baselines/gl2d_parcoords_coloraxis.png
  test/image/mocks/gl2d_parcoords_coloraxis.json
Labels: status: reviewable, type: bug

#3903 Accept number `0` as valid item in sunburst ids/parents
  src/traces/sunburst/calc.js
  test/jasmine/tests/sunburst_test.js
Labels: status: reviewable, type: bug

#3907 Fix sunburst text in sectors centered around theta=180
  src/traces/sunburst/plot.js
  test/image/baselines/sunburst_textfit.png
  test/image/mocks/sunburst_textfit.json
Labels: status: reviewable, type: bug

#3911 Funnel trace description
  src/traces/funnel/index.js
Labels: type: documentation

#3912 funnelarea trace description
  src/traces/funnelarea/index.js
Labels: type: documentation

#3916 Coloraxis for scattergl
  src/lib/gl_format_color.js
  test/image/baselines/gl2d_marker_coloraxis.png
  test/image/mocks/gl2d_marker_coloraxis.json
Labels: status: reviewable, type: bug

#3915 Fix2950 parcoords cannot select first enum
  src/traces/parcoords/axisbrush.js
  test/image/baselines/gl2d_parcoords_select_first_last_enum.png
  test/image/mocks/gl2d_parcoords_select_first_last_enum.json
Labels: status: reviewable, type: bug

#3917 treating rgba colors similar to rgb on parallel coordinates
  src/traces/parcoords/parcoords.js
  test/image/baselines/gl2d_parcoords_rgba_colorscale.png
  test/image/mocks/gl2d_parcoords_rgba_colorscale.json
Labels: status: reviewable, type: bug

#3922 histogram2d fixes
  src/plots/plots.js
  src/traces/heatmap/make_bound_array.js
  src/traces/histogram/calc.js
  src/traces/histogram/cross_trace_defaults.js
  src/traces/histogram2d/calc.js
  test/image/baselines/histogram2d_bingroup-coloraxis.png
  test/image/baselines/histogram2dcontour_bingroup-coloraxis.png
  test/image/mocks/histogram2d_bingroup-coloraxis.json
  test/image/mocks/histogram2dcontour_bingroup-coloraxis.json
  test/jasmine/tests/histogram2d_test.js
  test/jasmine/tests/histogram_test.js
  test/jasmine/tests/hover_label_test.js
Labels: status: reviewable, type: bug

#3925 Correct parcoords tickvals and ticktext documentation - no tickmode property
  src/traces/parcoords/attributes.js
Labels: status: reviewable, type: documentation

#3924 fix for ScatterGL hover and click events give the 'top' point instead of the 'bottom' point
  src/traces/scattergl/index.js
  test/jasmine/tests/gl2d_click_test.js
Labels: status: reviewable, type: bug

#3927 Fix carpet axis title position for decreasing a/b coords
  src/traces/carpet/plot.js
  test/image/baselines/carpet_ordering-labeling.png
  test/image/mocks/carpet_ordering-labeling.json
Labels: status: reviewable, type: bug
