Repository plotly/plotly.js, pull requests merged in 2019-02, with the labels that each got.

#3512 Clip scattercarpet traces with clipPath of ref'ed carpet
  src/traces/scattercarpet/plot.js
  test/image/baselines/scattercarpet-on-two-carpets.png
  test/image/mocks/scattercarpet-on-two-carpets.json
Labels: status: reviewable, type: bug

#3510 Fix axis automargin push offset
  src/plots/cartesian/axes.js
  test/image/baselines/axis_automargin_zero_margins.png
  test/image/baselines/legend_large_margin.png
  test/image/baselines/long_axis_labels.png
  test/image/baselines/multicategory2.png
  test/image/baselines/range_slider_top_axis.png
  test/image/mocks/axis_automargin_zero_margins.json
  test/jasmine/tests/axes_test.js
Labels: status: reviewable, type: bug

#3513 Fix mathjax placement in ternary aaxis titles
  src/lib/svg_text_utils.js
  test/image/baselines/ternary-mathjax.png
  test/image/mocks/ternary-mathjax.json
Labels: status: reviewable, type: bug

#3496 Enabling transparent webgl draws for scatter3d trace when colors are transparent
  package-lock.json
  package.json
  test/image/baselines/gl3d_scatter3d_line3d_error3d_enable-alpha-with-rgba-color.png
  test/image/baselines/gl3d_scatter3d_line3d_error3d_transparent-with-zero-alpha.png
  test/image/mocks/gl3d_scatter3d_line3d_error3d_enable-alpha-with-rgba-color.json
Labels: status: reviewable, type: bug

#3527 Fix react+uirevision when removing traces
  src/plot_api/plot_api.js
  test/jasmine/tests/plot_api_react_test.js
Labels: status: reviewable, type: bug

#3532 Bump dev deps 2019-02-10
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#3534 Fix annotations SVG errors on trace-less subplots
  src/components/annotations/draw.js
  src/plots/gl3d/scene.js
  test/image/strict-d3.js
  test/jasmine/tests/annotations_test.js
Labels: status: reviewable, type: bug

#3537 Fix finance chart null item hover
  src/traces/ohlc/hover.js
  test/jasmine/tests/finance_test.js
Labels: status: reviewable, type: bug

#3536 Fix bug in scattergl text update
  src/traces/scattergl/index.js
  test/jasmine/tests/scattergl_test.js
Labels: status: reviewable, type: bug

#3521 Increase the speed of isosurface creation
  src/traces/isosurface/attributes.js
  src/traces/isosurface/convert.js
  src/traces/isosurface/defaults.js
  test/image/baselines/gl3d_isosurface_2surfaces-checker_spaceframe.png
  test/image/baselines/gl3d_isosurface_math.png
  test/image/baselines/gl3d_isosurface_xycaps_volume_slices.png
  test/image/mocks/gl3d_isosurface_log-axis_slices_surface-fill.json
  test/image/mocks/gl3d_isosurface_thin_caps_different_dims.json
  test/image/mocks/gl3d_isosurface_uneven-scales_ranges_iso-null.json
  test/image/mocks/gl3d_isosurface_with_surface-pattern.json
  test/image/mocks/gl3d_isosurface_xycaps_volume_slices.json
Labels: status: reviewable, type: performance

#3538 Polar better angular tick label placement
  src/components/colorbar/draw.js
  src/plots/cartesian/axes.js
  src/plots/polar/polar.js
  src/plots/ternary/ternary.js
  test/image/baselines/glpolar_scatter.png
  test/image/baselines/glpolar_style.png
  test/image/baselines/glpolar_subplots.png
  test/image/baselines/layout_metatext.png
  test/image/baselines/polar_bar-overlay.png
  test/image/baselines/polar_bar-stacked.png
  test/image/baselines/polar_bar-width-base-offset.png
  test/image/baselines/polar_blank.png
  test/image/baselines/polar_categories.png
  test/image/baselines/polar_dates.png
  test/image/baselines/polar_direction.png
  test/image/baselines/polar_fills.png
  test/image/baselines/polar_funky-bars.png
  test/image/baselines/polar_hole.png
  test/image/baselines/polar_line.png
  test/image/baselines/polar_long-category-angular-labels.png
  test/image/baselines/polar_polygon-bars.png
  test/image/baselines/polar_polygon-grids.png
  test/image/baselines/polar_r0dr-theta0dtheta.png
  test/image/baselines/polar_radial-range.png
  test/image/baselines/polar_scatter.png
  test/image/baselines/polar_sector.png
  test/image/baselines/polar_subplots.png
  test/image/baselines/polar_template.png
  test/image/baselines/polar_ticks.png
  test/image/baselines/polar_transforms.png
  test/image/baselines/polar_wind-rose.png
  test/image/mocks/polar_long-category-angular-labels.json
Labels: status: reviewable, type: bug

#3500 Fix responsive WebGL figures and modebar
  build/plotcss.js
  src/components/modebar/modebar.js
  src/css/_modebar.scss
  src/plot_api/plot_api.js
  test/jasmine/tests/config_test.js
  test/jasmine/tests/modebar_test.js
Labels: status: reviewable, type: bug

#3535 handle large circular sankey diagram
  package-lock.json
  package.json
  src/traces/sankey/render.js
  test/image/baselines/sankey_circular_large.png
  test/image/baselines/sankey_circular_process.png
  test/image/baselines/sankey_circular_simple.png
  test/image/baselines/sankey_subplots_circular.png
  test/image/mocks/sankey_circular_large.json
  test/image/mocks/sankey_circular_simple.json
  test/jasmine/tests/sankey_test.js
Labels: status: in progress, type: performance

#3406 d3-sankey-circular
  package-lock.json
  package.json
  src/traces/sankey/calc.js
  src/traces/sankey/plot.js
  src/traces/sankey/render.js
  test/image/baselines/sankey_circular.png
  test/image/baselines/sankey_circular_large.png
  test/image/baselines/sankey_circular_process.png
  test/image/baselines/sankey_circular_simple.png
  test/image/baselines/sankey_large_padding.png
  test/image/baselines/sankey_subplots_circular.png
  test/image/mocks/sankey_circular.json
  test/image/mocks/sankey_circular_large.json
  test/image/mocks/sankey_circular_process.json
  test/image/mocks/sankey_circular_simple.json
  test/image/mocks/sankey_subplots_circular.json
  test/jasmine/tests/sankey_test.js
Labels: status: reviewable, type: feature

#3544 Fix finance trace auto-range
  src/traces/box/cross_trace_calc.js
  src/traces/ohlc/calc.js
  test/jasmine/tests/finance_test.js
Labels: status: reviewable, type: bug

#3548 More layout meta support
  src/components/fx/hover.js
  src/components/legend/draw.js
  src/components/rangeselector/draw.js
  src/components/sliders/draw.js
  src/components/updatemenus/draw.js
  src/lib/index.js
  src/plots/layout_attributes.js
  test/image/baselines/layout_metatext.png
  test/image/mocks/layout_metatext.json
  test/jasmine/tests/hover_label_test.js
Labels: status: reviewable, type: feature

#3530 More hovertemplates!
  src/components/fx/hover.js
  src/components/fx/hovertemplate_attributes.js
  src/plots/gl3d/scene.js
  src/traces/cone/attributes.js
  src/traces/cone/defaults.js
  src/traces/cone/index.js
  src/traces/contour/attributes.js
  src/traces/contour/defaults.js
  src/traces/heatmap/attributes.js
  src/traces/heatmap/defaults.js
  src/traces/histogram/event_data.js
  src/traces/histogram2d/attributes.js
  src/traces/histogram2d/defaults.js
  src/traces/histogram2dcontour/attributes.js
  src/traces/histogram2dcontour/defaults.js
  src/traces/isosurface/attributes.js
  src/traces/isosurface/defaults.js
  src/traces/mesh3d/attributes.js
  src/traces/mesh3d/defaults.js
  src/traces/parcats/attributes.js
  src/traces/parcats/defaults.js
  src/traces/parcats/parcats.js
  src/traces/scatter3d/attributes.js
  src/traces/scatter3d/defaults.js
  src/traces/scattercarpet/attributes.js
  src/traces/scattercarpet/defaults.js
  src/traces/scattercarpet/event_data.js
  src/traces/scattercarpet/hover.js
  src/traces/splom/attributes.js
  src/traces/splom/defaults.js
  src/traces/streamtube/attributes.js
  src/traces/streamtube/defaults.js
  src/traces/surface/attributes.js
  src/traces/surface/defaults.js
  test/jasmine/tests/carpet_test.js
  test/jasmine/tests/cone_test.js
  test/jasmine/tests/gl3d_plot_interact_test.js
  test/jasmine/tests/hover_label_test.js
  test/jasmine/tests/isosurface_test.js
  test/jasmine/tests/parcats_test.js
  test/jasmine/tests/splom_test.js
  test/jasmine/tests/streamtube_test.js
Labels: status: reviewable, type: feature

#3545 Isosurface opacity
  src/traces/isosurface/attributes.js
  src/traces/isosurface/convert.js
  src/traces/isosurface/defaults.js
  src/traces/surface/attributes.js
  test/image/baselines/gl3d_isosurface_log-axis_slices_surface-fill.png
  test/image/baselines/gl3d_isosurface_thin_slices_transparent.png
  test/image/baselines/gl3d_isosurface_transparent.png
  test/image/mocks/gl3d_isosurface_thin_slices_transparent.json
  test/image/mocks/gl3d_isosurface_transparent.json
Labels: status: reviewable, type: bug, type: feature

#3501 Sankey: colorscales per component, linked to concentration
  src/traces/sankey/attributes.js
  src/traces/sankey/calc.js
  src/traces/sankey/defaults.js
  src/traces/sankey/plot.js
  src/traces/sankey/render.js
  test/image/baselines/sankey_link_concentration.png
  test/image/mocks/sankey_link_concentration.json
  test/jasmine/tests/sankey_test.js
Labels: status: reviewable, type: feature

#3506 Implementing matching axes
  src/plot_api/plot_api.js
  src/plot_api/subroutines.js
  src/plots/cartesian/autorange.js
  src/plots/cartesian/constraint_defaults.js
  src/plots/cartesian/constraints.js
  src/plots/cartesian/dragbox.js
  src/plots/cartesian/layout_attributes.js
  src/plots/cartesian/layout_defaults.js
  src/plots/cartesian/set_convert.js
  src/traces/histogram/cross_trace_defaults.js
  src/traces/splom/attributes.js
  src/traces/splom/defaults.js
  test/image/baselines/axes_scaleanchor-constrain-domain-fixedrange.png
  test/image/baselines/axes_scaleanchor-with-matches.png
  test/image/baselines/hists-on-matching-axes.png
  test/image/baselines/matching-categories.png
  test/image/baselines/splom_iris-matching.png
  test/image/baselines/splom_lower-nodiag-matching.png
  test/image/mocks/axes_scaleanchor-constrain-domain-fixedrange.json
  test/image/mocks/axes_scaleanchor-with-matches.json
  test/image/mocks/hists-on-matching-axes.json
  test/image/mocks/matching-categories.json
  test/image/mocks/splom_iris-matching.json
  test/image/mocks/splom_lower-nodiag-matching.json
  test/jasmine/assets/custom_matchers.js
  test/jasmine/assets/drag.js
  test/jasmine/tests/axes_test.js
  test/jasmine/tests/cartesian_interact_test.js
  test/jasmine/tests/polar_test.js
  test/jasmine/tests/splom_test.js
Labels: status: reviewable, type: feature

#3529 Implement alignmentgroup and offsetgroup
  src/plots/cartesian/axis_ids.js
  src/plots/plots.js
  src/traces/bar/attributes.js
  src/traces/bar/cross_trace_calc.js
  src/traces/bar/defaults.js
  src/traces/bar/index.js
  src/traces/bar/layout_defaults.js
  src/traces/box/attributes.js
  src/traces/box/cross_trace_calc.js
  src/traces/box/defaults.js
  src/traces/box/index.js
  src/traces/box/layout_defaults.js
  src/traces/histogram/attributes.js
  src/traces/histogram/cross_trace_defaults.js
  src/traces/histogram/defaults.js
  src/traces/violin/attributes.js
  src/traces/violin/index.js
  test/image/baselines/bar-alignment-offset.png
  test/image/baselines/bar-grouping-vs-defaults.png
  test/image/baselines/bar-offsetgroups.png
  test/image/baselines/box-alignment-offset.png
  test/image/baselines/groups-over-matching-axes.png
  test/image/baselines/histogram-offsetgroups.png
  test/image/baselines/violin-offsetgroups.png
  test/image/mocks/bar-alignment-offset.json
  test/image/mocks/bar-grouping-vs-defaults.json
  test/image/mocks/bar-offsetgroups.json
  test/image/mocks/box-alignment-offset.json
  test/image/mocks/groups-over-matching-axes.json
  test/image/mocks/histogram-offsetgroups.json
  test/image/mocks/violin-offsetgroups.json
  test/jasmine/tests/bar_test.js
  test/jasmine/tests/box_test.js
  test/jasmine/tests/violin_test.js
Labels: status: reviewable, type: feature

#3554 Adapt `Colorscale.crossTraceDefaults` to array ` _module.colorbar` definitions
  src/components/colorscale/cross_trace_defaults.js
  test/jasmine/tests/colorscale_test.js
Labels: status: reviewable, type: regression

#3553 Add 'hovertext' attribute to all traces that support hover 'text'
  src/traces/barpolar/attributes.js
  src/traces/barpolar/defaults.js
  src/traces/box/attributes.js
  src/traces/box/calc.js
  src/traces/box/defaults.js
  src/traces/candlestick/attributes.js
  src/traces/candlestick/defaults.js
  src/traces/choropleth/attributes.js
  src/traces/choropleth/defaults.js
  src/traces/cone/attributes.js
  src/traces/cone/convert.js
  src/traces/cone/defaults.js
  src/traces/contour/attributes.js
  src/traces/contour/defaults.js
  src/traces/contourcarpet/attributes.js
  src/traces/heatmap/attributes.js
  src/traces/heatmap/calc.js
  src/traces/heatmap/convert_column_xyz.js
  src/traces/heatmap/defaults.js
  src/traces/heatmap/hover.js
  src/traces/histogram/attributes.js
  src/traces/histogram/defaults.js
  src/traces/isosurface/attributes.js
  src/traces/isosurface/convert.js
  src/traces/isosurface/defaults.js
  src/traces/mesh3d/attributes.js
  src/traces/mesh3d/convert.js
  src/traces/mesh3d/defaults.js
  src/traces/ohlc/attributes.js
  src/traces/ohlc/calc.js
  src/traces/ohlc/defaults.js
  src/traces/scattercarpet/attributes.js
  src/traces/scattercarpet/defaults.js
  src/traces/scattercarpet/hover.js
  src/traces/splom/attributes.js
  src/traces/splom/defaults.js
  src/traces/streamtube/attributes.js
  src/traces/streamtube/convert.js
  src/traces/streamtube/defaults.js
  src/traces/surface/attributes.js
  src/traces/surface/convert.js
  src/traces/surface/defaults.js
  src/traces/violin/attributes.js
  test/image/baselines/scattercarpet-text.png
  test/image/mocks/scattercarpet-text.json
  test/jasmine/tests/barpolar_test.js
  test/jasmine/tests/box_test.js
  test/jasmine/tests/carpet_test.js
  test/jasmine/tests/choropleth_test.js
  test/jasmine/tests/cone_test.js
  test/jasmine/tests/finance_test.js
  test/jasmine/tests/gl3d_plot_interact_test.js
  test/jasmine/tests/hover_label_test.js
  test/jasmine/tests/isosurface_test.js
  test/jasmine/tests/splom_test.js
  test/jasmine/tests/streamtube_test.js
  test/jasmine/tests/violin_test.js
Labels: status: reviewable, type: feature

#3549 Add midpoint attr to color scales
  src/components/colorscale/attributes.js
  src/components/colorscale/calc.js
  src/components/colorscale/defaults.js
  src/traces/scattermapbox/attributes.js
  test/image/baselines/cmid-zmid.png
  test/image/mocks/cmid-zmid.json
  test/jasmine/tests/plot_api_test.js
  test/jasmine/tests/scattergeo_test.js
  test/jasmine/tests/surface_test.js
Labels: status: reviewable, type: feature

#3399 Expose mapbox minzoom, maxzoom, and symbol-placement properties
  src/plots/mapbox/layers.js
  src/plots/mapbox/layout_attributes.js
  src/plots/mapbox/layout_defaults.js
  test/image/baselines/mapbox_geojson-attributes.png
  test/image/mocks/mapbox_geojson-attributes.json
Labels: status: reviewable, type: feature

#3550 Orthographic projection for 3D plots - finalist
  package-lock.json
  package.json
  src/components/modebar/buttons.js
  src/plot_api/subroutines.js
  src/plots/gl3d/camera.js
  src/plots/gl3d/index.js
  src/plots/gl3d/layout/defaults.js
  src/plots/gl3d/layout/layout_attributes.js
  src/plots/gl3d/scene.js
  test/image/baselines/gl3d_annotations_orthographic.png
  test/image/baselines/gl3d_isosurface_9more-surfaces_between-ranges_orthographic.png
  test/image/baselines/gl3d_mesh3d_surface3d_scatter3d_orthographic.png
  test/image/mocks/gl3d_annotations_orthographic.json
  test/image/mocks/gl3d_isosurface_9more-surfaces_between-ranges_orthographic.json
  test/image/mocks/gl3d_mesh3d_surface3d_scatter3d_orthographic.json
  test/jasmine/tests/gl3d_plot_interact_test.js
  test/jasmine/tests/gl_plot_interact_basic_test.js
  test/jasmine/tests/plot_api_react_test.js
Labels: status: reviewable, type: feature

#3558 Improve CI publish container
  .circleci/config.yml
  tasks/bundle_plot_schema.js
Labels: status: reviewable, type: maintenance

#3564 Sankey: properly set coordinates of node's origin prior to drag operation
  src/traces/sankey/render.js
  test/jasmine/tests/sankey_test.js
Labels: status: reviewable, type: bug

#3565 Fix category init for non-matching axes on graphs with matching axes
  src/plots/cartesian/set_convert.js
  test/image/baselines/axes_matches-linear-categories.png
  test/image/mocks/axes_matches-linear-categories.json
Labels: status: reviewable, type: bug

#3566 Fix automargin regression for superimposed subplots
  src/plots/cartesian/axes.js
  test/image/baselines/automargin-superimposed-axes.png
  test/image/mocks/automargin-superimposed-axes.json
Labels: status: reviewable, type: bug

#3575 Call styleTextSelection only on hasText traces
  src/traces/scattergl/index.js
  test/jasmine/tests/gl2d_plot_interact_test.js
Labels: status: reviewable, type: bug

#3577 Clear selection outline during 'axrange' relayout calls
  src/plot_api/plot_api.js
  test/jasmine/tests/select_test.js
Labels: status: reviewable, type: bug

#3578 No scattergl clustering below 1e5 pts
  src/traces/scattergl/index.js
  test/image/baselines/gl2d_no-clustering.png
  test/image/baselines/gl2d_no-clustering2.png
  test/image/baselines/gl2d_scatter-color-clustering.png
  test/image/baselines/gl2d_scatter-continuous-clustering.png
  test/image/mocks/gl2d_no-clustering.json
  test/image/mocks/gl2d_no-clustering2.json
Labels: status: reviewable, type: bug

#3556 Sankey: group nodes
  src/traces/sankey/attributes.js
  src/traces/sankey/calc.js
  src/traces/sankey/constants.js
  src/traces/sankey/defaults.js
  src/traces/sankey/render.js
  test/image/baselines/sankey_groups.png
  test/image/mocks/sankey_groups.json
  test/jasmine/tests/sankey_test.js
Labels: status: reviewable, type: feature

#3586 support locales in hovertemplate
  src/components/fx/hover.js
  src/lib/index.js
  test/image/mocks/sankey_link_concentration.json
  test/jasmine/tests/hover_label_test.js
  test/jasmine/tests/lib_test.js
Labels: status: reviewable, type: bug
