Repository plotly/plotly.js, pull requests merged in 2019-09, with the labels that each got.

#4168 Bump dev deps 2019 09 06
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#4170 Remove off-screen annotations during drag
  src/components/annotations/draw.js
  test/jasmine/tests/annotations_test.js
Labels: status: reviewable, type: bug, type: regression

#4169 Distribute minified files in own packages
  tasks/stats.js
  tasks/sync_packages.js
Labels: status: reviewable, type: feature

#4167 Fix multi-axis transition "leaks"
  src/plots/plots.js
  test/jasmine/tests/animate_test.js
  test/jasmine/tests/transition_test.js
Labels: status: reviewable, type: bug

#4165 Axes.draw w/o getBoundingClientRect + many axis automargin fixes
  src/components/fx/hover.js
  src/components/rangeslider/draw.js
  src/components/rangeslider/helpers.js
  src/lib/svg_text_utils.js
  src/plot_api/subroutines.js
  src/plots/cartesian/axes.js
  src/plots/plots.js
  src/plots/polar/polar.js
  test/image/baselines/automargin-mirror-all.png
  test/image/baselines/automargin-mirror-allticks.png
  test/image/baselines/automargin-multiline-titles.png
  test/image/baselines/automargin-rangeslider-and-sidepush.png
  test/image/baselines/finance_multicategory.png
  test/image/baselines/finance_subplots_categories.png
  test/image/baselines/multicategory-inside-ticks.png
  test/image/baselines/multicategory-mirror.png
  test/image/baselines/multicategory-sorting.png
  test/image/baselines/multicategory-y.png
  test/image/baselines/multicategory2.png
  test/image/baselines/multicategory_histograms.png
  test/image/baselines/range_slider_box.png
  test/image/baselines/range_slider_multiple.png
  test/image/baselines/violin_grouped_horz-multicategory.png
  test/image/mocks/automargin-mirror-all.json
  test/image/mocks/automargin-mirror-allticks.json
  test/image/mocks/automargin-multiline-titles.json
  test/image/mocks/automargin-rangeslider-and-sidepush.json
  test/image/mocks/multicategory2.json
  test/jasmine/tests/hover_spikeline_test.js
Labels: status: reviewable, type: bug, type: performance

#4177 Fix contour(carpet) label formatting via colorbar settings
  src/components/colorbar/draw.js
  src/traces/contour/plot.js
  src/traces/contourcarpet/plot.js
  test/image/baselines/contour_label-formatting-via-colorbar.png
  test/image/mocks/contour_label-formatting-via-colorbar.json
Labels: status: reviewable, type: bug, type: regression

#4176 Properly handle <br> and \n in scattermapbox text
  src/lib/svg_text_utils.js
  src/traces/scattermapbox/convert.js
  test/image/baselines/mapbox_bubbles-text.png
  test/image/mocks/mapbox_bubbles-text.json
  test/jasmine/tests/scattermapbox_test.js
Labels: status: reviewable, type: bug

#4179 texttemplate: accept empty text string
  src/traces/pie/helpers.js
  src/traces/pie/plot.js
  src/traces/sunburst/plot.js
  test/jasmine/assets/check_texttemplate.js
  test/jasmine/tests/pie_test.js
Labels: status: reviewable, type: bug

#4184 Fix toggleHover and resetViews modebar buttons for some partial bundle + graph setups
  src/components/modebar/buttons.js
  test/jasmine/tests/modebar_test.js
Labels: status: reviewable, type: bug

#4171 Adapt default axis ranges to rangemode
  src/plots/cartesian/set_convert.js
  test/jasmine/tests/axes_test.js
Labels: status: reviewable, type: bug

#4188 Fix tiny zoombox behavior
  src/plots/cartesian/dragbox.js
  test/jasmine/tests/cartesian_interact_test.js
  test/jasmine/tests/select_test.js
Labels: status: reviewable, type: bug

#4198 change devtools/test_dashboard/server.js to use full url ...
  devtools/test_dashboard/server.js
  package-lock.json
Labels: type: maintenance

#4197 A few mapbox fixes
  src/plot_api/plot_api.js
  src/plots/mapbox/layers.js
  src/traces/choropleth/hover.js
  test/jasmine/tests/choroplethmapbox_test.js
  test/jasmine/tests/mapbox_test.js
Labels: status: reviewable, type: bug

#4189 Show zeroline even when no grid lines are present
  src/plots/cartesian/axes.js
  src/traces/splom/base_plot.js
  test/jasmine/tests/axes_test.js
  test/jasmine/tests/splom_test.js
Labels: status: reviewable, type: bug

#4208 include color-rgba in package and bump gl-cone3d as well as gl-streamtube3d
  package-lock.json
  package.json
Labels: type: maintenance

#4209 remove duplicate keys and data from gl3d_isosurface_math mock
  test/image/mocks/gl3d_isosurface_math.json
Labels: type: maintenance

#4186 bar transitions: support object constancy
  src/traces/bar/plot.js
  test/image/mocks/animation_bar.json
  test/jasmine/assets/check_transitions.js
  test/jasmine/tests/bar_test.js
Labels: status: in progress, type: feature

#4181 additions to streamtube doc
  src/traces/streamtube/index.js
Labels: status: reviewable, type: documentation

#4148 add missing translation keys
  lib/locales/cs.js
  lib/locales/de.js
  lib/locales/es.js
  lib/locales/fr.js
  lib/locales/it.js
  lib/locales/ja.js
  lib/locales/pt-br.js
  lib/locales/sw.js
Labels: status: in progress, type: translation

#4204 Update RU and UK locales and fix FR locale keys
  lib/locales/fr.js
  lib/locales/ru.js
  lib/locales/uk.js
Labels: type: translation

#4211 Add constraint info to parcats click/hover events
  src/traces/parcats/calc.js
  src/traces/parcats/parcats.js
  test/jasmine/tests/parcats_test.js
Labels: status: reviewable, type: feature

#4160 Multiple legend positioning and sizing fixes
  src/components/legend/anchor_utils.js
  src/components/legend/attributes.js
  src/components/legend/constants.js
  src/components/legend/defaults.js
  src/components/legend/draw.js
  src/components/legend/get_legend_data.js
  src/plots/layout_attributes.js
  src/plots/plots.js
  test/image/baselines/legend_horizontal_bg_fit.png
  test/image/baselines/legend_horizontal_wrap-alll-lines.png
  test/image/baselines/legend_margin-autoexpand-false.png
  test/image/baselines/legend_negative_x.png
  test/image/baselines/legend_negative_x2.png
  test/image/baselines/legend_scroll_beyond_plotarea.png
  test/image/baselines/legend_small_horizontal.png
  test/image/baselines/legend_small_vertical.png
  test/image/baselines/legend_x_push_margin_constrained.png
  test/image/baselines/legendgroup_horizontal_bg_fit.png
  test/image/baselines/legendgroup_horizontal_wrapping.png
  test/image/mocks/legend_horizontal_bg_fit.json
  test/image/mocks/legend_margin-autoexpand-false.json
  test/image/mocks/legend_negative_x.json
  test/image/mocks/legend_negative_x2.json
  test/image/mocks/legend_scroll_beyond_plotarea.json
  test/image/mocks/legend_small_horizontal.json
  test/image/mocks/legend_small_vertical.json
  test/image/mocks/legend_x_push_margin_constrained.json
  test/image/mocks/legendgroup_horizontal_bg_fit.json
  test/jasmine/tests/legend_test.js
  test/jasmine/tests/splom_test.js
Labels: status: reviewable, type: bug

#4213 Fix scattergl hover over nulls
  src/traces/scattergl/hover.js
  src/traces/splom/hover.js
  test/jasmine/tests/gl2d_click_test.js
Labels: status: reviewable, type: bug

#4214 Add test for legend scroll via touch
  test/jasmine/tests/legend_scroll_test.js
Labels: status: reviewable, type: bug

#4215 Bump gl-cone3d and gl-streamtube3d to include all their required modules
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#4216 More auto-margin fixes (some of them temporary)
  src/plots/cartesian/axes.js
  src/plots/plots.js
  test/image/baselines/automargin-small-width.png
  test/image/mocks/automargin-small-width.json
Labels: status: reviewable, type: bug

#4218 Fix `line.width` attr declaration in *contour traces
  src/traces/contour/attributes.js
  src/traces/contourcarpet/attributes.js
  src/traces/histogram2dcontour/attributes.js
Labels: status: reviewable, type: documentation

#4219 Revise hierarchy referencing and fixup parent percentage at the root node of treemap and sunburst
  src/traces/sunburst/calc.js
  src/traces/sunburst/fx.js
  src/traces/sunburst/helpers.js
  src/traces/sunburst/plot.js
  test/image/baselines/treemap_textposition.png
  test/jasmine/tests/sunburst_test.js
  test/jasmine/tests/treemap_test.js
Labels: status: reviewable, type: bug

#4230 Bump mapbox-gl to v1.3.2
  package-lock.json
  package.json
  src/plots/mapbox/constants.js
  src/plots/mapbox/mapbox.js
Labels: status: reviewable, type: maintenance

#4227 Treemap text positions for out of range cases when transitioning with maxdepth
  src/traces/treemap/draw_ancestors.js
  src/traces/treemap/draw_descendants.js
  src/traces/treemap/plot.js
  test/jasmine/tests/treemap_test.js
Labels: status: reviewable, type: bug

#4231 [dragelement] Make touchmove event listener non passive
  src/components/dragelement/index.js
Labels: status: reviewable, type: bug
