Repository plotly/plotly.js, pull requests merged in 2019-04, with the labels that each got.

#3701 Draw blank bars as empty paths + allow blank bars to draw outsidetext
  src/traces/bar/plot.js
  test/image/baselines/blank-bar-outsidetext.png
  test/image/mocks/blank-bar-outsidetext.json
  test/jasmine/tests/bar_test.js
  test/jasmine/tests/waterfall_test.js
Labels: status: reviewable, type: bug

#3696 Always include the very first and last points for fills
  src/traces/scatter/line_points.js
  src/traces/scatter/plot.js
  test/image/baselines/ultra_zoom_fill.png
  test/image/mocks/ultra_zoom_fill.json
Labels: status: reviewable, type: bug

#3707 Fix `npm run test-image -- *` for mock lists w/o gl2d_* mocks
  test/image/compare_pixels_test.js
Labels: status: reviewable, type: maintenance

#3708 Add waterfall trace to finance bundle
  lib/index-finance.js
Labels: status: reviewable, type: feature

#3702 Bug fix colormap error for colorscales with length of 256
  package-lock.json
  package.json
  test/image/baselines/gl3d_colormap256.png
  test/image/mocks/gl3d_colormap256.json
Labels: status: reviewable, type: bug

#3711 Format numbers in waterfall hover
  src/traces/waterfall/hover.js
  test/jasmine/tests/waterfall_test.js
Labels: status: reviewable, type: bug

#3715 Don't try to access textfont when bar has no text
  src/traces/bar/plot.js
  test/jasmine/tests/bar_test.js
Labels: status: reviewable, type: bug

#3720 waterfall transform errors
  src/traces/bar/plot.js
  src/traces/waterfall/calc.js
  src/traces/waterfall/style.js
  test/jasmine/tests/waterfall_test.js
Labels: status: reviewable, type: bug

#3706 Geo grid fixes
  src/plots/geo/geo.js
  src/plots/geo/index.js
  src/plots/geo/layout/attributes.js
  src/plots/geo/layout_attributes.js
  src/plots/geo/layout_defaults.js
  test/image/baselines/geo_across-antimeridian.png
  test/image/baselines/geo_aitoff-sinusoidal.png
  test/image/baselines/geo_custom-colorscale.png
  test/image/baselines/geo_kavrayskiy7.png
  test/image/baselines/geo_stereographic.png
  test/image/baselines/geo_tick0.png
  test/image/baselines/geo_winkel-tripel.png
  test/image/mocks/geo_kavrayskiy7.json
  test/image/mocks/geo_tick0.json
  test/jasmine/tests/geo_test.js
Labels: status: reviewable, type: bug

#3716 Replot on drag
  src/components/dragelement/index.js
  src/plot_api/plot_api.js
  src/plots/cartesian/dragbox.js
  src/plots/cartesian/select.js
  src/plots/plots.js
  src/plots/polar/polar.js
  src/plots/ternary/ternary.js
  test/jasmine/tests/cartesian_interact_test.js
  test/jasmine/tests/plot_promise_test.js
  test/jasmine/tests/plots_test.js
Labels: status: reviewable, type: bug

#3469 Make surface contour levels configurable
  src/traces/isosurface/attributes.js
  src/traces/surface/attributes.js
  src/traces/surface/convert.js
  src/traces/surface/defaults.js
  test/image/baselines/gl3d_surface_contour_start-end-size.png
  test/image/mocks/gl3d_surface_contour_start-end-size.json
Labels: status: reviewable, type: feature

#3725 Fix3724 parenthesis in url draws data outside plot area
  src/components/drawing/index.js
  test/jasmine/assets/custom_assertions.js
  test/jasmine/assets/get_bbox.js
  test/jasmine/tests/drawing_test.js
  test/jasmine/tests/layout_images_test.js
  test/jasmine/tests/plot_interact_test.js
  test/jasmine/tests/shapes_test.js
  test/jasmine/tests/toimage_test.js
Labels: status: reviewable, type: bug

#3739 bump regl-error2d 2.0.7
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#3730 sankey: compare links in a flow on hover
  src/components/fx/hover.js
  src/components/modebar/manage.js
  src/traces/sankey/plot.js
  src/traces/sankey/render.js
  test/image/mocks/sankey_circular_large.json
  test/image/mocks/sankey_link_concentration.json
  test/jasmine/tests/sankey_test.js
Labels: status: reviewable, type: feature

#3745 Disable mapbox scroll zoom on init, when required
  src/plots/mapbox/mapbox.js
  test/jasmine/tests/mapbox_test.js
Labels: status: reviewable, type: bug

#3712 sankey: implement node grouping via mouse selection
  src/components/modebar/buttons.js
  src/components/modebar/manage.js
  src/plots/cartesian/select.js
  src/traces/sankey/base_plot.js
  src/traces/sankey/calc.js
  src/traces/sankey/index.js
  src/traces/sankey/plot.js
  src/traces/sankey/render.js
  src/traces/sankey/select.js
  test/jasmine/tests/sankey_test.js
  test/jasmine/tests/select_test.js
Labels: status: reviewable, type: feature

#3744 Enable transparency by alpha colors in mesh3d
  package-lock.json
  package.json
  test/image/baselines/gl3d_mesh3d_enable-alpha-with-rgba-color.png
  test/image/mocks/gl3d_mesh3d_enable-alpha-with-rgba-color.json
Labels: status: reviewable, type: bug

#3734 Fix namelength=0 case + implement namelength to loneHover traces
  src/components/fx/attributes.js
  src/components/fx/defaults.js
  src/components/fx/hover.js
  src/lib/svg_text_utils.js
  src/plot_api/plot_schema.js
  src/plots/gl2d/scene2d.js
  src/plots/gl3d/scene.js
  src/plots/plots.js
  src/traces/parcoords/attributes.js
  src/traces/parcoords/index.js
  src/traces/pie/plot.js
  src/traces/sankey/plot.js
  src/traces/sunburst/plot.js
  test/jasmine/bundle_tests/plotschema_test.js
  test/jasmine/tests/gl3d_plot_interact_test.js
  test/jasmine/tests/hover_label_test.js
  test/jasmine/tests/pie_test.js
  test/jasmine/tests/sankey_test.js
  test/jasmine/tests/sunburst_test.js
Labels: status: reviewable, type: bug

#3746 Add way for `toImage` to export images with current graph width/height
  src/components/modebar/buttons.js
  src/plot_api/to_image.js
  src/snapshot/download.js
  test/jasmine/tests/modebar_test.js
  test/jasmine/tests/toimage_test.js
Labels: status: reviewable, type: feature

#3750 sankey: support uirevision for node.groups
  src/plot_api/plot_api.js
  test/jasmine/tests/sankey_test.js
Labels: status: reviewable, type: bug

#3732 Add legend `itemsizing`
  src/components/drawing/index.js
  src/components/legend/attributes.js
  src/components/legend/defaults.js
  src/components/legend/style.js
  src/traces/pie/style_one.js
  test/image/baselines/gl3d_line_rectangle_render.png
  test/image/baselines/gl3d_log-axis-big.png
  test/image/baselines/gl3d_log-axis.png
  test/image/baselines/legend-constant-itemsizing.png
  test/image/mocks/legend-constant-itemsizing.json
  test/jasmine/tests/pie_test.js
Labels: status: reviewable, type: feature

#3753 Align hover label text content with *hoverlabel.align*
  src/components/fx/attributes.js
  src/components/fx/calc.js
  src/components/fx/hover.js
  src/components/fx/hoverlabel_defaults.js
  src/components/fx/layout_attributes.js
  src/plots/gl2d/scene2d.js
  src/plots/gl3d/scene.js
  src/traces/pie/plot.js
  src/traces/sankey/plot.js
  src/traces/sunburst/plot.js
  test/jasmine/tests/fx_test.js
  test/jasmine/tests/hover_label_test.js
  test/jasmine/tests/pie_test.js
Labels: status: reviewable, type: feature

#3756 More stable jasmine2 test runs
  .circleci/test.sh
Labels: type: maintenance

#3755 Don't try to call doneFnCompleted when it isn't set
  src/plots/cartesian/select.js
  test/jasmine/tests/select_test.js
Labels: status: reviewable, type: bug

#3762 Handle special bar insidetext case on log size axes
  src/traces/bar/plot.js
  test/image/baselines/bar-insidetext-log-size-axis.png
  test/image/mocks/bar-insidetext-log-size-axis.json
Labels: status: reviewable, type: bug

#3764 DRY loneHover routine
  src/components/fx/hover.js
  src/components/fx/index.js
  src/traces/parcats/parcats.js
  src/traces/sankey/plot.js
Labels: type: maintenance

#3765 Include baseUrl in gradient style references
  src/components/drawing/index.js
  test/jasmine/tests/drawing_test.js
Labels: status: reviewable, type: bug

#3772 Fix matching date axes
  src/plot_api/subroutines.js
  test/image/baselines/axes_linked_date_autorange.png
  test/image/mocks/axes_linked_date_autorange.json
Labels: status: reviewable, type: bug

#3773 Fix more bar/text/log size axis cases
  src/traces/bar/plot.js
  test/image/baselines/bar-autotext-log-size-axes.png
  test/image/mocks/bar-autotext-log-size-axes.json
Labels: status: reviewable, type: bug

#3778 Bug fix waterfall hovermode closest decreasing values
  src/traces/bar/hover.js
  test/image/mocks/waterfall_profit-loss_2018vs2019_rectangle.json
  test/jasmine/tests/waterfall_test.js
Labels: status: reviewable, type: bug

#3781 Fix hoverlabel.align for centered labels
  src/components/fx/hover.js
  test/jasmine/tests/hover_label_test.js
Labels: status: reviewable, type: bug

#3783 fix svgTextUtils for FF: use child element instead of SVG to getSize()
  src/lib/svg_text_utils.js
  tasks/test_bundle.js
Labels: status: reviewable, type: bug

#3788 Waterfall connector.line.color coerce and default fixup
  src/traces/waterfall/attributes.js
  test/image/baselines/waterfall-grouping-vs-defaults.png
  test/image/baselines/waterfall-offsetgroups.png
  test/image/baselines/waterfall_11.png
  test/image/baselines/waterfall_and_histogram.png
  test/image/baselines/waterfall_cliponaxis-false.png
  test/image/baselines/waterfall_line.png
  test/image/baselines/waterfall_multicategory.png
  test/image/baselines/waterfall_nonnumeric_sizes.png
  test/jasmine/tests/waterfall_test.js
Labels: status: reviewable, type: bug

#3789 Waterfall connector.line.width react bug in mode between
  src/traces/waterfall/attributes.js
  test/jasmine/tests/waterfall_test.js
Labels: status: reviewable, type: bug

#3791 fixup waterfall connectors on date axes
  src/traces/waterfall/cross_trace_calc.js
  src/traces/waterfall/plot.js
  test/image/baselines/waterfall_date-axes.png
  test/image/mocks/waterfall_date-axes.json
Labels: status: reviewable, type: bug

#3792 New lint rule to disallow named function expressions
  .eslintrc
  src/components/dragelement/unhover.js
  src/components/fx/helpers.js
  src/components/updatemenus/scrollbox.js
  src/lib/index.js
  src/lib/polygon.js
  src/plots/cartesian/constraints.js
  src/plots/gl2d/index.js
  src/plots/gl3d/index.js
  src/plots/mapbox/index.js
  src/plots/ternary/index.js
  src/traces/bar/sieve.js
  test/jasmine/assets/unpolyfill.js
Labels: type: maintenance

#3802 sankey: only stash initial view params if trace type is sankey
  src/traces/sankey/plot.js
  test/jasmine/tests/sankey_test.js
Labels: status: reviewable, type: bug

#3804 Refactor traces index exports
  src/traces/box/index.js
  src/traces/carpet/index.js
  src/traces/choropleth/index.js
  src/traces/contour/index.js
  src/traces/contourcarpet/index.js
  src/traces/contourgl/index.js
  src/traces/heatmap/index.js
  src/traces/heatmapgl/index.js
  src/traces/histogram/index.js
  src/traces/histogram2d/index.js
  src/traces/histogram2dcontour/index.js
  src/traces/isosurface/index.js
  src/traces/mesh3d/index.js
  src/traces/parcats/index.js
  src/traces/parcoords/index.js
  src/traces/pie/index.js
  src/traces/pointcloud/index.js
  src/traces/sankey/index.js
  src/traces/scatter/index.js
  src/traces/scatter3d/index.js
  src/traces/scattercarpet/index.js
  src/traces/scattergeo/index.js
  src/traces/scattermapbox/index.js
  src/traces/scatterternary/index.js
  src/traces/surface/index.js
  src/traces/table/index.js
  src/traces/volume/index.js
  src/traces/waterfall/index.js
Labels: type: maintenance

#3806 Fix bar selection on subplots with rangeslider
  src/traces/bar/plot.js
  src/traces/bar/select.js
  test/jasmine/tests/select_test.js
Labels: status: reviewable, type: bug

#3808 Group plot_api exports
  src/plot_api/plot_api.js
Labels: type: maintenance

#3810 scattergl selection fixes
  package.json
  src/traces/scattergl/index.js
  src/traces/scatterpolargl/index.js
  src/traces/splom/base_plot.js
  src/traces/splom/index.js
  test/jasmine/tests/gl2d_double_click_test.js
  test/jasmine/tests/gl2d_plot_interact_test.js
  test/jasmine/tests/splom_test.js
Labels: status: reviewable, type: bug

#3811 Better did-margin-change check
  src/plot_api/plot_api.js
  src/plots/plots.js
  test/jasmine/tests/plots_test.js
Labels: status: reviewable, type: bug
