Repository plotly/plotly.js, pull requests merged in 2019-11, with the labels that each got.

#4325 Skip non-numeric values in image trace plot
  src/traces/image/attributes.js
  src/traces/image/calc.js
  src/traces/image/constants.js
  src/traces/image/defaults.js
  src/traces/image/index.js
  src/traces/image/plot.js
  src/traces/image/style.js
  test/image/baselines/image_non_numeric.png
  test/image/mocks/image_non_numeric.json
Labels: status: reviewable, type: bug

#4344 remove noOpacity flag from surface index
  src/traces/surface/index.js
  test/image/baselines/gl3d_traces-with-opacity.png
  test/image/mocks/gl3d_traces-with-opacity.json
Labels: type: maintenance

#4347 Improve gl3d coloraxis mock
  test/image/baselines/gl3d_coloraxes.png
  test/image/mocks/gl3d_coloraxes.json
Labels: status: reviewable, type: maintenance

#4346 Do not coerce contour & colorscale attributes for mesh3d when not needed
  src/traces/mesh3d/defaults.js
  test/jasmine/tests/mesh3d_test.js
  test/jasmine/tests/surface_test.js
Labels: status: reviewable, type: bug

#4353 Handle missing vertexcolor and facecolor in mesh3d
  package-lock.json
  package.json
  test/image/baselines/gl3d_mesh3d-missing-colors.png
  test/image/mocks/gl3d_mesh3d-missing-colors.json
Labels: status: reviewable, type: bug

#4357 remove a duplicate function call in parcoords
  src/traces/parcoords/parcoords.js
Labels: status: reviewable, type: maintenance

#4362 Mention legend.bgcolor default in documentation
  src/components/legend/attributes.js
Labels: status: reviewable, type: documentation

#4356 Apply reversed colorscale setting and coloraxis in contour and histogramcontour legends
  src/components/legend/style.js
  src/traces/choropleth/attributes.js
  src/traces/densitymapbox/attributes.js
  src/traces/funnel/attributes.js
  src/traces/funnelarea/attributes.js
  src/traces/image/attributes.js
  src/traces/parcats/attributes.js
  src/traces/pie/attributes.js
  src/traces/sankey/attributes.js
  src/traces/scattercarpet/attributes.js
  src/traces/scattergeo/attributes.js
  src/traces/scattergl/attributes.js
  src/traces/scattermapbox/attributes.js
  src/traces/scatterpolar/attributes.js
  src/traces/scatterternary/attributes.js
  src/traces/sunburst/attributes.js
  src/traces/waterfall/attributes.js
  test/image/baselines/contour_legend-coloraxis.png
  test/image/baselines/contour_legend-colorscale.png
  test/image/baselines/histogram2d_legend-colorscale.png
  test/image/baselines/histogram2dcontour_legend-coloraxis.png
  test/image/mocks/contour_legend-coloraxis.json
  test/image/mocks/contour_legend-colorscale.json
  test/image/mocks/histogram2d_legend-colorscale.json
  test/image/mocks/histogram2dcontour_legend-coloraxis.json
Labels: status: reviewable, type: bug

#4366 Clear relinked cmin/cmax values in shared axes
  src/plots/plots.js
  test/jasmine/tests/colorscale_test.js
Labels: status: reviewable, type: bug

#4322 Use Node v12.13.0 (LTS) for development
  .circleci/config.yml
  CONTRIBUTING.md
  appveyor.yml
  package.json
  src/components/fx/hover.js
  test/jasmine/tests/colorbar_test.js
  test/jasmine/tests/hover_label_test.js
  test/jasmine/tests/splom_test.js
Labels: status: reviewable, type: maintenance

#4380 Text template formatting fixes
  src/components/drawing/index.js
  src/components/legend/style.js
  src/traces/bar/constants.js
  src/traces/bar/event_data.js
  src/traces/bar/hover.js
  src/traces/bar/index.js
  src/traces/bar/plot.js
  src/traces/barpolar/index.js
  src/traces/scatter/format_labels.js
  src/traces/scatter/index.js
  src/traces/scatter3d/convert.js
  src/traces/scattercarpet/format_labels.js
  src/traces/scattercarpet/hover.js
  src/traces/scattercarpet/index.js
  src/traces/scattergeo/format_labels.js
  src/traces/scattergeo/hover.js
  src/traces/scattergeo/index.js
  src/traces/scattergl/calc.js
  src/traces/scattergl/convert.js
  src/traces/scattergl/format_labels.js
  src/traces/scattergl/index.js
  src/traces/scattermapbox/convert.js
  src/traces/scattermapbox/format_labels.js
  src/traces/scattermapbox/hover.js
  src/traces/scattermapbox/index.js
  src/traces/scatterpolar/format_labels.js
  src/traces/scatterpolar/hover.js
  src/traces/scatterpolar/index.js
  src/traces/scatterpolargl/calc.js
  src/traces/scatterpolargl/format_labels.js
  src/traces/scatterpolargl/index.js
  src/traces/scatterternary/format_labels.js
  src/traces/scatterternary/hover.js
  src/traces/scatterternary/index.js
  test/image/baselines/gl3d_scatter3d-texttemplate.png
  test/jasmine/assets/check_texttemplate.js
  test/jasmine/tests/bar_test.js
  test/jasmine/tests/carpet_test.js
  test/jasmine/tests/scatter_test.js
  test/jasmine/tests/scattergeo_test.js
  test/jasmine/tests/scattergl_test.js
  test/jasmine/tests/scattermapbox_test.js
  test/jasmine/tests/scatterpolar_test.js
  test/jasmine/tests/scatterpolargl_test.js
  test/jasmine/tests/scatterternary_test.js
Labels: status: reviewable, type: bug

#4384 Fix hover for densitymapbox
  src/traces/densitymapbox/index.js
Labels: status: reviewable, type: bug

#4388 Fix notched box autorange
  src/traces/box/attributes.js
  src/traces/box/calc.js
  test/image/baselines/box_notched-inverted-end.png
  test/image/mocks/box_notched-inverted-end.json
Labels: status: reviewable, type: bug
