Repository plotly/plotly.js, pull requests merged in 2019-08, with the labels that each got.

#4096 Gl3d hover bug fix - pick most recent point if two share identical position
  package-lock.json
  package.json
  test/image/baselines/gl3d_transparent_same-depth.png
  test/image/mocks/gl3d_transparent_same-depth.json
  test/jasmine/tests/gl3d_hover_click_test.js
Labels: status: reviewable, type: bug

#4099 Use Axes.prepTicks not Axes.calcTicks for indicator number and delta
  src/traces/indicator/plot.js
Labels: status: reviewable, type: maintenance

#4100 using Attrs as the short form of Attributes everywhere
  src/components/annotations3d/attributes.js
  src/components/colorscale/cross_trace_defaults.js
  src/traces/mesh3d/attributes.js
  src/traces/sunburst/attributes.js
Labels: status: reviewable, type: maintenance

#4101 Making sunburst plot functions reusable for other hierarchical traces
  src/traces/sunburst/helpers.js
  src/traces/sunburst/plot.js
Labels: status: reviewable, type: maintenance

#4103 Removing duplicate domain definition from an indicator mock
  test/image/mocks/indicator_datacard3.json
Labels: status: reviewable, type: maintenance

#4115 indicator: rename steps' items to `step`
  src/traces/indicator/attributes.js
Labels: status: reviewable, type: bug, type: documentation

#4122 Add correct number formater
  lib/locales/it.js
Labels: type: translation

#4123 fix for invisible Sankey traces
  src/traces/sankey/plot.js
  test/image/mocks/sankey_subplots.json
Labels: status: reviewable, type: bug

#4125 scattergl: fill text arrays up to trace._length if necessary
  src/traces/scattergl/convert.js
  test/jasmine/tests/scattergl_test.js
Labels: status: reviewable, type: bug

#4126 scattergl: do not mutate text array
  src/traces/scattergl/convert.js
  test/jasmine/tests/scattergl_test.js
Labels: status: reviewable, type: bug

#4127 Use gs.l not margin.l to position rangeslider
  src/components/rangeslider/draw.js
  test/image/baselines/range_slider_legend_left.png
  test/image/mocks/range_slider_legend_left.json
Labels: status: reviewable, type: bug

#4140 Don't draw ticks on tick subplots when mirror:'all'
  src/plots/cartesian/axes.js
  test/image/baselines/mirror-all-vs-allticks.png
  test/image/mocks/mirror-all-vs-allticks.json
Labels: status: reviewable, type: bug

#4144 Fix access token validation logic for custom mapbox style URLs
  src/plots/mapbox/index.js
  test/jasmine/tests/mapbox_test.js
Labels: status: reviewable, type: regression

#4102 Constraint contours with rounded-off edgepath bug fix
  src/traces/carpet/attributes.js
  src/traces/carpet/index.js
  src/traces/contour/close_boundaries.js
  src/traces/contour/convert_to_constraints.js
  src/traces/contour/find_all_paths.js
  src/traces/contour/plot.js
  src/traces/contourcarpet/index.js
  src/traces/contourcarpet/join_all_paths.js
  src/traces/contourcarpet/map_pathinfo.js
  src/traces/contourcarpet/plot.js
  src/traces/scattercarpet/attributes.js
  test/image/baselines/carpet_rounded-off-edgepath-gt.png
  test/image/baselines/carpet_rounded-off-edgepath-lt.png
  test/image/baselines/carpet_rounded-off-edgepath.png
  test/image/baselines/contour_constraints_edge_cases.png
  test/image/baselines/contour_constraints_equal_boundary_minmax.png
  test/image/mocks/carpet_rounded-off-edgepath-gt.json
  test/image/mocks/carpet_rounded-off-edgepath-lt.json
  test/image/mocks/carpet_rounded-off-edgepath.json
  test/image/mocks/contour_constraints_edge_cases.json
  test/image/mocks/contour_constraints_equal_boundary_minmax.json
Labels: status: reviewable, type: bug

#4105 Process data uri images synchronously
  src/components/images/draw.js
  test/jasmine/tests/layout_images_test.js
Labels: status: reviewable, type: bug, type: performance
