Repository plotly/plotly.js, pull requests merged in 2019-12, with the labels that each got.

#4386 Add title feature to legend and support legend option for various traces
  src/components/legend/attributes.js
  src/components/legend/constants.js
  src/components/legend/defaults.js
  src/components/legend/draw.js
  src/components/legend/style.js
  src/plots/plots.js
  src/traces/choropleth/attributes.js
  src/traces/choropleth/index.js
  src/traces/choroplethmapbox/attributes.js
  src/traces/choroplethmapbox/index.js
  src/traces/cone/attributes.js
  src/traces/cone/index.js
  src/traces/densitymapbox/attributes.js
  src/traces/densitymapbox/index.js
  src/traces/heatmap/attributes.js
  src/traces/heatmap/index.js
  src/traces/histogram2d/attributes.js
  src/traces/histogram2d/index.js
  src/traces/isosurface/attributes.js
  src/traces/isosurface/index.js
  src/traces/mesh3d/attributes.js
  src/traces/mesh3d/index.js
  src/traces/streamtube/attributes.js
  src/traces/streamtube/index.js
  src/traces/surface/attributes.js
  src/traces/surface/index.js
  src/traces/volume/attributes.js
  src/traces/volume/index.js
  test/image/baselines/geo_choropleth-legend.png
  test/image/baselines/geo_choropleth-usa_legend.png
  test/image/baselines/gl3d_traces-with-legend.png
  test/image/baselines/heatmap_legend.png
  test/image/baselines/histogram2d_legend.png
  test/image/baselines/legend_mathjax_title_and_items.png
  test/image/baselines/legend_scroll_with_title.png
  test/image/baselines/mapbox_choropleth0-legend.png
  test/image/baselines/mapbox_density-mulitple_legend.png
  test/image/baselines/mapbox_density0-legend.png
  test/image/mocks/geo_choropleth-legend.json
  test/image/mocks/geo_choropleth-usa_legend.json
  test/image/mocks/gl3d_traces-with-legend.json
  test/image/mocks/heatmap_legend.json
  test/image/mocks/histogram2d_legend.json
  test/image/mocks/legend_mathjax_title_and_items.json
  test/image/mocks/legend_scroll_with_title.json
  test/image/mocks/mapbox_choropleth0-legend.json
  test/image/mocks/mapbox_density-mulitple_legend.json
  test/image/mocks/mapbox_density0-legend.json
  test/jasmine/bundle_tests/plotschema_test.js
  test/jasmine/tests/legend_test.js
Labels: status: reviewable, type: feature

#4315 translation to korean
  lib/locales/ko.js
Labels: type: translation

#4404 sankey: fix position of link hover labels in vertical orientation
  src/traces/sankey/plot.js
  test/jasmine/tests/sankey_test.js
Labels: status: reviewable, type: bug

#4406 Fix *toggleothers* behavior for graphs with traces not in legend
  src/components/legend/handle_click.js
  test/jasmine/tests/legend_test.js
Labels: status: reviewable, type: bug

#4412 Handle multiple positional args in make_baseline.js script
  test/image/make_baseline.js
Labels: status: reviewable, type: maintenance

#4392 Plots.resize: promises should always be resolved
  src/plots/plots.js
  test/jasmine/tests/plots_test.js
Labels: status: reviewable, type: bug

#4410 adding support for defining groups in data.transforms.groups using ty…
  src/transforms/groupby.js
  test/jasmine/tests/transform_groupby_test.js
Labels: status: reviewable, type: feature

#4413 Add coordinates of mapbox view as a derived property in plotly_relayo…
  src/plots/mapbox/mapbox.js
  test/jasmine/tests/mapbox_test.js
Labels: status: reviewable, type: feature

#4398 Add modebar buttons zoomInMapbox and zoomOutMapbox
  src/components/modebar/buttons.js
  src/components/modebar/manage.js
  test/jasmine/tests/modebar_test.js
Labels: status: reviewable, type: feature

#4418 Mapbox react updates
  src/plots/mapbox/layers.js
  src/plots/mapbox/mapbox.js
  test/jasmine/tests/mapbox_test.js
Labels: status: reviewable, type: performance

#4419 Geo improvements: fitbounds, 'geojson-id' locationmode and 'featureidkey'
  package-lock.json
  package.json
  src/components/modebar/buttons.js
  src/lib/geo_location_utils.js
  src/plot_api/plot_api.js
  src/plots/geo/geo.js
  src/plots/geo/layout_attributes.js
  src/plots/geo/layout_defaults.js
  src/plots/geo/zoom.js
  src/plots/mapbox/mapbox.js
  src/traces/choropleth/attributes.js
  src/traces/choropleth/defaults.js
  src/traces/choropleth/event_data.js
  src/traces/choropleth/index.js
  src/traces/choropleth/plot.js
  src/traces/choroplethmapbox/attributes.js
  src/traces/choroplethmapbox/convert.js
  src/traces/choroplethmapbox/defaults.js
  src/traces/scattergeo/attributes.js
  src/traces/scattergeo/calc.js
  src/traces/scattergeo/defaults.js
  src/traces/scattergeo/event_data.js
  src/traces/scattergeo/index.js
  src/traces/scattergeo/plot.js
  test/image/baselines/geo_custom-geojson.png
  test/image/baselines/geo_featureidkey.png
  test/image/baselines/geo_fitbounds-geojson.png
  test/image/baselines/geo_fitbounds-locations.png
  test/image/baselines/geo_fitbounds-scopes.png
  test/image/baselines/mapbox_choropleth-raw-geojson.png
  test/image/compare_pixels_test.js
  test/image/mocks/geo_custom-geojson.json
  test/image/mocks/geo_featureidkey.json
  test/image/mocks/geo_fitbounds-geojson.json
  test/image/mocks/geo_fitbounds-locations.json
  test/image/mocks/geo_fitbounds-scopes.json
  test/image/mocks/mapbox_choropleth-raw-geojson.json
  test/jasmine/tests/choropleth_test.js
  test/jasmine/tests/choroplethmapbox_test.js
  test/jasmine/tests/geo_test.js
  test/jasmine/tests/plot_api_react_test.js
  test/jasmine/tests/scattergeo_test.js
Labels: status: reviewable, type: feature

#4437 Fix colorbar of reversescale colorbars of heatmap-coloring contours
  src/traces/contour/colorbar.js
  test/image/baselines/contour_heatmap_coloring_reversescale.png
  test/image/mocks/contour_heatmap_coloring_reversescale.json
Labels: status: reviewable, type: bug

#4439 Fix histogram bingroup algo when calendars module is not registered
  src/traces/histogram/cross_trace_defaults.js
  test/jasmine/tests/histogram_test.js
Labels: status: reviewable, type: bug

#4441 Fix image exports for new #4386 mocks with SVG gradients
  src/components/drawing/index.js
  src/snapshot/tosvg.js
  test/jasmine/tests/snapshot_test.js
Labels: status: reviewable, type: bug, type: maintenance

#4442 Add ALMOST_EQUAL tolerance in branchvalue:total partial sum check
  src/traces/sunburst/calc.js
  test/image/baselines/sunburst_branchvalues-total-almost-equal.png
  test/image/mocks/sunburst_branchvalues-total-almost-equal.json
Labels: status: reviewable, type: bug

#4447 Replace mapbox access token with token from plotly-js-tests account
  tasks/noci_test.sh
  tasks/util/constants.js
  test/image/baselines/mapbox_custom-style.png
  test/image/mocks/mapbox_custom-style.json
  test/jasmine/tests/mapbox_test.js
Labels: status: reviewable, type: maintenance

#4431 Handle streamtube coordinates in string format and handle different data orders in isosurface and volume
  src/traces/isosurface/calc.js
  src/traces/isosurface/convert.js
  src/traces/streamtube/calc.js
  src/traces/streamtube/convert.js
  src/traces/streamtube/index.js
  src/traces/volume/convert.js
  test/image/baselines/gl3d_directions-isosurface1.png
  test/image/baselines/gl3d_directions-isosurface2.png
  test/image/baselines/gl3d_directions-volume1.png
  test/image/mocks/gl3d_directions-isosurface1.json
  test/image/mocks/gl3d_directions-isosurface2.json
  test/image/mocks/gl3d_directions-volume1.json
  test/jasmine/tests/isosurface_test.js
  test/jasmine/tests/streamtube_test.js
  test/jasmine/tests/volume_test.js
Labels: status: reviewable, type: bug, type: regression

#4446 Add intensitymode to allow cell intensity values in mesh3d
  package-lock.json
  package.json
  src/traces/mesh3d/attributes.js
  src/traces/mesh3d/convert.js
  src/traces/mesh3d/defaults.js
  test/image/baselines/gl3d_mesh3d_cell-intensity.png
  test/image/mocks/gl3d_mesh3d_cell-intensity.json
  test/jasmine/tests/mesh3d_test.js
Labels: status: reviewable, type: feature
