Repository plotly/plotly.js, pull requests merged in 2019-03, with the labels that each got.

#3591 Fixing cone plots lighting & rendering on some hardware including CircleCI image test
  package-lock.json
  package.json
  test/image/baselines/gl3d_cone-absolute.png
  test/image/baselines/gl3d_cone-autorange.png
  test/image/baselines/gl3d_cone-lighting.png
  test/image/baselines/gl3d_cone-newplot_reversed_ranges.png
  test/image/baselines/gl3d_cone-rossler.png
  test/image/baselines/gl3d_cone-simple.png
  test/image/baselines/gl3d_cone-single.png
  test/image/baselines/gl3d_cone-wind.png
  test/image/baselines/gl3d_cone-with-streamtube.png
  test/image/compare_pixels_test.js
Labels: status: reviewable, type: bug, type: maintenance

#3593 Streamtube lighting fix and image-test
  package-lock.json
  package.json
  test/image/baselines/gl3d_cone-with-streamtube.png
  test/image/baselines/gl3d_reversescale.png
  test/image/baselines/gl3d_streamtube-first.png
  test/image/baselines/gl3d_streamtube-simple.png
  test/image/baselines/gl3d_streamtube-thin.png
  test/image/baselines/gl3d_streamtube-wind.png
  test/image/baselines/gl3d_streamtube_reversed_ranges.png
Labels: status: reviewable, type: bug, type: maintenance

#3598 Fix parcoords dimensions values & line coloring error with integer TypedArray
  src/traces/parcoords/calc.js
  test/jasmine/tests/parcoords_test.js
Labels: status: reviewable, type: bug

#3605 Automargin edge cases
  src/plots/cartesian/axes.js
  src/plots/cartesian/set_convert.js
  src/plots/plots.js
  test/image/baselines/automargin-push-x-extra.png
  test/image/baselines/automargin-push-y-extra.png
  test/image/mocks/automargin-push-x-extra.json
  test/image/mocks/automargin-push-y-extra.json
  test/jasmine/tests/axes_test.js
Labels: status: reviewable, type: bug

#3597 fix reset camera buttons to work after switching projection between perspective and orthographic
  src/components/modebar/buttons.js
  src/plot_api/plot_api.js
  src/plots/gl3d/index.js
  src/plots/gl3d/scene.js
  test/jasmine/tests/gl3d_plot_interact_test.js
Labels: status: reviewable, type: bug

#3599 Adding third container for jasmine tests to avoid flaky fails
  .circleci/config.yml
  .circleci/test.sh
  test/jasmine/tests/select_test.js
Labels: type: maintenance

#3611 Updates d3-sankey-circular to 0.33.0
  package-lock.json
  package.json
Labels: status: reviewable, type: bug

#3612 CircleCI: improve caching for faster startup time
  .circleci/config.yml
Labels: type: maintenance

#3623 update description of `hovertemplate`
  src/components/fx/hovertemplate_attributes.js
Labels: status: reviewable, type: documentation

#3641 Bump gl-surface3d 1.4.3
  package-lock.json
  package.json
Labels: type: maintenance

#3635 legend: enable selection of a trace by clicking its symbol
  src/components/legend/draw.js
  test/jasmine/tests/legend_test.js
Labels: status: reviewable, type: bug, type: regression

#3645 Fix avoid-overlap hover label algo when "too close" label get filtered out
  src/components/fx/hover.js
  test/jasmine/tests/hover_label_test.js
Labels: status: reviewable, type: bug

#3646 Fix hovermode default logic for stacked scatter traces
  src/components/fx/layout_defaults.js
  test/jasmine/tests/fx_test.js
Labels: status: reviewable, type: bug

#3647 gl2d fixes
  src/plot_api/plot_api.js
  src/plots/gl2d/convert.js
  test/jasmine/tests/gl2d_pointcloud_test.js
Labels: status: reviewable, type: bug

#3652 histogram: remove gap when `barmode` is relative
  src/traces/bar/layout_defaults.js
  test/image/baselines/histogram_barmode_relative.png
  test/image/mocks/histogram_barmode_relative.json
  test/jasmine/tests/bar_test.js
Labels: status: reviewable, type: bug

#3626 `violin`: honor `bandwidth` attribute even if values in a trace are identical
  src/traces/violin/calc.js
  test/image/baselines/groups-over-matching-axes.png
  test/image/baselines/violin-offsetgroups.png
  test/image/baselines/violin_only_zeroes.png
  test/image/mocks/violin_only_zeroes.json
  test/jasmine/tests/violin_test.js
Labels: status: reviewable, type: bug

#3589 Display hoverlabels above modebar
  build/plotcss.js
  src/css/_modebar.scss
  src/plot_api/plot_api.js
  test/jasmine/tests/plots_test.js
Labels: status: reviewable, type: bug

#3601 Gl3d orthographic zoom using mouse scroll wheel
  package-lock.json
  package.json
Labels: type: bug, type: feature

#3656 No need to test `cone` traces during pre-release checklist
  tasks/noci_test.sh
Labels: status: reviewable, type: maintenance

#3585 Improve camera init
  package-lock.json
  package.json
  src/plots/gl3d/scene.js
  test/jasmine/tests/gl3d_plot_interact_test.js
  test/jasmine/tests/isosurface_test.js
  test/jasmine/tests/streamtube_test.js
Labels: status: reviewable, type: bug, type: performance

#3628 Fix #1913 by pushing overflowed legend items to a new line
  src/components/legend/draw.js
  test/image/baselines/legend_horizontal_groups.png
  test/image/baselines/legendgroup_horizontal_wrapping.png
  test/image/mocks/legendgroup_horizontal_wrapping.json
  test/jasmine/tests/legend_test.js
Labels: status: reviewable, type: bug

#3638 Implementation of connectgaps for the surface trace
  src/traces/surface/attributes.js
  src/traces/surface/convert.js
  src/traces/surface/defaults.js
  test/image/baselines/gl3d_surface_connectgaps.png
  test/image/mocks/gl3d_surface_connectgaps.json
  test/jasmine/tests/gl3d_plot_interact_test.js
Labels: status: reviewable, type: feature

#3583 Sankey: add attributes `node.(x|y)`
  src/plot_api/plot_api.js
  src/traces/sankey/attributes.js
  src/traces/sankey/defaults.js
  src/traces/sankey/render.js
  test/image/baselines/sankey_x_y.png
  test/image/mocks/sankey_x_y.json
  test/jasmine/assets/check_overlap.js
  test/jasmine/assets/drag.js
  test/jasmine/tests/sankey_test.js
Labels: status: reviewable, type: feature, type: regression

#3661 Clean CI run of gl hovers
  test/jasmine/tests/cone_test.js
  test/jasmine/tests/gl2d_click_test.js
  test/jasmine/tests/gl2d_pointcloud_test.js
  test/jasmine/tests/gl3d_plot_interact_test.js
  test/jasmine/tests/isosurface_test.js
  test/jasmine/tests/streamtube_test.js
Labels: status: reviewable, type: maintenance

#3665 Bump dev deps 2019-03-22
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#3666 Bug fix marker positions on date axes for iOS users
  package-lock.json
  package.json
Labels: status: reviewable, type: bug

#3672 Bug fix surface plot issue with large floats using iOS
  package-lock.json
  package.json
Labels: status: reviewable, type: bug

#3674 Bug fix scatter3d issue with large floats using iOS
  package-lock.json
  package.json
Labels: status: reviewable, type: bug

#3670 Bug fix - missing contour lines in some directions using FireFox
  package-lock.json
  package.json
Labels: status: reviewable, type: bug

#3676 More iOS gl3d bug fixes for graphs with large float numbers and dates
  package-lock.json
  package.json
Labels: status: reviewable, type: bug

#3678 ensure we create only one `modebar-container`
  src/plot_api/plot_api.js
  test/jasmine/tests/hover_label_test.js
  test/jasmine/tests/plot_api_test.js
Labels: status: reviewable, type: bug

#3681 Fit center-aligned hover labels within graph's horizontal span
  src/components/fx/hover.js
  test/jasmine/tests/pie_test.js
Labels: status: reviewable, type: bug

#3634 CircleCI: run jobs in parallel
  .circleci/config.yml
  .circleci/test.sh
  package.json
  test/image/compare_pixels_test.js
  test/jasmine/karma.conf.js
  test/jasmine/tests/sankey_test.js
Labels: status: reviewable, type: maintenance, type: performance

#3685 Hovertemplate for box/violin points
  src/components/fx/hover.js
  src/traces/box/attributes.js
  src/traces/box/defaults.js
  src/traces/box/hover.js
  src/traces/scatter/hover.js
  src/traces/violin/attributes.js
  src/traces/violin/hover.js
  test/jasmine/tests/box_test.js
  test/jasmine/tests/hover_label_test.js
  test/jasmine/tests/violin_test.js
Labels: status: reviewable, type: bug, type: feature

#3687 update description for `violin.scalegroup`
  src/traces/violin/attributes.js
Labels: status: reviewable, type: documentation

#3594 Sunburst traces
  lib/index.js
  lib/sunburst.js
  package-lock.json
  package.json
  src/components/fx/helpers.js
  src/lib/angles.js
  src/plot_api/plot_api.js
  src/plots/plots.js
  src/traces/pie/calc.js
  src/traces/pie/index.js
  src/traces/pie/plot.js
  src/traces/sunburst/attributes.js
  src/traces/sunburst/base_plot.js
  src/traces/sunburst/calc.js
  src/traces/sunburst/constants.js
  src/traces/sunburst/defaults.js
  src/traces/sunburst/index.js
  src/traces/sunburst/layout_attributes.js
  src/traces/sunburst/layout_defaults.js
  src/traces/sunburst/plot.js
  src/traces/sunburst/style.js
  tasks/test_syntax.js
  test/image/baselines/sunburst_coffee-maxdepth3.png
  test/image/baselines/sunburst_coffee.png
  test/image/baselines/sunburst_first.png
  test/image/baselines/sunburst_flare.png
  test/image/baselines/sunburst_level-depth.png
  test/image/baselines/sunburst_values.png
  test/image/mocks/sunburst_coffee-maxdepth3.json
  test/image/mocks/sunburst_coffee.json
  test/image/mocks/sunburst_first.json
  test/image/mocks/sunburst_flare.json
  test/image/mocks/sunburst_level-depth.json
  test/image/mocks/sunburst_values.json
  test/jasmine/assets/mock_lists.js
  test/jasmine/tests/plot_api_react_test.js
  test/jasmine/tests/sunburst_test.js
Labels: status: reviewable, type: new trace type

#3662 Fixup pie/sunburst unhover post plot/calc restyle calls
  src/traces/pie/base_plot.js
  src/traces/pie/plot.js
  src/traces/sunburst/plot.js
  test/jasmine/tests/pie_test.js
  test/jasmine/tests/sunburst_test.js
Labels: status: reviewable, type: bug

#3691 Fix bound arrays with "0" x/y categories
  src/traces/heatmap/calc.js
  src/traces/heatmap/make_bound_array.js
  test/image/baselines/heatmap-with-zero-category.png
  test/image/mocks/heatmap-with-zero-category.json
  test/jasmine/tests/heatmap_test.js
Labels: status: reviewable, type: bug

#3531 Waterfall charts
  lib/index.js
  lib/waterfall.js
  src/components/drawing/index.js
  src/components/legend/style.js
  src/plot_api/helpers.js
  src/plots/cartesian/axes.js
  src/plots/cartesian/constants.js
  src/plots/cartesian/index.js
  src/traces/bar/arrays_to_calcdata.js
  src/traces/bar/cross_trace_calc.js
  src/traces/bar/defaults.js
  src/traces/bar/hover.js
  src/traces/bar/plot.js
  src/traces/bar/style.js
  src/traces/waterfall/attributes.js
  src/traces/waterfall/calc.js
  src/traces/waterfall/cross_trace_calc.js
  src/traces/waterfall/defaults.js
  src/traces/waterfall/hover.js
  src/traces/waterfall/index.js
  src/traces/waterfall/layout_attributes.js
  src/traces/waterfall/layout_defaults.js
  src/traces/waterfall/plot.js
  src/traces/waterfall/style.js
  test/image/baselines/waterfall-grouping-vs-defaults.png
  test/image/baselines/waterfall-offsetgroups.png
  test/image/baselines/waterfall_11.png
  test/image/baselines/waterfall_and_bar.png
  test/image/baselines/waterfall_and_histogram.png
  test/image/baselines/waterfall_attrs.png
  test/image/baselines/waterfall_cliponaxis-false.png
  test/image/baselines/waterfall_custom.png
  test/image/baselines/waterfall_gap0.png
  test/image/baselines/waterfall_line.png
  test/image/baselines/waterfall_months.png
  test/image/baselines/waterfall_multicategory.png
  test/image/baselines/waterfall_nonnumeric_sizes.png
  test/image/baselines/waterfall_profit-loss_2018_positive-negative.png
  test/image/baselines/waterfall_profit-loss_2018vs2019_overlay.png
  test/image/baselines/waterfall_profit-loss_2018vs2019_rectangle.png
  test/image/mocks/waterfall-grouping-vs-defaults.json
  test/image/mocks/waterfall-offsetgroups.json
  test/image/mocks/waterfall_11.json
  test/image/mocks/waterfall_and_bar.json
  test/image/mocks/waterfall_and_histogram.json
  test/image/mocks/waterfall_attrs.json
  test/image/mocks/waterfall_cliponaxis-false.json
  test/image/mocks/waterfall_custom.json
  test/image/mocks/waterfall_gap0.json
  test/image/mocks/waterfall_line.json
  test/image/mocks/waterfall_months.json
  test/image/mocks/waterfall_multicategory.json
  test/image/mocks/waterfall_nonnumeric_sizes.json
  test/image/mocks/waterfall_profit-loss_2018_positive-negative.json
  test/image/mocks/waterfall_profit-loss_2018vs2019_overlay.json
  test/image/mocks/waterfall_profit-loss_2018vs2019_rectangle.json
  test/jasmine/assets/mock_lists.js
  test/jasmine/tests/select_test.js
  test/jasmine/tests/shapes_test.js
  test/jasmine/tests/waterfall_test.js
Labels: status: reviewable, type: new trace type

#3680 Unhide overlapping grouped bars within trace
  src/traces/bar/cross_trace_calc.js
  src/traces/bar/sieve.js
  test/image/baselines/bar_unhidden.png
  test/image/mocks/bar_unhidden.json
  test/jasmine/tests/bar_test.js
Labels: status: reviewable, type: bug

#3692 Fix stacked scatter for groupby traces
  src/traces/scatter/calc.js
  test/image/baselines/stacked_area_groupby.png
  test/image/mocks/stacked_area_groupby.json
Labels: status: reviewable, type: bug
