Repository plotly/plotly.js, pull requests merged in 2019-07, with the labels that each got.

#3904 Scatter3d and scattergl handling rgb colors with extra alpha values
  package-lock.json
  package.json
  test/image/baselines/gl2d_rgb_dont_accept_alpha_scattergl.png
  test/image/baselines/gl3d_rgb_dont_accept_alpha_scatter3d.png
  test/image/mocks/gl2d_rgb_dont_accept_alpha_scattergl.json
  test/image/mocks/gl3d_mesh3d_enable-alpha-with-rgba-color.json
  test/image/mocks/gl3d_rgb_dont_accept_alpha_scatter3d.json
  test/image/mocks/gl3d_scatter3d_line3d_error3d_enable-alpha-with-rgba-color.json
  test/image/mocks/gl3d_scatter3d_line3d_error3d_transparent-with-zero-alpha.json
Labels: status: reviewable, type: bug

#4006 Add support for raster and image mapbox layers
  src/plots/mapbox/layers.js
  src/plots/mapbox/layout_attributes.js
  src/plots/mapbox/layout_defaults.js
  test/image/baselines/mapbox_layers.png
  test/image/mocks/mapbox_layers.json
  test/jasmine/tests/mapbox_test.js
Labels: status: reviewable, type: feature

#4007 indicator: position delta using drawing.bBox
  src/snapshot/tosvg.js
  src/traces/indicator/constants.js
  src/traces/indicator/plot.js
  test/image/baselines/gl3d_indicator_scatter3d.png
  test/image/baselines/indicator_bignumber.png
  test/image/baselines/indicator_bullet.png
  test/image/baselines/indicator_datacard.png
  test/image/baselines/indicator_datacard2.png
  test/image/baselines/indicator_datacard3.png
  test/image/baselines/indicator_gauge.png
  test/image/baselines/indicator_grid_template.png
  test/image/baselines/indicator_scatter.png
  test/image/mocks/indicator_datacard.json
  test/image/mocks/indicator_datacard3.json
  test/jasmine/tests/indicator_test.js
  test/jasmine/tests/snapshot_test.js
Labels: status: reviewable, type: bug

#4009 gl-text patch to use to-px at 1.0.1
  package-lock.json
  package.json
Labels: status: reviewable, type: bug

#4008 Use URL.createObjectURL during Plotly.downloadImage
  src/lib/index.js
  src/plot_api/to_image.js
  src/snapshot/download.js
  src/snapshot/filesaver.js
  src/snapshot/helpers.js
  src/snapshot/svgtoimg.js
  test/jasmine/tests/download_test.js
Labels: status: reviewable, type: bug, type: performance

#4011 parcoords - bug fix handling undefined ranges and dticks for tickText
  src/traces/parcoords/parcoords.js
  test/image/baselines/gl2d_parcoords.png
  test/image/baselines/gl2d_parcoords_large.png
Labels: status: reviewable, type: bug

#4012 Better spec reporting on CI
  test/jasmine/assets/modebar_button.js
  test/jasmine/assets/mouse_event.js
  test/jasmine/assets/touch_event.js
  test/jasmine/karma.conf.js
  test/jasmine/tests/annotations_test.js
Labels: status: reviewable, type: maintenance

#4013 parcoords - reusing Lib.aggNums in finding extreme ranges
  src/traces/parcoords/parcoords.js
Labels: status: reviewable

#4014 Fixup noci test - post indicator merge
  src/traces/indicator/defaults.js
  test/jasmine/assets/mock_lists.js
Labels: status: reviewable, type: maintenance

#4022 Rangeslider style on select fix
  src/lib/make_trace_groups.js
  src/plots/cartesian/index.js
  src/plots/cartesian/select.js
  src/traces/bar/plot.js
  src/traces/bar/style.js
  src/traces/barpolar/index.js
  src/traces/barpolar/plot.js
  src/traces/box/plot.js
  src/traces/box/style.js
  src/traces/choropleth/plot.js
  src/traces/choroplethmapbox/index.js
  src/traces/funnel/style.js
  src/traces/ohlc/plot.js
  src/traces/ohlc/style.js
  src/traces/scatter/plot.js
  src/traces/scatter/style.js
  src/traces/scattergeo/plot.js
  src/traces/scattermapbox/index.js
  src/traces/scatterpolar/index.js
  src/traces/violin/plot.js
  src/traces/violin/style.js
  src/traces/waterfall/style.js
  test/jasmine/tests/scatter_test.js
  test/jasmine/tests/select_test.js
Labels: status: reviewable, type: bug

#4023 Command observer (bad) mutation fix
  src/plot_api/plot_api.js
  src/plots/command.js
  src/plots/plots.js
  test/jasmine/tests/command_test.js
Labels: status: reviewable, type: bug

#4024 Schema animatable + anim fixes
  src/plot_api/plot_api.js
  src/plot_api/plot_schema.js
  test/jasmine/bundle_tests/plotschema_test.js
  test/jasmine/tests/transition_test.js
Labels: status: reviewable, type: bug

#4030 edit error type description
  src/components/errorbars/attributes.js
Labels: status: reviewable, type: documentation

#4037 simplify opts passed in indicator plot
  src/traces/indicator/plot.js
Labels: status: reviewable, type: maintenance

#4038 Fix clean2dArray for categorial x/y with extra items
  src/traces/heatmap/clean_2d_array.js
  test/jasmine/tests/heatmap_test.js
Labels: status: reviewable, type: bug

#4044 Fix tickformat attribute description links
  src/components/fx/hovertemplate_attributes.js
  src/constants/docs.js
  src/plots/cartesian/layout_attributes.js
  src/traces/carpet/axis_attributes.js
  src/traces/contour/attributes.js
  src/traces/heatmap/attributes.js
  src/traces/indicator/attributes.js
  src/traces/sankey/attributes.js
  src/traces/table/attributes.js
Labels: status: reviewable, type: documentation

#4048 Fix lakes and rivers geometry on scoped geo subplots
  dist/topojson/africa_110m.json
  dist/topojson/africa_50m.json
  dist/topojson/asia_110m.json
  dist/topojson/asia_50m.json
  dist/topojson/europe_110m.json
  dist/topojson/europe_50m.json
  dist/topojson/north-america_110m.json
  dist/topojson/north-america_50m.json
  dist/topojson/south-america_110m.json
  dist/topojson/south-america_50m.json
  package-lock.json
  package.json
  test/image/baselines/geo_lakes-and-rivers.png
  test/image/mocks/geo_lakes-and-rivers.json
Labels: status: reviewable, type: bug

#4060 Fix typo in colorscale attr description
  src/components/colorscale/attributes.js
Labels: status: reviewable, type: documentation

#4056 Bug fix - do not display empty bars when line.width is zero
  src/lib/index.js
  src/traces/bar/arrays_to_calcdata.js
  src/traces/bar/helpers.js
  src/traces/bar/hover.js
  src/traces/bar/plot.js
  test/image/baselines/bar_display_height_zero_no_line_width.png
  test/image/baselines/bar_display_height_zero_only_line_width.png
  test/image/mocks/bar_display_height_zero_no_line_width.json
  test/image/mocks/bar_display_height_zero_only_line_width.json
Labels: status: reviewable, type: bug

#4062 Remove pull_font_svg step
  .gitignore
  .npmignore
  package-lock.json
  package.json
  src/components/modebar/buttons.js
  src/components/modebar/modebar.js
  src/core.js
  src/fonts/ploticon.js
  src/fonts/ploticon/_ploticon.scss
  src/fonts/ploticon/config.json
  src/fonts/ploticon/ploticon.eot
  src/fonts/ploticon/ploticon.svg
  src/fonts/ploticon/ploticon.ttf
  src/fonts/ploticon/ploticon.woff
  tasks/bundle.js
  tasks/preprocess.js
  tasks/util/constants.js
  tasks/util/pull_font_svg.js
Labels: status: reviewable, type: maintenance

#4058 Better mapbox trace / layout-layer *below*
  src/plots/mapbox/constants.js
  src/plots/mapbox/layers.js
  src/plots/mapbox/layout_attributes.js
  src/plots/mapbox/mapbox.js
  src/traces/choroplethmapbox/convert.js
  src/traces/choroplethmapbox/index.js
  src/traces/choroplethmapbox/plot.js
  src/traces/densitymapbox/convert.js
  src/traces/densitymapbox/index.js
  src/traces/densitymapbox/plot.js
  src/traces/scattermapbox/attributes.js
  src/traces/scattermapbox/defaults.js
  src/traces/scattermapbox/plot.js
  test/jasmine/tests/choroplethmapbox_test.js
  test/jasmine/tests/densitymapbox_test.js
  test/jasmine/tests/mapbox_test.js
Labels: status: reviewable, type: feature

#4029 `indicator`: several improvements/fixes
  src/traces/indicator/attributes.js
  src/traces/indicator/calc.js
  src/traces/indicator/defaults.js
  src/traces/indicator/plot.js
  test/image/baselines/gl3d_indicator_scatter3d.png
  test/image/baselines/indicator_attrs.png
  test/image/baselines/indicator_bignumber.png
  test/image/baselines/indicator_bullet.png
  test/image/baselines/indicator_datacard.png
  test/image/baselines/indicator_datacard2.png
  test/image/baselines/indicator_datacard3.png
  test/image/baselines/indicator_format_extremes.png
  test/image/baselines/indicator_gauge.png
  test/image/baselines/indicator_grid_template.png
  test/image/baselines/indicator_scatter.png
  test/image/mocks/indicator_attrs.json
  test/image/mocks/indicator_format_extremes.json
  test/image/mocks/indicator_grid_template.json
  test/jasmine/tests/indicator_test.js
Labels: status: reviewable, type: bug

#4061 Add showEditInChartStudio config option
  .gitignore
  .npmignore
  package-lock.json
  package.json
  src/components/modebar/buttons.js
  src/components/modebar/manage.js
  src/components/modebar/modebar.js
  src/core.js
  src/fonts/ploticon.js
  src/fonts/ploticon/_ploticon.scss
  src/fonts/ploticon/config.json
  src/fonts/ploticon/ploticon.eot
  src/fonts/ploticon/ploticon.svg
  src/fonts/ploticon/ploticon.ttf
  src/fonts/ploticon/ploticon.woff
  src/plot_api/plot_config.js
  tasks/bundle.js
  tasks/preprocess.js
  tasks/util/constants.js
  tasks/util/pull_font_svg.js
  test/jasmine/tests/modebar_test.js
Labels: status: reviewable, type: feature

#4068 mapbox: add shortcuts to additional tilesets
  src/plots/mapbox/constants.js
  src/plots/mapbox/mapbox.js
  test/image/baselines/mapbox_carto-style.png
  test/image/baselines/mapbox_stamen-style.png
  test/image/baselines/mapbox_white-bg-style.png
  test/image/mocks/mapbox_carto-style.json
  test/image/mocks/mapbox_stamen-style.json
  test/image/mocks/mapbox_white-bg-style.json
Labels: status: reviewable, type: feature

#4069 mapbox: add attributions
  src/plots/mapbox/constants.js
  src/plots/mapbox/index.js
  src/plots/mapbox/layers.js
  src/plots/mapbox/layout_attributes.js
  src/plots/mapbox/layout_defaults.js
  src/plots/mapbox/mapbox.js
  src/registry.js
  test/image/baselines/mapbox_0.png
  test/image/baselines/mapbox_angles.png
  test/image/baselines/mapbox_bubbles-text.png
  test/image/baselines/mapbox_bubbles.png
  test/image/baselines/mapbox_carto-style.png
  test/image/baselines/mapbox_choropleth-multiple.png
  test/image/baselines/mapbox_choropleth-raw-geojson.png
  test/image/baselines/mapbox_choropleth0.png
  test/image/baselines/mapbox_connectgaps.png
  test/image/baselines/mapbox_custom-style.png
  test/image/baselines/mapbox_density-mulitple.png
  test/image/baselines/mapbox_density0.png
  test/image/baselines/mapbox_earthquake-density.png
  test/image/baselines/mapbox_fill.png
  test/image/baselines/mapbox_geojson-attributes.png
  test/image/baselines/mapbox_layers.png
  test/image/baselines/mapbox_osm-style.png
  test/image/baselines/mapbox_stamen-style.png
  test/image/baselines/mapbox_symbol-text.png
  test/image/baselines/mapbox_white-bg-style.png
  test/image/mocks/mapbox_carto-style.json
  test/image/mocks/mapbox_stamen-style.json
  test/image/mocks/mapbox_white-bg-style.json
  test/jasmine/tests/mapbox_test.js
Labels: status: reviewable, type: feature

#3991 Configurable doubleclick
  src/components/dragelement/index.js
  src/components/legend/draw.js
  src/constants/interactions.js
  src/plot_api/plot_config.js
  src/plots/cartesian/dragbox.js
  src/plots/layout_attributes.js
  test/jasmine/assets/double_click.js
  test/jasmine/tests/annotations_test.js
  test/jasmine/tests/bar_test.js
  test/jasmine/tests/click_test.js
  test/jasmine/tests/dragelement_test.js
  test/jasmine/tests/geo_test.js
  test/jasmine/tests/legend_scroll_test.js
  test/jasmine/tests/legend_test.js
  test/jasmine/tests/select_test.js
Labels: status: reviewable, type: feature

#4064 do not show prefix and suffix for minor log axes
  src/plots/cartesian/axes.js
  test/image/baselines/log-axis_no-minor_suffix-prefix.png
  test/image/mocks/log-axis_no-minor_suffix-prefix.json
Labels: status: reviewable, type: bug

#4035 Improve `mapbox.style` description + use mapbox-gl v1.1.1
  package-lock.json
  package.json
  src/plots/mapbox/constants.js
  src/plots/mapbox/index.js
  src/plots/mapbox/layout_attributes.js
  src/plots/mapbox/mapbox.js
  test/jasmine/tests/mapbox_test.js
Labels: status: reviewable, type: bug, type: documentation

#4075 dev deps 07-2019 edition
  .eslintrc
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#4063 Filter numbers during calc step
  src/lib/index.js
  src/traces/funnel/arrays_to_calcdata.js
  src/traces/scatter/arrays_to_calcdata.js
  test/jasmine/tests/bar_test.js
  test/jasmine/tests/funnel_test.js
  test/jasmine/tests/scatter_test.js
  test/jasmine/tests/scattergeo_test.js
Labels: status: reviewable, type: bug

#4079 Fix mapbox.style values in attribution declaration
  src/plots/mapbox/layout_attributes.js
Labels: status: reviewable, type: documentation

#4081 Revise the output of bar text transform functions
  src/traces/bar/plot.js
  src/traces/funnelarea/plot.js
Labels: status: reviewable, type: maintenance

#4082 Bug fix parcoords when all the data is zero
  src/plots/cartesian/axes.js
  src/traces/parcoords/parcoords.js
  test/jasmine/tests/parcoords_test.js
Labels: status: reviewable, type: bug, type: regression

#4083 Parcoords bug fix - do not draw full select line when constraint range falls below range
  src/traces/parcoords/axisbrush.js
  test/image/baselines/gl2d_parcoords_out-of-range_selected-below.png
  test/image/mocks/gl2d_parcoords_out-of-range_selected-below.json
Labels: status: reviewable, type: bug

#4087 Bug fix parcoords - selecting lines outside displayed range axis
  src/traces/parcoords/axisbrush.js
  src/traces/parcoords/lines.js
  test/image/baselines/gl2d_parcoords_out-of-range_selected-above-below.png
  test/image/mocks/gl2d_parcoords_out-of-range_selected-above-below.json
  test/jasmine/tests/parcoords_test.js
Labels: status: reviewable, type: bug

#4090 Bump scatter3d to 1.2.2
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#4089 Bug fix - do not drop previous constraint on click
  src/traces/parcoords/axisbrush.js
  test/jasmine/tests/parcoords_test.js
Labels: status: reviewable, type: bug

#4094 Pin down mapbox-gl version
  package.json
Labels: status: reviewable, type: bug
