Repository plotly/plotly.js, pull requests merged in 2020-04, with the labels that each got.

#4725 Fix "extremes" opacityscale function
  src/traces/surface/defaults.js
  test/image/baselines/gl3d_volume_multiple-traces.png
Labels: status: reviewable, type: bug

#4731 Bump is-mobile & gl-vis modules
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#4714 Skip zeroline when negative sizes are present on positive base and vice versa
  src/traces/bar/cross_trace_calc.js
  test/image/baselines/bar-like_traces_no-tozero.png
  test/image/baselines/bar-like_traces_no-tozero_negative.png
  test/image/baselines/bar-like_traces_no-tozero_stack.png
  test/image/baselines/bar-like_traces_tozero.png
  test/image/baselines/bar_attrs_group.png
  test/image/baselines/bar_attrs_overlay.png
  test/image/mocks/bar-like_traces_no-tozero.json
  test/image/mocks/bar-like_traces_no-tozero_negative.json
  test/image/mocks/bar-like_traces_no-tozero_stack.json
  test/image/mocks/bar-like_traces_tozero.json
Labels: status: reviewable, type: bug

#4720 React mapbox style
  src/plots/mapbox/mapbox.js
  test/jasmine/tests/mapbox_test.js
Labels: status: reviewable, type: bug

#4740 Fix steps in indicator attributes mock
  test/image/baselines/indicator_attrs.png
  test/image/mocks/indicator_attrs.json
Labels: status: reviewable, type: maintenance

#4748 apply src tag in jasmine requires
  test/jasmine/assets/click.js
  test/jasmine/assets/custom_matchers.js
  test/jasmine/assets/modebar_button.js
  test/jasmine/assets/mouse_event.js
  test/jasmine/assets/touch_event.js
  test/jasmine/tests/bar_test.js
  test/jasmine/tests/funnel_test.js
  test/jasmine/tests/funnelarea_test.js
  test/jasmine/tests/pie_test.js
  test/jasmine/tests/waterfall_test.js
Labels: status: reviewable, type: maintenance

#4751 Bump jsdom from version 11 to 16
  package-lock.json
  package.json
Labels: type: maintenance

#4750 Print error before calling throw
  tasks/util/common.js
Labels: type: maintenance

#4770 bump dev -dependencies April-2020
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#4768 Bump d3-force to v1.2.1
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#4752 Bump mapbox-gl to 1.9.2
  package-lock.json
  package.json
  src/plots/mapbox/constants.js
Labels: status: reviewable, type: bug, type: feature

#4777 Fix Missing WebGL Message #4765
  src/lib/prepare_regl.js
Labels: status: reviewable, type: bug

#4736 Translation to Portuguese (Portugal)
  lib/locales/pt-pt.js
Labels: type: community, type: translation

#4772 bump minify-stream v2
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#4774 bump es6-promise v4
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#4773 bump topojson-client v3
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#4778 notifier: Use full font stack as elsewhere
  src/css/_notifier.scss
Labels: status: reviewable, type: bug

#4783 Addressing transform sort order with null values
  src/transforms/sort.js
  test/jasmine/tests/transform_sort_test.js
Labels: status: reviewable, type: bug, type: community

#4575 adding support for icon-rotate and icon-allow-overlap in mapbox
  src/traces/scattermapbox/attributes.js
  src/traces/scattermapbox/convert.js
  src/traces/scattermapbox/defaults.js
  test/image/baselines/mapbox_angles.png
  test/image/mocks/mapbox_angles.json
  test/jasmine/tests/scattermapbox_test.js
Labels: type: community, type: feature

#4775 Draw & adjust new shapes over image trace and cartesian subplots
  package.json
  src/components/dragelement/helpers.js
  src/components/fx/layout_attributes.js
  src/components/modebar/buttons.js
  src/components/modebar/manage.js
  src/components/shapes/attributes.js
  src/components/shapes/defaults.js
  src/components/shapes/draw.js
  src/components/shapes/draw_newshape/attributes.js
  src/components/shapes/draw_newshape/constants.js
  src/components/shapes/draw_newshape/defaults.js
  src/components/shapes/draw_newshape/display_outlines.js
  src/components/shapes/draw_newshape/helpers.js
  src/components/shapes/draw_newshape/newshapes.js
  src/components/shapes/helpers.js
  src/components/shapes/index.js
  src/fonts/ploticon.js
  src/plots/cartesian/dragbox.js
  src/plots/cartesian/handle_outline.js
  src/plots/cartesian/helpers.js
  src/plots/cartesian/select.js
  src/plots/geo/geo.js
  src/plots/gl2d/scene2d.js
  src/plots/layout_attributes.js
  src/plots/mapbox/mapbox.js
  src/plots/plots.js
  src/plots/ternary/ternary.js
  src/traces/scattergl/plot.js
  src/traces/splom/plot.js
  test/jasmine/tests/cartesian_interact_test.js
  test/jasmine/tests/draw_newshape_test.js
  test/jasmine/tests/modebar_test.js
  test/jasmine/tests/select_test.js
  test/jasmine/tests/shapes_test.js
Labels: status: reviewable, type: feature

#4791 Bump mapbox-gl to 1.10.0
  package-lock.json
  package.json
  src/plots/mapbox/constants.js
Labels: type: bug, type: feature

#4793 Sanitize sourceattribution in mapbox layers
  src/lib/svg_text_utils.js
  src/plots/mapbox/layers.js
  test/jasmine/tests/mapbox_test.js
  test/jasmine/tests/svg_text_utils_test.js
Labels: status: reviewable

#4794 Fixup default angle of markers on scattermapbox
  src/traces/scattermapbox/attributes.js
  src/traces/scattermapbox/convert.js
Labels: status: reviewable, type: bug, type: regression
