Repository plotly/plotly.js, pull requests merged in 2020-08, with the labels that each got.

#5041 bump browserify 16.5.2
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#5042 bump eslint 7.6.0
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#5043 bump prepend-file v2
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#5055 Do not display first tick added by period ticklabelmode
  src/plots/cartesian/axes.js
  test/image/baselines/date_axes_period2.png
  test/image/mocks/date_axes_period2.json
Labels: status: reviewable, type: bug

#5061 Fix small sizes of bar with base
  src/plots/cartesian/set_convert.js
  test/jasmine/tests/bar_test.js
Labels: status: reviewable, type: bug

#5051 Improved browser compatibility for table scroll
  src/traces/table/plot.js
  test/jasmine/assets/mouse_event.js
  test/jasmine/tests/table_test.js
Labels: type: bug, type: community

#5047 improve performance in few places at plot_api and modebar
  src/components/modebar/buttons.js
  src/plot_api/plot_api.js
Labels: status: reviewable

#5045 Update title and tick labels during react with transition
  src/plot_api/plot_api.js
  test/jasmine/tests/titles_test.js
Labels: status: reviewable, type: bug

#5060 Fixup labels on reversed axes when ticklabelmode is set to period
  src/plots/cartesian/axes.js
  test/image/baselines/date_axes_period2.png
Labels: status: reviewable, type: bug

#5065 handle various time formats in ticklabelmode period
  src/constants/numerical.js
  src/plots/cartesian/axes.js
  src/plots/cartesian/set_convert.js
  test/image/baselines/date_axes_period.png
  test/jasmine/tests/axes_test.js
Labels: status: reviewable, type: bug

#5078 Bump into-stream v6
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#5079 bump lodash v4.17.20
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#5073 Accept symbol numbers in string format
  src/components/drawing/index.js
  test/image/baselines/symbols_string-numbers.png
  test/image/compare_pixels_test.js
  test/image/mocks/symbols_string-numbers.json
  test/jasmine/tests/mock_test.js
Labels: status: reviewable, type: bug

#5068 Improve contribution guide & readme, add code of conduct
  CONTRIBUTING.md
  README.md
  code_of_conduct.md
Labels: status: reviewable, type: documentation

#5085 Bump glslify v7.1.0
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#5084 Bump dependencies to use bubleify v2
  package-lock.json
  package.json
  src/traces/scattergl/calc.js
  src/traces/scatterpolargl/plot.js
Labels: status: reviewable, type: maintenance

#5072 Set width of categorical bars & boxes to category unit i.e. 1
  src/lib/search.js
  src/traces/bar/cross_trace_calc.js
  src/traces/bar/sieve.js
  src/traces/box/cross_trace_calc.js
  test/jasmine/tests/bar_test.js
  test/jasmine/tests/box_test.js
Labels: status: reviewable, type: bug

#5086 Update devDependencies Aug 18, 2020
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#5088 Improve monthly period label positioning
  src/constants/numerical.js
  src/plots/cartesian/axes.js
  test/jasmine/tests/axes_test.js
Labels: status: reviewable, type: bug

#5110 Bump dev-dependencies Aug 30
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance
