Repository plotly/plotly.js, pull requests merged in 2020-05, with the labels that each got.

#4799 Dev install static eval
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#4800 Dev install acorn, espree and mkdirp modules
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#4802 Rebuild package lock - May 2020
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#4805 update package-lock May 2nd
  package-lock.json
Labels: type: maintenance

#4810 Apply and ensure stroke event only to activate editable shapes
  src/components/shapes/draw.js
  test/jasmine/tests/draw_newshape_test.js
Labels: status: reviewable, type: bug, type: regression

#4811 Downgrade acorn to v6
  package-lock.json
  package.json
Labels: status: reviewable, type: bug

#4816 Fix react to plot_bgcolor changes
  src/plot_api/plot_api.js
  src/plots/plots.js
  test/jasmine/tests/plot_api_react_test.js
Labels: status: reviewable, type: bug

#4814 Handle rangebreak gaps in `candlestick` & `ohlc`
  src/lib/search.js
  test/image/baselines/axes_breaks-candlestick.png
  test/image/baselines/axes_breaks-candlestick2.png
  test/image/mocks/axes_breaks-candlestick.json
  test/image/mocks/axes_breaks-candlestick2.json
  test/jasmine/tests/mock_test.js
Labels: status: reviewable, type: bug

#4821 Fix rangebreaks on heatmap with 2d z array
  src/traces/heatmap/calc.js
  src/traces/heatmap/convert_column_xyz.js
  test/image/baselines/axes_breaks-contour1d.png
  test/image/baselines/axes_breaks-contour2d.png
  test/image/baselines/axes_breaks-heatmap1d.png
  test/image/baselines/axes_breaks-heatmap2d.png
  test/image/mocks/axes_breaks-contour1d.json
  test/image/mocks/axes_breaks-contour2d.json
  test/image/mocks/axes_breaks-heatmap1d.json
  test/image/mocks/axes_breaks-heatmap2d.json
  test/jasmine/tests/mock_test.js
Labels: status: reviewable, type: bug

#4827 Fix legend title react
  src/components/legend/draw.js
  test/jasmine/tests/legend_test.js
Labels: status: reviewable, type: bug

#4829 Fix for histogram2d with rangebreaks
  src/traces/heatmap/calc.js
  test/image/baselines/axes_breaks-histogram2d.png
  test/image/mocks/axes_breaks-histogram2d.json
  test/jasmine/tests/mock_test.js
Labels: status: reviewable, type: bug

#4832 Fix react category order of matching axes
  src/lib/relink_private.js
  test/jasmine/tests/axes_test.js
Labels: status: reviewable, type: bug

#4851 Fix setting array tickmode on date & log axes
  src/plots/cartesian/tick_value_defaults.js
  test/image/baselines/axes_custom-ticks_log-date.png
  test/image/mocks/axes_custom-ticks_log-date.json
  test/jasmine/tests/axes_test.js
  test/jasmine/tests/mock_test.js
Labels: status: reviewable, type: bug

#4858 bypass non-string ids when matching axes
  src/plots/cartesian/axis_ids.js
  test/jasmine/tests/axes_test.js
Labels: status: reviewable, type: bug

#4859 bump mapbox-gl to v1.10.1
  package-lock.json
  package.json
  src/plots/mapbox/constants.js
Labels: status: reviewable, type: maintenance

#4860 Bump eslint v7
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#4861 Bump node sass, espree v7 and karma v5
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#4385 Fix bug wheel event for IE.
  src/plots/cartesian/dragbox.js
Labels: status: reviewable, type: bug, type: community

#4873 bump dev-deps May 26
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#4881 bump regl v1.6.0
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#4882 Bump fuse.js v6
  devtools/test_dashboard/devtools.js
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance
