Repository plotly/plotly.js, pull requests merged in 2020-01, with the labels that each got.

#4454 Improve sunbust and treemap click events behavior
  src/traces/sunburst/fx.js
  test/jasmine/tests/sunburst_test.js
  test/jasmine/tests/treemap_test.js
Labels: status: reviewable, type: feature

#4453 enables loading locales before Plotly
  src/core.js
  tasks/util/wrap_locale.js
Labels: status: reviewable, type: feature

#4432 Box pre-computed q1/median/q3 input signature + more quartile-computing methods
  src/lib/index.js
  src/plots/cartesian/type_defaults.js
  src/traces/box/attributes.js
  src/traces/box/calc.js
  src/traces/box/defaults.js
  src/traces/box/index.js
  src/traces/violin/attributes.js
  test/image/baselines/box_precomputed-stats.png
  test/image/baselines/box_quartile-methods.png
  test/image/mocks/box_precomputed-stats.json
  test/image/mocks/box_quartile-methods.json
  test/jasmine/tests/box_test.js
  test/jasmine/tests/select_test.js
Labels: status: reviewable, type: feature

#4463 Improve description of sunburst/treemap outsidetextfont
  src/traces/sunburst/attributes.js
  src/traces/treemap/attributes.js
Labels: status: reviewable, type: maintenance

#4465 Fix symbol numbers in scattergl and splom traces
  src/components/drawing/index.js
  src/traces/scattergl/convert.js
  src/traces/scattergl/defaults.js
  src/traces/scattergl/helpers.js
  src/traces/scattergl/hover.js
  src/traces/splom/defaults.js
  test/image/baselines/gl2d_symbol_numbers.png
  test/image/baselines/splom_symbol_numbers.png
  test/image/mocks/gl2d_symbol_numbers.json
  test/image/mocks/splom_symbol_numbers.json
Labels: status: reviewable, type: bug

#4464 Notifier logging
  src/lib/loggers.js
  src/lib/notifier.js
  src/plot_api/plot_config.js
  src/plots/mapbox/index.js
  test/image/compare_pixels_test.js
  test/jasmine/tests/lib_test.js
  test/jasmine/tests/mapbox_test.js
Labels: status: reviewable, type: feature

#4469 Improve text fit in treemap trace
  src/traces/bar/plot.js
  src/traces/treemap/plot.js
  test/image/baselines/treemap_coffee.png
  test/image/baselines/treemap_flare.png
  test/image/baselines/treemap_level-depth.png
  test/image/baselines/treemap_packages_colorscale_allone.png
  test/image/baselines/treemap_packages_colorscale_novalue.png
  test/image/baselines/treemap_packings.png
  test/image/baselines/treemap_pad_mirror.png
  test/image/baselines/treemap_pad_transpose.png
  test/image/baselines/treemap_sunburst_marker_colors.png
  test/image/baselines/treemap_textfit.png
  test/image/baselines/treemap_textposition.png
  test/image/baselines/treemap_values.png
  test/image/baselines/treemap_values_colorscale.png
  test/image/baselines/treemap_with-without_values.png
  test/image/baselines/treemap_with-without_values_template.png
  test/image/baselines/uniformtext_sunburst_treemap.png
  test/image/baselines/uniformtext_treemap.png
  test/image/baselines/uniformtext_treemap_coffee-maxdepth3.png
  test/image/mocks/uniformtext_treemap_coffee-maxdepth3.json
  test/jasmine/tests/treemap_test.js
Labels: status: reviewable, type: bug

#4416 Handle invalid values and zero totals for pie and funnelarea
  src/traces/funnelarea/defaults.js
  src/traces/pie/calc.js
  src/traces/pie/defaults.js
  src/traces/pie/index.js
  test/jasmine/tests/funnelarea_test.js
  test/jasmine/tests/pie_test.js
Labels: status: reviewable, type: bug

#4470 Fix colorbar templating for "non-root" colorscales
  src/components/colorscale/defaults.js
  test/image/baselines/marker_colorscale_template.png
  test/image/baselines/parcats_colorscale_template.png
  test/image/baselines/treemap_coffee.png
  test/image/compare_pixels_test.js
  test/image/mocks/parcats_colorscale_template.json
Labels: status: reviewable, type: bug

#4472 Fix event data and some hover templates for x/y/z heatmap + contour
  src/traces/heatmap/convert_column_xyz.js
  src/traces/heatmap/hover.js
  test/jasmine/tests/contour_test.js
  test/jasmine/tests/heatmap_test.js
  test/jasmine/tests/hover_label_test.js
Labels: status: reviewable, type: bug

#4483 geo.visible false should override template.layout.geo.show*
  src/plots/geo/layout_defaults.js
  test/image/baselines/geo_visible_false_override_template.png
  test/image/mocks/geo_visible_false_override_template.json
  test/jasmine/tests/geo_test.js
Labels: status: reviewable, type: bug

#4475 Dev deps bump PR - first one in 2020 edition
  package-lock.json
  package.json
  tasks/test_syntax.js
Labels: status: reviewable, type: maintenance

#4516 fix for tweaking visible attribute of treemap pathbar
  src/traces/treemap/plot.js
  test/jasmine/tests/treemap_test.js
Labels: status: reviewable, type: bug

#4525 Fix mapbox layer opacity for raster types
  src/plots/mapbox/layers.js
  test/image/baselines/mapbox_layers.png
  test/image/mocks/mapbox_layers.json
Labels: status: reviewable, type: bug

#4526 Allow 0 in grouby transform nameformat templates + fix Plotly.validate for valType:'any' attributes
  src/lib/index.js
  src/plot_api/validate.js
  test/jasmine/tests/lib_test.js
  test/jasmine/tests/validate_test.js
Labels: status: reviewable, type: bug

#4528 fix typo
  src/components/annotations/attributes.js
Labels: type: documentation

#4360 Refactor gl3d scene
  package-lock.json
  package.json
  src/plots/gl3d/scene.js
  test/jasmine/tests/gl3d_plot_interact_test.js
Labels: status: reviewable, type: maintenance

#4522 Fix - hide empty bars in interactive mode
  src/traces/bar/plot.js
  test/image/baselines/bar_hide_nulls.png
  test/image/mocks/bar_hide_nulls.json
  test/jasmine/tests/bar_test.js
Labels: status: reviewable, type: bug

#4523 Update insidetextorientation description for pie and sunburst traces
  src/traces/pie/attributes.js
Labels: type: documentation

#4529 Handle 'missing' matching axes
  src/plot_api/subroutines.js
  src/plots/cartesian/axes.js
  src/plots/cartesian/constants.js
  src/plots/cartesian/layout_defaults.js
  src/plots/plots.js
  test/image/baselines/matching-missing-axes.png
  test/image/compare_pixels_test.js
  test/image/mocks/matching-missing-axes.json
  test/jasmine/tests/axes_test.js
  test/jasmine/tests/cartesian_interact_test.js
Labels: status: reviewable, type: bug

#4534 Fix hover for mesh3d, isosurface and volume
  package-lock.json
  package.json
  test/image/baselines/gl3d_mesh3d_coloring.png
  test/image/mocks/gl3d_mesh3d_coloring.json
  test/jasmine/tests/gl3d_hover_click_test.js
  test/jasmine/tests/isosurface_test.js
  test/jasmine/tests/volume_test.js
Labels: status: reviewable, type: bug, type: regression

#4536 add the word background to bgcolor description so it will get indexed by algolia
  src/plots/layout_attributes.js
Labels: type: documentation

#4537 Fix waterfall 'closest' hover when cursor is below the size axis
  src/traces/bar/hover.js
  test/image/compare_pixels_test.js
  test/jasmine/tests/waterfall_test.js
Labels: status: reviewable, type: bug

#4539 Fix hover of mesh3d traces with face color and face intensity
  package-lock.json
  package.json
  src/traces/mesh3d/convert.js
  test/image/mocks/gl3d_mesh3d_cell-intensity.json
  test/jasmine/tests/gl3d_hover_click_test.js
Labels: status: reviewable, type: bug
