Repository plotly/plotly.js, pull requests merged in 2020-06, with the labels that each got.

#4831 Fix rangebreaks overlapping and tick positions
  src/plots/cartesian/axes.js
  src/plots/cartesian/set_convert.js
  test/image/baselines/axes_breaks-candlestick2.png
  test/image/baselines/axes_breaks-dtick_auto.png
  test/image/baselines/axes_breaks-dtick_hourly.png
  test/image/baselines/axes_breaks-finance.png
  test/image/baselines/axes_breaks-night_autorange-reversed.png
  test/image/baselines/axes_breaks-overlap.png
  test/image/baselines/axes_breaks-rangeslider.png
  test/image/baselines/axes_breaks-reversed-without-pattern.png
  test/image/baselines/axes_breaks-round-weekdays.png
  test/image/baselines/axes_breaks-values.png
  test/image/baselines/axes_breaks-weekends-weeknights.png
  test/image/baselines/axes_breaks.png
  test/image/mocks/axes_breaks-dtick_auto.json
  test/image/mocks/axes_breaks-dtick_hourly.json
  test/image/mocks/axes_breaks-overlap.json
  test/jasmine/tests/axes_test.js
  test/jasmine/tests/mock_test.js
Labels: status: reviewable, type: bug

#4900 Fix bar lengths in milliseconds from base
  src/plots/cartesian/set_convert.js
  src/traces/bar/calc.js
  test/image/baselines/bar-with-milliseconds.png
  test/image/baselines/bar_gantt-chart.png
  test/image/mocks/bar-with-milliseconds.json
  test/image/mocks/bar_gantt-chart.json
  test/jasmine/tests/bar_test.js
  test/jasmine/tests/mock_test.js
Labels: status: reviewable, type: bug

#4901 bump dev dependencies June 5
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#4182 Added docs about building Plotly correctly with Angular
  BUILDING.md
Labels: status: reviewable, type: documentation

#4903 Fix gl3d ticks when converting dates to milliseconds
  src/lib/index.js
  src/plots/cartesian/axes.js
  src/plots/cartesian/set_convert.js
  src/plots/gl3d/layout/tick_marks.js
  src/traces/bar/calc.js
  test/image/baselines/gl3d_ticks-milliseconds.png
  test/image/mocks/gl3d_ticks-milliseconds.json
Labels: status: reviewable, type: bug, type: regression

#4864 The `preprocess` script fix
  tasks/util/update_version.js
Labels: type: community, type: maintenance

#4905 Bump dev-dependencies June 07
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#4878 discard ranges for single value parcoords dimensions when drag a new axis range
  src/traces/parcoords/axisbrush.js
  test/jasmine/tests/parcoords_test.js
Labels: status: reviewable, type: bug

#4909 Bump dev deps - June 9
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#4925 only take container computed size in px
  src/plots/plots.js
  test/jasmine/tests/config_test.js
Labels: type: bug

#4904 Fix setting tickwidth, tickcolor, ticklen, linecolor and possibly more attributes via template
  src/lib/coerce.js
  test/image/baselines/axes_breaks-round-weekdays.png
  test/image/mocks/axes_custom-ticks_log-date.json
  test/jasmine/tests/axes_test.js
  test/jasmine/tests/lib_test.js
Labels: status: reviewable, type: bug

#4929 bump gl-plot2d & gl-plot3d and drop ndarray-fill
  package-lock.json
  package.json
  src/traces/surface/convert.js
Labels: status: reviewable, type: maintenance

#4930 drop cwise and inline ndarray-homography
  package-lock.json
  package.json
  src/traces/surface/convert.js
Labels: status: reviewable, type: maintenance

#4934 bump dev modules June 22
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#4938 handle undefined args in Plotly.validate
  src/plot_api/validate.js
  test/jasmine/tests/mock_test.js
Labels: status: reviewable, type: bug

#4937 Fix misalignment of candlestick, ohlc and box plots when using rangebreaks
  src/traces/box/plot.js
  src/traces/ohlc/plot.js
  test/image/baselines/axes_breaks-ohlc_candlestick_box.png
  test/image/baselines/axes_breaks-rangeslider.png
  test/image/mocks/axes_breaks-ohlc_candlestick_box.json
  test/jasmine/tests/mock_test.js
Labels: status: reviewable, type: bug

#4939 Fix divider placement on reversed axes
  src/plots/cartesian/axes.js
  test/image/baselines/reversed-axis-dividers.png
  test/image/mocks/reversed-axis-dividers.json
Labels: status: reviewable, type: bug, type: community

#4947 bump through2, fuse.js and eslint versions
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#4948 bump is-mobile v2.2.2
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#4950 Fix heatmapgl supplyDefaults
  src/traces/heatmap/xyz_defaults.js
  src/traces/heatmapgl/defaults.js
  src/traces/heatmapgl/index.js
  test/jasmine/tests/heatmapgl_test.js
Labels: status: reviewable, type: bug

#4951 Fix contourgl supplyDefaults
  src/traces/heatmap/xyz_defaults.js
  test/jasmine/tests/contourgl_test.js
Labels: status: reviewable, type: bug

#4969 Fix median transform aggregation
  src/transforms/aggregate.js
  test/jasmine/tests/transform_aggregate_test.js
Labels: status: reviewable, type: bug

#4970 Bump dev-dependencies - June 30
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance
