Repository plotly/plotly.js, pull requests merged in 2020-10, with the labels that each got.

#5181 Fix modebar not recreated when makePlotFramework called
  src/plot_api/plot_api.js
  test/jasmine/tests/modebar_test.js
Labels: status: reviewable, type: bug, type: community

#5183 Fixup new period mocks
  test/image/baselines/period_positioning2.png
  test/image/mocks/period_positioning2.json
  test/image/mocks/period_positioning7.json
Labels: status: reviewable, type: maintenance

#5189 Bump color modules to fix import problem using webpack
  package-lock.json
  package.json
Labels: status: reviewable, type: bug, type: regression

#5014 Add axis domain references to shapes, annotations, and layout images
  .gitignore
  package-lock.json
  package.json
  src/components/annotations/attributes.js
  src/components/annotations/calc_autorange.js
  src/components/annotations/defaults.js
  src/components/annotations/draw.js
  src/components/images/attributes.js
  src/components/images/defaults.js
  src/components/images/draw.js
  src/components/shapes/attributes.js
  src/components/shapes/calc_autorange.js
  src/components/shapes/defaults.js
  src/components/shapes/draw.js
  src/components/shapes/helpers.js
  src/constants/axis_placeable_objects.js
  src/plot_api/helpers.js
  src/plots/cartesian/axes.js
  src/plots/cartesian/axis_ids.js
  src/plots/cartesian/constants.js
  src/plots/cartesian/include_components.js
  test/image/baselines/domain_ref_axis_types.png
  test/image/baselines/domain_refs.png
  test/image/mocks/domain_ref_axis_types.json
  test/image/mocks/domain_refs.json
  test/jasmine/assets/domain_ref/components.js
  test/jasmine/assets/domain_ref/domain_ref_base.json
  test/jasmine/assets/domain_ref/domain_refs_editable.json
  test/jasmine/assets/get_rect_center.js
  test/jasmine/assets/get_svg_elem_screen_bbox.js
  test/jasmine/assets/pixel_calc.js
  test/jasmine/assets/svg_tools.js
  test/jasmine/bundle_tests/plotschema_test.js
  test/jasmine/karma.conf.js
  test/jasmine/tests/domain_ref_interact_test.js
  test/jasmine/tests/domain_ref_test.js
  test/jasmine/tests/gl2d_plot_interact_test.js
  test/jasmine/tests/gl3d_hover_click_test.js
  test/jasmine/tests/gl3d_plot_interact_test.js
  test/jasmine/tests/mock_test.js
  test/jasmine/tests/parcats_test.js
  test/jasmine/tests/polar_test.js
  test/jasmine/tests/scatter3d_test.js
  test/jasmine/tests/scattergl_test.js
Labels: status: reviewable, type: feature

#5171 sunburst Rotation
  src/traces/sunburst/attributes.js
  src/traces/sunburst/defaults.js
  src/traces/sunburst/plot.js
Labels: status: reviewable, type: community, type: feature

#5187 improve labels on axes with rangebreaks
  src/plots/cartesian/axes.js
  test/image/baselines/axes_breaks-candlestick2.png
  test/image/baselines/axes_breaks-dtick_auto.png
  test/image/baselines/axes_breaks-finance.png
  test/image/baselines/axes_breaks-night_autorange-reversed.png
  test/image/baselines/axes_breaks-overlap.png
  test/image/baselines/axes_breaks-rangeslider.png
  test/image/baselines/axes_breaks-reversed-without-pattern.png
  test/image/baselines/axes_breaks-round-weekdays.png
  test/image/baselines/axes_breaks-values.png
  test/image/baselines/axes_breaks-weekends-weeknights.png
  test/image/baselines/axes_breaks-weekends_autorange-reversed.png
  test/image/baselines/axes_breaks.png
  test/image/baselines/date_axes_period_breaks_automargin.png
  test/image/baselines/period_positioning3.png
  test/image/baselines/period_positioning4.png
  test/image/mocks/axes_breaks-contour1d.json
  test/image/mocks/axes_breaks-contour2d.json
  test/image/mocks/axes_breaks-heatmap1d.json
  test/image/mocks/axes_breaks-heatmap2d.json
  test/image/mocks/axes_breaks-histogram2d.json
  test/jasmine/tests/axes_test.js
Labels: status: reviewable, type: bug

#5201 more sunburst rotation
  src/traces/pie/helpers.js
  src/traces/pie/plot.js
  src/traces/sunburst/plot.js
  test/image/baselines/treemap_sunburst_basic.png
  test/image/mocks/treemap_sunburst_basic.json
Labels: status: reviewable, type: bug, type: feature

#5204 Mention the full-json option in the Plotly.toImage warning
  src/lib/index.js
  src/plot_api/to_image.js
  test/jasmine/tests/toimage_test.js
Labels: status: reviewable, type: bug, type: maintenance

#5203 Provide computed margins in full-json export
  src/plots/layout_attributes.js
  src/plots/plots.js
  test/jasmine/tests/toimage_test.js
Labels: status: reviewable, type: feature

#5209 Force default dims for downloadImage to null
  src/snapshot/download.js
  src/traces/image/calc.js
  src/traces/image/helpers.js
  test/jasmine/tests/download_test.js
Labels: status: reviewable, type: bug

#5208 Fix positioning monthly tickformat when initial auto dtick is weekly
  src/plots/cartesian/axes.js
  test/jasmine/tests/axes_test.js
Labels: status: reviewable, type: bug

#5216 Provide a default hovertemplate label for attribute "base" in bar traces
  src/traces/bar/hover.js
  test/jasmine/tests/bar_test.js
Labels: status: reviewable, type: bug

#5210 Fix staticPlot behaviour for range slider and legend
  src/components/legend/draw.js
  src/components/rangeslider/draw.js
  test/jasmine/tests/legend_test.js
  test/jasmine/tests/range_slider_test.js
Labels: status: reviewable, type: bug, type: community

#5220 Update pull-request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: status: reviewable

#5217 Fix issue where styles weren't reset when re-using SVGs in colorbar
  src/components/colorbar/draw.js
  test/jasmine/tests/colorbar_test.js
Labels: hacktoberfest, status: reviewable, type: bug, type: community

#5223 Downgrade color* modules to working versions to fix import
  package-lock.json
  package.json
Labels: status: reviewable, type: regression

#5225 Record last actual margins when plot involving too many redraws
  src/plots/plots.js
  test/jasmine/tests/pie_test.js
  test/jasmine/tests/toimage_test.js
Labels: status: reviewable, type: bug

#5226 Bump dev-dependencies 20 October 2020
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#5233 Revise gl3d scene initialization
  src/plots/gl3d/scene.js
Labels: status: reviewable, type: maintenance

#5236 Avoid unnecessary styling of backgrounds during automargin redraws when subplot positions are incomplete
  src/plot_api/subroutines.js
Labels: status: reviewable, type: bug, type: regression
