Repository plotly/plotly.js, pull requests merged in 2020-03, with the labels that each got.

#4610 check-node-version: accept any nodejs version in 12.x
  package.json
Labels: type: maintenance

#4519 Improve pie and sunburst inside text pad
  src/traces/pie/plot.js
  test/image/baselines/display-text_zero-number.png
  test/image/baselines/funnelarea_pie_colorways.png
  test/image/baselines/funnelarea_with_other_traces.png
  test/image/baselines/legend-constant-itemsizing.png
  test/image/baselines/mathjax.png
  test/image/baselines/pie_automargin.png
  test/image/baselines/pie_fonts.png
  test/image/baselines/pie_inside-text-orientation.png
  test/image/baselines/pie_scale_textpos_hideslices.png
  test/image/baselines/pie_style_arrays.png
  test/image/baselines/pie_textpad_radial.png
  test/image/baselines/pie_textpad_tangential.png
  test/image/baselines/sunburst_branchvalues-total-almost-equal.png
  test/image/baselines/sunburst_coffee.png
  test/image/baselines/sunburst_count_branches.png
  test/image/baselines/sunburst_flare.png
  test/image/baselines/sunburst_inside-text-orientation.png
  test/image/baselines/sunburst_inside-text-orientation_clock.png
  test/image/baselines/sunburst_packages_colorscale_novalue.png
  test/image/baselines/sunburst_textfit.png
  test/image/baselines/sunburst_textpad_radial.png
  test/image/baselines/sunburst_textpad_tangential.png
  test/image/baselines/sunburst_values.png
  test/image/baselines/sunburst_values_colorscale.png
  test/image/baselines/sunburst_with-without_values.png
  test/image/baselines/texttemplate.png
  test/image/baselines/treemap_level-depth.png
  test/image/baselines/treemap_sunburst_marker_colors.png
  test/image/baselines/uniformtext_pie_16_auto.png
  test/image/baselines/uniformtext_pie_8_horizontal.png
  test/image/baselines/uniformtext_pie_8_horizontal_center.png
  test/image/baselines/uniformtext_pie_8_radial.png
  test/image/baselines/uniformtext_pie_8_tangential.png
  test/image/baselines/uniformtext_pie_inside-text-orientation.png
  test/image/baselines/uniformtext_sunburst_inside-text-orientation.png
  test/image/mocks/pie_fonts.json
  test/image/mocks/pie_textpad_radial.json
  test/image/mocks/pie_textpad_tangential.json
  test/image/mocks/sunburst_textpad_radial.json
  test/image/mocks/sunburst_textpad_tangential.json
  test/jasmine/tests/pie_test.js
  test/jasmine/tests/sunburst_test.js
Labels: status: reviewable, type: bug

#4566 Fix download images to match live gl3d plot
  src/plots/gl3d/scene.js
  test/image/baselines/gl3d_bunny-hull.png
  test/image/baselines/gl3d_bunny.png
  test/image/baselines/gl3d_coloraxes.png
  test/image/baselines/gl3d_cone-lighting.png
  test/image/baselines/gl3d_convex-hull.png
  test/image/baselines/gl3d_cube.png
  test/image/baselines/gl3d_directions-streamtube1.png
  test/image/baselines/gl3d_directions-streamtube2.png
  test/image/baselines/gl3d_directions-volume1.png
  test/image/baselines/gl3d_indicator_scatter3d.png
  test/image/baselines/gl3d_isosurface_thin_slices_transparent.png
  test/image/baselines/gl3d_isosurface_transparent.png
  test/image/baselines/gl3d_marker-arrays.png
  test/image/baselines/gl3d_marker-color.png
  test/image/baselines/gl3d_mesh3d_enable-alpha-with-rgba-color.png
  test/image/baselines/gl3d_opacity-scaling-spikes.png
  test/image/baselines/gl3d_rgb_dont_accept_alpha_scatter3d.png
  test/image/baselines/gl3d_scatter3d-colorscale.png
  test/image/baselines/gl3d_scatter3d_line3d_error3d_enable-alpha-with-rgba-color.png
  test/image/baselines/gl3d_scatter3d_line3d_error3d_transparent-with-zero-alpha.png
  test/image/baselines/gl3d_surface-lighting.png
  test/image/baselines/gl3d_traces-with-legend.png
  test/image/baselines/gl3d_traces-with-opacity.png
  test/image/baselines/gl3d_transparent_same-depth.png
  test/image/baselines/gl3d_volume_airflow.png
  test/image/baselines/gl3d_volume_multiple-traces.png
  test/image/baselines/gl3d_volume_multiple-traces_one-cube.png
  test/image/baselines/gl3d_volume_opacityscale-iso.png
Labels: status: reviewable, type: bug

#4480 Implement surface opacityscale & correct display of transparent surfaces
  package-lock.json
  package.json
  src/traces/surface/attributes.js
  src/traces/surface/convert.js
  src/traces/surface/defaults.js
  src/traces/surface/index.js
  src/traces/volume/attributes.js
  src/traces/volume/defaults.js
  test/image/baselines/gl3d_opacity-surface.png
  test/image/baselines/gl3d_surface-circular-opacityscale.png
  test/image/baselines/gl3d_surface_opacity-and-opacityscale.png
  test/image/baselines/gl3d_surface_opacity_match_mesh3d.png
  test/image/baselines/gl3d_surface_opacityscale_contour.png
  test/image/baselines/gl3d_traces-with-opacity.png
  test/image/mocks/gl3d_surface-circular-opacityscale.json
  test/image/mocks/gl3d_surface_opacity-and-opacityscale.json
  test/image/mocks/gl3d_surface_opacity_match_mesh3d.json
  test/image/mocks/gl3d_surface_opacityscale_contour.json
Labels: status: reviewable, type: bug, type: feature

#4621 sankey: introducing attributes (node|link).customdata
  src/traces/sankey/attributes.js
  src/traces/sankey/calc.js
  src/traces/sankey/defaults.js
  test/jasmine/tests/sankey_test.js
Labels: status: reviewable, type: feature

#4624 Improve CONTRIBUTING.md
  CONTRIBUTING.md
  test/image/README.md
Labels: status: reviewable, type: maintenance

#4634 Fix4631 - handle NaN cases to allow breaks on bar-like traces
  src/traces/bar/plot.js
  test/jasmine/tests/bar_test.js
Labels: status: reviewable, type: bug, type: regression

#4614 Introduce cartesian axis breaks
  src/components/rangeslider/draw.js
  src/plots/cartesian/autorange.js
  src/plots/cartesian/axes.js
  src/plots/cartesian/axis_defaults.js
  src/plots/cartesian/dragbox.js
  src/plots/cartesian/layout_attributes.js
  src/plots/cartesian/set_convert.js
  test/image/baselines/axes_breaks-bars.png
  test/image/baselines/axes_breaks-finance.png
  test/image/baselines/axes_breaks-rangeslider.png
  test/image/baselines/axes_breaks-tickvals.png
  test/image/baselines/axes_breaks-values.png
  test/image/baselines/axes_breaks-weekends-weeknights.png
  test/image/baselines/axes_breaks-weekends_autorange-reversed.png
  test/image/baselines/axes_breaks.png
  test/image/mocks/axes_breaks-bars.json
  test/image/mocks/axes_breaks-finance.json
  test/image/mocks/axes_breaks-rangeslider.json
  test/image/mocks/axes_breaks-tickvals.json
  test/image/mocks/axes_breaks-values.json
  test/image/mocks/axes_breaks-weekends-weeknights.json
  test/image/mocks/axes_breaks-weekends_autorange-reversed.json
  test/image/mocks/axes_breaks.json
  test/jasmine/tests/axes_test.js
  test/jasmine/tests/cartesian_interact_test.js
  test/jasmine/tests/hover_label_test.js
  test/jasmine/tests/range_slider_test.js
Labels: status: reviewable, type: feature

#4639 Fix reverse autorange on cartesian axes with breaks
  src/plots/cartesian/autorange.js
  src/plots/cartesian/axes.js
  src/plots/cartesian/dragbox.js
  src/plots/cartesian/set_convert.js
  test/image/baselines/axes_breaks-night_autorange-reversed.png
  test/image/mocks/axes_breaks-night_autorange-reversed.json
Labels: status: reviewable, type: bug

#4637 fix for spikedistance=-1
  src/components/fx/hover.js
  src/traces/bar/hover.js
  test/jasmine/tests/hover_spikeline_test.js
Labels: status: reviewable, type: bug

#4620 unified hover label
  src/components/fx/helpers.js
  src/components/fx/hover.js
  src/components/fx/layout_attributes.js
  src/components/fx/layout_defaults.js
  src/components/legend/draw.js
  src/components/legend/get_legend_data.js
  src/components/legend/style.js
  src/components/modebar/manage.js
  src/plot_api/plot_api.js
  src/plots/cartesian/layout_defaults.js
  test/jasmine/tests/hover_label_test.js
  test/jasmine/tests/legend_test.js
Labels: status: reviewable, type: feature

#4618 Corrected typo in histogram hover
  src/traces/histogram/hover.js
Labels: type: maintenance

#4540 Contour label extra pad and correct minus sign
  src/traces/contour/plot.js
  test/image/baselines/cheater.png
  test/image/baselines/cheater_contour.png
  test/image/baselines/contour_constraints.png
  test/image/baselines/contour_constraints_equal_boundary_minmax.png
  test/image/baselines/contour_edge_cases.png
  test/image/baselines/contour_label-font-size.png
  test/image/baselines/contour_label-formatting-via-colorbar.png
  test/image/baselines/contour_label-reversed-axes.png
  test/image/baselines/contour_label-reversed-xy.png
  test/image/baselines/contour_label-thousands-suffix.png
  test/image/baselines/contour_legend.png
  test/image/baselines/contour_lines_coloring.png
  test/image/baselines/contour_nolines.png
  test/image/baselines/contour_scatter.png
  test/image/baselines/contour_transposed-irregular.png
  test/image/baselines/heatmap_contour_irregular_bricks.png
  test/image/baselines/heatmap_multicategory.png
  test/image/mocks/contour_label-font-size.json
Labels: status: reviewable, type: bug

#4635 expose parcoords context line color
  src/traces/parcoords/attributes.js
  src/traces/parcoords/constants.js
  src/traces/parcoords/defaults.js
  src/traces/parcoords/parcoords.js
  test/jasmine/tests/parcoords_test.js
Labels: status: reviewable, type: feature

#4641 rename axis.breaks to axis.rangebreaks
  src/components/rangeslider/draw.js
  src/plots/cartesian/autorange.js
  src/plots/cartesian/axes.js
  src/plots/cartesian/axis_defaults.js
  src/plots/cartesian/dragbox.js
  src/plots/cartesian/layout_attributes.js
  src/plots/cartesian/set_convert.js
  test/image/mocks/axes_breaks-bars.json
  test/image/mocks/axes_breaks-finance.json
  test/image/mocks/axes_breaks-night_autorange-reversed.json
  test/image/mocks/axes_breaks-rangeslider.json
  test/image/mocks/axes_breaks-tickvals.json
  test/image/mocks/axes_breaks-values.json
  test/image/mocks/axes_breaks-weekends-weeknights.json
  test/image/mocks/axes_breaks-weekends_autorange-reversed.json
  test/image/mocks/axes_breaks.json
  test/jasmine/tests/axes_test.js
  test/jasmine/tests/cartesian_interact_test.js
  test/jasmine/tests/hover_label_test.js
  test/jasmine/tests/range_slider_test.js
Labels: status: reviewable, type: bug, type: feature

#4642 Fix to display transparent surface with contours when opacity is less than one
  package-lock.json
  package.json
  test/image/baselines/gl3d_surface_transparent-with-contours.png
  test/image/mocks/gl3d_surface_transparent-with-contours.json
Labels: status: reviewable, type: bug

#4649 keep the total length of rangebreaks positive
  src/plots/cartesian/axes.js
  src/plots/cartesian/set_convert.js
Labels: type: maintenance

#4650 Revert "expose parcoords context line color"
  src/traces/parcoords/attributes.js
  src/traces/parcoords/constants.js
  src/traces/parcoords/defaults.js
  src/traces/parcoords/parcoords.js
  test/jasmine/tests/parcoords_test.js
Labels: status: reviewable

#4644 Handle hover over rangebreaks for bar-like traces
  src/traces/bar/hover.js
  test/jasmine/tests/axes_test.js
  test/jasmine/tests/hover_label_test.js
Labels: status: reviewable, type: bug

#4652 revise rangebreak operation default
  src/plots/cartesian/layout_attributes.js
  test/image/mocks/axes_breaks-finance.json
  test/image/mocks/axes_breaks-tickvals.json
  test/image/mocks/axes_breaks-values.json
  test/jasmine/tests/axes_test.js
Labels: status: reviewable

#4653 Revise flags of rangebreak pattern
  src/plots/cartesian/constants.js
  src/plots/cartesian/layout_attributes.js
  src/plots/cartesian/set_convert.js
  test/image/mocks/axes_breaks-finance.json
  test/image/mocks/axes_breaks-night_autorange-reversed.json
  test/image/mocks/axes_breaks-rangeslider.json
  test/image/mocks/axes_breaks-weekends-weeknights.json
  test/image/mocks/axes_breaks-weekends_autorange-reversed.json
  test/jasmine/tests/axes_test.js
Labels: status: reviewable, type: bug

#4660 Revise operation in rangebreaks
  src/plots/cartesian/axis_defaults.js
  src/plots/cartesian/layout_attributes.js
  src/plots/cartesian/set_convert.js
  test/image/baselines/axes_breaks-bars.png
  test/image/baselines/axes_breaks-rangeslider.png
  test/image/baselines/axes_breaks-values.png
  test/image/baselines/axes_breaks-weekends-weeknights.png
  test/image/mocks/axes_breaks-bars.json
  test/image/mocks/axes_breaks-finance.json
  test/image/mocks/axes_breaks-night_autorange-reversed.json
  test/image/mocks/axes_breaks-rangeslider.json
  test/image/mocks/axes_breaks-tickvals.json
  test/image/mocks/axes_breaks-values.json
  test/image/mocks/axes_breaks-weekends-weeknights.json
  test/image/mocks/axes_breaks-weekends_autorange-reversed.json
  test/jasmine/tests/axes_test.js
Labels: status: reviewable, type: bug

#4662 histogram: in hover labels, harmonize start/end values of shared bins
  src/traces/bar/cross_trace_calc.js
  src/traces/histogram/calc.js
  test/jasmine/tests/histogram_test.js
Labels: status: reviewable, type: bug

#4661 Handle weekday strings in rangebreaks
  src/plots/cartesian/axis_defaults.js
  src/plots/cartesian/layout_attributes.js
  test/jasmine/tests/axes_test.js
Labels: status: reviewable, type: feature

#4663 Handle NaN positions in funnel & waterfall and skip connectors over rangebreaks
  src/traces/funnel/plot.js
  src/traces/waterfall/plot.js
  test/jasmine/tests/bar_test.js
  test/jasmine/tests/funnel_test.js
  test/jasmine/tests/waterfall_test.js
Labels: status: reviewable, type: bug

#4664 compare/unified hover include all points at same coordinate
  src/components/fx/hover.js
  test/jasmine/tests/hover_label_test.js
Labels: status: reviewable, type: bug

#4665 introduce spikesnap mode "hovered data"
  src/components/fx/hover.js
  src/plots/cartesian/layout_attributes.js
  src/plots/cartesian/layout_defaults.js
  test/jasmine/tests/hover_label_test.js
  test/jasmine/tests/hover_spikeline_test.js
Labels: status: reviewable, type: feature

#4669 Set unified hovermode via template
  src/components/fx/helpers.js
  src/components/fx/hover.js
  src/components/fx/hovermode_defaults.js
  src/components/fx/layout_defaults.js
  src/components/modebar/manage.js
  src/plots/cartesian/layout_defaults.js
  test/jasmine/tests/hover_label_test.js
Labels: status: reviewable, type: bug

#4670 Set Cartesian axis attributes via template
  src/plots/cartesian/axis_defaults.js
  src/plots/cartesian/tick_label_defaults.js
  test/jasmine/tests/axes_test.js
Labels: status: reviewable, type: bug

#4677 Improve auto ticks over axes with rangebreaks
  src/plots/cartesian/axes.js
  test/image/baselines/axes_breaks-finance.png
  test/image/baselines/axes_breaks-gridlines.png
  test/image/baselines/axes_breaks-night_autorange-reversed.png
  test/image/baselines/axes_breaks-rangeslider.png
  test/image/baselines/axes_breaks-weekends-weeknights.png
  test/image/baselines/axes_breaks-weekends_autorange-reversed.png
  test/image/baselines/axes_breaks.png
  test/image/mocks/axes_breaks-gridlines.json
  test/jasmine/tests/axes_test.js
  test/jasmine/tests/cartesian_interact_test.js
Labels: status: reviewable, type: bug

#4684 Handle date heads on axes with rangebreaks
  src/plots/cartesian/axes.js
  test/image/baselines/axes_breaks-finance.png
  test/image/baselines/axes_breaks-night_autorange-reversed.png
  test/image/baselines/axes_breaks-weekends-weeknights.png
Labels: status: reviewable, type: bug

#4685 Set tick value defaults via template
  src/plots/cartesian/tick_value_defaults.js
  test/jasmine/tests/axes_test.js
Labels: status: reviewable, type: bug

#4688 Avoid missing gridlines on axis with rangebreaks using "day of week" pattern
  src/plots/cartesian/axes.js
  src/plots/cartesian/axis_defaults.js
  test/image/baselines/axes_breaks-round-weekdays.png
  test/image/mocks/axes_breaks-round-weekdays.json
Labels: status: reviewable, type: bug

#4690 Disable plotly server URL by default
  src/plot_api/plot_config.js
  src/plots/plots.js
  test/jasmine/tests/config_test.js
Labels: status: reviewable, type: maintenance

#4687 unified hover: honor layout.hoverlabel
  src/components/fx/hover.js
  src/components/fx/hoverlabel_defaults.js
  src/components/fx/layout_defaults.js
  src/core.js
  test/jasmine/tests/hover_label_test.js
Labels: status: reviewable, type: bug

#4691 Apply 2020 plotly logo darker colors to the existing icon
  src/fonts/ploticon.js
Labels: status: reviewable, type: maintenance

#4694 Update links to new websites - edition March 2020
  README.md
  SECURITY.md
  bower.json
  composer.json
  lib/locales/fr.js
  src/components/modebar/modebar.js
  src/plot_api/plot_api.js
  src/plot_api/plot_config.js
  src/plot_api/plot_schema.js
  src/plots/attributes.js
  src/plots/font_attributes.js
  src/plots/layout_attributes.js
  src/plots/plots.js
  src/plots/template_attributes.js
  src/registry.js
  tasks/stats.js
  test/image/mocks/sankey_energy.json
  test/image/mocks/sankey_energy_dark.json
  test/jasmine/tests/animate_test.js
  test/jasmine/tests/annotations_test.js
  test/jasmine/tests/drawing_test.js
  test/jasmine/tests/plot_interact_test.js
  test/jasmine/tests/svg_text_utils_test.js
  test/jasmine/tests/toimage_test.js
Labels: status: reviewable, type: documentation, type: maintenance

#4695 Avoid tight daily labels on axes with rangebreaks when using "day of week" pattern
  src/plots/cartesian/axes.js
  test/image/baselines/axes_breaks-round-weekdays.png
  test/image/mocks/axes_breaks-round-weekdays.json
Labels: status: reviewable, type: bug

#4696 Do not show tick labels falling inside rangebreaks
  src/plots/cartesian/axes.js
  test/image/baselines/axes_breaks-finance.png
  test/image/baselines/axes_breaks-night_autorange-reversed.png
  test/image/baselines/axes_breaks-rangeslider.png
  test/image/baselines/axes_breaks-round-weekdays.png
  test/image/baselines/axes_breaks-weekends-weeknights.png
Labels: status: reviewable, type: bug

#4698 Improve positioning of rangebreaks
  src/plots/cartesian/set_convert.js
  test/image/baselines/axes_breaks-night_autorange-reversed.png
Labels: status: reviewable, type: bug

#4699 Fixup rangebreaks l2p and p2l functions
  src/plots/cartesian/autorange.js
  src/plots/cartesian/axes.js
  src/plots/cartesian/set_convert.js
  test/image/baselines/axes_breaks-night_autorange-reversed.png
  test/image/baselines/axes_breaks-reversed-without-pattern.png
  test/image/mocks/axes_breaks-reversed-without-pattern.json
  test/jasmine/tests/axes_test.js
  test/jasmine/tests/hover_label_test.js
Labels: status: reviewable, type: bug

#4708 Edit mocks
  test/image/mocks/8.json
  test/image/mocks/bar_attrs_group.json
  test/image/mocks/bar_attrs_overlay.json
  test/image/mocks/bar_attrs_relative.json
  test/image/mocks/matching-missing-axes.json
Labels: status: reviewable, type: maintenance
