Repository plotly/plotly.js, pull requests merged in 2020-11, with the labels that each got.

#5239 Fix hover on mobile and tablet devices for gl3d subplots
  package-lock.json
  package.json
  test/jasmine/tests/gl3d_plot_interact_test.js
Labels: status: reviewable, type: bug, type: regression

#5232 sunburst & treemap root color attribute
  src/traces/sunburst/attributes.js
  src/traces/sunburst/calc.js
  src/traces/sunburst/defaults.js
  src/traces/treemap/attributes.js
  src/traces/treemap/defaults.js
Labels: status: in progress, type: community, type: feature

#5245 Apply root.color in treemap & sunburst style and adopt tests
  src/traces/treemap/style.js
  test/image/baselines/sunburst_inside-text-orientation_clock.png
  test/image/baselines/treemap_textposition.png
  test/image/mocks/sunburst_inside-text-orientation_clock.json
  test/image/mocks/treemap_textposition.json
Labels: type: bug, type: feature

#5212 Configurable width of the symbol area of legends
  src/components/legend/attributes.js
  src/components/legend/constants.js
  src/components/legend/defaults.js
  src/components/legend/draw.js
  src/components/legend/style.js
  test/image/baselines/legend_itemwidth_dashline.png
  test/image/mocks/legend_itemwidth_dashline.json
  test/jasmine/tests/mock_test.js
Labels: status: reviewable, type: community, type: feature

#5237 Provide room for large computed margins
  src/plots/plots.js
  test/image/baselines/automargin-large-margins-both-sides.png
  test/image/baselines/automargin-large-margins-horizontal.png
  test/image/baselines/automargin-large-margins.png
  test/image/baselines/legend_small_horizontal.png
  test/image/mocks/automargin-large-margins-both-sides.json
  test/image/mocks/automargin-large-margins-horizontal.json
  test/image/mocks/automargin-large-margins.json
  test/jasmine/tests/axes_test.js
  test/jasmine/tests/indicator_test.js
  test/jasmine/tests/legend_scroll_test.js
  test/jasmine/tests/mock_test.js
Labels: status: reviewable, type: bug

#5240 Implement strict autotypenumbers
  src/plots/cartesian/axes.js
  src/plots/cartesian/axis_autotype.js
  src/plots/cartesian/layout_attributes.js
  src/plots/cartesian/layout_defaults.js
  src/plots/cartesian/type_defaults.js
  src/plots/gl3d/layout/axis_attributes.js
  src/plots/gl3d/layout/defaults.js
  src/plots/layout_attributes.js
  src/plots/plots.js
  src/plots/polar/layout_attributes.js
  src/plots/polar/layout_defaults.js
  src/traces/box/defaults.js
  src/traces/carpet/ab_defaults.js
  src/traces/carpet/axis_attributes.js
  src/traces/carpet/axis_defaults.js
  test/jasmine/tests/axes_test.js
  test/jasmine/tests/box_test.js
  test/jasmine/tests/carpet_test.js
  test/jasmine/tests/gl3dlayout_test.js
  test/jasmine/tests/polar_test.js
Labels: status: reviewable, type: bug, type: feature

#5253 Correct link in README.md
  README.md
Labels: type: community, type: documentation

#5254 Centralize transform functions
  src/components/annotations/draw.js
  src/components/annotations/draw_arrow_head.js
  src/components/colorbar/draw.js
  src/components/drawing/index.js
  src/components/fx/hover.js
  src/components/legend/style.js
  src/components/rangeselector/draw.js
  src/components/rangeslider/draw.js
  src/components/sliders/draw.js
  src/components/titles/index.js
  src/lib/index.js
  src/lib/svg_text_utils.js
  src/plots/cartesian/axes.js
  src/plots/cartesian/dragbox.js
  src/plots/cartesian/helpers.js
  src/plots/geo/geo.js
  src/plots/mapbox/index.js
  src/plots/polar/polar.js
  src/plots/ternary/ternary.js
  src/traces/carpet/plot.js
  src/traces/funnelarea/plot.js
  src/traces/indicator/plot.js
  src/traces/parcats/parcats.js
  src/traces/parcoords/axisbrush.js
  src/traces/parcoords/parcoords.js
  src/traces/pie/plot.js
  src/traces/sankey/render.js
  src/traces/table/plot.js
  test/jasmine/tests/click_test.js
  test/jasmine/tests/colorbar_test.js
  test/jasmine/tests/drawing_test.js
  test/jasmine/tests/indicator_test.js
  test/jasmine/tests/legend_scroll_test.js
  test/jasmine/tests/parcats_test.js
Labels: status: reviewable, type: maintenance

#5255 Fix typo in Czech locale file
  lib/locales/cs.js
Labels: status: reviewable, type: community, type: translation

#5257 fixup tests to pass on CI and more mock validation
  test/image/compare_pixels_test.js
  test/image/mocks/legend_horizontal_testwrap.json
  test/jasmine/tests/mock_test.js
Labels: type: maintenance

#5258 Bump some dev dependencies - Nov 9
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#5268 Fixup categoryorder for missing values in cartesian traces
  src/plots/plots.js
  test/image/baselines/missing-category-order.png
  test/image/mocks/missing-category-order.json
  test/jasmine/tests/mock_test.js
Labels: status: reviewable, type: bug

#5269 Fix reordering of mapbox raster/image layers on update
  src/plots/mapbox/layers.js
  test/jasmine/tests/mapbox_test.js
Labels: status: reviewable, type: bug

#5193 Align interactions when plot created inside scaled and/or translated elements using CSS transform
  package-lock.json
  src/components/fx/hover.js
  src/lib/dom.js
  src/lib/index.js
  src/lib/matrix.js
  src/lib/svg_text_utils.js
  src/plot_api/plot_api.js
  src/plots/cartesian/dragbox.js
  src/plots/cartesian/select.js
  src/plots/gl3d/scene.js
  src/plots/mapbox/mapbox.js
  src/plots/polar/polar.js
  src/plots/ternary/ternary.js
  src/traces/choropleth/hover.js
  src/traces/parcats/parcats.js
  src/traces/sankey/plot.js
  tasks/test_syntax.js
  test/jasmine/tests/cartesian_interact_test.js
  test/jasmine/tests/choropleth_test.js
  test/jasmine/tests/choroplethmapbox_test.js
  test/jasmine/tests/polar_test.js
  test/jasmine/tests/scattermapbox_test.js
  test/jasmine/tests/select_test.js
  test/jasmine/tests/ternary_test.js
Labels: status: reviewable, type: bug, type: community, type: feature

#5293 Set false locale
  src/plots/plots.js
  src/traces/histogram/cross_trace_defaults.js
Labels: status: reviewable, type: bug

#5294 In staticPlot, do not draw-zero length bars
  src/traces/bar/plot.js
  test/jasmine/tests/bar_test.js
Labels: status: reviewable, type: bug

#5287 rework matching & scaleanchor so they work together
  src/plot_api/plot_api.js
  src/plot_api/subroutines.js
  src/plots/cartesian/autorange.js
  src/plots/cartesian/axis_ids.js
  src/plots/cartesian/constraints.js
  src/plots/cartesian/dragbox.js
  src/plots/cartesian/index.js
  src/plots/cartesian/layout_attributes.js
  src/plots/cartesian/layout_defaults.js
  src/plots/cartesian/scale_zoom.js
  src/plots/cartesian/set_convert.js
  src/plots/plots.js
  src/traces/bar/cross_trace_calc.js
  src/traces/bar/defaults.js
  src/traces/box/cross_trace_calc.js
  src/traces/histogram/cross_trace_defaults.js
  test/image/baselines/axes_breaks-matches.png
  test/image/baselines/axes_chain_scaleanchor_matches.png
  test/image/baselines/axes_chain_scaleanchor_matches2.png
  test/image/baselines/axes_linked_date_autorange.png
  test/image/baselines/axes_scaleanchor-with-matches.png
  test/image/baselines/gl2d_marker_coloraxis.png
  test/image/baselines/matching-categories.png
  test/image/mocks/axes_breaks-matches.json
  test/image/mocks/axes_chain_scaleanchor_matches.json
  test/image/mocks/axes_chain_scaleanchor_matches2.json
  test/jasmine/tests/axes_test.js
  test/jasmine/tests/cartesian_interact_test.js
  test/jasmine/tests/image_test.js
  test/jasmine/tests/splom_test.js
Labels: type: bug, type: feature

#5302 5291: recalculation of dynamic CSS transforms on hover
  src/components/fx/hover.js
  src/lib/dom.js
  src/lib/index.js
  src/lib/svg_text_utils.js
  src/plot_api/plot_api.js
  src/plots/cartesian/dragbox.js
  src/plots/cartesian/select.js
  src/plots/gl3d/scene.js
  src/plots/polar/polar.js
  src/plots/ternary/ternary.js
  src/traces/parcats/parcats.js
  src/traces/sankey/plot.js
  test/jasmine/tests/cartesian_interact_test.js
  test/jasmine/tests/choropleth_test.js
  test/jasmine/tests/choroplethmapbox_test.js
  test/jasmine/tests/polar_test.js
  test/jasmine/tests/scattermapbox_test.js
  test/jasmine/tests/select_test.js
  test/jasmine/tests/ternary_test.js
Labels: status: reviewable, type: bug, type: community

#5308 WIP: Typed array encoding in supplyDefaults with Caching
  src/lib/array.js
  src/lib/coerce.js
  src/plots/plots.js
  src/traces/heatmap/xyz_defaults.js
  src/traces/isosurface/defaults.js
  src/traces/scatter/xy_defaults.js
  src/traces/scatter3d/defaults.js
Labels: status: reviewable, type: feature, type: performance

#5307 Use CSS to support fast image rendering on linear axes
  src/traces/image/plot.js
  test/image/baselines/image_source_axis_reverse.png
  test/image/mocks/image_source_axis_reverse.json
  test/jasmine/tests/image_test.js
  test/jasmine/tests/mock_test.js
Labels: status: reviewable, type: bug, type: feature

#5297 Bump events to v3 in glslify-deps
  package-lock.json
Labels: status: reviewable, type: maintenance
