Repository plotly/plotly.js, pull requests merged in 2020-07, with the labels that each got.

#4973 Fix parcats category order when dimension only includes numbers
  src/traces/parcats/calc.js
  test/image/baselines/parcats_numeric_sort.png
  test/image/mocks/parcats_numeric_sort.json
  test/jasmine/tests/mock_test.js
Labels: status: reviewable, type: bug

#4975 Fix numeric sort in ternary drag
  src/plots/ternary/ternary.js
Labels: status: reviewable, type: bug

#4977 Relink matching axes categories during Plotly.relayout calls
  src/lib/relink_private.js
  src/plot_api/plot_api.js
  src/plots/cartesian/set_convert.js
  test/jasmine/tests/axes_test.js
Labels: status: reviewable, type: bug, type: regression

#4981 Fix spelling and lint Markdown.
  BUILDING.md
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
Labels: status: reviewable, type: community, type: documentation

#4988 Bump and control the version of lodash in dev-dependencies
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#4982 Lint Markdown. Fix missing HTTPS on links.
  test/image/README.md
Labels: status: reviewable, type: community

#5016 Revert PR 4904 i.e. "undo the Fix for setting tickwidth, tickcolor, ticklen, linecolor and possibly more attributes via template"
  src/lib/coerce.js
  test/image/baselines/axes_breaks-round-weekdays.png
  test/image/mocks/axes_custom-ticks_log-date.json
  test/jasmine/tests/axes_test.js
  test/jasmine/tests/lib_test.js
Labels: status: reviewable, type: regression

#5015 Accept ISO-8601 short time offset format
  src/lib/dates.js
  test/jasmine/tests/lib_date_test.js
Labels: status: reviewable, type: bug, type: community

#5010 Implement horizontal and vertical markers for arrow charts
  src/components/drawing/symbol_defs.js
  test/image/baselines/arrow-markers.png
  test/image/mocks/arrow-markers.json
  test/jasmine/tests/mock_test.js
Labels: status: reviewable, type: feature

#4953 Discrete heatmapgl
  package-lock.json
  package.json
  src/traces/heatmapgl/attributes.js
  src/traces/heatmapgl/convert.js
  src/traces/heatmapgl/defaults.js
  test/image/baselines/gl2d_heatmapgl_discrete.png
  test/image/mocks/gl2d_heatmapgl_discrete.json
  test/jasmine/tests/mock_test.js
Labels: status: in progress, type: community, type: feature

#4993 Implement period ticklabelmode on cartesian date axes
  src/components/colorbar/draw.js
  src/plots/cartesian/axes.js
  src/plots/cartesian/axis_defaults.js
  src/plots/cartesian/layout_attributes.js
  src/plots/gl3d/layout/axis_defaults.js
  test/image/baselines/date_axes_period.png
  test/image/baselines/date_axes_period2.png
  test/image/mocks/date_axes_period.json
  test/image/mocks/date_axes_period2.json
  test/jasmine/tests/mock_test.js
Labels: status: reviewable, type: feature

#5026 Upgrade d3 time format to expose new formatting options for weekdays, weeks and quarters
  package-lock.json
  package.json
  src/constants/docs.js
  src/lib/dates.js
  src/lib/index.js
  src/plots/cartesian/set_convert.js
  src/plots/plots.js
  test/jasmine/tests/axes_test.js
  test/jasmine/tests/lib_date_test.js
  test/jasmine/tests/localize_test.js
Labels: status: reviewable, type: bug, type: feature

#5027 bump karma 5.1.1
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#5028 bump fuse.js 6.4.1
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#5029 dev-install elliptic 6.5.3
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#5033 Fix default half span of latitude
  src/plots/geo/geo.js
  test/image/baselines/geo_fitbounds-locations.png
Labels: status: reviewable, type: bug

#5025 Add Touch Support to RangeSlider #1098
  src/components/rangeslider/draw.js
Labels: status: reviewable, type: bug, type: community, type: feature

#5035 Fix typo in plotinfo keys
  src/plots/cartesian/index.js
Labels: status: reviewable, type: bug
