Repository plotly/plotly.js, pull requests merged in 2021-08, with the labels that each got.

#5873 tag `mapbox_custom-style` mock as flaky
  test/image/compare_pixels_test.js
Labels: type: maintenance

#5870 Bump regl from 1.6.1 to v2.1.0
  draftlogs/5870_change.md
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#5876 increase tolerance for flaky mocks
  test/image/compare_pixels_test.js
Labels: type: maintenance

#5875 Upgrade tar to version 6.1.2 or later
  package-lock.json
Labels: type: maintenance

#5878 removed invalid .then call using lib.promiseError which does not exis…
  draftlogs/5878_fix.md
  src/lib/index.js
Labels: status: reviewable, type: bug, type: community

#5885 upgrade path-parse to version 1.0.7
  package-lock.json
Labels: type: maintenance

#5894 bump plotly.py to v5.2.1
  .circleci/env_image.sh
Labels: type: maintenance

#5900 bump jsdom v17
  package-lock.json
  package.json
Labels: type: maintenance

#5901 Remove espree and mkdirp packages from root install
  package.json
Labels: type: maintenance

#5902 bump madge from v4 to v5
  package-lock.json
  package.json
Labels: type: maintenance

#5904 Use maskTexture name for parcoords regl setup
  src/traces/parcoords/lines.js
  src/traces/parcoords/shaders/vertex.glsl
Labels: type: maintenance

#5856 Added touchmove support to slider component
  draftlogs/5856_add.md
  src/components/sliders/draw.js
  test/jasmine/assets/touch_event.js
  test/jasmine/tests/sliders_test.js
Labels: type: feature, type: community, status: reviewable

#5895 Use `hoverlabel.font` for group titles in unified hover modes
  draftlogs/5895_fix.md
  src/components/fx/hover.js
  src/components/legend/get_legend_data.js
  test/jasmine/tests/hover_label_test.js
Labels: type: bug, status: reviewable

#5914 Add css transform input to devtool
  devtools/test_dashboard/devtools.js
  devtools/test_dashboard/index-strict.html
  devtools/test_dashboard/index.html
Labels: status: reviewable

#5915 bump tar version
  package-lock.json
Labels: type: maintenance

#5913 Handle case of div with zero dimension when positioning unified hover box
  draftlogs/5913_fix.md
  src/components/fx/hover.js
Labels: type: bug, status: reviewable, type: regression
