Repository plotly/plotly.js, pull requests merged in 2021-03, with the labels that each got.

#5527 Custom bundle script details
  lib/index-basic.js
  lib/index-cartesian.js
  lib/index-finance.js
  lib/index-geo.js
  lib/index-gl2d.js
  lib/index-gl3d.js
  lib/index-mapbox.js
  lib/index-strict.js
  lib/index.js
  tasks/extra_bundles.js
  tasks/partial_bundle.js
  tasks/util/browserify_wrapper.js
  tasks/util/constants.js
  tasks/util/wrap_locale.js
Labels: status: reviewable, type: feature

#5531 Fixup sankey text and shadow
  src/lib/svg_text_utils.js
  src/traces/parcats/parcats.js
  src/traces/parcoords/parcoords.js
  src/traces/sankey/constants.js
  src/traces/sankey/render.js
  test/image/baselines/sankey_circular.png
  test/image/baselines/sankey_circular_large.png
  test/image/baselines/sankey_circular_process.png
  test/image/baselines/sankey_circular_simple.png
  test/image/baselines/sankey_circular_simple2.png
  test/image/baselines/sankey_energy.png
  test/image/baselines/sankey_energy_dark.png
  test/image/baselines/sankey_groups.png
  test/image/baselines/sankey_large_padding.png
  test/image/baselines/sankey_link_concentration.png
  test/image/baselines/sankey_messy.png
  test/image/baselines/sankey_subplots.png
  test/image/baselines/sankey_subplots_circular.png
  test/image/baselines/sankey_x_y.png
  test/image/mocks/sankey_energy_dark.json
  test/image/mocks/sankey_subplots.json
  test/jasmine/tests/sankey_test.js
Labels: Major change, type: bug, type: feature

#5534 scattergl: make selection's eventData the same as in scatter traces
  src/traces/scattergl/select.js
  test/jasmine/tests/scattergl_select_test.js
  test/jasmine/tests/scatterpolargl_test.js
Labels: status: reviewable, type: bug

#5520 Add pattern fill for histogram, bar and barpolar traces
  src/components/drawing/index.js
  src/components/legend/style.js
  src/plot_api/plot_api.js
  src/snapshot/tosvg.js
  src/traces/bar/attributes.js
  src/traces/bar/style_defaults.js
  test/image/baselines/bar_patternfill.png
  test/image/mocks/bar_patternfill.json
  test/jasmine/tests/mock_test.js
Labels: status: reviewable, type: community, type: feature

#5536 Bump elliptic to v6.5.4 and uninstall it from root
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#5548 Bump madge v4
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#5542 Fixup bar spike distance
  src/components/fx/hover.js
  src/traces/bar/hover.js
  test/jasmine/tests/hover_spikeline_test.js
Labels: status: reviewable, type: bug

#5565 Refactor Treemap Trace: remove extra if statement in default.js
  src/traces/treemap/defaults.js
Labels: status: reviewable, type: maintenance

#5571 audit fix for y18n using v4.0.1
  package-lock.json
Labels: status: reviewable, type: maintenance
