Repository plotly/plotly.js, pull requests merged in 2021-06, with the labels that each got.

#5697 No longer publish or overwrite any "latest" bundles on CDN
  README.md
  tasks/cdn_publish.sh
  tasks/stats.js
Labels: Major change, status: reviewable

#5690 Implement (x|y)other hovertemplate to format differing positions in compare and unified modes
  src/components/fx/hover.js
  src/lib/index.js
  src/plots/template_attributes.js
  test/jasmine/tests/hover_label_test.js
Labels: status: reviewable, type: feature

#5607 Fix geo plot hover interaction for Firefox
  src/lib/index.js
  src/plots/geo/geo.js
Labels: status: reviewable, type: bug, type: community

#5696 Revise attributions of Carto, Stamen and Open Street Map styles
  src/plots/mapbox/constants.js
  test/image/baselines/mapbox_carto-style.png
  test/image/baselines/mapbox_density0-legend.png
  test/image/baselines/mapbox_osm-style.png
  test/image/baselines/mapbox_stamen-style.png
  test/jasmine/tests/mapbox_test.js
Labels: status: reviewable, type: bug

#5703 Update readme of distributed files
  dist/README.md
  tasks/stats.js
Labels: status: reviewable, type: documentation, type: maintenance

#5702 Revise partial bundle section in README
  README.md
Labels: type: documentation

#5704 Revise building readme
  BUILDING.md
  README.md
Labels: type: documentation, type: maintenance

#5705 Improve readme to get started with plotly.js JSON interface for non-JavaScript developers and adjust dist/README
  BUILDING.md
  CUSTOM_BUNDLE.md
  README.md
  dist/README.md
  tasks/stats.js
  tasks/test_syntax.js
Labels: status: reviewable, type: documentation

#5708 Fix ES6 import
  devtools/test_dashboard/index.html
  package-lock.json
  package.json
Labels: status: reviewable, type: bug

#5711 Improve readme sync packages
  README.md
  tasks/sync_packages.js
Labels: status: reviewable, type: documentation

#5712 Separate command line script for making custom bundles and rename it to "custom-bundle"
  CUSTOM_BUNDLE.md
  package.json
  tasks/custom_bundle.js
  tasks/extra_bundles.js
  tasks/partial_bundle.js
Labels: status: reviewable, type: bug, type: feature

#5713 Revise readme headers and more edits
  README.md
Labels: status: reviewable, type: documentation

#5716 Bump matrix-camera-controller to use binary-search-bounds v2
  package-lock.json
  package.json
Labels: type: maintenance

#5717 Combine all differing baselines for easy download from CircleCI
  .circleci/config.yml
Labels: type: maintenance

#5718 Audit fix glob-parent
  package-lock.json
Labels: type: maintenance

#5719 use exit instead of return to avoid script error
  .circleci/config.yml
Labels: type: maintenance

#5729 Replace deprecated node-sass with Dart Sass and update plot-CSS
  build/plotcss.js
  package-lock.json
  package.json
  tasks/preprocess.js
Labels: status: reviewable, type: maintenance

#5591 Implement legendrank attribute in traces
  src/components/legend/get_legend_data.js
  src/plots/attributes.js
  src/plots/plots.js
  src/traces/parcats/attributes.js
  test/image/baselines/legendrank.png
  test/image/baselines/legendrank2.png
  test/image/mocks/legendrank.json
  test/image/mocks/legendrank2.json
  test/jasmine/tests/legend_test.js
Labels: status: reviewable, type: feature

#5732 Set the maximum width of categorical bars & boxes to category unit - case of categoryarray
  src/lib/search.js
  src/traces/bar/cross_trace_calc.js
  src/traces/bar/sieve.js
  src/traces/box/calc.js
  src/traces/box/cross_trace_calc.js
  test/jasmine/tests/bar_test.js
Labels: status: reviewable, type: bug

#5737 update flaky list of image-test
  test/image/compare_pixels_test.js
Labels: type: maintenance

#5738 bump sass, open and eslint dev-dependencies
  package-lock.json
  package.json
Labels: type: maintenance

#5740 bump node-canvas 2.8.0 dev-dependency
  package-lock.json
  package.json
Labels: type: maintenance

#5739 Bump probe-image-size to v7.2.1
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#5742 bump karma-firefox-launcher v2.1.1
  package-lock.json
  package.json
Labels: type: maintenance

#5743 bump karma v6.3.4
  package-lock.json
  package.json
Labels: type: maintenance

#5733 Implement fgopacity, fgcolor & "overlay" fillmode for bars, fix bar legend and pattern with marker colorscale
  src/components/drawing/attributes.js
  src/components/drawing/index.js
  src/components/legend/style.js
  src/lib/coerce.js
  src/traces/bar/style_defaults.js
  tasks/test_mock.js
  test/image/baselines/pattern_bars.png
  test/image/baselines/pattern_fgcolor_overlay_fillmode.png
  test/image/baselines/pattern_legend_variations.png
  test/image/baselines/pattern_with_colorscale.png
  test/image/mocks/pattern_fgcolor_overlay_fillmode.json
  test/image/mocks/pattern_legend_variations.json
  test/image/mocks/pattern_with_colorscale.json
  test/jasmine/tests/bar_test.js
Labels: status: reviewable, type: bug, type: feature

#5744 update flaky list for image test
  test/image/compare_pixels_test.js
Labels: type: maintenance

#5745 Add missing noCI tests required to add the new trace type icicle
  test/jasmine/assets/mock_lists.js
  test/jasmine/tests/plot_api_react_test.js
Labels: type: maintenance

#5746 correct readme links
  README.md
Labels: status: reviewable, type: documentation

#5757 Join duplicated tests for sunburst, icicle and treemap
  test/jasmine/tests/plot_api_react_test.js
Labels: type: maintenance

#5747 Bump turf bbox dependency to v6.4.0
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#5755 Rewrite and make a centralized jsdom utility to get Plotly object in node.js test scripts and generating the schema
  tasks/test_mock.js
  tasks/test_plain_obj.js
  tasks/util/make_schema.js
  tasks/util/plotly_node.js
Labels: status: reviewable, type: maintenance

#5748 Bump turf area dependency to v6.4.0
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#5659 cache values and patterns in set_convert for rangebreaked axis
  src/plots/cartesian/set_convert.js
Labels: status: reviewable, type: community, type: performance

#5752 Legend group titles
  src/components/legend/draw.js
  src/components/legend/get_legend_data.js
  src/components/legend/handle_click.js
  src/plots/attributes.js
  src/plots/plots.js
  test/image/baselines/legendgroup-titles-pie.png
  test/image/baselines/legendgroup-titles.png
  test/image/baselines/legendrank.png
  test/image/baselines/legendrank2.png
  test/image/mocks/legendgroup-titles-pie.json
  test/image/mocks/legendgroup-titles.json
  test/image/mocks/legendrank.json
  test/image/mocks/legendrank2.json
Labels: status: reviewable, type: feature

#5763 Fix fetching geojson when ES6 import is used to load the library
  package-lock.json
  package.json
Labels: status: reviewable, type: bug

#5762 Add half-year directive (%h) for formatting dates and improve descriptions to include extra date formatting options
  src/lib/dates.js
  src/plots/cartesian/axis_format_attributes.js
  src/plots/cartesian/layout_attributes.js
  src/plots/hoverformat_attributes.js
  src/traces/bar/attributes.js
  src/traces/box/attributes.js
  src/traces/candlestick/attributes.js
  src/traces/carpet/axis_attributes.js
  src/traces/cone/attributes.js
  src/traces/contour/attributes.js
  src/traces/funnel/attributes.js
  src/traces/heatmap/attributes.js
  src/traces/histogram/attributes.js
  src/traces/histogram2d/attributes.js
  src/traces/histogram2dcontour/attributes.js
  src/traces/indicator/attributes.js
  src/traces/isosurface/attributes.js
  src/traces/mesh3d/attributes.js
  src/traces/ohlc/attributes.js
  src/traces/sankey/attributes.js
  src/traces/scatter/attributes.js
  src/traces/scatter3d/attributes.js
  src/traces/scattergl/attributes.js
  src/traces/splom/attributes.js
  src/traces/streamtube/attributes.js
  src/traces/surface/attributes.js
  src/traces/table/attributes.js
  src/traces/violin/attributes.js
  src/traces/waterfall/attributes.js
  test/image/baselines/period_positioning9.png
  test/image/mocks/period_positioning9.json
Labels: status: reviewable, type: documentation, type: feature

#5768 Fix downloading OpenSans fonts in image test
  .circleci/config.yml
  .circleci/download_google_fonts.py
  .circleci/fonts/truetype/googleFonts/.gitignore
  .circleci/fonts/truetype/googleFonts/OpenSans/OpenSans-Bold.ttf
  .circleci/fonts/truetype/googleFonts/OpenSans/OpenSans-BoldItalic.ttf
  .circleci/fonts/truetype/googleFonts/OpenSans/OpenSans-ExtraBold.ttf
  .circleci/fonts/truetype/googleFonts/OpenSans/OpenSans-ExtraBoldItalic.ttf
  .circleci/fonts/truetype/googleFonts/OpenSans/OpenSans-Italic.ttf
  .circleci/fonts/truetype/googleFonts/OpenSans/OpenSans-Light.ttf
  .circleci/fonts/truetype/googleFonts/OpenSans/OpenSans-LightItalic.ttf
  .circleci/fonts/truetype/googleFonts/OpenSans/OpenSans-Regular.ttf
  .circleci/fonts/truetype/googleFonts/OpenSans/OpenSans-Semibold.ttf
  .circleci/fonts/truetype/googleFonts/OpenSans/OpenSans-SemiboldItalic.ttf
Labels: type: maintenance

#5769 Provide Dosis font for image test
  .circleci/config.yml
  .circleci/download_google_fonts.py
  test/image/baselines/gl3d_indicator_scatter3d.png
  test/image/baselines/indicator_bignumber.png
  test/image/baselines/indicator_scatter.png
Labels: type: maintenance

#5772 rename flaky container
  .circleci/config.yml
  .circleci/test.sh
Labels: type: maintenance

#5773 decrease tolerance for flaky baselines namely mapbox
  test/image/compare_pixels_test.js
Labels: type: maintenance

#5774 Modify CircleCI config - remove extra dot pointing to current directory
  .circleci/config.yml
Labels: type: maintenance

#5775 Simplify makeSchema by returning the results
  tasks/bundle.js
  tasks/util/make_schema.js
Labels: type: maintenance

#5779 Improve README for ES6 module import
  README.md
Labels: type: community, type: documentation

#5781 increase compare tolerance for mapbox_geojson-attributes
  test/image/compare_pixels_test.js
Labels: type: maintenance

#5782 Add a compact script to help install kaleido and fonts in the docker
  .circleci/config.yml
  .circleci/env_image.sh
Labels: status: reviewable, type: maintenance

#5784 Improve baseline system and add test for emoji with color
  .circleci/env_image.sh
  test/image/baselines/worldcup.png
  test/image/mocks/worldcup.json
Labels: status: reviewable, type: maintenance

#5785 Disable progress bar of pip install to avoid undesirable log files
  .circleci/env_image.sh
Labels: type: maintenance

#5788 Speed up publishing dist on the CircleCI and testing bundles
  .circleci/config.yml
  .circleci/env_build.sh
Labels: type: maintenance

#5789 Reuse env_image script in export tests
  .circleci/config.yml
  test/image/make_exports.py
Labels: type: maintenance

#5786 use to-float32-v1.1.0 in regl scatter line error 2d packages
  package-lock.json
  package.json
Labels: status: reviewable, type: performance

#5112 Upgrade d3 geo projections
  package-lock.json
  package.json
  src/plots/geo/constants.js
  src/plots/geo/geo.js
  src/plots/geo/projections.js
  test/image/baselines/geo_fitbounds-locations.png
  test/image/baselines/geo_stereographic.png
  test/jasmine/tests/geo_test.js
Labels: status: reviewable, type: bug, type: maintenance
