Repository plotly/plotly.js, pull requests merged in 2021-10, with the labels that each got.

#5960 Do not coerce tick prefix suffix twice
  src/plots/cartesian/tick_label_defaults.js
Labels: type: maintenance

#5963 Separate file to handle prefix and suffix defaults
  src/components/colorbar/defaults.js
  src/plots/cartesian/axis_defaults.js
  src/plots/cartesian/prefix_suffix_defaults.js
  src/plots/cartesian/show_dflt.js
  src/plots/cartesian/tick_label_defaults.js
  src/plots/polar/layout_defaults.js
  src/plots/ternary/layout_defaults.js
  src/traces/carpet/axis_defaults.js
  src/traces/indicator/defaults.js
Labels: type: maintenance

#5964 Display prefix and suffix of invisible polar axes in hover
  draftlogs/5964_fix.md
  src/plots/polar/layout_defaults.js
  test/jasmine/tests/scatterpolar_test.js
Labels: type: bug

#5968 Migrating from eslint-v6 API to eslint-v7 API
  tasks/no_es6_dist.js
Labels: type: maintenance

#5958 Fix scatter3d opacity restyle bug
  draftlogs/5958_fix.md
  src/traces/scatter3d/attributes.js
  test/jasmine/tests/scatter3d_test.js
  test/plot-schema.json
Labels: type: bug, type: community, status: reviewable

#5969 Bump eslint to v8 release candidate including fixes for `no-new-func` test
  draftlogs/5969_change.md
  package-lock.json
  package.json
  test/jasmine/tests/choropleth_test.js
  test/jasmine/tests/mapbox_test.js
Labels: type: maintenance, status: reviewable

#5992 Adjust imaginary tickvals default to fix react
  draftlogs/5956_add.md
  src/plots/smith/layout_defaults.js
Labels: type: bug, status: reviewable
