Repository plotly/plotly.js, pull requests merged in 2021-05, with the labels that each got.

#5605 Fix the list of traces for publishing packages to npm
  tasks/sync_packages.js
  tasks/util/constants.js
Labels: status: reviewable, type: bug

#5626 Bump karma from v5 to v6
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#5627 Adjust splom test to run smoothly on the CircleCI
  test/jasmine/tests/splom_test.js
Labels: status: reviewable, type: maintenance

#5628 Bump various dev-dependencies - May 4
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#5632 Address scattergl performance issue with TypeArrays
  src/components/color/index.js
  src/traces/scattergl/calc.js
Labels: status: reviewable, type: community, type: performance

#5622 Fixup texttemplate on log axes
  src/components/drawing/index.js
  src/traces/bar/plot.js
  src/traces/scatter/format_labels.js
  test/jasmine/tests/bar_test.js
  test/jasmine/tests/scatter_test.js
Labels: status: reviewable, type: bug

#5633 Adjust parcoords tests and revise karma config
  test/jasmine/karma.conf.js
  test/jasmine/tests/parcoords_test.js
Labels: status: reviewable, type: maintenance

#5636 Bump karma dev-dependencies
  package-lock.json
  package.json
Labels: type: maintenance

#5637 simplify ensureNumber
  src/constants/numerical.js
  src/lib/index.js
Labels: status: reviewable, type: maintenance, type: performance

#5644 bump node-sass v6
  package-lock.json
  package.json
Labels: type: maintenance

#5645 skip pattern_bars mock validation
  test/jasmine/tests/mock_test.js
Labels: type: maintenance

#5604 using a more recent nodejs v12 and Chrome verisions on the CircleCI
  .circleci/config.yml
  tasks/noci_test.sh
  tasks/test_bundle.js
  test/jasmine/tests/shapes_test.js
Labels: status: reviewable, type: maintenance

#5646 Adjust some noCI gl tests and run them on CircleCI
  .circleci/test.sh
  test/jasmine/tests/gl3d_hover_click_test.js
  test/jasmine/tests/select_test.js
Labels: type: maintenance

#5649 bump postcss
  package-lock.json
Labels: type: maintenance

#5638 Revise textposition default for bar, histogram and waterfall
  src/traces/bar/attributes.js
  src/traces/funnel/attributes.js
  test/image/baselines/histogram-offsetgroups.png
  test/image/mocks/bar-autotext-log-size-axes.json
  test/image/mocks/bar-like_textangle45.json
  test/image/mocks/bar-like_textangle60.json
  test/image/mocks/bar-like_traces_tozero.json
  test/image/mocks/bar_display_height_zero.json
  test/image/mocks/bar_display_height_zero_no_line_width.json
  test/image/mocks/bar_display_height_zero_only_line_width.json
  test/image/mocks/bar_hide_nulls.json
  test/image/mocks/display-text_zero-number.json
  test/image/mocks/mathjax.json
  test/image/mocks/uniformtext_bar-like_10_auto.json
  test/image/mocks/uniformtext_bar-like_8_horizontal.json
  test/image/mocks/uniformtext_bar-like_8_textangle.json
  test/image/mocks/uniformtext_bar-like_8_textangle45.json
  test/image/mocks/uniformtext_bar_edgecase1.json
  test/image/mocks/uniformtext_bar_edgecase3.json
  test/image/mocks/uniformtext_bar_edgecase4.json
  test/image/mocks/uniformtext_bar_edgecase5.json
  test/image/mocks/uniformtext_bar_edgecase6.json
  test/image/mocks/uniformtext_bar_edgecase7.json
  test/image/mocks/uniformtext_bar_edgecase8.json
  test/image/mocks/waterfall_attrs.json
  test/image/mocks/waterfall_axis.json
  test/jasmine/tests/bar_test.js
  test/jasmine/tests/waterfall_test.js
Labels: Major change, status: reviewable

#5648 New spike defaults in plotly.js v2
  src/components/fx/layout_attributes.js
  src/components/fx/layout_defaults.js
  src/plots/cartesian/layout_attributes.js
  src/plots/cartesian/layout_defaults.js
  test/jasmine/tests/hover_spikeline_test.js
Labels: Major change, status: reviewable

#5653 Mock validation utility
  .circleci/config.yml
  package.json
  tasks/test_mock.js
  tasks/test_plain_obj.js
  test/image/README.md
  test/jasmine/tests/mock_test.js
Labels: type: documentation, type: maintenance

#5618 Fixup hover on period positioned points
  src/components/fx/hover.js
  src/traces/bar/hover.js
  test/jasmine/tests/hover_label_test.js
Labels: status: reviewable, type: bug

#5654 Hide hover and spike modebar buttons in plotly.js v2 by default and add config options to bring them back in
  src/components/modebar/manage.js
  test/jasmine/tests/gl3d_plot_interact_test.js
  test/jasmine/tests/modebar_test.js
  test/jasmine/tests/plot_api_test.js
Labels: Major change, status: reviewable

#5658 Document enabling predefined hidden modebar buttons via config.modeBarButtonsToAdd
  src/plot_api/plot_config.js
Labels: status: reviewable, type: documentation

#5657 Deprecate transform attributes
  src/components/calendars/index.js
  src/plots/attributes.js
Labels: Major change, status: reviewable, type: documentation

#5660 Enable & disable predefined modebar buttons via layout and template
  src/components/modebar/attributes.js
  src/components/modebar/buttons.js
  src/components/modebar/constants.js
  src/components/modebar/defaults.js
  src/components/modebar/index.js
  src/components/modebar/manage.js
  src/core.js
  src/plots/layout_attributes.js
  src/plots/plots.js
  test/jasmine/tests/modebar_test.js
Labels: status: reviewable, type: feature

#5662 Fixup and simplify bar hover min and max positions with period
  src/traces/bar/hover.js
Labels: status: reviewable, type: bug

#5664 Use an object to pass various optional arguments into hoverPoints methods of modules
  src/components/fx/hover.js
  src/traces/contour/hover.js
  src/traces/heatmap/hover.js
  src/traces/histogram2d/hover.js
  src/traces/violin/hover.js
Labels: type: maintenance

#5663 Set indentation for plot-schema to 1
  tasks/util/make_schema.js
Labels: status: reviewable, type: maintenance

#5665 Minor refactor in fx hover.js
  src/components/fx/hover.js
Labels: type: maintenance

#5666 Fix bar get color
  src/traces/bar/style.js
  test/image/baselines/bar-colorscale-colorbar.png
  test/image/mocks/bar-colorscale-colorbar.json
Labels: status: reviewable, type: bug

#5670 reorder black list in mock test and add comments
  tasks/test_mock.js
Labels: type: maintenance

#5671 Validate few more mocks
  tasks/test_mock.js
  test/image/mocks/2dhistogram_contour_subplots.json
  test/image/mocks/2dhistogram_contour_subplots_bingroup.json
  test/image/mocks/axes_category_ascending.json
  test/image/mocks/axes_category_descending.json
  test/image/mocks/axes_category_descending_with_gaps.json
  test/image/mocks/bar-alignment-offset.json
  test/image/mocks/box-alignment-offset.json
  test/image/mocks/funnel_11.json
  test/image/mocks/hist_cum_stacked.json
  test/image/mocks/waterfall_11.json
  test/image/mocks/world-cals.json
Labels: status: reviewable, type: maintenance

#5676 Provide latLon hover labels on scattermapbox and densitymapbox
  src/traces/densitymapbox/hover.js
  src/traces/scattermapbox/hover.js
  src/traces/scattermapbox/index.js
  test/jasmine/tests/densitymapbox_test.js
  test/jasmine/tests/scattermapbox_test.js
Labels: status: reviewable, type: bug

#5668 Fixup hover filters
  src/components/fx/hover.js
  src/traces/bar/hover.js
  src/traces/funnel/hover.js
  src/traces/histogram/hover.js
  src/traces/ohlc/hover.js
  src/traces/waterfall/hover.js
  test/jasmine/tests/bar_test.js
  test/jasmine/tests/funnel_test.js
  test/jasmine/tests/hover_label_test.js
  test/jasmine/tests/violin_test.js
  test/jasmine/tests/waterfall_test.js
Labels: status: reviewable, type: bug

#5684 Fixup hidden mathjax ticklabel
  src/plots/cartesian/axes.js
Labels: status: reviewable, type: bug

#5686 Fixup misinterpreted clip-path by some programs after export
  src/components/drawing/index.js
  test/jasmine/assets/custom_assertions.js
  test/jasmine/assets/get_bbox.js
  test/jasmine/tests/drawing_test.js
  test/jasmine/tests/layout_images_test.js
  test/jasmine/tests/plot_interact_test.js
  test/jasmine/tests/shapes_test.js
  test/jasmine/tests/toimage_test.js
Labels: status: reviewable, type: bug

#5682 Do not show Aa text in legends unless there is only text in the legend item
  src/components/legend/style.js
  test/image/baselines/cliponaxis_false-dates-log.png
  test/image/baselines/geo_africa-insets.png
  test/image/baselines/geo_legendonly.png
  test/image/baselines/gl2d_point-selection.png
  test/image/baselines/gl2d_text_chart_arrays.png
  test/image/baselines/gl2d_text_chart_invalid-arrays.png
  test/image/baselines/gl3d_scatter3d-align-texts.png
  test/image/baselines/gl3d_scatter3d-blank-text.png
  test/image/baselines/gl3d_scatter3d-texttemplate.png
  test/image/baselines/legend-constant-itemsizing.png
  test/image/baselines/mathjax.png
  test/image/baselines/point-selection.png
  test/image/baselines/scattercarpet-text.png
  test/image/baselines/text_chart_arrays.png
  test/image/baselines/text_chart_invalid-arrays.png
  test/image/baselines/texttemplate.png
  test/image/mocks/gl2d_text_chart_arrays.json
  test/image/mocks/gl2d_text_chart_invalid-arrays.json
  test/image/mocks/text_chart_arrays.json
  test/image/mocks/text_chart_invalid-arrays.json
  test/jasmine/tests/scatter_test.js
Labels: Major change, status: reviewable

#5692 Reinstall karma and bump jsdom to get ws 7.4.6 patch
  package-lock.json
  package.json
Labels: type: maintenance

#5694 Regenerate noci baselines
  test/image/baselines/legend_mathjax_title_and_items.png
  test/image/baselines/mapbox_0.png
  test/image/baselines/mapbox_angles.png
  test/image/baselines/mapbox_bubbles-text.png
  test/image/baselines/mapbox_bubbles.png
  test/image/baselines/mapbox_carto-style.png
  test/image/baselines/mapbox_choropleth-multiple.png
  test/image/baselines/mapbox_choropleth-raw-geojson.png
  test/image/baselines/mapbox_choropleth0-legend.png
  test/image/baselines/mapbox_choropleth0.png
  test/image/baselines/mapbox_connectgaps.png
  test/image/baselines/mapbox_custom-style.png
  test/image/baselines/mapbox_density-multiple.png
  test/image/baselines/mapbox_density-multiple_legend.png
  test/image/baselines/mapbox_density0-legend.png
  test/image/baselines/mapbox_density0.png
  test/image/baselines/mapbox_earthquake-density.png
  test/image/baselines/mapbox_fill.png
  test/image/baselines/mapbox_geojson-attributes.png
  test/image/baselines/mapbox_layers.png
  test/image/baselines/mapbox_osm-style.png
  test/image/baselines/mapbox_stamen-style.png
  test/image/baselines/mapbox_symbol-text.png
  test/image/baselines/mapbox_texttemplate.png
  test/image/baselines/mapbox_white-bg-style.png
Labels: type: maintenance
