Repository plotly/plotly.js, pull requests merged in 2021-01, with the labels that each got.

#5368 Bump some dev-dependencies Jan 4, 2021
  package-lock.json
  package.json
Labels: status: reviewable, type: maintenance

#5340 Return and handle promises in tests
  .circleci/test.sh
  test/jasmine/tests/animate_test.js
  test/jasmine/tests/annotations_test.js
  test/jasmine/tests/axes_test.js
  test/jasmine/tests/calcdata_test.js
  test/jasmine/tests/carpet_test.js
  test/jasmine/tests/cartesian_interact_test.js
  test/jasmine/tests/choropleth_test.js
  test/jasmine/tests/choroplethmapbox_test.js
  test/jasmine/tests/click_test.js
  test/jasmine/tests/command_test.js
  test/jasmine/tests/config_test.js
  test/jasmine/tests/contourgl_test.js
  test/jasmine/tests/densitymapbox_test.js
  test/jasmine/tests/draw_newshape_test.js
  test/jasmine/tests/errorbars_test.js
  test/jasmine/tests/funnelarea_test.js
  test/jasmine/tests/fx_test.js
  test/jasmine/tests/geo_test.js
  test/jasmine/tests/gl3d_hover_click_test.js
  test/jasmine/tests/gl3d_plot_interact_test.js
  test/jasmine/tests/histogram2d_test.js
  test/jasmine/tests/histogram_test.js
  test/jasmine/tests/hover_label_test.js
  test/jasmine/tests/layout_images_test.js
  test/jasmine/tests/legend_scroll_test.js
  test/jasmine/tests/legend_test.js
  test/jasmine/tests/lib_test.js
  test/jasmine/tests/mapbox_test.js
  test/jasmine/tests/modebar_test.js
  test/jasmine/tests/parcoords_test.js
  test/jasmine/tests/pie_test.js
  test/jasmine/tests/plot_api_react_test.js
  test/jasmine/tests/plot_api_test.js
  test/jasmine/tests/plot_interact_test.js
  test/jasmine/tests/plots_test.js
  test/jasmine/tests/polar_test.js
  test/jasmine/tests/range_selector_test.js
  test/jasmine/tests/sankey_test.js
  test/jasmine/tests/scatter3d_test.js
  test/jasmine/tests/scattergeo_test.js
  test/jasmine/tests/scattergl_test.js
  test/jasmine/tests/scattermapbox_test.js
  test/jasmine/tests/select_test.js
  test/jasmine/tests/shapes_test.js
  test/jasmine/tests/sliders_test.js
  test/jasmine/tests/snapshot_test.js
  test/jasmine/tests/sunburst_test.js
  test/jasmine/tests/table_test.js
  test/jasmine/tests/template_test.js
  test/jasmine/tests/ternary_test.js
  test/jasmine/tests/titles_test.js
  test/jasmine/tests/toimage_test.js
  test/jasmine/tests/transform_aggregate_test.js
  test/jasmine/tests/transform_filter_test.js
  test/jasmine/tests/transform_multi_test.js
  test/jasmine/tests/transition_test.js
  test/jasmine/tests/treemap_test.js
  test/jasmine/tests/updatemenus_test.js
Labels: status: reviewable, type: maintenance

#5371 reduce logs of domain_ref tests
  test/jasmine/assets/domain_ref/components.js
Labels: status: reviewable, type: maintenance

#5256 Correct wrong element targeting on hover in shadow DOM
  src/components/fx/hover.js
Labels: status: in progress, type: bug, type: community

#5376 Update docs to mention the dropped support for old browsers IE9 and IE10
  CHANGELOG.md
  devtools/test_dashboard/index.html
  dist/README.md
  tasks/stats.js
Labels: status: reviewable, type: documentation

#5379 Include transforms in partial bundles
  lib/index-basic.js
  lib/index-cartesian.js
  lib/index-finance.js
  lib/index-geo.js
  lib/index-gl2d.js
  lib/index-gl3d.js
  lib/index-mapbox.js
  tasks/util/common.js
Labels: status: reviewable, type: bug

#5383 Add publish test for avoiding function constructors in non-gl(2d|3d) partial bundles
  .circleci/config.yml
  package.json
Labels: status: reviewable, type: maintenance

#5354 Implement fast zsmooth option for image trace
  src/traces/image/attributes.js
  src/traces/image/constants.js
  src/traces/image/defaults.js
  src/traces/image/plot.js
Labels: status: reviewable, type: community, type: feature

#5387 Disable all inline config comments in no-new-func test
  package.json
Labels: status: reviewable, type: maintenance

#5388 Use probe-image-size module to read width and height of images
  package-lock.json
  package.json
  src/traces/image/helpers.js
  test/image/export_test.js
Labels: status: reviewable, type: bug

#5380 Cleanup unused IE9 and IE10 fallbacks
  src/lib/array.js
  src/lib/index.js
  src/lib/loggers.js
  src/snapshot/filesaver.js
  src/snapshot/svgtoimg.js
  src/snapshot/tosvg.js
  test/image/strict-d3.js
  test/jasmine/bundle_tests/ie9_test.js
  test/jasmine/karma.conf.js
  test/jasmine/tests/lib_test.js
Labels: status: reviewable, type: maintenance

#5389 Fixup image_viewer
  devtools/image_viewer/index.html
Labels: status: reviewable, type: maintenance

#5393 More newPlot calls in tests
  devtools/test_dashboard/devtools.js
  test/jasmine/assets/check_component.js
  test/jasmine/assets/check_event_data.js
  test/jasmine/assets/fail_test.js
  test/jasmine/bundle_tests/bar_test.js
  test/jasmine/bundle_tests/choropleth_test.js
  test/jasmine/bundle_tests/contour_test.js
  test/jasmine/bundle_tests/core_test.js
  test/jasmine/bundle_tests/finance_test.js
  test/jasmine/bundle_tests/histogram2dcontour_test.js
  test/jasmine/bundle_tests/mathjax_test.js
  test/jasmine/tests/contour_test.js
  test/jasmine/tests/geo_test.js
  test/jasmine/tests/gl2d_plot_interact_test.js
  test/jasmine/tests/gl3d_plot_interact_test.js
  test/jasmine/tests/heatmap_test.js
  test/jasmine/tests/legend_test.js
  test/jasmine/tests/localize_test.js
  test/jasmine/tests/mapbox_test.js
  test/jasmine/tests/parcoords_test.js
  test/jasmine/tests/plot_promise_test.js
Labels: status: reviewable, type: maintenance

#5386 Fix download image and add image test for images with source and fast zsmooth
  src/traces/image/plot.js
  test/image/baselines/image_source_axis_reverse_zsmooth.png
  test/image/mocks/image_source_axis_reverse_zsmooth.json
  test/jasmine/tests/image_test.js
  test/jasmine/tests/mock_test.js
Labels: status: reviewable, type: bug

#5399 Drop legacy polar
  src/plot_api/plot_api.js
  src/plot_api/plot_schema.js
  src/plots/plots.js
  src/plots/polar/legacy/area_attributes.js
  src/plots/polar/legacy/axis_attributes.js
  src/plots/polar/legacy/index.js
  src/plots/polar/legacy/micropolar.js
  src/plots/polar/legacy/micropolar_manager.js
  src/plots/polar/legacy/undo_manager.js
  src/registry.js
  src/snapshot/helpers.js
  src/traces/scatter/attributes.js
  test/image/baselines/6.png
  test/image/baselines/7.png
  test/image/baselines/8.png
  test/image/baselines/polar_area_chart.png
  test/image/mocks/6.json
  test/image/mocks/7.json
  test/image/mocks/8.json
  test/image/mocks/polar_area_chart.json
  test/jasmine/bundle_tests/plotschema_test.js
  test/jasmine/tests/mock_test.js
  test/jasmine/tests/polar_test.js
Labels: Major change, status: reviewable

#5406 Fixup strict d3 require in devtools
  devtools/image_viewer/viewer.js
  devtools/test_dashboard/devtools.js
Labels: type: bug

#5398 Drop contourgl and pointcloud traces from the code and API
  lib/contourgl.js
  lib/index-gl2d.js
  lib/index.js
  lib/pointcloud.js
  package-lock.json
  package.json
  src/components/images/draw.js
  src/components/modebar/manage.js
  src/plot_api/plot_schema.js
  src/plot_api/subroutines.js
  src/plots/cartesian/axes.js
  src/plots/cartesian/include_components.js
  src/plots/plots.js
  src/traces/contourgl/convert.js
  src/traces/contourgl/index.js
  src/traces/heatmap/make_bound_array.js
  src/traces/heatmap/xyz_defaults.js
  src/traces/pointcloud/attributes.js
  src/traces/pointcloud/convert.js
  src/traces/pointcloud/defaults.js
  src/traces/pointcloud/index.js
  test/image/baselines/gl2d_pointcloud-basic.png
  test/image/compare_pixels_test.js
  test/image/mocks/gl2d_pointcloud-basic.json
  test/jasmine/assets/mock_lists.js
  test/jasmine/bundle_tests/no_webgl_test.js
  test/jasmine/tests/contourgl_test.js
  test/jasmine/tests/gl2d_click_test.js
  test/jasmine/tests/mock_test.js
  test/jasmine/tests/modebar_test.js
  test/jasmine/tests/plot_api_react_test.js
  test/jasmine/tests/pointcloud_test.js
  test/jasmine/tests/transition_test.js
Labels: Major change, status: reviewable

#5408 Cleanup unused r and t attributes from bar
  src/traces/bar/attributes.js
Labels: status: reviewable, type: maintenance

#5409 No longer attach _has plot types to fullLayout
  src/plots/plots.js
Labels: Major change, status: reviewable, type: maintenance

#5411 Revise second condition in is_plain_object
  src/lib/is_plain_object.js
Labels: Major change, status: reviewable

#5412 Drop Plotly.plot from the API
  src/plot_api/edit_types.js
  src/plot_api/index.js
  src/plot_api/plot_api.js
  src/plot_api/plot_config.js
  src/plot_api/subroutines.js
  src/plot_api/to_image.js
  src/plots/mapbox/constants.js
  src/plots/plots.js
  src/snapshot/toimage.js
  tasks/util/container_commands.js
  test/jasmine/tests/parcoords_test.js
  test/jasmine/tests/plot_api_react_test.js
  test/jasmine/tests/plot_api_test.js
  test/jasmine/tests/plot_promise_test.js
  test/jasmine/tests/table_test.js
Labels: Major change, status: reviewable

#5414 Cleanup legacy polar framework
  src/lib/queue.js
  src/plot_api/plot_api.js
  src/plots/plots.js
  src/snapshot/cloneplot.js
  test/jasmine/tests/plot_promise_test.js
Labels: status: reviewable, type: maintenance

#5415 update comments about v2 changes that moved to another major
  src/components/annotations/click.js
  src/components/annotations/convert_coords.js
  src/components/colorscale/helpers.js
  src/components/images/convert_coords.js
  src/components/legend/defaults.js
  src/components/shapes/defaults.js
  src/components/shapes/helpers.js
  src/plot_api/plot_config.js
  src/plots/cartesian/helpers.js
  src/plots/cartesian/select.js
  src/plots/cartesian/set_convert.js
  src/plots/plots.js
  src/traces/splom/attributes.js
  test/jasmine/tests/axes_test.js
  test/jasmine/tests/histogram_test.js
  test/jasmine/tests/plot_api_test.js
  test/jasmine/tests/select_test.js
  test/jasmine/tests/shapes_test.js
Labels: status: reviewable, type: documentation, type: maintenance

#5419 Bump regl-scatter2d and regl-splom and maintain point-cluster at v3
  package-lock.json
  package.json
Labels: status: reviewable

#5413 Add strict partial bundles
  dist/plotly-strict.js
  dist/plotly-strict.min.js
  lib/index-strict.js
  tasks/stats.js
  tasks/util/constants.js
Labels: status: reviewable, type: feature

#5420 Drop various methods from Plotly.Fx and Plotly.Plots in the API
  src/core.js
  test/jasmine/bundle_tests/finance_test.js
  test/jasmine/tests/animate_test.js
  test/jasmine/tests/click_test.js
  test/jasmine/tests/command_test.js
  test/jasmine/tests/config_test.js
  test/jasmine/tests/transition_test.js
Labels: Major change, status: reviewable

#5423 Drop Plotly.Queue from the API
  src/core.js
  test/jasmine/tests/frame_api_test.js
  test/jasmine/tests/plot_api_test.js
Labels: Major change, status: in progress

#5424 Catch unexpected chars at build time
  .circleci/config.yml
  package.json
Labels: status: reviewable, type: maintenance

#5422 Include calendars in all bundles
  lib/index-basic.js
  lib/index-cartesian.js
  lib/index-finance.js
  lib/index-geo.js
  lib/index-gl2d.js
  lib/index-gl3d.js
  lib/index-mapbox.js
  lib/index-strict.js
  lib/index.js
  lib/register_extra.js
Labels: status: reviewable, type: bug

#5426 Improve compress_attributes browserify transform and fixup unexpected characters in bundles
  .circleci/config.yml
  lib/index-basic.js
  lib/index-cartesian.js
  lib/index-finance.js
  lib/index-geo.js
  lib/index-gl2d.js
  lib/index-gl3d.js
  lib/index-mapbox.js
  lib/index-strict.js
  lib/index.js
  lib/register_extra.js
  tasks/compress_attributes.js
Labels: status: reviewable, type: bug

#5427 Reinstall karma v5.2.3 to bump socket.io at v2.4.1
  package-lock.json
Labels: status: reviewable, type: maintenance

#5429 Leave no whitespace in compress_attributes when removing an attribute
  tasks/compress_attributes.js
Labels: status: reviewable, type: maintenance

#5430 Fixes indicator traces with a threshold equal to 0
  src/traces/indicator/plot.js
Labels: status: reviewable, type: bug

#5432 Bring back roles with value object
  src/plot_api/plot_schema.js
  tasks/compress_attributes.js
  test/jasmine/bundle_tests/plotschema_test.js
Labels: Major change, status: reviewable

#5439 Avoid redundant plotly.js copyright comments in bundles
  package.json
  tasks/compress_headers.js
Labels: status: reviewable, type: maintenance

#5438 Keep pointcloud trace type in v2 API
  lib/index-gl2d.js
  lib/index.js
  lib/pointcloud.js
  package-lock.json
  package.json
  src/components/images/draw.js
  src/components/modebar/manage.js
  src/plot_api/plot_schema.js
  src/plot_api/subroutines.js
  src/plots/cartesian/axes.js
  src/plots/cartesian/include_components.js
  src/plots/plots.js
  src/traces/heatmap/make_bound_array.js
  src/traces/pointcloud/attributes.js
  src/traces/pointcloud/convert.js
  src/traces/pointcloud/defaults.js
  src/traces/pointcloud/index.js
  test/image/baselines/gl2d_pointcloud-basic.png
  test/image/compare_pixels_test.js
  test/image/mocks/gl2d_pointcloud-basic.json
  test/jasmine/assets/mock_lists.js
  test/jasmine/bundle_tests/no_webgl_test.js
  test/jasmine/tests/gl2d_click_test.js
  test/jasmine/tests/mock_test.js
  test/jasmine/tests/modebar_test.js
  test/jasmine/tests/pointcloud_test.js
Labels: status: reviewable

#5444 Add scattergl traces to the strict bundle
  lib/index-strict.js
  package-lock.json
Labels: status: reviewable, type: feature

#5407 Fire unhover when dragging plot
  src/components/dragelement/index.js
  src/components/dragelement/unhover.js
  test/jasmine/tests/hover_label_test.js
Labels: status: reviewable, type: bug

#5436 Split header task into two tasks for dist and sources
  package.json
  tasks/header_dist.js
  tasks/header_src.js
Labels: status: reviewable, type: maintenance

#5449 Require unminified mapbox-gl for unminified bundles and improve compression of minified bundles
  src/plots/mapbox/index.js
  src/plots/mapbox/mapbox.js
  tasks/util/constants.js
Labels: status: reviewable

#5447 Add deprecated warnings for pointcloud and heatmapgl
  src/traces/heatmapgl/index.js
  src/traces/pointcloud/index.js
Labels: status: reviewable, type: documentation
