Repository plotly/plotly.js, pull requests merged in 2021-09, with the labels that each got.

#5917 bump node.js containers to v12.22.5
  .circleci/config.yml
  test/jasmine/tests/bar_test.js
  test/jasmine/tests/funnel_test.js
  test/jasmine/tests/waterfall_test.js
Labels: type: maintenance

#5888 Include gl3d in strict bundle
  draftlogs/5888_add.md
  lib/index-strict.js
  package-lock.json
  package.json
  tasks/util/constants.js
Labels: type: feature, status: reviewable

#5919 Use node.js v14 in tests and publishing
  .circleci/config.yml
  draftlogs/5919_change.md
  package.json
Labels: type: maintenance, status: reviewable

#5916 Adjust position of hover in respect to CSS transform
  draftlogs/5916_fix.md
  src/components/fx/hover.js
Labels: type: bug, status: reviewable

#5922 Use npm v7 and node.js 16 in development and testing
  .circleci/config.yml
  .circleci/env_build.sh
  draftlogs/5919_change.md
  package-lock.json
  package.json
  test/jasmine/tests/cartesian_interact_test.js
  test/jasmine/tests/pie_test.js
Labels: type: bug, type: maintenance, status: reviewable

#5924 run no-new-func test on gl3d bundles as well
  package.json
Labels: type: maintenance

#5928 use 3d-view v2.0.1
  package-lock.json
  package.json
Labels: type: maintenance

#5930 Bump regl-line2d and regl-scatter2d
  package-lock.json
  package.json
Labels: type: maintenance

#5934 Reduce bundle size by removing unused code from surface-nets module
  package-lock.json
  package.json
Labels: type: maintenance

#5935 Reduce bundle size by removing unused code from robust-determinant module
  package-lock.json
  package.json
Labels: type: maintenance, type: performance

#5936 Reduce bundle size by removing unused code from robust-linear-solve module
  package-lock.json
  package.json
Labels: type: maintenance, type: performance

#5933 Update outdated Prerequisites
  CONTRIBUTING.md
Labels: type: community, type: maintenance, type: documentation

#5939 bump regl-scatter2d v3.2.8
  package-lock.json
  package.json
Labels: type: maintenance

#5940 Bump gl-text module with simplified shader programs
  package-lock.json
  package.json
Labels: type: maintenance

#5941 bump gl-text to v1.3.1
  package-lock.json
  package.json
Labels: type: maintenance

#5937 Use node v16 in appveyor config
  appveyor.yml
Labels: type: maintenance, status: reviewable

#5948 Migrate most of legacy `circleci` images to new `cimg`
  .circleci/config.yml
Labels: type: maintenance, type: performance

#5947 Drop duplicate set scale call it polar
  src/plots/polar/polar.js
Labels: status: reviewable, type: performance

#5615 Add a basic smith chart
  lib/index.js
  lib/scattersmith.js
  src/plot_api/plot_api.js
  src/plots/smith/constants.js
  src/plots/smith/index.js
  src/plots/smith/layout_attributes.js
  src/plots/smith/layout_defaults.js
  src/plots/smith/set_convert.js
  src/plots/smith/smith.js
  src/traces/scattersmith/attributes.js
  src/traces/scattersmith/calc.js
  src/traces/scattersmith/defaults.js
  src/traces/scattersmith/format_labels.js
  src/traces/scattersmith/hover.js
  src/traces/scattersmith/index.js
  src/traces/scattersmith/plot.js
  test/image/baselines/zzz_smith_axes.png
  test/image/baselines/zzz_smith_basic.png
  test/image/baselines/zzz_smith_fill.png
  test/image/baselines/zzz_smith_gaps.png
  test/image/baselines/zzz_smith_line.png
  test/image/baselines/zzz_smith_single.png
  test/image/mocks/zzz_smith_axes.json
  test/image/mocks/zzz_smith_basic.json
  test/image/mocks/zzz_smith_fill.json
  test/image/mocks/zzz_smith_gaps.json
  test/image/mocks/zzz_smith_line.json
  test/image/mocks/zzz_smith_single.json
  test/jasmine/assets/mock_lists.js
  test/jasmine/bundle_tests/plotschema_test.js
  test/jasmine/tests/plot_api_react_test.js
  test/jasmine/tests/scattersmith_test.js
  test/jasmine/tests/select_test.js
  test/jasmine/tests/smith_test.js
  test/plot-schema.json
Labels: status: has TODOs, type: new trace type
