Repository plotly/plotly.js, pull requests merged in 2021-07, with the labels that each got.

#5804 fix mapbox_geojson-attributes mock & baseline
  test/image/baselines/mapbox_geojson-attributes.png
  test/image/mocks/mapbox_geojson-attributes.json
Labels: type: maintenance

#5780 Commit PR notes to draftlogs and add scripts to provide draft release notes (CHANGELOG.md) and empty draftlogs
  .github/PULL_REQUEST_TEMPLATE.md
  draftlogs/5779_fix.md
  draftlogs/README.md
  package.json
  tasks/empty_dist.js
  tasks/empty_draftlogs.js
  tasks/use_draftlogs.js
  tasks/util/constants.js
  tasks/util/make_empty_directory.js
Labels: status: reviewable, type: documentation, type: feature

#5792 improve CONTRIBUTING guidelines for creating & updating baselines
  .circleci/env_image.sh
  CONTRIBUTING.md
Labels: status: reviewable, type: documentation

#5776 Sort plot-schema and add test to track plot-schema changes
  .circleci/config.yml
  CONTRIBUTING.md
  draftlogs/5776_change.md
  package.json
  tasks/bundle.js
  tasks/schema.js
  tasks/util/constants.js
  tasks/util/make_schema.js
  tasks/util/watchified_bundle.js
  test/plot-schema.json
Labels: status: reviewable, type: documentation, type: feature

#5806 Add draft logs for merged PRs since 2.2.1
  draftlogs/5112_change.md
  draftlogs/5786_change.md
  draftlogs/5792_change.md
  draftlogs/5804_fix.md
Labels: type: documentation, type: maintenance

#5808 Preview CHANGELOG when building dist on master
  .circleci/config.yml
  draftlogs/5808_add.md
Labels: type: documentation, type: feature

#5814 Preview plot-schema changes between previous and next release when building dist on master
  .circleci/config.yml
  draftlogs/5814_add.md
Labels: type: documentation, type: feature

#5815 Label draft bundles and show package.json diff between versions when publishing dist artifacts on CircleCI
  .circleci/config.yml
  draftlogs/5815_change.md
Labels: status: reviewable, type: documentation

#5818 Adjust links to time format options so that they point to the d3-time-format v2.2.3 applied not the latest
  draftlogs/5818_fix.md
  src/constants/docs.js
  test/plot-schema.json
Labels: type: bug, type: documentation

#5820 Add jasmine tests in respect to current `d3.format` options
  src/lib/index.js
  test/jasmine/tests/lib_number_format_test.js
Labels: type: documentation, type: maintenance

#5825 adjust comparison tolerance for some flaky mapbox mocks
  test/image/compare_pixels_test.js
Labels: type: maintenance

#5826 Replace `d3.interpolate` method with `d3-interpolate` module in `icicle`, `indicator`, `parcats`, `sunburst` and `treemap`
  draftlogs/5826_change.md
  src/traces/indicator/plot.js
  src/traces/parcats/parcats.js
  src/traces/sunburst/plot.js
  src/traces/treemap/plot_one.js
Labels: status: reviewable, type: maintenance

#5334 Add clustering to scattermapbox
  src/traces/scattermapbox/attributes.js
  src/traces/scattermapbox/convert.js
  src/traces/scattermapbox/defaults.js
  src/traces/scattermapbox/hover.js
  src/traces/scattermapbox/plot.js
  test/image/baselines/mapbox_scattercluster.png
  test/image/mocks/mapbox_scattercluster.json
  test/jasmine/tests/mock_test.js
  test/jasmine/tests/scattermapbox_test.js
Labels: status: has TODOs, type: community, type: feature

#5791 improve CONTRIBUTING and describe how to clone from your fork
  CONTRIBUTING.md
  draftlogs/5791_change.md
Labels: status: reviewable, type: documentation

#5813 Sort object key values in schema
  draftlogs/5813_change.md
  src/components/calendars/index.js
  src/components/colorscale/attributes.js
  src/lib/index.js
  src/lib/sort_object_keys.js
  src/plots/geo/layout_attributes.js
  src/plots/mapbox/constants.js
  src/traces/scatter3d/attributes.js
  src/traces/scattergl/attributes.js
  test/plot-schema.json
Labels: status: reviewable, type: documentation

#5831 Drop Dosis font from image test
  .circleci/download_google_fonts.py
  test/image/baselines/gl3d_indicator_scatter3d.png
  test/image/baselines/indicator_bignumber.png
  test/image/baselines/indicator_scatter.png
  test/image/mocks/gl3d_indicator_scatter3d.json
  test/image/mocks/indicator_bignumber.json
  test/image/mocks/indicator_scatter.json
Labels: type: maintenance

#5673 Fixup parcoords constraintrange valType and validate parcoords mocks
  draftlogs/5673_change.md
  src/traces/parcoords/attributes.js
  tasks/test_mock.js
  test/image/mocks/gl2d_parcoords_out-of-range_selected-all.json
  test/plot-schema.json
Labels: status: reviewable, type: bug

#5771 Allow clickable legend group titles when group has no pie-like traces
  draftlogs/5771_fix.md
  src/components/legend/get_legend_data.js
  src/components/legend/handle_click.js
Labels: status: reviewable, type: bug

#5125 Add new formatting options by replacing `d3.format` method with more recent `d3-format` module
  draftlogs/5615_add.md
  package-lock.json
  package.json
  src/components/drawing/index.js
  src/components/rangeselector/get_update_object.js
  src/constants/docs.js
  src/lib/index.js
  src/plots/cartesian/dragbox.js
  src/plots/cartesian/set_convert.js
  src/plots/geo/geo.js
  src/plots/plots.js
  src/traces/parcoords/parcoords.js
  src/traces/sankey/plot.js
  src/traces/table/plot.js
  test/image/baselines/indicator_bignumber.png
  test/image/baselines/tick-percent.png
  test/jasmine/tests/lib_number_format_test.js
  test/plot-schema.json
Labels: status: reviewable, type: bug, type: feature

#5832 Simplify devtool by relying on XMLHttpRequest instead of varying d3.json function
  devtools/test_dashboard/devtools.js
  draftlogs/5832_change.md
Labels: status: reviewable, type: maintenance

#5835 Avoid unexpected character in partial bundles
  package.json
  tasks/bundle.js
  tasks/locales.js
Labels: type: maintenance

#5837 increase compare tolerance for mapbox_layers mock
  test/image/compare_pixels_test.js
Labels: type: maintenance

#5609 Fix Safari Download
  src/snapshot/filesaver.js
Labels: status: has TODOs, type: bug, type: community

#5839 bump some dev dependencies
  package-lock.json
  package.json
Labels: type: maintenance

#5838 Fix unknown filename when exporting charts using new versions of Safari
  draftlogs/5838_fix.md
  src/snapshot/filesaver.js
  test/jasmine/tests/download_test.js
Labels: status: reviewable, type: bug, type: community

#5836 Fix scatter and scattergl hover on axes with period and adjust the unified hover position in respect to mean
  draftlogs/5836_fix.md
  src/components/fx/hover.js
  src/traces/scatter/calc.js
  src/traces/scatter/hover.js
  src/traces/scattergl/hover.js
  test/jasmine/tests/gl2d_click_test.js
  test/jasmine/tests/hover_label_test.js
Labels: status: reviewable, type: bug

#5843 Revert " Fix scatter and scattergl hover on axes with period and adjust the unified hover position in respect to mean"
  draftlogs/5836_fix.md
  src/components/fx/hover.js
  src/traces/scatter/calc.js
  src/traces/scatter/hover.js
  src/traces/scattergl/hover.js
  test/jasmine/tests/gl2d_click_test.js
  test/jasmine/tests/hover_label_test.js
Labels: type: regression

#5845 Position hover in respect to the average of values in (x|y) unified modes
  draftlogs/5845_fix.md
  src/components/fx/hover.js
Labels: type: bug, type: regression

#5842 Add tests for padding and alignment without formatting numbers
  test/jasmine/tests/lib_number_format_test.js
Labels: status: reviewable, type: documentation, type: maintenance

#5846 Fix hover with period alignment points and improve positioning of spikes and unified hover label
  draftlogs/5846_fix.md
  src/components/fx/hover.js
  src/plots/cartesian/align_period.js
  src/traces/bar/calc.js
  src/traces/bar/cross_trace_calc.js
  src/traces/bar/hover.js
  src/traces/box/calc.js
  src/traces/candlestick/calc.js
  src/traces/funnel/calc.js
  src/traces/heatmap/calc.js
  src/traces/heatmap/convert_column_xyz.js
  src/traces/ohlc/calc.js
  src/traces/scatter/calc.js
  src/traces/scatter/hover.js
  src/traces/scattergl/calc.js
  src/traces/scattergl/hover.js
  src/traces/waterfall/calc.js
  test/jasmine/tests/hover_label_test.js
  test/jasmine/tests/hover_spikeline_test.js
Labels: status: reviewable, type: bug

#5857 Changelog edits after v2.3.0
  CHANGELOG.md
Labels: type: documentation

#5859 change trace names in hover label test when all have end alignments
  test/jasmine/tests/hover_label_test.js
Labels: type: maintenance

#5860 Revisit setting timezone on CircleCI
  .circleci/config.yml
  .circleci/test.sh
Labels: type: maintenance

#5862 move up bundle-jasmine in config below other jasmine tests
  .circleci/config.yml
Labels: type: maintenance

#5863 use CircleCI environment TZ to set timezone
  .circleci/config.yml
  .circleci/test.sh
Labels: type: maintenance

#5864 Fix period positioned hover to work in different time zones as well as on grouped bars
  .circleci/config.yml
  draftlogs/5864_fix.md
  src/components/fx/hover.js
  src/traces/bar/calc.js
  src/traces/bar/cross_trace_calc.js
  src/traces/bar/hover.js
  src/traces/funnel/calc.js
  src/traces/scatter/hover.js
  src/traces/scattergl/hover.js
  src/traces/waterfall/calc.js
  test/jasmine/tests/hover_label_test.js
Labels: status: reviewable, type: bug

#5852 Use ids from axes instead of [object Object] in hover data key
  draftlogs/5852_fix.md
  src/components/fx/hover.js
Labels: status: reviewable, type: bug

#5865 Excluding regl based traces from the strict bundle
  devtools/test_dashboard/index-strict.html
  devtools/test_dashboard/server.js
  draftlogs/5865_fix.md
  lib/index-strict.js
  package.json
  tasks/util/constants.js
  tasks/util/watchified_bundle.js
  tasks/watch.js
Labels: status: reviewable, type: bug

#5868 Propose fixing eslint module to catch calls to Function.apply
  draftlogs/5868_fix.md
  package-lock.json
  package.json
Labels: status: reviewable, type: bug

#5869 Utility to display location and number of function constructors in plotly.js source
  .circleci/config.yml
  package.json
  tasks/show_eval_lines.sh
Labels: status: reviewable, type: maintenance
