Repository plotly/plotly.js, pull requests merged in 2022-01, with the labels that each got.

#6079 bump follow-redirects to v1.14.7
  package-lock.json
Labels: type: maintenance

#6080 bump socket.io to use engine.io v6.1.1
  package-lock.json
Labels: type: maintenance

#6077 Display the version of plotly.js when hovering over the modebar
  draftlogs/6077_change.md
  lib/locales/cs.js
  lib/locales/cy.js
  lib/locales/de.js
  lib/locales/es.js
  lib/locales/fi.js
  lib/locales/fr.js
  lib/locales/it.js
  lib/locales/ja.js
  lib/locales/ko.js
  lib/locales/pt-br.js
  lib/locales/pt-pt.js
  lib/locales/ru.js
  lib/locales/sv.js
  lib/locales/sw.js
  lib/locales/uk.js
  lib/locales/zh-cn.js
  src/components/modebar/modebar.js
Labels: status: reviewable

#6090 Address `log4js` audit warning
  package-lock.json
  package.json
Labels: type: maintenance

#6092 `nanoid` package audit fix
  package-lock.json
Labels: type: maintenance

#6095 Bump some dev dependencies
  package-lock.json
  package.json
Labels: type: maintenance

#6097 bump cached-path-relative 1.1.0
  package-lock.json
Labels: type: maintenance

#6096 devtools/test_dashboard: tweak ES6 import
  devtools/test_dashboard/index.html
Labels: type: documentation
