Repository plotly/plotly.js, pull requests merged in 2022-02, with the labels that each got.

#6094 Fix vertical spacing of legend items in horizontal mode
  draftlogs/6094_fix.md
  src/components/legend/draw.js
  test/image/baselines/z-legend-row-group-height.png
  test/image/mocks/z-legend-row-group-height.json
Labels: type: bug, status: reviewable

#6088 Implement `ticklabelstep` on 2D axes & colorbars
  draftlogs/6088_add.md
  src/components/colorbar/attributes.js
  src/components/colorbar/draw.js
  src/plots/cartesian/axes.js
  src/plots/cartesian/layout_attributes.js
  src/plots/cartesian/tick_label_defaults.js
  src/plots/gl3d/layout/axis_defaults.js
  src/plots/polar/layout_attributes.js
  src/plots/smith/layout_defaults.js
  src/plots/ternary/layout_attributes.js
  src/traces/carpet/ab_defaults.js
  src/traces/indicator/attributes.js
  test/image/baselines/h-colorbar05.png
  test/image/baselines/indicator_attrs.png
  test/image/baselines/period_positioning7.png
  test/image/baselines/polar_ticks.png
  test/image/baselines/ternary_array_styles.png
  test/image/baselines/z-date_axes-ticklabelstep.png
  test/image/mocks/h-colorbar05.json
  test/image/mocks/indicator_attrs.json
  test/image/mocks/period_positioning7.json
  test/image/mocks/polar_ticks.json
  test/image/mocks/ternary_array_styles.json
  test/image/mocks/z-date_axes-ticklabelstep.json
  test/plot-schema.json
Labels: type: feature, status: reviewable

#6107 bump simple-get to v3.1.1
  package-lock.json
Labels: type: maintenance

#6109 Depend on the latest `probe-image-size` module v7.2.3
  package-lock.json
  package.json
Labels: type: bug, type: maintenance

#6110 Bump some of the dev dependencies on Feb 4, 2022
  package-lock.json
  package.json
Labels: type: maintenance

#6111 Address `ansi-regex` audit warnings
  package-lock.json
Labels: type: maintenance

#6113 bump karma to v6.3.16
  package-lock.json
  package.json
Labels: type: maintenance

#6115 bump follow-redirects to 1.14.8
  package-lock.json
Labels: type: maintenance

#6101 Add pattern fill for scatter filled area
  draftlogs/6101_add.md
  src/components/drawing/index.js
  src/components/legend/style.js
  src/snapshot/tosvg.js
  src/traces/scatter/attributes.js
  src/traces/scatter/defaults.js
  src/traces/scatter/plot.js
  src/traces/scatter/style.js
  test/image/baselines/z-scatter_fill_pattern.png
  test/image/mocks/z-scatter_fill_pattern.json
  test/plot-schema.json
Labels: type: feature, type: community, status: reviewable
