Repository plotly/plotly.js, pull requests merged in 2022-07, with the labels that each got.

#6236 use middle gray instead of 777 for default `parcoords` unselected line color
  src/traces/parcoords/attributes.js
  test/image/baselines/gl2d_parcoords.png
  test/image/baselines/gl2d_parcoords_2.png
  test/image/baselines/gl2d_parcoords_60_dims.png
  test/image/baselines/gl2d_parcoords_blocks.png
  test/image/baselines/gl2d_parcoords_coloraxis.png
  test/image/baselines/gl2d_parcoords_dark_background.png
  test/image/baselines/gl2d_parcoords_large.png
  test/image/baselines/gl2d_parcoords_out-of-range_selected-above-below.png
  test/image/baselines/gl2d_parcoords_out-of-range_selected-all.png
  test/image/baselines/gl2d_parcoords_out-of-range_selected-below.png
  test/image/baselines/gl2d_parcoords_out-of-range_selected-none.png
  test/image/baselines/gl2d_parcoords_rgba_colorscale.png
  test/image/baselines/gl2d_parcoords_select_first_last_enum.png
  test/image/baselines/gl2d_parcoords_style_labels.png
  test/image/baselines/gl2d_parcoords_tick_format.png
  test/plot-schema.json
Labels: type: bug, status: reviewable

#6246 add `delta.prefix` and `delta.suffix` in Indicator trace
  draftlogs/6246_add.md
  src/traces/indicator/attributes.js
  src/traces/indicator/defaults.js
  src/traces/indicator/plot.js
  test/image/mocks/indicator_scatter.json
Labels: type: feature, type: community, status: reviewable

#6250 Bump dev dependencies - July 5, 2022
  package-lock.json
  package.json
Labels: type: maintenance

#6238 Add si locale for Sinhala language
  draftlogs/6238_add.md
  lib/locales/si.js
Labels: type: community, status: has TODOs, status: reviewable, type: translation

#6247 Update zh-tw.js
  draftlogs/6238_add.md
  draftlogs/6247_add.md
  lib/locales/zh-tw.js
Labels: type: community, status: reviewable, type: translation

#6258 Fix `mapbox` shift select regression
  src/components/selections/select.js
  src/plots/geo/geo.js
  src/plots/mapbox/mapbox.js
Labels: type: bug

#6260 Avoid attaching selections to missing eventData
  draftlogs/6260_fix.md
  src/components/selections/select.js
Labels: type: bug, status: reviewable, type: regression

#6267 Handle missing drag layer of invisible `sankey` traces to fix select error
  draftlogs/6267_fix.md
  src/traces/sankey/base_plot.js
Labels: type: bug, status: reviewable

#6262 Emit selection events in drawmode when an existing selection modified
  draftlogs/6262_fix.md
  src/components/selections/select.js
  test/jasmine/tests/draw_newselection_test.js
Labels: type: bug, status: reviewable

#6274 bump terser 4.8.1
  package-lock.json
Labels: type: maintenance

#6277 emit `plotly_selected` event on plot API calls and GUI edits
  src/components/selections/select.js
  src/plots/plots.js
  test/jasmine/tests/draw_newselection_test.js
  test/jasmine/tests/selections_test.js
Labels: type: bug, status: reviewable
