Repository plotly/plotly.js, pull requests merged in 2023-04, with the labels that each got.

#6557 Add --strict option to custom bundle
  CUSTOM_BUNDLE.md
  draftlogs/6557_add.md
  tasks/custom_bundle.js
  tasks/partial_bundle.js
  tasks/util/constants.js
Labels: type: feature, type: community, status: reviewable

#6527 Add `texttemplate` attribute to `shape.label`
  src/components/shapes/attributes.js
  src/components/shapes/defaults.js
  src/components/shapes/draw.js
  src/components/shapes/draw_newshape/attributes.js
  src/components/shapes/draw_newshape/defaults.js
  src/components/shapes/label_texttemplate.js
  src/lib/index.js
  src/plots/template_attributes.js
  test/image/baselines/zz-text_on_shapes_texttemplate.png
  test/image/mocks/zz-text_on_shapes_texttemplate.json
  test/plot-schema.json
Labels: type: feature, status: reviewable

#6565 Fix heatmap rendering when zsmooth=fast
  draftlogs/6565_fix.md
  src/traces/heatmap/plot.js
  test/image/baselines/zz-heatmap_small_layout_zsmooth_fast.png
  test/image/mocks/zz-heatmap_small_layout_zsmooth_fast.json
  test/jasmine/tests/heatmap_test.js
Labels: type: bug, type: community, status: reviewable

#6555 fix-6507 fixed colorbar.showticklabels: false
  src/components/colorbar/defaults.js
Labels: type: bug, status: reviewable

#6572 Rename new mocks 2.21.0
  test/image/baselines/heatmap_small_layout_zsmooth_fast.png
  test/image/baselines/text_on_shapes_texttemplate.png
  test/image/baselines/treemap_textfit.png
  test/image/baselines/treemap_textposition.png
  test/image/baselines/uniformtext_bar_edgecase1.png
  test/image/baselines/uniformtext_sunburst_treemap.png
  test/image/mocks/heatmap_small_layout_zsmooth_fast.json
  test/image/mocks/text_on_shapes_texttemplate.json
  test/jasmine/tests/heatmap_test.js
Labels: type: maintenance

#6563 added tabletmode to fire plotly_click event for mobile devices.
  draftlogs/6563_fix.md
  src/plots/gl3d/scene.js
Labels: type: bug, type: community, status: reviewable

#6535 Draw multiple legends on a graph
  draftlogs/6535_add.md
  src/components/legend/attributes.js
  src/components/legend/defaults.js
  src/components/legend/draw.js
  src/components/legend/get_legend_data.js
  src/plots/attributes.js
  src/plots/plots.js
  src/traces/parcats/attributes.js
  test/image/baselines/zz-multi-legends.png
  test/image/mocks/zz-multi-legends.json
  test/jasmine/bundle_tests/plotschema_test.js
  test/jasmine/tests/legend_test.js
  test/plot-schema.json
Labels: type: feature, status: reviewable

#5410 Update locale no with new dictionary and number formats
  lib/locales/no.js
Labels: type: community, status: reviewable, type: translation

#6581 #6571 fix scatter3d marker opacity when marker.opacity is set to 0
  draftlogs/6581_fix.md
  src/traces/scatter3d/convert.js
  test/jasmine/tests/scatter3d_test.js
Labels: type: bug, type: community, status: reviewable
