Repository plotly/plotly.js, pull requests merged in 2023-05, with the labels that each got.

#6574 Improve heatmap rendering performance when `zsmooth` is false
  draftlogs/6574_change.md
  src/constants/pixelated_image.js
  src/lib/supports_pixelated_image.js
  src/traces/heatmap/calc.js
  src/traces/heatmap/plot.js
  src/traces/image/constants.js
  src/traces/image/plot.js
  tasks/test_syntax.js
  test/image/baselines/cmid-zmid.png
  test/image/baselines/dendrogram.png
  test/image/baselines/heatmap_multicategory.png
  test/image/baselines/histogram2d_bingroup-coloraxis.png
  test/image/baselines/updatemenus.png
  test/jasmine/tests/heatmap_test.js
Labels: type: community, status: reviewable, type: performance

#6593 Add `xref` and `yref` to colorbars
  draftlogs/6593_add.md
  src/components/colorbar/attributes.js
  src/components/colorbar/defaults.js
  src/components/colorbar/draw.js
  test/image/baselines/zz-container-colorbar-horizontal.png
  test/image/baselines/zz-container-colorbar-vertical.png
  test/image/mocks/zz-container-colorbar-horizontal.json
  test/image/mocks/zz-container-colorbar-vertical.json
  test/plot-schema.json
Labels: type: feature, status: reviewable

#6589 Add `xref` and `yref` to legends
  draftlogs/6589_add.md
  src/components/legend/attributes.js
  src/components/legend/defaults.js
  src/components/legend/draw.js
  test/image/baselines/zz-container-legend.png
  test/image/mocks/zz-container-legend.json
  test/plot-schema.json
Labels: type: feature, status: reviewable

#6501 [Documentation] Clarify x0,y0 in image trace
  src/traces/image/attributes.js
  test/plot-schema.json
Labels: type: community, type: documentation

#6602 Dev deps 2023 05 12
  package-lock.json
  package.json
Labels: type: maintenance

#6603 Rename new mocks 2023 05 12
  test/image/baselines/container-colorbar-horizontal.png
  test/image/baselines/container-colorbar-vertical.png
  test/image/baselines/container-legend.png
  test/image/baselines/multi-legends.png
  test/image/baselines/pattern_bars.png
  test/image/baselines/pattern_fgcolor_overlay_fillmode.png
  test/image/baselines/sunburst_inside-text-orientation.png
  test/image/baselines/sunburst_packages_colorscale_novalue.png
  test/image/baselines/treemap_sunburst_marker_colors.png
  test/image/baselines/treemap_textfit.png
  test/image/baselines/uniformtext_bar_edgecase1.png
  test/image/mocks/container-colorbar-horizontal.json
  test/image/mocks/container-colorbar-vertical.json
  test/image/mocks/container-legend.json
  test/image/mocks/multi-legends.json
Labels: type: maintenance

#6605 Fix heatmap/image traces without zsmooth on Safari/iOS
  draftlogs/6605_fix.md
  src/lib/supports_pixelated_image.js
Labels: type: bug, type: community, status: reviewable, type: regression

#6607 fix bar and waterfall orientation descriptions
  src/traces/bar/index.js
  src/traces/barpolar/index.js
  src/traces/waterfall/index.js
  test/plot-schema.json
Labels: type: documentation

#6608 Render shape label while drawing
  src/components/selections/select.js
  src/components/shapes/display_labels.js
  src/components/shapes/display_outlines.js
  src/components/shapes/draw.js
  src/components/shapes/draw_newshape/newshapes.js
Labels: type: bug, type: feature, status: has TODOs, status: reviewable

#6610 new mapbox token for testing
  tasks/noci_test.sh
  tasks/util/constants.js
  test/image/compare_pixels_test.js
  test/image/make_baseline.py
  test/jasmine/tests/mapbox_test.js
Labels: type: maintenance

#6615 Fix for #6614
  draftlogs/6615_fix.md
  src/components/fx/hover.js
  test/jasmine/tests/hover_label_test.js
Labels: type: bug, type: community, status: reviewable, type: regression

#6601 pie : add Pattern
  draftlogs/6601_add.md
  src/components/drawing/index.js
  src/components/legend/style.js
  src/traces/pie/attributes.js
  src/traces/pie/defaults.js
  src/traces/pie/style.js
  src/traces/pie/style_one.js
  test/image/baselines/zz-pie_pattern.png
  test/image/mocks/zz-pie_pattern.json
  test/plot-schema.json
Labels: type: feature, type: community, status: reviewable

#6619 add pattern to `funnelarea`
  draftlogs/6601_add.md
  src/traces/funnelarea/attributes.js
  src/traces/funnelarea/defaults.js
  src/traces/funnelarea/style.js
  src/traces/pie/defaults.js
  test/image/baselines/zz-pie_pattern.png
  test/image/mocks/zz-pie_pattern.json
  test/plot-schema.json
Labels: type: feature

#6620 bump socket.io-parser
  package-lock.json
Labels: type: maintenance
