Repository plotly/plotly.js, pull requests merged in 2023-01, with the labels that each got.

#6423 Ensure `jasmine-core` v3.5.0 is installed
  package-lock.json
  package.json
Labels: type: maintenance

#6424 pin `jasmine` version for npm v8 users
  package-lock.json
  package.json
Labels: type: maintenance

#6433 Bump required npm version from 7 to 8
  package.json
Labels: type: maintenance

#6434 bump dockers to `cimg` node 16.17.1
  .circleci/config.yml
Labels: type: maintenance

#6356 Add sync option to `tickmode` of cartesian axes to sync ticks with `overlaying` axis
  draftlogs/6356_add.md
  src/components/colorbar/attributes.js
  src/plots/cartesian/axes.js
  src/plots/cartesian/dragbox.js
  src/plots/cartesian/layout_attributes.js
  src/plots/cartesian/position_defaults.js
  src/plots/cartesian/tick_value_defaults.js
  src/plots/gl3d/layout/axis_attributes.js
  src/plots/polar/layout_attributes.js
  src/plots/ternary/layout_attributes.js
  src/traces/indicator/attributes.js
  test/image/baselines/z-new_tickmode_sync.png
  test/image/mocks/z-new_tickmode_sync.json
  test/plot-schema.json
Labels: type: feature, type: community, status: reviewable

#6432 Improve detection of mobile & tablet devices
  draftlogs/6432_change.md
  package-lock.json
  package.json
Labels: type: bug, type: maintenance, status: reviewable

#6436 bump json5 - audit fix
  package-lock.json
Labels: type: maintenance

#6437 Fix es5 dist on master
  .circleci/config.yml
  webpack.config.js
Labels: type: bug

#6443 Avoid extra redraw calls when updating axes with `tickmode` other than sync
  draftlogs/6356_add.md
  src/plots/cartesian/dragbox.js
Labels: type: bug

#6445 Fix scaling of SVG exports by not adding `vector-effect` to static plots
  draftlogs/6445_fix.md
  src/components/errorbars/plot.js
  src/traces/bar/plot.js
  src/traces/barpolar/plot.js
  src/traces/box/plot.js
  src/traces/carpet/plot.js
  src/traces/contour/plot.js
  src/traces/contourcarpet/plot.js
  src/traces/scatter/plot.js
  src/traces/violin/plot.js
  test/image/baselines/17.png
  test/image/baselines/28.png
  test/image/baselines/line_scatter.png
Labels: type: bug, status: reviewable
