Repository plotly/plotly.js, pull requests merged in 2023-02, with the labels that each got.

#6461 Update README.md
  README.md
Labels: type: documentation

#6463 Bump `d3-interpolate`
  draftlogs/6463_change.md
  package-lock.json
  package.json
  webpack.config.js
Labels: type: maintenance

#6464 bump `ua-parser-js` in `karma`
  package-lock.json
Labels: type: maintenance

#6485 Upgrade chrome to fix jasmine tests on CircleCI
  .circleci/config.yml
  test/jasmine/tests/geo_test.js
  test/jasmine/tests/sankey_test.js
  test/jasmine/tests/select_test.js
Labels: type: maintenance

#6487 Avoid attaching internal d3 object to the window
  package-lock.json
  package.json
  test/jasmine/bundle_tests/minified_bundle_test.js
Labels: type: bug, status: reviewable, type: regression

#6476 Fix lower / upper fence french translation
  lib/locales/fr.js
Labels: type: bug, type: community, type: translation

#6451 Correct es-PE locale
  lib/locales/es-pe.js
Labels: type: bug, type: community, type: translation

#6495 Rename browserify wrapper
  tasks/bundle.js
  tasks/cibundle.js
  tasks/locales.js
  tasks/partial_bundle.js
  tasks/util/bundle_wrapper.js
Labels: type: maintenance

#6494 Use identical version of `is-mobile` in `stackgl` modules and src code
  stackgl_modules/index.js
  stackgl_modules/package-lock.json
  stackgl_modules/package.json
  stackgl_modules/webpack.config.js
Labels: type: maintenance

#6481 Add `labelalias` to various axes
  draftlogs/6481_add.md
  src/components/colorbar/attributes.js
  src/components/colorbar/draw.js
  src/plots/cartesian/axes.js
  src/plots/cartesian/layout_attributes.js
  src/plots/cartesian/tick_label_defaults.js
  src/plots/gl3d/layout/axis_attributes.js
  src/plots/polar/layout_attributes.js
  src/plots/smith/layout_attributes.js
  src/plots/ternary/layout_attributes.js
  src/traces/carpet/axis_attributes.js
  src/traces/indicator/attributes.js
  test/image/baselines/carpet_grid_dash.png
  test/image/baselines/grid_subplot_types.png
  test/image/baselines/indicator_bullet.png
  test/image/baselines/indicator_format_extremes.png
  test/image/baselines/mathjax3___ternary-mathjax.png
  test/image/baselines/polar_blank.png
  test/image/baselines/smith_blank.png
  test/image/baselines/ternary-mathjax.png
  test/image/mocks/carpet_grid_dash.json
  test/image/mocks/grid_subplot_types.json
  test/image/mocks/indicator_bullet.json
  test/image/mocks/indicator_format_extremes.json
  test/image/mocks/polar_blank.json
  test/image/mocks/smith_blank.json
  test/image/mocks/ternary-mathjax.json
  test/plot-schema.json
Labels: type: feature, status: reviewable
