Repository plotly/plotly.js, pull requests merged in 2023-11, with the labels that each got.

#6775 skip running mapbox tests using stamen style on CircleCi
  test/jasmine/tests/mapbox_test.js
Labels: type: maintenance

#6776 stamen styles are now served by stadiamaps.com
  draftlogs/6776_change.md
  src/plots/mapbox/constants.js
Labels: type: bug, status: reviewable

#6778 additional setup needed to pass api key for `stamen` styles
  draftlogs/6776_change.md
  src/plots/mapbox/constants.js
  src/plots/mapbox/index.js
  src/plots/mapbox/mapbox.js
  test/image/make_baseline.py
Labels: type: bug, status: reviewable

#6781 plot schema should not show `line.shape` options for `scatterpolargl` trace
  draftlogs/6781_fix.md
  src/traces/scatterpolargl/attributes.js
  test/plot-schema.json
Labels: type: bug

#6782 Bump `mapbox-gl` dependency from `v1.10.1` to `v1.13.3`
  package-lock.json
  package.json
  src/plots/mapbox/constants.js
  test/jasmine/tests/mapbox_test.js
  test/jasmine/tests/plot_api_react_test.js
Labels: type: bug, status: reviewable

#6780 Do not break if mouse moves to x=0 when using rangeslider
  draftlogs/6780_fix.md
  src/components/rangeslider/draw.js
Labels: type: bug, type: community, status: reviewable

#6787 fix scattergl legend with marker angle array
  draftlogs/6787_fix.md
  src/components/drawing/index.js
  test/image/baselines/gl2d_period_positioning.png
  test/image/mocks/gl2d_period_positioning.json
Labels: type: bug, status: reviewable

#6802 use mathjax v3.2.2 to create mathjax v3 baselines
  test/image/baselines/mathjax3___legend_mathjax_title_and_items.png
  test/image/baselines/mathjax3___mathjax.png
  test/image/make_baseline.py
Labels: type: maintenance
