Repository plotly/plotly.js, pull requests merged in 2023-10, with the labels that each got.

#6739 Don't hide compilation errors
  draftlogs/6739_fix.md
  tasks/util/bundle_wrapper.js
Labels: type: bug, type: maintenance

#6743 Fix range interactions affecting partial ranges in other subplots
  draftlogs/6743_fix.md
  src/plot_api/plot_api.js
  src/plots/cartesian/axis_defaults.js
  src/plots/cartesian/range_defaults.js
  test/jasmine/tests/axes_test.js
Labels: type: bug, status: reviewable

#6741 Add willReadFrequently to 2d canvas contexts to heatmap
  src/traces/heatmap/plot.js
Labels: type: bug, type: performance

#6724 Emit plotly_click event on touchscreens with "select" dragmode
  src/components/selections/select.js
Labels: type: bug, type: community, status: reviewable

#6744 bump nanoid to address audit warning
  package-lock.json
Labels: type: maintenance

#6718 Fixed issue - column order changes on hover
  draftlogs/6718_fix.md
  src/plots/plots.js
  test/jasmine/tests/calcdata_test.js
Labels: type: bug, type: community, status: reviewable

#6754 audit fix babel traverse
  package-lock.json
Labels: type: maintenance

#6757 Clear empty boxes and candlestick using react
  src/traces/box/plot.js
  test/jasmine/tests/finance_test.js
Labels: type: bug

#6752 Fix issue 6751: epoch date formats '%H:%M:%S' as 'undefined'
  draftlogs/6751_fix.md
  src/plots/cartesian/axes.js
Labels: type: bug, type: community, status: reviewable

#6758 handle multi-line text in title automargin
  draftlogs/6758_fix.md
  src/plot_api/subroutines.js
  test/image/baselines/automargin-title-paper-multiline.png
  test/image/baselines/zzz-automargin-title-paper-multiline-bottom.png
  test/image/mocks/zzz-automargin-title-paper-multiline-bottom.json
Labels: type: bug, status: reviewable

#6763 Add a test to for custom hover format of epoch timestamp
  test/jasmine/tests/hover_label_test.js
Labels: type: community, type: maintenance

#6766 npm audit fix `browserify-sign`
  package-lock.json
Labels: type: maintenance
