Repository plotly/plotly.js, pull requests merged in 2023-03, with the labels that each got.

#6442 Avoid overlap of point and axis hover labels
  draftlogs/6442_fix.md
  src/components/fx/hover.js
  test/jasmine/tests/hover_label_test.js
Labels: type: bug, type: community, status: reviewable

#6514 Fix webpack config to run `strict` dashboard
  devtools/test_dashboard/server.js
Labels: type: maintenance

#6454 Support adding text labels to lines and shapes
  draftlogs/6454_add.md
  src/components/shapes/attributes.js
  src/components/shapes/defaults.js
  src/components/shapes/display_outlines.js
  src/components/shapes/draw.js
  src/components/shapes/draw_newshape/attributes.js
  src/components/shapes/draw_newshape/defaults.js
  src/components/shapes/draw_newshape/newshapes.js
  test/image/baselines/zz-text_on_shapes_basic.png
  test/image/baselines/zz-text_on_shapes_position.png
  test/image/baselines/zz-text_on_shapes_reversed_axes.png
  test/image/mocks/zz-text_on_shapes_basic.json
  test/image/mocks/zz-text_on_shapes_position.json
  test/image/mocks/zz-text_on_shapes_reversed_axes.json
  test/jasmine/tests/draw_newshape_test.js
  test/jasmine/tests/shapes_test.js
  test/plot-schema.json
Labels: type: feature, status: reviewable

#6516 Bump some dev dependencies
  package-lock.json
  package.json
Labels: type: maintenance

#6517 Fix feature detection for Samsung browser on desktop
  draftlogs/6517_fix.md
  package-lock.json
  package.json
  stackgl_modules/index.js
  stackgl_modules/package-lock.json
  stackgl_modules/package.json
Labels: type: bug, status: reviewable

#6518 Bump dev dependencies
  package-lock.json
  package.json
Labels: type: maintenance

#4448 ensure newRng stays in bounds
  src/components/rangeslider/draw.js
  test/jasmine/tests/range_slider_test.js
Labels: type: bug, type: community, status: reviewable

#6428 Adding automargin support to plot titles
  draftlogs/6428_add.md
  src/components/titles/index.js
  src/plot_api/plot_api.js
  src/plot_api/subroutines.js
  src/plots/layout_attributes.js
  src/plots/plots.js
  test/image/baselines/zzz-automargin-title-container-bottom.png
  test/image/baselines/zzz-automargin-title-container.png
  test/image/baselines/zzz-automargin-title-paper-bottom.png
  test/image/baselines/zzz-automargin-title-paper-multiline.png
  test/image/baselines/zzz-automargin-title-paper.png
  test/image/mocks/zzz-automargin-title-container-bottom.json
  test/image/mocks/zzz-automargin-title-container.json
  test/image/mocks/zzz-automargin-title-paper-bottom.json
  test/image/mocks/zzz-automargin-title-paper-multiline.json
  test/image/mocks/zzz-automargin-title-paper.json
  test/jasmine/tests/titles_test.js
  test/plot-schema.json
Labels: type: feature, status: reviewable

#6534 Rename new mocks to adjust image tests for new pulls
  test/image/baselines/automargin-title-container-bottom.png
  test/image/baselines/automargin-title-container.png
  test/image/baselines/automargin-title-paper-bottom.png
  test/image/baselines/automargin-title-paper-multiline.png
  test/image/baselines/automargin-title-paper.png
  test/image/baselines/text_on_shapes_basic.png
  test/image/baselines/text_on_shapes_position.png
  test/image/baselines/text_on_shapes_reversed_axes.png
  test/image/baselines/treemap_sunburst_marker_colors.png
  test/image/baselines/treemap_textfit.png
  test/image/baselines/treemap_textposition.png
  test/image/baselines/uniformtext_bar_edgecase1.png
  test/image/baselines/uniformtext_sunburst_treemap.png
  test/image/mocks/automargin-title-container-bottom.json
  test/image/mocks/automargin-title-container.json
  test/image/mocks/automargin-title-paper-bottom.json
  test/image/mocks/automargin-title-paper-multiline.json
  test/image/mocks/automargin-title-paper.json
  test/image/mocks/text_on_shapes_basic.json
  test/image/mocks/text_on_shapes_position.json
  test/image/mocks/text_on_shapes_reversed_axes.json
Labels: type: maintenance
