Repository plotly/plotly.js, pull requests merged in 2024-05, with the labels that each got.

#6992 bump plotly/d3 v3.8.2
  draftlogs/6992_fix.md
  package-lock.json
  package.json
Labels: type: bug

#6990 Add support for numeric font `weight`
  draftlogs/6990_add.md
  src/lib/coerce.js
  src/plots/font_attributes.js
  src/snapshot/tosvg.js
  src/traces/scattergl/attributes.js
  src/traces/scattergl/convert.js
  src/traces/scattermapbox/constants.js
  src/traces/scattermapbox/convert.js
  src/traces/scattermapbox/defaults.js
  stackgl_modules/index.js
  stackgl_modules/package-lock.json
  stackgl_modules/package.json
  tasks/test_mock.js
  test/image/baselines/gl2d_heatmapgl_discrete.png
  test/image/baselines/mapbox_fonts-supported-metropolis-weight.png
  test/image/baselines/mapbox_fonts-supported-metropolis.png
  test/image/baselines/mapbox_fonts-supported-open-sans-weight.png
  test/image/baselines/mapbox_fonts-supported-open-sans.png
  test/image/baselines/mapbox_scattercluster.png
  test/image/baselines/zz-font-weight-bar.png
  test/image/baselines/zz-font-weight-scatter.png
  test/image/baselines/zz-gl2d_font-weight-scatter.png
  test/image/baselines/zz-gl3d_font-weight-scatter.png
  test/image/mocks/gl2d_heatmapgl_discrete.json
  test/image/mocks/mapbox_fonts-supported-metropolis-weight.json
  test/image/mocks/mapbox_fonts-supported-metropolis.json
  test/image/mocks/mapbox_fonts-supported-open-sans-weight.json
  test/image/mocks/mapbox_fonts-supported-open-sans.json
  test/image/mocks/mapbox_scattercluster.json
  test/image/mocks/texttemplate.json
  test/image/mocks/texttemplate_scatter.json
  test/image/mocks/zz-font-weight-bar.json
  test/image/mocks/zz-font-weight-scatter.json
  test/image/mocks/zz-gl2d_font-weight-scatter.json
  test/image/mocks/zz-gl3d_font-weight-scatter.json
  test/plot-schema.json
Labels: type: feature, status: reviewable

#6994 Additional test for 6990, rename mocks and update baselines using new rendering order on CI
  tasks/test_mock.js
  test/image/baselines/font-weight-bar.png
  test/image/baselines/font-weight-scatter.png
  test/image/baselines/gl2d_font-weight-scatter.png
  test/image/baselines/gl3d_font-weight-scatter.png
  test/image/baselines/icicle_textposition.png
  test/image/baselines/mapbox_fonts-supported-metropolis-italic.png
  test/image/baselines/pattern_bars.png
  test/image/baselines/pattern_fgcolor_overlay_fillmode.png
  test/image/baselines/pie_textpad_radial.png
  test/image/baselines/sunburst_packages_colorscale_novalue.png
  test/image/baselines/treemap_sunburst_marker_colors.png
  test/image/baselines/uniformtext_bar_edgecase1.png
  test/image/baselines/uniformtext_sunburst_treemap.png
  test/image/mocks/font-weight-bar.json
  test/image/mocks/font-weight-scatter.json
  test/image/mocks/gl2d_font-weight-scatter.json
  test/image/mocks/gl3d_font-weight-scatter.json
  test/image/mocks/mapbox_fonts-supported-metropolis-italic.json
Labels: type: maintenance

#6996 fix getFullTransformMatrix in shadow DOM
  draftlogs/6996_fix.md
  src/lib/dom.js
Labels: type: bug, type: community, status: reviewable

#6997 Fix drag on legend scrollbar while `edits.legendPosition` is `true`
  draftlogs/6997_fix.md
  src/components/legend/draw.js
Labels: type: bug, type: community, status: reviewable

#6999 Improve precision of surface3d worldPosition calculation
  draftlogs/6999_fix.md
  stackgl_modules/index.js
  stackgl_modules/package-lock.json
  stackgl_modules/package.json
  test/image/baselines/gl3d_autocolorscale.png
  test/image/baselines/gl3d_autorange-zero.png
  test/image/baselines/gl3d_chrisp-nan-1.png
  test/image/baselines/gl3d_contour-lines.png
  test/image/baselines/gl3d_contour-lines2.png
  test/image/baselines/gl3d_cufflinks.png
  test/image/baselines/gl3d_ibm-plot.png
  test/image/baselines/gl3d_parametric_surface_data_precision.png
  test/image/baselines/gl3d_perspective_tick_distances.png
  test/image/baselines/gl3d_ribbons.png
  test/image/baselines/gl3d_surface-circular-colorscale.png
  test/image/baselines/gl3d_surface-circular-opacityscale.png
  test/image/baselines/gl3d_surface-lighting.png
  test/image/baselines/gl3d_surface_connectgaps.png
  test/image/baselines/gl3d_surface_contour_precision.png
  test/image/baselines/gl3d_surface_contour_start-end-size.png
  test/image/baselines/gl3d_surface_opacityscale_contour.png
  test/image/baselines/gl3d_surface_transparent-with-contours.png
  test/image/baselines/gl3d_world-cals.png
  test/image/baselines/gl3d_xy-defined-ticks.png
  test/image/baselines/trace_metatext.png
  test/image/baselines/zz-gl3d_surface_small_timerange.png
  test/image/mocks/zz-gl3d_surface_small_timerange.json
Labels: type: bug, type: community, status: reviewable

#7002 Fix `isosurface` maximum value calculation when `isomax` is set to null
  draftlogs/7002_fix.md
  src/traces/isosurface/calc.js
Labels: type: bug
