Repository plotly/plotly.js, pull requests merged in 2024-03, with the labels that each got.

#6910 Fix insiderange with category axes
  draftlogs/6910_fix.md
  src/plots/cartesian/axes.js
  test/image/baselines/zz-insiderange-category.png
  test/image/mocks/zz-insiderange-category.json
Labels: type: bug, status: reviewable

#6912 Add x boundaries for ticksarray
  draftlogs/6912_fix.md
  src/plots/cartesian/axes.js
  test/image/baselines/zz-tickson_boundaries_showgrid_categorical.png
Labels: type: bug, status: reviewable

#6905 Add fill gradients for scatter traces
  draftlogs/6905_add.md
  src/components/color/index.js
  src/components/drawing/index.js
  src/components/legend/style.js
  src/traces/box/attributes.js
  src/traces/scatter/attributes.js
  src/traces/scatter/defaults.js
  src/traces/scatter/fillcolor_attribute.js
  src/traces/scatter/fillcolor_defaults.js
  src/traces/scatter/style.js
  src/traces/scattercarpet/attributes.js
  src/traces/scattergeo/attributes.js
  src/traces/scattergl/attributes.js
  src/traces/scattermapbox/attributes.js
  src/traces/scatterpolar/attributes.js
  src/traces/scattersmith/attributes.js
  src/traces/scatterternary/attributes.js
  test/image/baselines/zz-scatter_fill_gradient_tonext.png
  test/image/baselines/zz-scatter_fill_gradient_tonexty_toself.png
  test/image/mocks/zz-scatter_fill_gradient_tonext.json
  test/image/mocks/zz-scatter_fill_gradient_tonexty_toself.json
  test/plot-schema.json
Labels: type: feature, type: community, status: reviewable

#6884 Add Jasmine Test for bugfix #6870
  test/jasmine/tests/select_test.js
Labels: status: reviewable

#6889 Bug/pikul standoff position
  src/plots/cartesian/axes.js
Labels: type: bug, type: community, status: reviewable

#6915 Rename newly added mocks before releasing v2.30.0
  tasks/test_mock.js
  test/image/baselines/insiderange-category.png
  test/image/baselines/insiderange-x-multi-y.png
  test/image/baselines/insiderange-y-multi-x.png
  test/image/baselines/legend_indentation.png
  test/image/baselines/line_scatter_change_side.png
  test/image/baselines/line_scatter_change_side_shrunk.png
  test/image/baselines/line_scatter_regular_side.png
  test/image/baselines/line_scatter_regular_side_shrunk.png
  test/image/baselines/petrophysics.png
  test/image/baselines/pie_textpad_radial.png
  test/image/baselines/scatter_fill_gradient_tonext.png
  test/image/baselines/scatter_fill_gradient_tonexty_toself.png
  test/image/baselines/sunburst_flare.png
  test/image/baselines/sunburst_inside-text-orientation.png
  test/image/baselines/sunburst_packages_colorscale_novalue.png
  test/image/baselines/sunburst_textpad_radial.png
  test/image/baselines/tickson_boundaries_showgrid_categorical.png
  test/image/baselines/treemap_packages_colorscale_novalue.png
  test/image/baselines/treemap_sunburst_marker_colors.png
  test/image/baselines/treemap_textfit.png
  test/image/baselines/uniformtext_sunburst_treemap.png
  test/image/mocks/insiderange-category.json
  test/image/mocks/insiderange-x-multi-y.json
  test/image/mocks/insiderange-y-multi-x.json
  test/image/mocks/legend_indentation.json
  test/image/mocks/line_scatter_change_side.json
  test/image/mocks/line_scatter_change_side_shrunk.json
  test/image/mocks/line_scatter_regular_side.json
  test/image/mocks/line_scatter_regular_side_shrunk.json
  test/image/mocks/petrophysics.json
  test/image/mocks/scatter_fill_gradient_tonext.json
  test/image/mocks/scatter_fill_gradient_tonexty_toself.json
  test/image/mocks/tickson_boundaries_showgrid_categorical.json
Labels: type: maintenance

#6893 Fix resizing `pie` like traces when `textinfo` is set to "none"
  draftlogs/6893_fix.md
  src/traces/funnelarea/defaults.js
  src/traces/pie/defaults.js
Labels: type: bug, type: community, status: reviewable

#6923 Fix centering multi-line headers for `treemap` traces
  draftlogs/6923_fix.md
  src/traces/treemap/draw_descendants.js
  test/image/baselines/zz-treemap_multi-line_headers.png
  test/image/mocks/zz-treemap_multi-line_headers.json
Labels: type: bug, status: reviewable

#6924 Fix `heatmap` text color and `texttemplate` on cells with missing data
  draftlogs/6924_fix.md
  src/lib/index.js
  src/traces/heatmap/plot.js
  test/image/baselines/heatmap_xyz-gaps-on-sides.png
  test/image/baselines/zz-heatmap-text-color-on-missing-data.png
  test/image/mocks/zz-heatmap-text-color-on-missing-data.json
Labels: type: bug, status: reviewable

#6928 Fix `scattergl` rendering when colors include capital letters
  draftlogs/6928_fix.md
  package-lock.json
  package.json
  test/image/baselines/zz-gl2d-case-insenstive-colors.png
  test/image/mocks/zz-gl2d-case-insenstive-colors.json
Labels: type: bug, status: reviewable

#6931 Rename new mocks before the release
  test/image/baselines/gl2d-case-insenstive-colors.png
  test/image/baselines/heatmap-text-color-on-missing-data.png
  test/image/baselines/icicle_textposition.png
  test/image/baselines/pattern_bars.png
  test/image/baselines/treemap_multi-line_headers.png
  test/image/baselines/treemap_sunburst_marker_colors.png
  test/image/baselines/treemap_textfit.png
  test/image/baselines/treemap_textposition.png
  test/image/baselines/uniformtext_sunburst_treemap.png
  test/image/mocks/gl2d-case-insenstive-colors.json
  test/image/mocks/heatmap-text-color-on-missing-data.json
  test/image/mocks/treemap_multi-line_headers.json
Labels: type: maintenance

#6932 bump follow-redirects
  package-lock.json
Labels: type: maintenance

#6927 Add shapes.layer "between" for drawing between gridlines and traces
  draftlogs/6927_add.md
  src/components/shapes/attributes.js
  src/components/shapes/draw.js
  src/components/shapes/draw_newshape/attributes.js
  src/plots/cartesian/index.js
  test/image/baselines/zz-shapes_layer_below_traces.png
  test/image/mocks/zz-shapes_layer_below_traces.json
  test/jasmine/tests/splom_test.js
  test/plot-schema.json
Labels: type: feature, type: community, status: reviewable

#6938 Add "raw" `sizemode` to cone trace
  draftlogs/6938_add.md
  src/traces/cone/attributes.js
  src/traces/cone/convert.js
  src/traces/cone/defaults.js
  stackgl_modules/index.js
  stackgl_modules/package-lock.json
  stackgl_modules/package.json
  test/image/baselines/zz-gl3d_cone-sizemode_vector.png
  test/image/baselines/zz-gl3d_cone-sizemode_vector2.png
  test/image/baselines/zz-gl3d_cone-sizemode_vector3.png
  test/image/mocks/zz-gl3d_cone-sizemode_vector.json
  test/image/mocks/zz-gl3d_cone-sizemode_vector2.json
  test/image/mocks/zz-gl3d_cone-sizemode_vector3.json
  test/plot-schema.json
Labels: type: feature, status: reviewable

#6944 Fix hover count info label in `createHoverLabelForColorHovermode`
  draftlogs/6944_change.md
  src/traces/parcats/parcats.js
  test/image/mocks/parcats_hoveron_color.json
Labels: type: bug, type: community, status: reviewable
