Repository plotly/plotly.js, pull requests merged in 2024-09, with the labels that each got.

#7140 Inline maplibre css from node_modules
  draftlogs/7140_fix.md
  package-lock.json
  package.json
  src/registry.js
  webpack.config.js
Labels: community, P1, fix

#7141 Fix `zorder` on overlayed subplots case of multiple traces in each subplot
  src/plots/cartesian/index.js
  test/image/baselines/zorder-overlayed-subplots-multiple-traces-main-subplot.png
  test/image/baselines/zorder-overlayed-subplots-multiple-traces-main-subplot2.png
  test/image/baselines/zorder-overlayed-subplots-multiple-traces-one-subplot.png
  test/image/mocks/zorder-overlayed-subplots-multiple-traces-main-subplot.json
  test/image/mocks/zorder-overlayed-subplots-multiple-traces-main-subplot2.json
  test/image/mocks/zorder-overlayed-subplots-multiple-traces-one-subplot.json
Labels: P1, fix

#6909 Switch to `esbuild` for faster builds and also to allow using more modern JavaScript syntax and features
  .circleci/config.yml
  devtools/regl_codegen/server.mjs
  devtools/test_dashboard/index.html
  devtools/test_dashboard/server.js
  devtools/test_dashboard/server.mjs
  draftlogs/6909_change.md
  draftlogs/7124_change.md
  esbuild-config.js
  package-lock.json
  package.json
  src/components/drawing/symbol_defs.js
  src/plots/map/constants.js
  src/plots/map/styles/arcgis-sat-hybrid.js
  src/plots/map/styles/arcgis-sat.js
  tasks/bundle.mjs
  tasks/cibundle.js
  tasks/cibundle.mjs
  tasks/custom_bundle.mjs
  tasks/extra_bundles.mjs
  tasks/partial_bundle.mjs
  tasks/schema.mjs
  tasks/test_mock.mjs
  tasks/test_plain_obj.mjs
  tasks/util/bundle_wrapper.js
  tasks/util/bundle_wrapper.mjs
  tasks/util/plotly_node.mjs
  test/jasmine/bundle_tests/minified_bundle_test.js
  test/jasmine/karma.conf.js
Labels: feature, P1, infrastructure

#7100 Add dependabot.yml to reduce manual work
  .github/dependabot.yml
  .gitignore
Labels: community, P1, fix

#7150 Fix hiding of axis lines and of images
  src/components/images/draw.js
  src/plot_api/subroutines.js
Labels: community, P1, fix

#7164 fix to allow you to add fake selections
  draftlogs/7164_fix.md
  src/components/selections/select.js
  test/jasmine/tests/select_test.js
Labels: bug

#7167 Fix scatterternary with ids attribute
  draftlogs/7167_fix.md
  src/traces/scatterternary/calc.js
  test/image/mocks/ternary_simple.json
  test/jasmine/tests/select_test.js
  test/jasmine/tests/ternary_test.js
Labels: bug
