Repository plotly/plotly.js, pull requests merged in 2024-04, with the labels that each got.

#6947 Add `layout.subplots` to enable (x|y) hover effects across multiple cartesian and splom suplots sharing one axis
  draftlogs/6947_add.md
  src/components/fx/hover.js
  src/components/fx/hovermode_defaults.js
  src/components/fx/layout_attributes.js
  src/traces/splom/hover.js
  test/jasmine/tests/hover_label_test.js
  test/plot-schema.json
Labels: type: feature, status: reviewable

#6918 Add z-index stacking attribute to cartesian SVG traces
  draftlogs/6918_add.md
  src/plots/cartesian/index.js
  src/plots/get_data.js
  src/traces/bar/attributes.js
  src/traces/bar/defaults.js
  src/traces/bar/style.js
  src/traces/box/attributes.js
  src/traces/box/defaults.js
  src/traces/candlestick/attributes.js
  src/traces/candlestick/defaults.js
  src/traces/carpet/attributes.js
  src/traces/carpet/defaults.js
  src/traces/contour/attributes.js
  src/traces/contour/defaults.js
  src/traces/contourcarpet/attributes.js
  src/traces/contourcarpet/defaults.js
  src/traces/funnel/attributes.js
  src/traces/funnel/defaults.js
  src/traces/funnel/style.js
  src/traces/heatmap/attributes.js
  src/traces/heatmap/defaults.js
  src/traces/histogram/attributes.js
  src/traces/histogram/defaults.js
  src/traces/image/attributes.js
  src/traces/image/defaults.js
  src/traces/ohlc/attributes.js
  src/traces/ohlc/defaults.js
  src/traces/scatter/attributes.js
  src/traces/scatter/defaults.js
  src/traces/scattercarpet/attributes.js
  src/traces/scattercarpet/defaults.js
  src/traces/violin/attributes.js
  src/traces/violin/defaults.js
  src/traces/waterfall/attributes.js
  src/traces/waterfall/defaults.js
  src/traces/waterfall/style.js
  test/image/baselines/funnel_axis_with_other_traces.png
  test/image/baselines/zz-zorder-contour.png
  test/image/baselines/zz-zorder-heatmap.png
  test/image/baselines/zz-zorder-scatter-image.png
  test/image/baselines/zz-zorder_basic.png
  test/image/baselines/zz-zorder_funnel_carpet_waterfall.png
  test/image/baselines/zz-zorder_violin_box.png
  test/image/mocks/funnel_axis_with_other_traces.json
  test/image/mocks/zz-zorder-contour.json
  test/image/mocks/zz-zorder-heatmap.json
  test/image/mocks/zz-zorder-scatter-image.json
  test/image/mocks/zz-zorder_basic.json
  test/image/mocks/zz-zorder_funnel_carpet_waterfall.json
  test/image/mocks/zz-zorder_violin_box.json
  test/jasmine/tests/cartesian_interact_test.js
  test/jasmine/tests/select_test.js
  test/plot-schema.json
Labels: type: feature, status: reviewable

#6951 Rename new mocks before v2.31.0 and regenerate baselines
  test/image/baselines/gl3d_cone-sizemode_vector.png
  test/image/baselines/gl3d_cone-sizemode_vector2.png
  test/image/baselines/gl3d_cone-sizemode_vector3.png
  test/image/baselines/pattern_fgcolor_overlay_fillmode.png
  test/image/baselines/pie_textpad_radial.png
  test/image/baselines/shapes_layer_below_traces.png
  test/image/baselines/sunburst_flare.png
  test/image/baselines/sunburst_packages_colorscale_novalue.png
  test/image/baselines/treemap_textposition.png
  test/image/baselines/uniformtext_bar_edgecase1.png
  test/image/baselines/zorder-contour.png
  test/image/baselines/zorder-heatmap.png
  test/image/baselines/zorder-scatter-image.png
  test/image/baselines/zorder_basic.png
  test/image/baselines/zorder_funnel_carpet_waterfall.png
  test/image/baselines/zorder_violin_box.png
  test/image/mocks/gl3d_cone-sizemode_vector.json
  test/image/mocks/gl3d_cone-sizemode_vector2.json
  test/image/mocks/gl3d_cone-sizemode_vector3.json
  test/image/mocks/shapes_layer_below_traces.json
  test/image/mocks/zorder-contour.json
  test/image/mocks/zorder-heatmap.json
  test/image/mocks/zorder-scatter-image.json
  test/image/mocks/zorder_basic.json
  test/image/mocks/zorder_funnel_carpet_waterfall.json
  test/image/mocks/zorder_violin_box.json
Labels: type: maintenance

#6953 Fix closest hover and click+select with `zorder`
  draftlogs/6918_add.md
  src/components/fx/hover.js
  test/jasmine/tests/hover_label_test.js
  test/jasmine/tests/select_test.js
Labels: type: bug

#6961 Update `stackgl` dev dependency
  stackgl_modules/package-lock.json
Labels: type: maintenance

#6962 Maintain original drawing order of traces when traces with similar type are sent to back
  draftlogs/6962_fix.md
  src/plots/cartesian/index.js
  test/image/baselines/zz-zorder_default-orders.png
  test/image/mocks/zz-zorder_default-orders.json
Labels: type: bug, status: reviewable

#6965 Avoid duplicate points in splom hover
  draftlogs/6965_fix.md
  src/traces/splom/hover.js
  test/jasmine/tests/hover_label_test.js
Labels: type: bug

#6963 Ensure winning points of hover are listed first when `hoversubplots` is set to "axis" and sorting by distance
  draftlogs/6963_fix.md
  src/components/fx/hover.js
  test/jasmine/tests/hover_label_test.js
Labels: type: bug, status: reviewable

#6972 Use raw sizemode in a cone mock
  test/image/baselines/gl3d_cone-wind.png
  test/image/mocks/gl3d_cone-wind.json
Labels: type: maintenance

#6967 autotickangles for axes with tickson="boundaries" or showdividers=true
  draftlogs/6967_fix.md
  src/plots/cartesian/axes.js
  test/image/baselines/tickson_boundaries.png
  test/jasmine/tests/axes_test.js
  test/jasmine/tests/cartesian_interact_test.js
Labels: type: bug, status: reviewable

#6970 Fix inconsistent axis title standoff when title is one text line vs. multiple lines
  draftlogs/6970_fix.md
  src/plots/cartesian/axes.js
  test/image/baselines/axis-title-standoff.png
  test/image/baselines/line_scatter_change_side.png
  test/image/baselines/line_scatter_change_side_shrunk.png
  test/image/baselines/line_scatter_regular_side.png
  test/image/baselines/line_scatter_regular_side_shrunk.png
  test/image/baselines/mult-yaxes-simple.png
  test/image/baselines/petrophysics.png
  test/image/baselines/zz-axis_title_standoff0.png
  test/image/mocks/axis-title-standoff.json
  test/image/mocks/zz-axis_title_standoff0.json
Labels: type: bug, type: community, status: reviewable

#6980 Simplify drawing font args
  src/components/drawing/index.js
  test/jasmine/tests/drawing_test.js
Labels: type: maintenance, type: performance

#6981 Rename new mocks and update baselines with new CI order
  tasks/test_mock.js
  test/image/baselines/axis_title_standoff0.png
  test/image/baselines/font-variant-bar.png
  test/image/baselines/font-variant-scatter.png
  test/image/baselines/gl2d-font-variant-scatter.png
  test/image/baselines/gl2d_font-variant-scatter.png
  test/image/baselines/gl3d_font-variant-scatter.png
  test/image/baselines/icicle_textposition.png
  test/image/baselines/pattern_bars.png
  test/image/baselines/treemap_textfit.png
  test/image/baselines/uniformtext_sunburst_treemap.png
  test/image/baselines/zorder_default-orders.png
  test/image/mocks/axis_title_standoff0.json
  test/image/mocks/font-variant-bar.json
  test/image/mocks/font-variant-scatter.json
  test/image/mocks/gl2d_font-variant-scatter.json
  test/image/mocks/gl3d_font-variant-scatter.json
  test/image/mocks/zorder_default-orders.json
Labels: type: maintenance

#6985 adjust parallelism of `make-baselines-virtual-webgl` to reduce falkiness
  .circleci/config.yml
Labels: type: maintenance
