Repository plotly/plotly.js, pull requests merged in 2024-10, with the labels that each got.

#7165 updating year(s) in license
  LICENSE
Labels: P2, fix, documentation

#7199 Use URLs directly for layout images
  draftlogs/7199_fix.md
  src/components/images/draw.js
  test/jasmine/tests/layout_images_test.js
Labels: bug, performance

#7215 Drop support for deprecated `annotation.ref` attribute (use `annotation.xref` and `annotation.yref` instead)
  draftlogs/7215_remove.md
  src/components/annotations/attributes.js
  src/plot_api/helpers.js
  test/image/mocks/11.json
  test/image/mocks/14.json
  test/image/mocks/17.json
  test/image/mocks/27.json
  test/image/mocks/29.json
  test/jasmine/tests/plot_api_test.js
  test/plot-schema.json
Labels: feature, P1

#7217 Drop support for deprecated attribute `gl3d.cameraposition` (use `gl3d.camera` instead)
  draftlogs/7217_remove.md
  src/plot_api/helpers.js
  src/plots/gl3d/layout/layout_attributes.js
  test/image/mocks/gl3d_ibm-plot.json
  test/image/mocks/gl3d_opacity-surface.json
  test/image/mocks/gl3d_surface-lighting.json
  test/plot-schema.json
Labels: feature, P1

#7213 Drop deprecated `pointcloud` and `heatmapgl` traces and `gl2d` subplots
  draftlogs/7213_remove.md
  lib/heatmapgl.js
  lib/index-gl2d.js
  lib/index-strict.js
  lib/index.js
  lib/pointcloud.js
  src/components/fx/hover.js
  src/components/images/draw.js
  src/components/modebar/buttons.js
  src/components/modebar/manage.js
  src/components/rangeslider/helpers.js
  src/plot_api/plot_api.js
  src/plot_api/plot_schema.js
  src/plot_api/subroutines.js
  src/plots/cartesian/include_components.js
  src/plots/cartesian/index.js
  src/plots/cartesian/layout_defaults.js
  src/plots/get_data.js
  src/plots/gl2d/camera.js
  src/plots/gl2d/convert.js
  src/plots/gl2d/index.js
  src/plots/gl2d/scene2d.js
  src/plots/plots.js
  src/snapshot/helpers.js
  src/traces/heatmap/calc.js
  src/traces/heatmap/make_bound_array.js
  src/traces/heatmap/xyz_defaults.js
  src/traces/heatmapgl/attributes.js
  src/traces/heatmapgl/convert.js
  src/traces/heatmapgl/defaults.js
  src/traces/heatmapgl/index.js
  src/traces/pointcloud/attributes.js
  src/traces/pointcloud/convert.js
  src/traces/pointcloud/defaults.js
  src/traces/pointcloud/index.js
  stackgl_modules/index.js
  stackgl_modules/main.js
  stackgl_modules/package-lock.json
  stackgl_modules/package.json
  tasks/test_mock.mjs
  tasks/util/constants.js
  test/image/baselines/gl2d_heatmapgl.png
  test/image/baselines/gl2d_heatmapgl_discrete.png
  test/image/baselines/gl2d_pointcloud-basic.png
  test/image/baselines/icicle_textposition.png
  test/image/baselines/pattern_bars.png
  test/image/make_baseline.py
  test/image/mocks/gl2d_heatmapgl.json
  test/image/mocks/gl2d_heatmapgl_discrete.json
  test/image/mocks/gl2d_pointcloud-basic.json
  test/image/mocks/petrophysics.json
  test/jasmine/assets/mock_lists.js
  test/jasmine/bundle_tests/no_webgl_test.js
  test/jasmine/bundle_tests/plotschema_test.js
  test/jasmine/tests/gl2d_click_test.js
  test/jasmine/tests/heatmap_test.js
  test/jasmine/tests/heatmapgl_test.js
  test/jasmine/tests/modebar_test.js
  test/jasmine/tests/pointcloud_test.js
  test/plot-schema.json
Labels: feature, P1

#7212 Drop support for passing a string to the `title` attribute, and drop support for deprecated attributes `titlefont`, `titleposition`, `titleside`, and `titleoffset`
  draftlogs/7212_remove.md
  src/components/colorbar/attributes.js
  src/components/titles/index.js
  src/plot_api/helpers.js
  src/plot_api/plot_api.js
  src/plots/cartesian/layout_attributes.js
  src/plots/cartesian/tick_label_defaults.js
  src/plots/gl3d/layout/axis_attributes.js
  src/plots/layout_attributes.js
  src/plots/polar/layout_attributes.js
  src/plots/ternary/layout_attributes.js
  src/traces/carpet/axis_attributes.js
  src/traces/pie/attributes.js
  test/jasmine/bundle_tests/mathjax_test.js
  test/jasmine/tests/cartesian_test.js
  test/jasmine/tests/click_test.js
  test/jasmine/tests/funnelarea_test.js
  test/jasmine/tests/pie_test.js
  test/jasmine/tests/plot_api_test.js
  test/jasmine/tests/plots_test.js
  test/jasmine/tests/polar_test.js
  test/jasmine/tests/shapes_test.js
  test/jasmine/tests/ternary_test.js
  test/jasmine/tests/titles_test.js
  test/plot-schema.json
Labels: feature, P1

#7171 Fix lower zorder traces behing some gridlines on overlayed suplots
  src/plots/cartesian/index.js
  test/image/baselines/zorder-overlayed-subplots-multiple-traces-main-subplot.png
Labels: bug, P1

#7009 make offsetgroup work with barmode 'stacked' and 'relative' for bar traces
  draftlogs/7009_change.md
  src/traces/bar/cross_trace_calc.js
  src/traces/bar/defaults.js
  src/traces/bar/layout_defaults.js
  src/traces/bar/sieve.js
  src/traces/box/defaults.js
  src/traces/funnel/defaults.js
  src/traces/histogram/cross_trace_defaults.js
  src/traces/scatter/cross_trace_defaults.js
  src/traces/scatter/grouping_defaults.js
  src/traces/waterfall/defaults.js
  test/image/baselines/funnel_attrs.png
  test/image/baselines/legendgroup_bar-stack.png
  test/image/baselines/zzz_bar_relative_offsetgroup.png
  test/image/mocks/zzz_bar_relative_offsetgroup.json
  test/jasmine/tests/bar_test.js
  test/jasmine/tests/funnel_test.js
Labels: feature, community, P1, cs

#7109 Remove inline styles that break plots in strict CSP setups
  draftlogs/7109_fix.md
  src/components/modebar/modebar.js
  src/fonts/ploticon.js
  src/lib/dom.js
  src/lib/index.js
  tasks/preprocess.js
  tasks/util/constants.js
  test/jasmine/tests/modebar_test.js
Labels: community, P2, fix
