Repository plotly/plotly.js, pull requests merged in 2024-06, with the labels that each got.

#7018 Fix issue where scattergl traces disappear while zooming or panning
  draftlogs/7018_fix.md
  src/plots/cartesian/dragbox.js
Labels: type: bug, type: community, status: reviewable, type: regression

#7019 update mapbox_carto baselines
  test/image/baselines/mapbox_carto-style.png
  test/image/baselines/mapbox_carto-text.png
Labels: type: maintenance

#7030 Skip `restyle radial axis title` Jasmine test in CI (test is not reliable)
  test/jasmine/tests/polar_test.js
Labels: type: maintenance, status: reviewable

#7033 npm audit fix
  package-lock.json
Labels: type: maintenance

#7032 Handle `zorder` between overlayed cartesian subplots
  src/components/fx/hover.js
  src/plot_api/subroutines.js
  src/plots/cartesian/constants.js
  src/plots/cartesian/index.js
  test/image/baselines/zz-zorder-overlayed-subplots.png
  test/image/mocks/zz-zorder-overlayed-subplots.json
  test/jasmine/tests/animate_test.js
  test/jasmine/tests/bar_test.js
  test/jasmine/tests/cartesian_interact_test.js
  test/jasmine/tests/cartesian_test.js
  test/jasmine/tests/click_test.js
  test/jasmine/tests/scatter_test.js
  test/jasmine/tests/select_test.js
  test/jasmine/tests/splom_test.js
  test/jasmine/tests/toimage_test.js
Labels: type: bug, type: feature, status: reviewable
