Repository plotly/plotly.js, pull requests merged in 2024-07, with the labels that each got.

#7006 Add `ticklabelstandoff` and `ticklabelshift` to cartesian axes
  draftlogs/7006_add.md
  src/components/colorbar/defaults.js
  src/plots/cartesian/axes.js
  src/plots/cartesian/layout_attributes.js
  src/plots/cartesian/tick_label_defaults.js
  src/plots/gl3d/layout/axis_defaults.js
  src/plots/polar/layout_defaults.js
  src/plots/smith/layout_defaults.js
  src/plots/ternary/layout_defaults.js
  src/traces/carpet/ab_defaults.js
  src/traces/indicator/defaults.js
  test/image/baselines/zzz_ticklabelshift_ticklabelstandoff.png
  test/image/mocks/zzz_ticklabelshift_ticklabelstandoff.json
  test/plot-schema.json
Labels: type: feature, type: community, status: reviewable

#7036 Property `ticklabelindex` for custom tick label display
  draftlogs/7006_add.md
  draftlogs/7036_add.md
  src/constants/numerical.js
  src/plots/cartesian/axes.js
  src/plots/cartesian/axis_defaults.js
  src/plots/cartesian/layout_attributes.js
  src/plots/gl3d/layout/axis_defaults.js
  test/image/baselines/zzz_date_axes-ticklabelstep-ticklabelindex.png
  test/image/baselines/zzz_date_axes_period2_ticklabelindex.png
  test/image/baselines/zzz_date_axes_period_ticklabelindex.png
  test/image/baselines/zzz_date_axes_ticklabelindex.png
  test/image/baselines/zzz_ticklabelindex.png
  test/image/baselines/zzz_ticklabelindex_period_axes.png
  test/image/mocks/zzz_date_axes-ticklabelstep-ticklabelindex.json
  test/image/mocks/zzz_date_axes_period2_ticklabelindex.json
  test/image/mocks/zzz_date_axes_period_ticklabelindex.json
  test/image/mocks/zzz_date_axes_ticklabelindex.json
  test/image/mocks/zzz_ticklabelindex.json
  test/plot-schema.json
Labels: type: feature, type: community, status: reviewable

#5879 Fix cartesian hover toggle
  src/components/modebar/manage.js
Labels: type: bug, type: community, status: has TODOs

#6223 feature(geomean): add geomean function
  draftlogs/6223_add.md
  src/lib/index.js
  src/lib/stats.js
  src/plots/cartesian/layout_attributes.js
  src/plots/plots.js
  test/jasmine/tests/calcdata_test.js
  test/jasmine/tests/lib_test.js
  test/plot-schema.json
Labels: type: feature, type: community, status: has TODOs, status: reviewable

#7047 Tiny typo fix
  src/plots/font_attributes.js
  test/plot-schema.json
Labels: status: reviewable, type: documentation

#7005 property x0shift, x1shift, y0shift, y1shift for adjusting the shape coordinates
  draftlogs/7005_add.md
  src/components/shapes/attributes.js
  src/components/shapes/calc_autorange.js
  src/components/shapes/defaults.js
  src/components/shapes/display_labels.js
  src/components/shapes/draw.js
  src/components/shapes/draw_newshape/newshapes.js
  src/components/shapes/helpers.js
  src/components/shapes/label_texttemplate.js
  test/image/baselines/zzz_shape_shift_horizontal.png
  test/image/baselines/zzz_shape_shift_vertical.png
  test/image/mocks/zzz_shape_shift_horizontal.json
  test/image/mocks/zzz_shape_shift_vertical.json
  test/jasmine/tests/shapes_test.js
  test/plot-schema.json
Labels: type: feature, type: community, status: reviewable

#7044 Adjust failing modebar test after merging PR #5879
  src/components/modebar/manage.js
  test/jasmine/tests/modebar_test.js
Labels: type: bug

#7043 Add '<s>' and '<u>' pseudo html options for strike-through and underlining SVG text
  draftlogs/7043_add.md
  src/components/annotations/attributes.js
  src/components/fx/hover.js
  src/lib/svg_text_utils.js
  test/image/baselines/pie_title_middle_center_multiline.png
  test/image/mocks/pie_title_middle_center_multiline.json
  test/plot-schema.json
Labels: type: feature, status: reviewable

#7053 Rename new mocks 2024 07 18
  .circleci/test.sh
  test/image/baselines/date_axes-ticklabelstep-ticklabelindex.png
  test/image/baselines/date_axes_period2_ticklabelindex.png
  test/image/baselines/date_axes_period_ticklabelindex.png
  test/image/baselines/date_axes_ticklabelindex.png
  test/image/baselines/font-decorline-scatter.png
  test/image/baselines/font-textcase-scatter.png
  test/image/baselines/font-textshadow-scatter.png
  test/image/baselines/gl3d_surface_small_timerange.png
  test/image/baselines/mathjax3___ternary-mathjax-title-place-subtitle.png
  test/image/baselines/pattern_bars.png
  test/image/baselines/pie_textpad_radial.png
  test/image/baselines/shape_shift_horizontal.png
  test/image/baselines/shape_shift_vertical.png
  test/image/baselines/subtitle-font-styling.png
  test/image/baselines/subtitle.png
  test/image/baselines/sunburst_coffee.png
  test/image/baselines/ternary-mathjax-title-place-subtitle.png
  test/image/baselines/ticklabelindex.png
  test/image/baselines/ticklabelindex_period_axes.png
  test/image/baselines/ticklabelshift_ticklabelstandoff.png
  test/image/baselines/treemap_sunburst_marker_colors.png
  test/image/baselines/treemap_textfit.png
  test/image/baselines/treemap_textposition.png
  test/image/baselines/uniformtext_bar_edgecase1.png
  test/image/baselines/uniformtext_sunburst_treemap.png
  test/image/baselines/zorder-overlayed-subplots.png
  test/image/compare_pixels_test.js
  test/image/make_baseline.js
  test/image/mocks/date_axes-ticklabelstep-ticklabelindex.json
  test/image/mocks/date_axes_period2_ticklabelindex.json
  test/image/mocks/date_axes_period_ticklabelindex.json
  test/image/mocks/date_axes_ticklabelindex.json
  test/image/mocks/font-decorline-scatter.json
  test/image/mocks/font-textcase-scatter.json
  test/image/mocks/font-textshadow-scatter.json
  test/image/mocks/gl3d_surface_small_timerange.json
  test/image/mocks/shape_shift_horizontal.json
  test/image/mocks/shape_shift_vertical.json
  test/image/mocks/subtitle-font-styling.json
  test/image/mocks/subtitle.json
  test/image/mocks/ternary-mathjax-title-place-subtitle.json
  test/image/mocks/ticklabelindex.json
  test/image/mocks/ticklabelshift_ticklabelstandoff.json
  test/image/mocks/zorder-overlayed-subplots.json
  test/plot-schema.json
Labels: type: maintenance

#7057 Fix missing cursor for ternary plot
  draftlogs/7057_fix.md
  src/plots/ternary/index.js
  src/plots/ternary/ternary.js
Labels: type: bug, type: community, status: reviewable

#7068 load maki icon
  src/plots/map/map.js
  test/image/baselines/map_angles.png
  test/image/baselines/map_symbol-text.png
  test/image/compare_pixels_test.js
Labels: type: bug, type: community, status: reviewable
