Repository plotly/plotly.js, pull requests merged in 2024-02, with the labels that each got.

#6870 Fix interacting with selection on subplots with overlaid axes
  draftlogs/6870_change.md
  src/components/selections/select.js
Labels: type: bug, status: reviewable

#6761 Add option for rounded corners on bar charts
  draftlogs/6761_add.md
  src/components/legend/style.js
  src/traces/bar/attributes.js
  src/traces/bar/cross_trace_calc.js
  src/traces/bar/defaults.js
  src/traces/bar/layout_attributes.js
  src/traces/bar/layout_defaults.js
  src/traces/bar/plot.js
  src/traces/barpolar/attributes.js
  src/traces/funnel/attributes.js
  src/traces/histogram/cross_trace_defaults.js
  test/image/baselines/bar_gantt-chart.png
  test/image/baselines/hist_cum_stacked.png
  test/image/baselines/histogram-offsetgroups.png
  test/image/baselines/histogram_colorscale.png
  test/image/baselines/period_positioning9.png
  test/image/baselines/zz-bar-rounded-corners.png
  test/image/baselines/zz-round-bar_attrs_relative.png
  test/image/baselines/zz-round-bar_stackto100_negative.png
  test/image/baselines/zz-round-worldcup.png
  test/image/baselines/zz-rounded-bar_display_height_zero_no_line_width.png
  test/image/mocks/bar_gantt-chart.json
  test/image/mocks/hist_cum_stacked.json
  test/image/mocks/histogram-offsetgroups.json
  test/image/mocks/histogram_colorscale.json
  test/image/mocks/period_positioning9.json
  test/image/mocks/zz-bar-rounded-corners.json
  test/image/mocks/zz-round-bar_attrs_relative.json
  test/image/mocks/zz-round-bar_stackto100_negative.json
  test/image/mocks/zz-round-worldcup.json
  test/image/mocks/zz-rounded-bar_display_height_zero_no_line_width.json
  test/plot-schema.json
Labels: type: feature, status: reviewable

#6876 Rename newly added mocks
  test/image/baselines/allowed-range-small.png
  test/image/baselines/allowed-range.png
  test/image/baselines/automargin-title-paper-multiline-bottom.png
  test/image/baselines/bar-rounded-corners.png
  test/image/baselines/container-colorbar-vertical-w-margin.png
  test/image/baselines/heatmap-log-scale.png
  test/image/baselines/histogram_overlay-1point-date.png
  test/image/baselines/icicle_textposition.png
  test/image/baselines/insiderange-x-narrow.png
  test/image/baselines/insiderange-x.png
  test/image/baselines/insiderange-y-narrow.png
  test/image/baselines/insiderange-y.png
  test/image/baselines/partial-autorange-matching-axes.png
  test/image/baselines/pattern_bars.png
  test/image/baselines/pie_pattern.png
  test/image/baselines/round-bar_attrs_relative.png
  test/image/baselines/round-bar_stackto100_negative.png
  test/image/baselines/round-worldcup.png
  test/image/baselines/rounded-bar_display_height_zero_no_line_width.png
  test/image/baselines/sankey_circular_align_right.png
  test/image/baselines/sunburst_flare.png
  test/image/baselines/sunburst_inside-text-orientation.png
  test/image/baselines/sunburst_packages_colorscale_novalue.png
  test/image/baselines/sunburst_pattern.png
  test/image/baselines/treemap_packages_colorscale_novalue.png
  test/image/baselines/treemap_sunburst_marker_colors.png
  test/image/baselines/treemap_textfit.png
  test/image/baselines/uniformtext_sunburst_treemap.png
  test/image/mocks/allowed-range-small.json
  test/image/mocks/allowed-range.json
  test/image/mocks/automargin-title-paper-multiline-bottom.json
  test/image/mocks/bar-rounded-corners.json
  test/image/mocks/container-colorbar-vertical-w-margin.json
  test/image/mocks/heatmap-log-scale.json
  test/image/mocks/histogram_overlay-1point-date.json
  test/image/mocks/insiderange-x-narrow.json
  test/image/mocks/insiderange-x.json
  test/image/mocks/insiderange-y-narrow.json
  test/image/mocks/insiderange-y.json
  test/image/mocks/partial-autorange-matching-axes.json
  test/image/mocks/pie_pattern.json
  test/image/mocks/round-bar_attrs_relative.json
  test/image/mocks/round-bar_stackto100_negative.json
  test/image/mocks/round-worldcup.json
  test/image/mocks/rounded-bar_display_height_zero_no_line_width.json
  test/image/mocks/sankey_circular_align_right.json
  test/image/mocks/sunburst_pattern.json
Labels: type: maintenance

#6877 Bump some dev-dependencies
  package-lock.json
  package.json
Labels: type: maintenance

#6882 fix link
  CHANGELOG.md
Labels: type: documentation

#6885 Bugfix: categorical axis tickson boundaries showgrid
  draftlogs/6885_change.md
  src/plots/cartesian/axes.js
  test/image/baselines/zz-tickson_boundaries_showgrid_categorical.png
  test/image/mocks/zz-tickson_boundaries_showgrid_categorical.json
Labels: type: bug, status: reviewable

#6817 Respect `insiderange` when multiple overlaid axes having `insideticklabel`
  draftlogs/6817_fix.md
  src/plots/cartesian/axes.js
  test/image/baselines/zz-insiderange-x-multi-y.png
  test/image/baselines/zz-insiderange-y-multi-x.png
  test/image/mocks/zz-insiderange-x-multi-y.json
  test/image/mocks/zz-insiderange-y-multi-x.json
Labels: type: bug, status: has TODOs

#6906 improve amdefine and requirejs against an empty object
  tasks/test_amdefine.js
  tasks/test_requirejs.js
Labels: type: maintenance

#6901 fix: tooltip pointer position in hovermode x
  draftlogs/6900_fix.md
  src/components/fx/hover.js
Labels: type: bug, type: community, status: reviewable

#6874 legend indentation
  draftlogs/6874_add.md
  src/components/legend/attributes.js
  src/components/legend/defaults.js
  src/components/legend/draw.js
  src/components/legend/style.js
  test/image/baselines/zz-legend_indentation.png
  test/image/mocks/zz-legend_indentation.json
  test/plot-schema.json
Labels: type: feature, type: community
