Repository plotly/plotly.js, pull requests merged in 2024-08, with the labels that each got.

#7085 no predefined stamen styles in map subplots
  draftlogs/7060_add.md
  src/plots/map/constants.js
  test/image/mocks/map_stamen-style.json
  test/jasmine/tests/map_test.js
  test/plot-schema.json
Labels: bug

#7080 Use cimg/node instead of circleci/node
  .circleci/config.yml
  .circleci/test.sh
  draftlogs/7080_change.md
  tasks/test_syntax.js
  test/jasmine/bundle_tests/mathjax_test.js
Labels: feature, P2, infrastructure

#7037 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: P2, infrastructure, fix

#7078 Use `node.js v18` and `npm v10` in development
  .circleci/config.yml
  CONTRIBUTING.md
  draftlogs/7078_change.md
  package.json
Labels: feature, P2, infrastructure, fix

#7099 Bump package-lockfile to v3
  draftlogs/7099_change.md
  package-lock.json
Labels: P1, infrastructure, fix

#7122 Add amd wrapper to fix esbuild
  tasks/bundle.mjs
Labels: community, P1, fix

#7087 add deprecation warning for mapbox traces and mapbox subplot
  draftlogs/7087_change.md
  src/plots/mapbox/index.js
  src/traces/choroplethmapbox/index.js
  src/traces/densitymapbox/index.js
  src/traces/scattermapbox/index.js
  test/plot-schema.json
Labels: feature, P1
