Repository plotly/plotly.js, pull requests merged in 2025-07, with the labels that each got.

#7390 Fix #7387: Specify buffers in regl.clear() to avoid performance warning
  src/traces/scattergl/plot.js
Labels: feature, community, P2

#7456 Fix Persian calendar leap year
  draftlogs/7456_fix.md
  package-lock.json
  package.json
  test/jasmine/tests/lib_date_test.js
Labels: P1, fix

#7468 feat: Add `minorloglabels` to cartesian axes
  draftlogs/7468_add.md
  src/plots/cartesian/axes.js
  src/plots/cartesian/layout_attributes.js
  src/plots/cartesian/tick_label_defaults.js
  src/plots/gl3d/layout/axis_defaults.js
  src/plots/polar/layout_attributes.js
  test/image/baselines/zz-minorloglabels.png
  test/image/mocks/zz-minorloglabels.json
  test/plot-schema.json
Labels: feature, cs

#7358 feat: New cartesian axis `modebardisable` attribute
  draftlogs/7358_add.md
  src/components/modebar/buttons.js
  src/components/modebar/manage.js
  src/plots/cartesian/layout_attributes.js
  src/plots/cartesian/layout_defaults.js
  test/jasmine/tests/modebar_test.js
  test/plot-schema.json
Labels: feature, P1

#7470 Fix NaN positions for shapes when dragging them.
  draftlogs/7470_fix.md
  src/components/shapes/draw_newshape/newshapes.js
  test/jasmine/tests/draw_newshape_test.js
Labels: community, regression, P1, fix

#7479 fix: Add method to check for WebKit WebView user agent string
  draftlogs/7479_fix.md
  src/lib/index.js
  src/lib/supports_pixelated_image.js
  test/jasmine/tests/lib_test.js
Labels: bug

#7439 feat: Add `unifiedhovertitle` to format unified hover title
  draftlogs/7439_add.md
  src/components/fx/hover.js
  src/plots/cartesian/axis_defaults.js
  src/plots/cartesian/layout_attributes.js
  src/plots/gl3d/layout/axis_defaults.js
  src/plots/template_attributes.js
  test/jasmine/tests/hover_label_test.js
  test/plot-schema.json
Labels: feature, cs
