Repository plotly/plotly.js, pull requests merged in 2025-06, with the labels that each got.

#7381 Fix: Fix installing dependencies in node v22
  .circleci/config.yml
  draftlogs/7381_fix.md
  package-lock.json
  package.json
Labels: community, P1, fix, dependencies

#7343 Run noCI tests using GitHub workflows
  .github/workflows/test.yml
  test/jasmine/assets/mouse_event.js
  test/jasmine/tests/bar_test.js
  test/jasmine/tests/cartesian_interact_test.js
  test/jasmine/tests/funnel_test.js
  test/jasmine/tests/gl3d_plot_interact_test.js
  test/jasmine/tests/page_test.js
  test/jasmine/tests/plot_api_react_test.js
  test/jasmine/tests/polar_test.js
  test/jasmine/tests/sankey_test.js
  test/jasmine/tests/select_test.js
  test/jasmine/tests/splom_test.js
  test/jasmine/tests/transition_test.js
Labels: P1, fix, testing

#7280 Path pattern fills
  draftlogs/7280_add.md
  src/components/drawing/attributes.js
  src/components/drawing/index.js
  src/components/legend/style.js
  src/lib/coerce.js
  src/plot_api/validate.js
  test/image/baselines/zz-pattern_bars-path.png
  test/image/mocks/zz-pattern_bars-path.json
  test/plot-schema.json
Labels: feature, P1

#7420 Add support for `ticklabelposition` "inside"/"outside" for category axes with `tickson` set to "boundaries"
  draftlogs/7420_add.md
  src/plots/cartesian/axes.js
  src/plots/cartesian/axis_defaults.js
  src/plots/cartesian/layout_attributes.js
  test/image/baselines/zz-tickson_boundaries_ticklabelposition.png
  test/image/mocks/zz-tickson_boundaries_ticklabelposition.json
  test/plot-schema.json
Labels: feature, community, P1
