Repository plotly/plotly.js, pull requests merged in 2025-08, with the labels that each got.

#7469 fix: minor documentation formatting issues
  src/components/annotations/attributes.js
  src/components/errorbars/attributes.js
  src/plots/cartesian/layout_attributes.js
  src/plots/polar/layout_attributes.js
  src/plots/template_attributes.js
  src/traces/carpet/axis_attributes.js
  src/traces/contour/attributes.js
  test/plot-schema.json
Labels: P1, fix, documentation

#7483 fix: Update legend maxheight calculation logic
  src/components/legend/attributes.js
  src/components/legend/defaults.js
  src/components/legend/draw.js
  test/image/baselines/zz-legend-vertical-maxheight.png
  test/image/mocks/zz-legend-vertical-maxheight.json
  test/plot-schema.json
Labels: regression, P1, fix

#7517 fix wheel event handler Violation in Chromium by setting passive: true
  src/lib/events.js
Labels: P1, fix

#7529 Update Biome to v2.2.0; migrate config file
  biome.json
  package-lock.json
  package.json
  test/image/mocks/27.json
Labels: P1, fix, dependencies

#7539 fix: tidying up some Markdown documentation
  src/plots/map/layout_attributes.js
  src/plots/mapbox/layout_attributes.js
  src/traces/parcats/attributes.js
Labels: P1, documentation

#7540 fix: escaping angle bracket in documentation
  src/traces/image/attributes.js
  test/plot-schema.json
Labels: P1, documentation

#7526 Fix broken styling of map attributions
  esbuild-config.js
  package-lock.json
  package.json
  tasks/util/bundle_wrapper.mjs
Labels: P1, fix
