Repository plotly/plotly.js, pull requests merged in 2025-02, with the labels that each got.

#4425 Added `concentration` and small fixes
  lib/locales/it.js
Labels: feature, community, P2

#7352 Update Turkish locale
  lib/locales/tr.js
Labels: feature, community, P1

#7351 Update Romanian locale
  lib/locales/ro.js
Labels: feature, community, P2

#7360 Allow null and NaN in text templates
  draftlogs/7360_fix.md
  src/lib/index.js
  src/lib/nested_property.js
  test/jasmine/tests/lib_test.js
Labels: P1, fix

#7325 Update `color-rgba` to `3.0.0` to fix hsl color conversion bug
  draftlogs/7325_change.md
  package-lock.json
  package.json
  src/traces/parcoords/parcoords.js
Labels: community, fix
